# Vise Portfolio Strategy — Comparative Analysis
### UT Austin MSBA // Vise Capstone

---

## Objective

This notebook runs a full combinatorial backtest across:
- **2 portfolios**: 40/60 and 100/0 (Target Allocation ETF family, date 2025-05-20, with historical replacements)
- **3 time periods**: Bear market (2007–2008), Baseline (2010–2019), Bull market (2023–2024)
- **= 6 portfolio × period combinations**

Within each combination, all strategy variants are stacked:
- **TLH**: off (benchmark) vs on (10% loss threshold)
- **Calendar rebalancing**: Monthly, Quarterly, Yearly
- **Absolute threshold rebalancing**: 5%, 10%, 20%
- **Relative threshold rebalancing**: 25%, 50%

Total strategies per combination: 8 (3 calendar + 5 threshold) × 2 (TLH on/off) = **16 runs**  
Total runs: 6 × 16 = **96 runs**

Each no-TLH run is the benchmark for its TLH counterpart — tracking error and information ratio measure the TLH value-add.

---

In [1]:
# ══════════════════════════════════════════════════════════════════════════════
# CELL 1 — IMPORTS & EMBEDDED ENGINE FUNCTIONS
# Engine functions are embedded directly to avoid importing the Streamlit app
# (portfolio_returns_engine.py) which fails outside a Streamlit context.
# Only optimizer_msba_v1_engine.py is imported — it is a pure Python module.
# ══════════════════════════════════════════════════════════════════════════════

import os, sys, warnings, itertools
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from scipy import stats as sp_stats
from IPython.display import display

warnings.filterwarnings('ignore')

# ── Resolve paths ─────────────────────────────────────────────────────────────
NOTEBOOK_DIR = Path(os.path.abspath(''))
REPO_ROOT    = NOTEBOOK_DIR.parent
DATA_DIR     = REPO_ROOT.parent / 'data'
if not DATA_DIR.exists():
    DATA_DIR = REPO_ROOT / 'data'

sys.path.insert(0, str(REPO_ROOT))
from optimizer_msba_v1_engine import run_optimizer_simulation

# ══════════════════════════════════════════════════════════════════════════════
# EMBEDDED ENGINE FUNCTIONS  (extracted from portfolio_returns_engine.py V4)
# ══════════════════════════════════════════════════════════════════════════════

def _get_rebalance_dates(trading_dates, freq):
    """Return set of rebalance dates for a given calendar frequency."""
    dates = pd.DatetimeIndex(trading_dates)
    if len(dates) < 2:
        return set()
    if freq == 'Daily':
        return set(dates[1:])
    rebal_set = set()
    prev_month = dates[0].month
    prev_year  = dates[0].year
    prev_week  = dates[0].isocalendar()[1]
    if freq == 'Weekly':
        for dt in dates[1:]:
            iso = dt.isocalendar()
            if iso[1] != prev_week or dt.year != prev_year:
                rebal_set.add(dt); prev_week = iso[1]; prev_year = dt.year
    elif freq == 'Monthly':
        for dt in dates[1:]:
            if dt.month != prev_month or dt.year != prev_year:
                rebal_set.add(dt); prev_month = dt.month; prev_year = dt.year
    elif freq == 'Quarterly':
        for dt in dates[1:]:
            if dt.month in {1, 4, 7, 10} and (dt.month != prev_month or dt.year != prev_year):
                rebal_set.add(dt)
            if dt.month != prev_month or dt.year != prev_year:
                prev_month = dt.month; prev_year = dt.year
    elif freq == 'Yearly':
        for dt in dates[1:]:
            if dt.year != prev_year:
                rebal_set.add(dt); prev_month = dt.month; prev_year = dt.year
    else:
        raise ValueError(f'Unknown rebalance frequency: {freq}')
    return rebal_set


def build_rebalanced_series(prices_wide, target_weights, initial_capital, rebalance_freq,
                            cost_bps=12.0):
    """
    Calendar-only rebalancing engine (V3). Returns (rebal_daily, rebal_stats).

    cost_bps : total one-way transaction cost in basis points (commission + slippage + spread).
               Default 12 bps = 5 commission + 5 slippage + 2 bid-ask, matching optimizer engine.
               Pass 0.0 to disable cost deduction.

    NOTE — No look-ahead bias: day-i prices are used only to value existing positions and
    execute rebalancing trades. Target weights are fixed inputs computed before the loop.

    NOTE — Dividends excluded: this engine does not model dividend reinvestment. Portfolios
    with high-yielding constituents will show slightly lower NAV relative to the TLH engine,
    which models DRIP. This is a data-availability constraint, not a model choice.
    """
    cost_rate = cost_bps / 10_000.0
    tickers = list(target_weights.keys())
    dates   = prices_wide.index.tolist()
    n_days  = len(dates)
    if n_days == 0:
        raise ValueError('No trading dates in the filtered price data.')
    rebal_dates = _get_rebalance_dates(dates, rebalance_freq)
    shares = {tk: initial_capital * target_weights[tk] / prices_wide.loc[dates[0], tk]
              for tk in tickers}
    portfolio_values        = np.empty(n_days, dtype=np.float64)
    rebalance_count         = 0
    total_turnover_dollars  = 0.0
    total_transaction_costs = 0.0
    for i, dt in enumerate(dates):
        tv = {tk: shares[tk] * prices_wide.loc[dt, tk] for tk in tickers}
        total_value = sum(tv.values())
        portfolio_values[i] = total_value
        if dt in rebal_dates and total_value > 0:
            if any(abs(tv[tk] / total_value - target_weights[tk]) > 1e-10 for tk in tickers):
                rebalance_count += 1
                # Compute gross turnover (dollar volume of all trades this event)
                trade_turn = sum(
                    abs(target_weights[tk] * total_value / prices_wide.loc[dt, tk] - shares[tk])
                    * prices_wide.loc[dt, tk]
                    for tk in tickers
                )
                total_turnover_dollars  += trade_turn
                cost_amount              = trade_turn * cost_rate
                total_transaction_costs += cost_amount
                # Allocate net-of-cost value to target weights so cost compounds forward
                net_value = total_value - cost_amount
                for tk in tickers:
                    shares[tk] = target_weights[tk] * net_value / prices_wide.loc[dt, tk]
                portfolio_values[i] = net_value
    avg_val = np.mean(portfolio_values)
    rebal_daily = pd.DataFrame({'Portfolio Value': portfolio_values}, index=dates)
    rebal_daily.index.name = 'PRICEDATE'
    rebal_stats = {
        'rebalance_count':         rebalance_count,
        'turnover_proxy':          round(total_turnover_dollars / avg_val if avg_val > 0 else 0, 4),
        'total_turnover_dollars':  round(total_turnover_dollars, 2),
        'transaction_costs_total': round(total_transaction_costs, 2),
        'final_value':             round(portfolio_values[-1], 2),
        'total_return':            round(portfolio_values[-1] / initial_capital - 1, 6),
    }
    return rebal_daily, rebal_stats


def compute_weights(shares, prices):
    values = {tk: shares[tk] * prices[tk] for tk in shares}
    total  = sum(values.values())
    return {tk: values[tk] / total for tk in shares} if total > 0 else {tk: 0.0 for tk in shares}


def compute_drift(current_weights, target_weights, drift_mode='Absolute'):
    """
    Compute per-asset drift between current and target weights.

    Relative mode uses the symmetric log-ratio |log(w_cur / w_tgt)| instead of
    |w_cur/w_tgt - 1|. The log formula treats over- and under-weight positions
    symmetrically: doubling (2->4%) and halving (4->2%) produce equal drift values.
    """
    drift = {}
    for tk, w_tgt in target_weights.items():
        w_cur = current_weights.get(tk, 0.0)
        if drift_mode == 'Relative':
            # FIX: symmetric log-ratio — avoids asymmetry of |w/tgt - 1|
            if w_tgt >= 1e-12 and w_cur > 1e-12:
                drift[tk] = abs(np.log(w_cur / w_tgt))
            elif w_tgt >= 1e-12:
                drift[tk] = abs(np.log(1e-12 / w_tgt))
            else:
                drift[tk] = abs(w_cur)
        else:
            drift[tk] = abs(w_cur - w_tgt)
    return drift


def find_threshold_triggers(drift, tolerances):
    return [tk for tk, d in drift.items() if d > tolerances.get(tk, 0.05) + 1e-12]


def apply_rebalance_full(shares, target_weights, prices, total_value, cost_rate=0.0):
    """
    Rebalance to target weights. Returns (new_shares, gross_turnover, cost_amount).
    Gross turnover = sum of |dollar trade| across all assets (before costs).
    Net NAV after costs = total_value - cost_amount.
    """
    trade_turn = sum(
        abs(target_weights[tk] * total_value / prices[tk] - shares[tk]) * prices[tk]
        for tk in target_weights if prices.get(tk, 0) > 0
    )
    cost_amount = trade_turn * cost_rate
    net_value   = total_value - cost_amount
    new_shares  = {
        tk: target_weights[tk] * net_value / prices[tk] if prices.get(tk, 0) > 0 else 0.0
        for tk in target_weights
    }
    return new_shares, trade_turn, cost_amount


def build_threshold_rebalanced_series(
    prices_wide, target_weights, initial_capital, tolerances,
    drift_mode='Absolute', rebalance_action='Full', cooldown_days=0,
    calendar_freq=None, enable_calendar=False, enable_threshold=True,
    cost_bps=12.0,
):
    """
    Threshold (drift-band) rebalancing engine (V4).

    cost_bps : total one-way transaction cost in basis points. Default 12 bps.

    NOTE — No look-ahead bias: breach detection on day i schedules a rebalance on day i+1;
    the trade executes at day-i+1 prices (represented here by day-i+1 close, consistent with
    the rest of the simulation). Triggers are never computed from future prices.

    NOTE — Dividends excluded: see build_rebalanced_series docstring.
    """
    cost_rate = cost_bps / 10_000.0
    tickers = list(target_weights.keys())
    dates   = prices_wide.index.tolist()
    n_days  = len(dates)
    if n_days == 0:
        raise ValueError('No trading dates in the filtered price data.')
    calendar_dates = set()
    if enable_calendar and calendar_freq and calendar_freq != 'None':
        calendar_dates = _get_rebalance_dates(dates, calendar_freq)
    shares = {tk: initial_capital * target_weights[tk] / prices_wide.loc[dates[0], tk]
              for tk in tickers}
    portfolio_values = np.empty(n_days, dtype=np.float64)
    drift_history    = {tk: [] for tk in tickers}
    event_log        = []
    rebalance_count  = calendar_rebal_count = threshold_rebal_count = 0
    total_turnover          = 0.0
    total_transaction_costs = 0.0
    cooldown_remaining = 0
    pending = False; p_tickers = []; p_max_drift = 0.0
    for i, dt in enumerate(dates):
        pt = {tk: float(prices_wide.loc[dt, tk]) for tk in tickers}
        tv = sum(shares[tk] * pt[tk] for tk in tickers)
        portfolio_values[i] = tv
        cw    = compute_weights(shares, pt)
        drift = compute_drift(cw, target_weights, drift_mode)
        for tk in tickers:
            drift_history[tk].append(drift.get(tk, 0.0))
        did_rebal = False
        if pending and enable_threshold and i > 0 and cooldown_remaining <= 0 and tv > 0:
            shares, turn, cost_amt = apply_rebalance_full(shares, target_weights, pt, tv, cost_rate)
            total_turnover += turn; total_transaction_costs += cost_amt
            rebalance_count += 1; threshold_rebal_count += 1
            did_rebal = True; cooldown_remaining = cooldown_days
            tv = sum(shares[tk] * pt[tk] for tk in tickers)
            portfolio_values[i] = tv
            event_log.append({'date': dt, 'reason': 'threshold',
                               'breached_tickers': ', '.join(p_tickers),
                               'max_drift': round(p_max_drift, 6), 'turnover_dollars': round(turn, 2)})
        pending = False; p_tickers = []; p_max_drift = 0.0
        if enable_calendar and dt in calendar_dates and tv > 0:
            cw_now = compute_weights(shares, pt)
            if any(abs(cw_now.get(tk, 0) - target_weights[tk]) > 1e-10 for tk in tickers):
                shares, turn, cost_amt = apply_rebalance_full(shares, target_weights, pt, tv, cost_rate)
                total_turnover += turn; total_transaction_costs += cost_amt
                calendar_rebal_count += 1
                if not did_rebal: rebalance_count += 1
                tv = sum(shares[tk] * pt[tk] for tk in tickers)
                portfolio_values[i] = tv
                event_log.append({'date': dt, 'reason': 'calendar', 'breached_tickers': '',
                                   'max_drift': round(max(drift.values(), default=0), 6),
                                   'turnover_dollars': round(turn, 2)})
        if enable_threshold and i < n_days - 1:
            cw_post  = compute_weights(shares, pt)
            dp       = compute_drift(cw_post, target_weights, drift_mode)
            breached = find_threshold_triggers(dp, tolerances)
            if breached and cooldown_remaining <= 0:
                pending = True; p_tickers = breached
                p_max_drift = max(dp[tk] for tk in breached)
        if cooldown_remaining > 0: cooldown_remaining -= 1
    avg_val    = np.mean(portfolio_values)
    rebal_daily = pd.DataFrame({'Portfolio Value': portfolio_values}, index=dates)
    rebal_daily.index.name = 'PRICEDATE'
    rebal_stats = {
        'rebalance_count':         rebalance_count,
        'calendar_rebal_count':    calendar_rebal_count,
        'threshold_rebal_count':   threshold_rebal_count,
        'turnover_proxy':          round(total_turnover / avg_val if avg_val > 0 else 0, 4),
        'total_turnover_dollars':  round(total_turnover, 2),
        'transaction_costs_total': round(total_transaction_costs, 2),
        'final_value':             round(portfolio_values[-1], 2),
        'total_return':            round(portfolio_values[-1] / initial_capital - 1, 6),
    }
    event_log_df = pd.DataFrame(event_log) if event_log else \
        pd.DataFrame(columns=['date', 'reason', 'breached_tickers', 'max_drift', 'turnover_dollars'])
    return rebal_daily, rebal_stats, event_log_df, drift_history


def compute_strategy_metrics(daily_values, initial_capital, benchmark_values=None):
    """Compute performance metrics from a daily portfolio value array or Series."""
    if isinstance(daily_values, pd.Series):
        daily_values = daily_values.values
    n = len(daily_values)
    if n < 2:
        return {'total_return': 0.0, 'cagr': 0.0, 'annualized_vol': 0.0, 'sharpe': 0.0,
                'max_drawdown': 0.0, 'skewness': 0.0, 'kurtosis': 0.0, 'avg_drawdown': 0.0,
                'tracking_error': 0.0, 'information_ratio': 0.0}
    total_return = daily_values[-1] / initial_capital - 1
    years = max(n - 1, 1) / 252.0
    cagr  = (daily_values[-1] / initial_capital) ** (1 / years) - 1 if years > 0 and daily_values[-1] > 0 else 0.0
    daily_rets = np.diff(daily_values) / daily_values[:-1]
    ann_vol    = float(np.std(daily_rets, ddof=1) * np.sqrt(252)) if len(daily_rets) > 1 else 0.0
    sharpe     = cagr / ann_vol if ann_vol > 0 else 0.0
    running_max = np.maximum.accumulate(daily_values)
    drawdowns   = (daily_values - running_max) / running_max
    max_dd      = float(np.min(drawdowns))
    avg_dd      = float(np.mean(drawdowns))
    skewness    = float(sp_stats.skew(daily_rets))   if len(daily_rets) > 2 else 0.0
    kurtosis    = float(sp_stats.kurtosis(daily_rets, fisher=True)) if len(daily_rets) > 3 else 0.0
    te = ir = 0.0
    if benchmark_values is not None:
        if isinstance(benchmark_values, pd.Series): benchmark_values = benchmark_values.values
        if len(benchmark_values) == n:
            bm_rets = np.diff(benchmark_values) / benchmark_values[:-1]
            active  = daily_rets - bm_rets
            te      = float(np.std(active, ddof=1) * np.sqrt(252)) if len(active) > 1 else 0.0
            if te > 1e-12:
                # FIX: IR numerator = CAGR difference (geometric), not mean(daily) * 252.
                # mean(daily) * 252 is an arithmetic approximation that diverges from realized
                # excess return over multi-year periods.
                bm_cagr = float((benchmark_values[-1] / benchmark_values[0]) ** (1.0 / years) - 1.0) \
                          if benchmark_values[0] > 0 else 0.0
                ir = (cagr - bm_cagr) / te
    return {'total_return': round(total_return, 6), 'cagr': round(cagr, 6),
            'annualized_vol': round(ann_vol, 6), 'sharpe': round(sharpe, 4),
            'max_drawdown': round(max_dd, 6), 'skewness': round(skewness, 4),
            'kurtosis': round(kurtosis, 4), 'avg_drawdown': round(avg_dd, 6),
            'tracking_error': round(te, 6), 'information_ratio': round(ir, 4)}


print(f'Repo root : {REPO_ROOT}')
print(f'Data dir  : {DATA_DIR}')
print('All engine functions loaded (no Streamlit dependency).')

Repo root : c:\Users\ry092\Desktop\MIS 382N - Capstone\portfolio-tlh-optimizer
Data dir  : c:\Users\ry092\Desktop\MIS 382N - Capstone\data
All engine functions loaded (no Streamlit dependency).

In [2]:
# ══════════════════════════════════════════════════════════════════════════════
# CELL 2 — VALIDATE DATA FILES & LOAD PRICE / DIVIDEND / PROXY DATA
#
# Accepts either parquet or CSV for price data (parquet preferred if available).
# Auto-converts proxy_lookup.xlsx -> CSV if the CSV export is missing.
# ══════════════════════════════════════════════════════════════════════════════

PRICE_PARQUET = DATA_DIR / 'price_data.parquet'
PRICE_CSV     = DATA_DIR / 'price_data.csv'
DIV_PATH      = REPO_ROOT / 'dividend_data.csv'
PROXY_CSV     = DATA_DIR / 'proxy_lookup.xlsx - proxy_lookup.csv'

print(f'Repo root : {REPO_ROOT}')
print(f'Data dir  : {DATA_DIR}')
print()

# ── Resolve which price file to use ──────────────────────────────────────────
if PRICE_PARQUET.exists():
    PRICE_PATH = PRICE_PARQUET
elif PRICE_CSV.exists():
    PRICE_PATH = PRICE_CSV
else:
    PRICE_PATH = None

# ── Auto-convert proxy_lookup.xlsx -> CSV if needed ──────────────────────────
if not PROXY_CSV.exists():
    _xlsx_alt = DATA_DIR / 'proxy_lookup.xlsx'
    if _xlsx_alt.exists():
        print(f'Converting proxy_lookup.xlsx -> CSV ...')
        _tmp = pd.read_excel(_xlsx_alt)
        _tmp.to_csv(PROXY_CSV, index=False)
        print(f'  Created {PROXY_CSV.name}  ({len(_tmp):,} rows)')

# ── Pre-flight validation ────────────────────────────────────────────────────
_missing = []
if not DATA_DIR.exists():
    _missing.append(f'  DATA DIRECTORY not found: {DATA_DIR}')
if PRICE_PATH is None:
    _missing.append(f'  PRICE DATA not found: need price_data.parquet or price_data.csv in {DATA_DIR}')
if not PROXY_CSV.exists():
    _missing.append(f'  PROXY LOOKUP not found: {PROXY_CSV}'
                    f'\n         Need proxy_lookup.xlsx or the CSV export in {DATA_DIR}')
if not (REPO_ROOT / 'optimizer_msba_v1_engine.py').exists():
    _missing.append(f'  ENGINE MODULE not found: {REPO_ROOT / "optimizer_msba_v1_engine.py"}')

if _missing:
    print('=' * 70)
    print('MISSING FILES -- the notebook cannot run without these:\n')
    for m in _missing:
        print(m)
    if not DIV_PATH.exists():
        print(f'\n  (optional) dividend_data.csv not found: {DIV_PATH}')
        print(f'             Notebook will run without dividends.')
    print('\n' + '=' * 70)
    raise FileNotFoundError(
        f'{len(_missing)} required file(s) missing. See messages above.'
    )

print('All required files found.\n')

# ── Load price data ──────────────────────────────────────────────────────────
print(f'Loading price data from {PRICE_PATH.name} ...')
if PRICE_PATH.suffix == '.parquet':
    prices_raw = pd.read_parquet(PRICE_PATH)
else:
    prices_raw = pd.read_csv(PRICE_PATH)
prices_raw['PRICEDATE'] = pd.to_datetime(prices_raw['PRICEDATE'])
if 'TRADINGITEMSTATUSID' in prices_raw.columns:
    prices_raw = prices_raw[prices_raw['TRADINGITEMSTATUSID'].isin([1, 15])].copy()
prices_raw['PRICECLOSE'] = pd.to_numeric(prices_raw['PRICECLOSE'], errors='coerce')
prices_raw = prices_raw.dropna(subset=['PRICECLOSE'])
prices_raw['TICKERSYMBOL'] = prices_raw['TICKERSYMBOL'].astype(str).str.strip().str.upper()
print(f'Price data: {len(prices_raw):,} rows | {prices_raw["TICKERSYMBOL"].nunique()} tickers')
print(f'Date range: {prices_raw["PRICEDATE"].min().date()} \u2192 {prices_raw["PRICEDATE"].max().date()}')

# ── Load dividends (optional) ────────────────────────────────────────────────
div_df = None
if DIV_PATH.exists():
    div_df = pd.read_csv(DIV_PATH)
    print(f'Dividends loaded: {len(div_df):,} rows')
else:
    print('No dividend_data.csv found -- running without dividends.')

# ── Load and clean proxy lookup ──────────────────────────────────────────────
proxy_lookup_raw = pd.read_csv(PROXY_CSV)
proxy_lookup_raw['symbol']        = proxy_lookup_raw['symbol'].str.strip().str.upper()
proxy_lookup_raw['lookup_symbol'] = proxy_lookup_raw['lookup_symbol'].str.strip().str.upper()
PROXY_FULL = (
    proxy_lookup_raw[['symbol', 'lookup_type', 'lookup_symbol', 'order']]
    .drop_duplicates(subset=['symbol', 'lookup_symbol'])
    .sort_values(['symbol', 'order'])
    .reset_index(drop=True)
)
print(f'Proxy lookup loaded: {len(PROXY_FULL)} unique symbol\u2192proxy pairs')


def build_proxy_df(portfolio_tickers, start_date, end_date, prices_df):
    """
    Return a proxy_df filtered to:
      1. Only portfolio tickers that need proxies.
      2. Only proxy tickers that have price data in the given period.
    Falls back to the next-ranked proxy if the primary is unavailable.
    """
    avail_px = set(
        prices_df[
            (prices_df['PRICEDATE'] >= pd.Timestamp(start_date)) &
            (prices_df['PRICEDATE'] <= pd.Timestamp(end_date))
        ]['TICKERSYMBOL'].unique()
    )
    sub = PROXY_FULL[
        PROXY_FULL['symbol'].isin(portfolio_tickers) &
        PROXY_FULL['lookup_symbol'].isin(avail_px)
    ].copy()
    return sub.reset_index(drop=True)

Repo root : c:\Users\ry092\Desktop\MIS 382N - Capstone\portfolio-tlh-optimizer
Data dir  : c:\Users\ry092\Desktop\MIS 382N - Capstone\data

All required files found.

Loading price data from price_data.csv ...
Price data: 2,254,430 rows | 696 tickers
Date range: 1980-06-23 → 2026-01-30
Dividends loaded: 55,064 rows
Proxy lookup loaded: 700 unique symbol→proxy pairs

In [3]:
# ══════════════════════════════════════════════════════════════════════════════
# CELL 3 — PORTFOLIO DEFINITIONS (auto-loaded from Models.xlsx)
#
# Loads ALL portfolios from Models.xlsx, using the latest snapshot per portfolio.
# Cash positions ("$") are removed and weights renormalized.
# Portfolios are classified into 3 categories by equity allocation:
#   Equity-Heavy (>=70%), Balanced (30-69%), Fixed Income-Heavy (<30%)
# ══════════════════════════════════════════════════════════════════════════════

MODELS_PATH = DATA_DIR / 'Models.xlsx'
if not MODELS_PATH.exists():
    raise FileNotFoundError(f'Models.xlsx not found: {MODELS_PATH}')

print('Loading portfolio definitions from Models.xlsx ...')
models_raw = pd.read_excel(MODELS_PATH)
models_raw['Trade Date'] = pd.to_datetime(models_raw['Trade Date'])
models_raw['Ticker'] = models_raw['Ticker'].astype(str).str.strip().str.upper()
models_raw['Weight'] = pd.to_numeric(models_raw['Weight'], errors='coerce').fillna(0.0)

# Use the LATEST snapshot per portfolio (most current weights)
latest_dates = models_raw.groupby('full_name')['Trade Date'].max().reset_index()
latest_dates.columns = ['full_name', 'Trade Date']
models_latest = models_raw.merge(latest_dates, on=['full_name', 'Trade Date'])

# Remove cash positions
models_latest = models_latest[models_latest['Ticker'] != '$'].copy()

# Equity asset classes (for categorization)
EQUITY_CLASSES = {
    'US Equities', 'International/Global Equities',
    'Emerging Market Equities', 'Global Equities',
}

# ── Build PORTFOLIOS dict and metadata ───────────────────────────────────────
PORTFOLIOS = {}
PORTFOLIO_META = {}  # name -> {model_family, portfolio_label, category, equity_pct}

for full_name, group in models_latest.groupby('full_name'):
    tickers = group['Ticker'].tolist()
    weights = group['Weight'].tolist()

    # Normalize weights to sum to 1.0 (handles cash removal + data errors like 9.0 weight)
    total_w = sum(weights)
    if total_w < 1e-6:
        continue  # skip empty portfolios
    weights = [w / total_w for w in weights]

    port_dict = {}
    for tk, w in zip(tickers, weights):
        if w > 1e-8:
            port_dict[tk] = port_dict.get(tk, 0.0) + w  # merge duplicate tickers

    if not port_dict:
        continue

    PORTFOLIOS[full_name] = port_dict

    # Classify by equity allocation
    equity_pct = group.loc[
        group['Asset Class'].isin(EQUITY_CLASSES), 'Weight'
    ].sum() / total_w

    if equity_pct >= 0.70:
        category = 'Equity-Heavy'
    elif equity_pct >= 0.30:
        category = 'Balanced'
    else:
        category = 'Fixed Income-Heavy'

    PORTFOLIO_META[full_name] = {
        'model_family': group['Model_Family'].iloc[0],
        'portfolio_label': group['Portfolio'].iloc[0],
        'category': category,
        'equity_pct': round(equity_pct, 3),
        'n_tickers': len(port_dict),
    }

# ── Summary ──────────────────────────────────────────────────────────────────
print(f'\nLoaded {len(PORTFOLIOS)} portfolios from {models_raw["Model_Family"].nunique()} model families')
print(f'Unique tickers across all portfolios: {len(set(tk for p in PORTFOLIOS.values() for tk in p))}')
print()

# Category breakdown
from collections import Counter
cat_counts = Counter(m['category'] for m in PORTFOLIO_META.values())
for cat in ['Equity-Heavy', 'Balanced', 'Fixed Income-Heavy']:
    count = cat_counts.get(cat, 0)
    families = sorted(set(m['model_family'] for n, m in PORTFOLIO_META.items() if m['category'] == cat))
    print(f'  {cat:20s}: {count:3d} portfolios  ({", ".join(families[:5])}{"..." if len(families) > 5 else ""})')

print(f'Ready: {len(PORTFOLIOS)} portfolios loaded')

Loading portfolio definitions from Models.xlsx ...

Loaded 158 portfolios from 20 model families
Unique tickers across all portfolios: 146

  Equity-Heavy        :  35 portfolios  (FFG Qualified, FFG Taxable High, FFG Taxable Medium, GA Aviator, GA Aviator TaxAware...)
  Balanced            :  79 portfolios  (FFG Qualified, FFG Taxable High, FFG Taxable Medium, GA Aviator, GA Aviator TaxAware...)
  Fixed Income-Heavy  :  44 portfolios  (FFG Qualified, FFG Taxable High, FFG Taxable Medium, GA Aviator, GA Aviator TaxAware...)
Ready: 158 portfolios loaded

In [4]:
# ══════════════════════════════════════════════════════════════════════════════
# CELL 4 — SIMULATION PARAMETERS
# ══════════════════════════════════════════════════════════════════════════════

# ── Time periods ──────────────────────────────────────────────────────────────
TIME_PERIODS = {
    'Bear (2007–2008)':     ('2007-01-01', '2008-12-31'),
    'Baseline (2010–2019)': ('2010-01-01', '2019-12-31'),
    'Bull (2023–2024)':     ('2023-01-01', '2024-12-31'),
    'Past 5Y (2021–2025)':  ('2021-01-01', '2025-12-31'),
    'Past 10Y (2016–2025)': ('2016-01-01', '2025-12-31'),
    'Past 20Y (2006–2025)': ('2006-01-01', '2025-12-31'),
}

# ── Capital & tax assumptions ─────────────────────────────────────────────────
INITIAL_CAPITAL = 1_000_000.0
TAX_RATES       = {'st_rate': 0.35, 'lt_rate': 0.20}
PRICE_FIELD     = 'PRICECLOSE'
COST_CONFIG     = {'commission_bps': 5.0, 'slippage_bps': 5.0, 'bid_ask_bps': 2.0}

# ── TLH threshold ─────────────────────────────────────────────────────────────
TLH_THRESHOLD = 0.10   # 10% loss triggers harvest

# ── Strategy grid ─────────────────────────────────────────────────────────────
# Calendar rebalancing frequencies
CALENDAR_FREQS = ['Monthly', 'Quarterly', 'Yearly']

# Absolute threshold bands (drift > X% triggers rebalance)
ABS_THRESHOLDS = [0.05, 0.10, 0.20]   # 5%, 10%, 20%

# Relative threshold bands (drift > X% of target weight triggers rebalance)
REL_THRESHOLDS = [0.25, 0.50]         # 25%, 50%

# ── Strategy labels ───────────────────────────────────────────────────────────
def strategy_label(strat_type, strat_val, tlh_on):
    """Build a human-readable label clearly showing all stacked dimensions."""
    tlh_tag = 'TLH=10%' if tlh_on else 'No TLH'
    if strat_type == 'calendar':
        return f'{strat_val} Rebal | {tlh_tag}'
    elif strat_type == 'abs':
        pct = int(strat_val * 100)
        return f'Abs Threshold {pct}% | {tlh_tag}'
    elif strat_type == 'rel':
        pct = int(strat_val * 100)
        return f'Rel Threshold {pct}% | {tlh_tag}'

print('Strategy grid:')
for freq in CALENDAR_FREQS:
    print(f'  Calendar: {strategy_label("calendar", freq, False)} / {strategy_label("calendar", freq, True)}')
for tol in ABS_THRESHOLDS:
    print(f'  Absolute: {strategy_label("abs", tol, False)} / {strategy_label("abs", tol, True)}')
for tol in REL_THRESHOLDS:
    print(f'  Relative: {strategy_label("rel", tol, False)} / {strategy_label("rel", tol, True)}')
print(f'\n{len(CALENDAR_FREQS) + len(ABS_THRESHOLDS) + len(REL_THRESHOLDS)} strategy types × 2 TLH states = '
      f'{(len(CALENDAR_FREQS) + len(ABS_THRESHOLDS) + len(REL_THRESHOLDS)) * 2} runs per combination')
print(f'{len(TIME_PERIODS)} periods × {len(PORTFOLIOS)} portfolios × '
      f'{(len(CALENDAR_FREQS) + len(ABS_THRESHOLDS) + len(REL_THRESHOLDS)) * 2} = '
      f'{len(TIME_PERIODS) * len(PORTFOLIOS) * (len(CALENDAR_FREQS) + len(ABS_THRESHOLDS) + len(REL_THRESHOLDS)) * 2} total runs')

Strategy grid:
  Calendar: Monthly Rebal | No TLH / Monthly Rebal | TLH=10%
  Calendar: Quarterly Rebal | No TLH / Quarterly Rebal | TLH=10%
  Calendar: Yearly Rebal | No TLH / Yearly Rebal | TLH=10%
  Absolute: Abs Threshold 5% | No TLH / Abs Threshold 5% | TLH=10%
  Absolute: Abs Threshold 10% | No TLH / Abs Threshold 10% | TLH=10%
  Absolute: Abs Threshold 20% | No TLH / Abs Threshold 20% | TLH=10%
  Relative: Rel Threshold 25% | No TLH / Rel Threshold 25% | TLH=10%
  Relative: Rel Threshold 50% | No TLH / Rel Threshold 50% | TLH=10%

8 strategy types × 2 TLH states = 16 runs per combination
6 periods × 158 portfolios × 16 = 15168 total runs

In [5]:
# ══════════════════════════════════════════════════════════════════════════════
# CELL 5 — HELPER: BUILD WIDE PRICE MATRIX
# ══════════════════════════════════════════════════════════════════════════════

def build_prices_wide(prices_df, tickers, start_date, end_date, price_field='PRICECLOSE'):
    """Filter price data to tickers and date range, pivot to wide format."""
    mask = (
        prices_df['TICKERSYMBOL'].isin(tickers) &
        (prices_df['PRICEDATE'] >= pd.Timestamp(start_date)) &
        (prices_df['PRICEDATE'] <= pd.Timestamp(end_date))
    )
    subset = prices_df.loc[mask, ['TICKERSYMBOL', 'PRICEDATE', price_field]].copy()
    subset = subset.drop_duplicates(subset=['TICKERSYMBOL', 'PRICEDATE'])
    wide = subset.pivot(index='PRICEDATE', columns='TICKERSYMBOL', values=price_field)
    wide = wide.sort_index().dropna()
    return wide


def verify_ticker_coverage(portfolio_dict, start_date, end_date, period_name):
    """Check which tickers are present in price data for a given period."""
    tickers = list(portfolio_dict.keys())
    wide = build_prices_wide(prices_raw, tickers, start_date, end_date)
    present  = [t for t in tickers if t in wide.columns]
    missing  = [t for t in tickers if t not in wide.columns]
    coverage = sum(portfolio_dict[t] for t in present)
    print(f'  {period_name}: {len(present)}/{len(tickers)} tickers | weight coverage {coverage:.1%}')
    if missing:
        print(f'    Missing: {missing}')
    return present, missing


print('Ticker coverage verification:')
for port_name, port_dict in PORTFOLIOS.items():
    print(f'\n{port_name}:')
    for period_name, (start, end) in TIME_PERIODS.items():
        verify_ticker_coverage(port_dict, start, end, period_name)

Ticker coverage verification:

FFG Qualified - 0-100:
  Bear (2007–2008): 1/11 tickers | weight coverage 10.0%
    Missing: ['BINC', 'BSIIX', 'IUSB', 'MAHQX', 'PIMIX', 'SYSB', 'PFUIX', 'VEGBX', 'BIMBX', 'ICVT']
  Baseline (2010–2019): 4/11 tickers | weight coverage 35.0%
    Missing: ['BINC', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Bull (2023–2024): 5/11 tickers | weight coverage 45.0%
    Missing: ['BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 5Y (2021–2025): 5/11 tickers | weight coverage 45.0%
    Missing: ['BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 10Y (2016–2025): 5/11 tickers | weight coverage 45.0%
    Missing: ['BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 20Y (2006–2025): 5/11 tickers | weight coverage 45.0%
    Missing: ['BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']

FFG Qualified - 10-90:
  Bear (2007–2008): 4/17 tickers | weight coverage 12.0%
    Missing: ['DYNF', 'BROIX', 'GQGIX', 'BINC', 'BSIIX', 'IUSB', 'MAHQX', 'PIMIX', 'SYSB', 'PFUIX', 'VEGBX', 'BIMBX', 'ICVT']
  Baseline (2010–2019): 8/17 tickers | weight coverage 40.0%
    Missing: ['BROIX', 'GQGIX', 'BINC', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Bull (2023–2024): 9/17 tickers | weight coverage 49.0%
    Missing: ['BROIX', 'GQGIX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 5Y (2021–2025): 9/17 tickers | weight coverage 49.0%
    Missing: ['BROIX', 'GQGIX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 10Y (2016–2025): 9/17 tickers | weight coverage 49.0%
    Missing: ['BROIX', 'GQGIX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 20Y (2006–2025): 9/17 tickers | weight coverage 49.0%
    Missing: ['BROIX', 'GQGIX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']

FFG Qualified - 100-0:
  Bear (2007–2008): 4/13 tickers | weight coverage 35.0%
    Missing: ['DYNF', 'QUAL', 'BAI', 'CIBR', 'SHLD', 'THRO', 'BROIX', 'GQGIX', 'GSIMX']
  Baseline (2010–2019): 7/13 tickers | weight coverage 69.0%
    Missing: ['BAI', 'SHLD', 'THRO', 'BROIX', 'GQGIX', 'GSIMX']
  Bull (2023–2024): 10/13 tickers | weight coverage 82.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX']
  Past 5Y (2021–2025): 10/13 tickers | weight coverage 82.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX']
  Past 10Y (2016–2025): 10/13 tickers | weight coverage 82.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX']
  Past 20Y (2006–2025): 10/13 tickers | weight coverage 82.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX']

FFG Qualified - 20-80:
  Bear (2007–2008): 5/21 tickers | weight coverage 16.0%
    Missing: ['DYNF', 'CIBR', 'THRO', 'BROIX', 'GQGIX', 'GSIMX', 'BINC', 'BSIIX', 'IUSB', 'MAHQX', 'PIMIX', 'SYSB', 'PFUIX', 'VEGBX', 'BIMBX', 'ICVT']
  Baseline (2010–2019): 10/21 tickers | weight coverage 42.0%
    Missing: ['THRO', 'BROIX', 'GQGIX', 'GSIMX', 'BINC', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Bull (2023–2024): 12/21 tickers | weight coverage 52.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 5Y (2021–2025): 12/21 tickers | weight coverage 52.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 10Y (2016–2025): 12/21 tickers | weight coverage 52.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 20Y (2006–2025): 12/21 tickers | weight coverage 52.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']

FFG Qualified - 30-70:
  Bear (2007–2008): 5/22 tickers | weight coverage 19.0%
    Missing: ['DYNF', 'BAI', 'CIBR', 'THRO', 'BROIX', 'GQGIX', 'GSIMX', 'BINC', 'BSIIX', 'IUSB', 'MAHQX', 'PIMIX', 'SYSB', 'PFUIX', 'VEGBX', 'BIMBX', 'ICVT']
  Baseline (2010–2019): 10/22 tickers | weight coverage 47.0%
    Missing: ['BAI', 'THRO', 'BROIX', 'GQGIX', 'GSIMX', 'BINC', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Bull (2023–2024): 13/22 tickers | weight coverage 57.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 5Y (2021–2025): 13/22 tickers | weight coverage 57.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 10Y (2016–2025): 13/22 tickers | weight coverage 57.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 20Y (2006–2025): 13/22 tickers | weight coverage 57.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']

FFG Qualified - 35-65:
  Bear (2007–2008): 5/23 tickers | weight coverage 20.0%
    Missing: ['DYNF', 'QUAL', 'BAI', 'CIBR', 'THRO', 'BROIX', 'GQGIX', 'GSIMX', 'BINC', 'BSIIX', 'IUSB', 'MAHQX', 'PIMIX', 'SYSB', 'PFUIX', 'VEGBX', 'BIMBX', 'ICVT']
  Baseline (2010–2019): 11/23 tickers | weight coverage 50.0%
    Missing: ['BAI', 'THRO', 'BROIX', 'GQGIX', 'GSIMX', 'BINC', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Bull (2023–2024): 14/23 tickers | weight coverage 60.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 5Y (2021–2025): 14/23 tickers | weight coverage 60.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 10Y (2016–2025): 14/23 tickers | weight coverage 60.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 20Y (2006–2025): 14/23 tickers | weight coverage 60.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']

FFG Qualified - 40-60:
  Bear (2007–2008): 5/23 tickers | weight coverage 22.0%
    Missing: ['DYNF', 'QUAL', 'BAI', 'CIBR', 'THRO', 'BROIX', 'GQGIX', 'GSIMX', 'BINC', 'BSIIX', 'IUSB', 'MAHQX', 'PIMIX', 'SYSB', 'PFUIX', 'VEGBX', 'BIMBX', 'ICVT']
  Baseline (2010–2019): 11/23 tickers | weight coverage 51.0%
    Missing: ['BAI', 'THRO', 'BROIX', 'GQGIX', 'GSIMX', 'BINC', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Bull (2023–2024): 14/23 tickers | weight coverage 61.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 5Y (2021–2025): 14/23 tickers | weight coverage 61.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 10Y (2016–2025): 14/23 tickers | weight coverage 61.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 20Y (2006–2025): 14/23 tickers | weight coverage 61.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']

FFG Qualified - 45-55:
  Bear (2007–2008): 5/24 tickers | weight coverage 23.0%
    Missing: ['THRO', 'BROIX', 'GQGIX', 'GSIMX', 'BINC', 'BSIIX', 'IUSB', 'DYNF', 'QUAL', 'BAI', 'CIBR', 'SHLD', 'MAHQX', 'PIMIX', 'SYSB', 'PFUIX', 'VEGBX', 'BIMBX', 'ICVT']
  Baseline (2010–2019): 11/24 tickers | weight coverage 51.0%
    Missing: ['THRO', 'BROIX', 'GQGIX', 'GSIMX', 'BINC', 'BSIIX', 'BAI', 'SHLD', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Bull (2023–2024): 15/24 tickers | weight coverage 63.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 5Y (2021–2025): 15/24 tickers | weight coverage 63.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 10Y (2016–2025): 15/24 tickers | weight coverage 63.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 20Y (2006–2025): 15/24 tickers | weight coverage 63.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']

FFG Qualified - 50-50:
  Bear (2007–2008): 5/23 tickers | weight coverage 24.0%
    Missing: ['DYNF', 'QUAL', 'BAI', 'CIBR', 'SHLD', 'THRO', 'BROIX', 'GQGIX', 'GSIMX', 'BINC', 'BSIIX', 'IUSB', 'MAHQX', 'PIMIX', 'SYSB', 'PFUIX', 'VEGBX', 'BIMBX']
  Baseline (2010–2019): 10/23 tickers | weight coverage 51.0%
    Missing: ['BAI', 'SHLD', 'THRO', 'BROIX', 'GQGIX', 'GSIMX', 'BINC', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Bull (2023–2024): 14/23 tickers | weight coverage 63.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 5Y (2021–2025): 14/23 tickers | weight coverage 63.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 10Y (2016–2025): 14/23 tickers | weight coverage 63.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 20Y (2006–2025): 14/23 tickers | weight coverage 63.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']

FFG Qualified - 55-45:
  Bear (2007–2008): 5/23 tickers | weight coverage 25.0%
    Missing: ['THRO', 'BROIX', 'GQGIX', 'GSIMX', 'BINC', 'BSIIX', 'IUSB', 'MAHQX', 'PIMIX', 'SYSB', 'PFUIX', 'VEGBX', 'BIMBX', 'DYNF', 'QUAL', 'BAI', 'CIBR', 'SHLD']
  Baseline (2010–2019): 10/23 tickers | weight coverage 51.0%
    Missing: ['THRO', 'BROIX', 'GQGIX', 'GSIMX', 'BINC', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX', 'BAI', 'SHLD']
  Bull (2023–2024): 14/23 tickers | weight coverage 63.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 5Y (2021–2025): 14/23 tickers | weight coverage 63.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 10Y (2016–2025): 14/23 tickers | weight coverage 63.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 20Y (2006–2025): 14/23 tickers | weight coverage 63.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']

FFG Qualified - 60-40:
  Bear (2007–2008): 5/22 tickers | weight coverage 25.0%
    Missing: ['DYNF', 'QUAL', 'BAI', 'CIBR', 'SHLD', 'THRO', 'BROIX', 'GQGIX', 'GSIMX', 'BINC', 'BSIIX', 'IUSB', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Baseline (2010–2019): 9/22 tickers | weight coverage 51.0%
    Missing: ['BAI', 'SHLD', 'THRO', 'BROIX', 'GQGIX', 'GSIMX', 'BINC', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Bull (2023–2024): 13/22 tickers | weight coverage 63.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 5Y (2021–2025): 13/22 tickers | weight coverage 63.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 10Y (2016–2025): 13/22 tickers | weight coverage 63.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 20Y (2006–2025): 13/22 tickers | weight coverage 63.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']

FFG Qualified - 65-35:
  Bear (2007–2008): 5/22 tickers | weight coverage 27.0%
    Missing: ['DYNF', 'QUAL', 'BAI', 'CIBR', 'SHLD', 'THRO', 'BROIX', 'GQGIX', 'GSIMX', 'BINC', 'BSIIX', 'IUSB', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Baseline (2010–2019): 9/22 tickers | weight coverage 55.0%
    Missing: ['BAI', 'SHLD', 'THRO', 'BROIX', 'GQGIX', 'GSIMX', 'BINC', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Bull (2023–2024): 13/22 tickers | weight coverage 66.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 5Y (2021–2025): 13/22 tickers | weight coverage 66.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 10Y (2016–2025): 13/22 tickers | weight coverage 66.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']
  Past 20Y (2006–2025): 13/22 tickers | weight coverage 66.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'VEGBX', 'BIMBX']

FFG Qualified - 70-30:
  Bear (2007–2008): 5/21 tickers | weight coverage 28.0%
    Missing: ['DYNF', 'QUAL', 'BAI', 'CIBR', 'SHLD', 'THRO', 'BROIX', 'GQGIX', 'GSIMX', 'BINC', 'BSIIX', 'IUSB', 'MAHQX', 'PIMIX', 'PFUIX', 'BIMBX']
  Baseline (2010–2019): 9/21 tickers | weight coverage 57.0%
    Missing: ['BAI', 'SHLD', 'THRO', 'BROIX', 'GQGIX', 'GSIMX', 'BINC', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'BIMBX']
  Bull (2023–2024): 13/21 tickers | weight coverage 69.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'BIMBX']
  Past 5Y (2021–2025): 13/21 tickers | weight coverage 69.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'BIMBX']
  Past 10Y (2016–2025): 13/21 tickers | weight coverage 69.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'BIMBX']
  Past 20Y (2006–2025): 13/21 tickers | weight coverage 69.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'BIMBX']

FFG Qualified - 75-25:
  Bear (2007–2008): 5/21 tickers | weight coverage 29.0%
    Missing: ['DYNF', 'QUAL', 'BAI', 'CIBR', 'SHLD', 'THRO', 'BROIX', 'GQGIX', 'GSIMX', 'BINC', 'BSIIX', 'IUSB', 'MAHQX', 'PIMIX', 'PFUIX', 'BIMBX']
  Baseline (2010–2019): 9/21 tickers | weight coverage 59.0%
    Missing: ['BAI', 'SHLD', 'THRO', 'BROIX', 'GQGIX', 'GSIMX', 'BINC', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'BIMBX']
  Bull (2023–2024): 13/21 tickers | weight coverage 70.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'BIMBX']
  Past 5Y (2021–2025): 13/21 tickers | weight coverage 70.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'BIMBX']
  Past 10Y (2016–2025): 13/21 tickers | weight coverage 70.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'BIMBX']
  Past 20Y (2006–2025): 13/21 tickers | weight coverage 70.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'BIMBX']

FFG Qualified - 80-20:
  Bear (2007–2008): 5/20 tickers | weight coverage 30.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'IUSB', 'DYNF', 'QUAL', 'BAI', 'CIBR', 'SHLD', 'THRO', 'MAHQX', 'PIMIX', 'PFUIX', 'BIMBX']
  Baseline (2010–2019): 9/20 tickers | weight coverage 61.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'BAI', 'SHLD', 'THRO', 'MAHQX', 'PIMIX', 'PFUIX', 'BIMBX']
  Bull (2023–2024): 12/20 tickers | weight coverage 71.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'BIMBX']
  Past 5Y (2021–2025): 12/20 tickers | weight coverage 71.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'BIMBX']
  Past 10Y (2016–2025): 12/20 tickers | weight coverage 71.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'BIMBX']
  Past 20Y (2006–2025): 12/20 tickers | weight coverage 71.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'BSIIX', 'MAHQX', 'PIMIX', 'PFUIX', 'BIMBX']

FFG Qualified - 90-10:
  Bear (2007–2008): 4/16 tickers | weight coverage 32.0%
    Missing: ['DYNF', 'QUAL', 'BAI', 'CIBR', 'SHLD', 'THRO', 'BROIX', 'GQGIX', 'GSIMX', 'IUSB', 'PIMIX', 'BIMBX']
  Baseline (2010–2019): 8/16 tickers | weight coverage 65.0%
    Missing: ['BAI', 'SHLD', 'THRO', 'BROIX', 'GQGIX', 'GSIMX', 'PIMIX', 'BIMBX']
  Bull (2023–2024): 11/16 tickers | weight coverage 77.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'PIMIX', 'BIMBX']
  Past 5Y (2021–2025): 11/16 tickers | weight coverage 77.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'PIMIX', 'BIMBX']
  Past 10Y (2016–2025): 11/16 tickers | weight coverage 77.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'PIMIX', 'BIMBX']
  Past 20Y (2006–2025): 11/16 tickers | weight coverage 77.0%
    Missing: ['BROIX', 'GQGIX', 'GSIMX', 'PIMIX', 'BIMBX']

FFG Taxable High - 0-100:
  Bear (2007–2008): 1/7 tickers | weight coverage 12.0%
    Missing: ['FMB', 'HIMU', 'INMU', 'VWIUX', 'VTIP', 'BIMBX']
  Baseline (2010–2019): 3/7 tickers | weight coverage 40.0%
    Missing: ['HIMU', 'INMU', 'VWIUX', 'BIMBX']
  Bull (2023–2024): 4/7 tickers | weight coverage 65.0%
    Missing: ['HIMU', 'VWIUX', 'BIMBX']
  Past 5Y (2021–2025): 5/7 tickers | weight coverage 73.0%
    Missing: ['VWIUX', 'BIMBX']
  Past 10Y (2016–2025): 5/7 tickers | weight coverage 73.0%
    Missing: ['VWIUX', 'BIMBX']
  Past 20Y (2006–2025): 5/7 tickers | weight coverage 73.0%
    Missing: ['VWIUX', 'BIMBX']

FFG Taxable High - 10-90:
  Bear (2007–2008): 4/13 tickers | weight coverage 17.0%
    Missing: ['DYNF', 'QUAL', 'BROIX', 'FMB', 'HIMU', 'INMU', 'VWIUX', 'VTIP', 'BIMBX']
  Baseline (2010–2019): 8/13 tickers | weight coverage 45.0%
    Missing: ['BROIX', 'HIMU', 'INMU', 'VWIUX', 'BIMBX']
  Bull (2023–2024): 9/13 tickers | weight coverage 67.0%
    Missing: ['BROIX', 'HIMU', 'VWIUX', 'BIMBX']
  Past 5Y (2021–2025): 10/13 tickers | weight coverage 74.0%
    Missing: ['BROIX', 'VWIUX', 'BIMBX']
  Past 10Y (2016–2025): 10/13 tickers | weight coverage 74.0%
    Missing: ['BROIX', 'VWIUX', 'BIMBX']
  Past 20Y (2006–2025): 10/13 tickers | weight coverage 74.0%
    Missing: ['BROIX', 'VWIUX', 'BIMBX']

FFG Taxable High - 100-0:
  Bear (2007–2008): 4/13 tickers | weight coverage 37.0%
    Missing: ['DYNF', 'QUAL', 'BAI', 'CIBR', 'SHLD', 'THRO', 'BROIX', 'IEMG', 'GSIMX']
  Baseline (2010–2019): 8/13 tickers | weight coverage 71.0%
    Missing: ['BAI', 'SHLD', 'THRO', 'BROIX', 'GSIMX']
  Bull (2023–2024): 11/13 tickers | weight coverage 84.0%
    Missing: ['BROIX', 'GSIMX']
  Past 5Y (2021–2025): 11/13 tickers | weight coverage 84.0%
    Missing: ['BROIX', 'GSIMX']
  Past 10Y (2016–2025): 11/13 tickers | weight coverage 84.0%
    Missing: ['BROIX', 'GSIMX']
  Past 20Y (2006–2025): 11/13 tickers | weight coverage 84.0%
    Missing: ['BROIX', 'GSIMX']

FFG Taxable High - 20-80:
  Bear (2007–2008): 5/18 tickers | weight coverage 18.0%
    Missing: ['DYNF', 'QUAL', 'CIBR', 'THRO', 'BROIX', 'IEMG', 'GSIMX', 'FMB', 'HIMU', 'INMU', 'VWIUX', 'VTIP', 'BIMBX']
  Baseline (2010–2019): 11/18 tickers | weight coverage 48.0%
    Missing: ['THRO', 'BROIX', 'GSIMX', 'HIMU', 'INMU', 'VWIUX', 'BIMBX']
  Bull (2023–2024): 13/18 tickers | weight coverage 69.0%
    Missing: ['BROIX', 'GSIMX', 'HIMU', 'VWIUX', 'BIMBX']
  Past 5Y (2021–2025): 14/18 tickers | weight coverage 75.0%
    Missing: ['BROIX', 'GSIMX', 'VWIUX', 'BIMBX']
  Past 10Y (2016–2025): 14/18 tickers | weight coverage 75.0%
    Missing: ['BROIX', 'GSIMX', 'VWIUX', 'BIMBX']
  Past 20Y (2006–2025): 14/18 tickers | weight coverage 75.0%
    Missing: ['BROIX', 'GSIMX', 'VWIUX', 'BIMBX']

FFG Taxable High - 30-70:
  Bear (2007–2008): 5/18 tickers | weight coverage 21.0%
    Missing: ['DYNF', 'QUAL', 'CIBR', 'THRO', 'BROIX', 'IEMG', 'GSIMX', 'FMB', 'HIMU', 'INMU', 'VWIUX', 'VTIP', 'BIMBX']
  Baseline (2010–2019): 11/18 tickers | weight coverage 52.0%
    Missing: ['THRO', 'BROIX', 'GSIMX', 'HIMU', 'INMU', 'VWIUX', 'BIMBX']
  Bull (2023–2024): 13/18 tickers | weight coverage 71.0%
    Missing: ['BROIX', 'GSIMX', 'HIMU', 'VWIUX', 'BIMBX']
  Past 5Y (2021–2025): 14/18 tickers | weight coverage 76.0%
    Missing: ['BROIX', 'GSIMX', 'VWIUX', 'BIMBX']
  Past 10Y (2016–2025): 14/18 tickers | weight coverage 76.0%
    Missing: ['BROIX', 'GSIMX', 'VWIUX', 'BIMBX']
  Past 20Y (2006–2025): 14/18 tickers | weight coverage 76.0%
    Missing: ['BROIX', 'GSIMX', 'VWIUX', 'BIMBX']

FFG Taxable High - 35-65:
  Bear (2007–2008): 5/19 tickers | weight coverage 23.0%
    Missing: ['DYNF', 'QUAL', 'BAI', 'CIBR', 'THRO', 'BROIX', 'IEMG', 'GSIMX', 'FMB', 'HIMU', 'INMU', 'VWIUX', 'VTIP', 'BIMBX']
  Baseline (2010–2019): 11/19 tickers | weight coverage 51.0%
    Missing: ['BAI', 'THRO', 'BROIX', 'GSIMX', 'HIMU', 'INMU', 'VWIUX', 'BIMBX']
  Bull (2023–2024): 14/19 tickers | weight coverage 71.0%
    Missing: ['BROIX', 'GSIMX', 'HIMU', 'VWIUX', 'BIMBX']
  Past 5Y (2021–2025): 15/19 tickers | weight coverage 76.0%
    Missing: ['BROIX', 'GSIMX', 'VWIUX', 'BIMBX']
  Past 10Y (2016–2025): 15/19 tickers | weight coverage 76.0%

In [6]:
# ══════════════════════════════════════════════════════════════════════════════
# CELL 6 — METRICS WRAPPER
# Wraps compute_strategy_metrics() to return title-case keys for consistency
# with the results DataFrame columns used in later cells.
# ══════════════════════════════════════════════════════════════════════════════

def compute_metrics(nav_series, initial_capital, benchmark_nav=None):
    """
    Compute full performance metrics for a NAV Series.
    Returns title-case keys matching the results DataFrame columns.
    """
    if nav_series is None or len(nav_series) < 2:
        return {}
    bm_vals = None
    if benchmark_nav is not None:
        bm_aligned = benchmark_nav.reindex(nav_series.index).ffill().dropna()
        common = nav_series.index.intersection(bm_aligned.index)
        if len(common) > 2:
            bm_vals = bm_aligned.loc[common].values
            nav_series = nav_series.loc[common]
    m = compute_strategy_metrics(nav_series, initial_capital, benchmark_values=bm_vals)
    return {
        'Final NAV ($)':     round(nav_series.iloc[-1], 2),
        'Total Return':      m['total_return'],
        'CAGR':              m['cagr'],
        'Volatility':        m['annualized_vol'],
        'Sharpe Ratio':      m['sharpe'],
        'Max Drawdown':      m['max_drawdown'],
        'Skewness':          m['skewness'],
        'Kurtosis':          m['kurtosis'],
        'Tracking Error':    m['tracking_error'],
        'Information Ratio': m['information_ratio'],
    }


print('compute_metrics wrapper ready.')

compute_metrics wrapper ready.

In [7]:
# ══════════════════════════════════════════════════════════════════════════════
# CELL 7 — MAIN SIMULATION LOOP  (V1 engine, parallelized)
#
# Phase 0: Build job list — pre-filter prices ONCE per period (not per portfolio)
# Phase 1: Run all simulations in parallel via joblib
# Phase 2: Pair TLH-on/off results, compute metrics (sequential, fast)
# ══════════════════════════════════════════════════════════════════════════════

import os
from time import time

try:
    from joblib import Parallel, delayed
    N_JOBS = max(1, os.cpu_count() - 1)
except ImportError:
    N_JOBS = 1

print(f'Parallelization: {N_JOBS} workers' if N_JOBS > 1 else 'Running sequentially (install joblib for parallel)')


def _run_sim_safe(repo_root_str, sim_params):
    """Worker: run one simulation inside a spawned process."""
    import sys
    if repo_root_str not in sys.path:
        sys.path.insert(0, repo_root_str)
    from optimizer_msba_v1_engine import run_optimizer_simulation as _run
    try:
        return {'ok': True, 'res': _run(**sim_params)}
    except Exception as e:
        return {'ok': False, 'error': str(e)}


# ── Phase 0: Build job list ──────────────────────────────────────────────────
t0 = time()
jobs = []

n_portfolios = len(PORTFOLIOS)
n_periods = len(TIME_PERIODS)
print(f'\nPhase 0: Building jobs for {n_portfolios} portfolios x {n_periods} periods ...')

# Pre-filter prices ONCE per period (avoid 948 full-DataFrame scans)
period_prices_cache = {}
for period_name, (start, end) in TIME_PERIODS.items():
    period_prices_cache[period_name] = prices_raw[
        (prices_raw['PRICEDATE'] >= pd.Timestamp(start)) &
        (prices_raw['PRICEDATE'] <= pd.Timestamp(end))
    ].copy()
    print(f'  Cached {period_name}: {len(period_prices_cache[period_name]):,} rows')

port_count = 0
for port_name, port_dict in PORTFOLIOS.items():
    port_count += 1
    tickers = list(port_dict.keys())

    for period_name, (start, end) in TIME_PERIODS.items():
        period_prices = period_prices_cache[period_name]

        # Build wide price matrix from period-cached prices
        subset = period_prices[period_prices['TICKERSYMBOL'].isin(tickers)].copy()
        if subset.empty:
            continue
        subset = subset.drop_duplicates(subset=['TICKERSYMBOL', 'PRICEDATE'])
        wide = subset.pivot(index='PRICEDATE', columns='TICKERSYMBOL', values=PRICE_FIELD)
        wide = wide.sort_index().dropna()
        avail_tickers = [t for t in tickers if t in wide.columns]

        raw_weights  = {t: port_dict[t] for t in avail_tickers}
        total_w      = sum(raw_weights.values())
        if total_w < 1e-6 or not avail_tickers:
            continue
        norm_weights = {t: w / total_w for t, w in raw_weights.items()}
        norm_w_list  = [norm_weights[t] for t in avail_tickers]

        period_proxy_df = build_proxy_df(avail_tickers, start, end, period_prices)

        # Pre-filter prices to only tickers this portfolio+proxies need
        all_needed = set(avail_tickers)
        if not period_proxy_df.empty:
            all_needed |= set(period_proxy_df['lookup_symbol'].unique())
        group_prices = period_prices[
            period_prices['TICKERSYMBOL'].isin(all_needed)
        ].copy()

        strategies = []
        for freq in CALENDAR_FREQS:
            strategies.append(('calendar', freq))
        for tol in ABS_THRESHOLDS:
            strategies.append(('abs', tol))
        for tol in REL_THRESHOLDS:
            strategies.append(('rel', tol))

        for strat_type, strat_val in strategies:
            strat_key = f'{strat_type}_{strat_val}'

            _trigger_dates = set()
            _threshold_rebal_count = 0
            if strat_type in ('abs', 'rel'):
                drift_mode = 'Absolute' if strat_type == 'abs' else 'Relative'
                if not wide.empty and len(avail_tickers) > 0:
                    _shares = {tk: INITIAL_CAPITAL * norm_weights[tk] / float(wide.iloc[0][tk])
                               for tk in avail_tickers if tk in wide.columns and wide.iloc[0][tk] > 0}
                    if _shares:
                        _cooldown = 0
                        for _i, _dt in enumerate(wide.index):
                            if _i == 0:
                                continue
                            _pt = {tk: float(wide.loc[_dt, tk]) for tk in _shares}
                            _tv = sum(_shares[tk] * _pt[tk] for tk in _shares)
                            if _tv <= 0:
                                continue
                            _cw = {tk: _shares[tk] * _pt[tk] / _tv for tk in _shares}
                            _drift = compute_drift(_cw, {tk: norm_weights[tk] for tk in _shares}, drift_mode)
                            if _cooldown <= 0 and any(_drift[tk] > strat_val for tk in _shares):
                                _trigger_dates.add(_dt)
                                _cooldown = 5
                                for tk in _shares:
                                    _shares[tk] = norm_weights[tk] * _tv / _pt[tk] if _pt[tk] > 0 else _shares[tk]
                            if _cooldown > 0:
                                _cooldown -= 1
                        _threshold_rebal_count = len(_trigger_dates & set(wide.index))

            for tlh_on in [False, True]:
                label = strategy_label(strat_type, strat_val, tlh_on)
                _tlh_thresh = TLH_THRESHOLD if tlh_on else 0.0

                params = dict(
                    prices_df=group_prices,
                    dividends_df=div_df,
                    tickers=avail_tickers,
                    weights=norm_w_list,
                    start_date=start,
                    end_date=end,
                    rebalance_frequency=strat_val if strat_type == 'calendar' else 'None',
                    tax_rates=TAX_RATES,
                    tlh_threshold=_tlh_thresh,
                    reinvest_dividends=True,
                    initial_capital=INITIAL_CAPITAL,
                    price_field=PRICE_FIELD,
                    static=False,
                    cost_config=COST_CONFIG,
                    proxy_df=period_proxy_df,
                    wash_sale_days=30,
                    compute_tax_alpha=tlh_on,
                )
                if strat_type != 'calendar':
                    params['forced_rebalance_dates'] = _trigger_dates

                meta = dict(
                    port_name=port_name, period_name=period_name,
                    strat_type=strat_type, strat_val=strat_val,
                    strat_key=strat_key, tlh_on=tlh_on, label=label,
                    threshold_rebal_count=_threshold_rebal_count,
                )
                jobs.append((params, meta))

    if port_count % 20 == 0 or port_count == n_portfolios:
        print(f'  {port_count}/{n_portfolios} portfolios prepared ({len(jobs):,} jobs so far) [{time()-t0:.0f}s]')

print(f'Phase 0 complete: {len(jobs):,} jobs in {time() - t0:.1f}s')

# ── Phase 1: Run simulations ─────────────────────────────────────────────────
print(f'\nPhase 1: Running {len(jobs):,} simulations ({N_JOBS} workers) ...')
t1 = time()
_repo_str = str(REPO_ROOT)

if N_JOBS > 1:
    raw_results = Parallel(n_jobs=N_JOBS, verbose=10)(
        delayed(_run_sim_safe)(_repo_str, p) for p, _ in jobs
    )
else:
    raw_results = []
    for i, (p, m) in enumerate(jobs):
        raw_results.append(_run_sim_safe(_repo_str, p))
        if (i + 1) % 50 == 0 or i == len(jobs) - 1:
            print(f'  {i + 1:,}/{len(jobs):,} done [{time()-t1:.0f}s]')

elapsed = time() - t1
print(f'Phase 1 complete: {elapsed:.1f}s  ({elapsed / max(len(jobs),1):.2f}s/run)')

# ── Phase 2: Assemble results ────────────────────────────────────────────────
print(f'\nPhase 2: Assembling results ...')
t2 = time()
all_results   = []
nav_store     = {}
failed_runs   = []

# First pass: collect TLH-off benchmarks for tracking error
benchmark_navs = {}
for (_, meta), raw in zip(jobs, raw_results):
    if raw['ok'] and not meta['tlh_on']:
        bm_key = (meta['port_name'], meta['period_name'], meta['strat_key'])
        benchmark_navs[bm_key] = raw['res']['nav_series']

# Second pass: build all result rows
for (_, meta), raw in zip(jobs, raw_results):
    run_id = (meta['port_name'], meta['period_name'], meta['label'])

    if not raw['ok']:
        failed_runs.append({'run_id': run_id, 'error': raw['error']})
        continue

    res = raw['res']
    nav_series = res['nav_series']
    nav_store[run_id] = nav_series

    _rdf = res.get('realized_df', pd.DataFrame())
    _tlh_events = int(_rdf['reason'].str.startswith('TLH_SELL').sum()) \
        if not _rdf.empty and 'reason' in _rdf.columns else 0
    _tlh_losses = _rebal_losses = 0.0
    if not _rdf.empty and 'reason' in _rdf.columns and 'gain_loss' in _rdf.columns:
        _is_tlh  = _rdf['reason'].str.startswith('TLH_SELL')
        _is_init = _rdf['reason'].str.startswith('INIT')
        _tlh_losses   = float(_rdf.loc[_is_tlh  & (_rdf['gain_loss'] < 0), 'gain_loss'].abs().sum())
        _rebal_losses = float(_rdf.loc[~_is_tlh & ~_is_init & (_rdf['gain_loss'] < 0), 'gain_loss'].abs().sum())

    extra_fields = {
        'Tax Paid ($)':              res.get('tax_paid_total', 0),
        'Losses Harvested ($)':      res.get('losses_harvested', 0),
        'TLH Losses ($)':            _tlh_losses,
        'Rebal Losses ($)':          _rebal_losses,
        'TLH Events':                _tlh_events,
        'Exec Costs ($)':            res.get('transaction_costs_total', 0),
        'Tax Alpha 2 ($)':           res.get('tax_alpha_2_final', None),
        'Loss CF ST ($)':            res.get('loss_carryforward_st', None),
        'Loss CF LT ($)':            res.get('loss_carryforward_lt', None),
        'Liquidation NAV ($)':       res.get('liquidation_nav', None),
        'Unrealized Gain ST ($)':    res.get('unrealized_gain_st', None),
        'Unrealized Gain LT ($)':    res.get('unrealized_gain_lt', None),
        'Liquidation Tax ($)':       res.get('liquidation_tax', None),
        'Liquidation Exec Cost ($)': res.get('liquidation_exec_cost', None),
    }
    if meta['strat_type'] in ('abs', 'rel'):
        extra_fields['Threshold Rebal Count'] = meta['threshold_rebal_count']

    bm_key = (meta['port_name'], meta['period_name'], meta['strat_key'])
    bm_nav = benchmark_navs.get(bm_key) if meta['tlh_on'] else None
    metrics = compute_metrics(nav_series, INITIAL_CAPITAL, benchmark_nav=bm_nav)

    _pm = PORTFOLIO_META.get(meta['port_name'], {})
    row = {
        'Portfolio':       meta['port_name'],
        'Model Family':    _pm.get('model_family', ''),
        'Category':        _pm.get('category', ''),
        'Equity %':        _pm.get('equity_pct', 0.0),
        'Period':          meta['period_name'],
        'Strategy':        meta['label'],
        'Strategy Type':   meta['strat_type'],
        'Strategy Value':  meta['strat_val'],
        'TLH':             'On (10%)' if meta['tlh_on'] else 'Off',
        'Rebal/Threshold': meta['strat_key'],
    }
    row.update(metrics)
    row.update(extra_fields)
    all_results.append(row)

# ── Summary ──────────────────────────────────────────────────────────────────
total_time = time() - t0
print(f'\n{"=" * 80}')
print(f'Complete: {len(all_results):,} succeeded, {len(failed_runs):,} failed')
print(f'Time: Phase 0={time()-t0-elapsed-(time()-t2):.0f}s  Phase 1={elapsed:.0f}s  Phase 2={time()-t2:.0f}s  Total={total_time:.0f}s')
if failed_runs:
    # Show summary, not all failures
    error_counts = {}
    for f in failed_runs:
        e = f['error'][:80]
        error_counts[e] = error_counts.get(e, 0) + 1
    print(f'\nFailure summary ({len(failed_runs):,} total):')
    for err, cnt in sorted(error_counts.items(), key=lambda x: -x[1])[:10]:
        print(f'  {cnt:4d}x  {err}')

Parallelization: 7 workers

Phase 0: Building jobs for 158 portfolios x 6 periods ...
  Cached Bear (2007–2008): 100,903 rows
  Cached Baseline (2010–2019): 959,917 rows
  Cached Bull (2023–2024): 331,544 rows
  Cached Past 5Y (2021–2025): 807,628 rows
  Cached Past 10Y (2016–2025): 1,427,258 rows
  Cached Past 20Y (2006–2025): 2,102,521 rows
  20/158 portfolios prepared (1,920 jobs so far) [41s]
  40/158 portfolios prepared (3,840 jobs so far) [75s]
  60/158 portfolios prepared (5,760 jobs so far) [109s]
  80/158 portfolios prepared (7,680 jobs so far) [146s]
  100/158 portfolios prepared (9,600 jobs so far) [190s]
  120/158 portfolios prepared (11,504 jobs so far) [229s]
  140/158 portfolios prepared (13,408 jobs so far) [269s]
  158/158 portfolios prepared (15,136 jobs so far) [310s]
Phase 0 complete: 15,136 jobs in 309.7s

Phase 1: Running 15,136 simulations (7 workers) ...

[Parallel(n_jobs=7)]: Using backend LokyBackend with 7 concurrent workers.
[Parallel(n_jobs=7)]: Done   4 tasks      | elapsed:    1.1s
[Parallel(n_jobs=7)]: Done  11 tasks      | elapsed:    1.3s
[Parallel(n_jobs=7)]: Done  18 tasks      | elapsed:    1.8s
[Parallel(n_jobs=7)]: Done  27 tasks      | elapsed:    2.5s
[Parallel(n_jobs=7)]: Done  36 tasks      | elapsed:    3.1s
[Parallel(n_jobs=7)]: Done  47 tasks      | elapsed:    3.7s
[Parallel(n_jobs=7)]: Done  58 tasks      | elapsed:    4.4s
[Parallel(n_jobs=7)]: Done  71 tasks      | elapsed:    5.3s
[Parallel(n_jobs=7)]: Done  84 tasks      | elapsed:    6.3s
[Parallel(n_jobs=7)]: Done  99 tasks      | elapsed:    7.3s
[Parallel(n_jobs=7)]: Done 114 tasks      | elapsed:    7.9s
[Parallel(n_jobs=7)]: Done 131 tasks      | elapsed:    9.0s
[Parallel(n_jobs=7)]: Done 148 tasks      | elapsed:   10.5s
[Parallel(n_jobs=7)]: Done 167 tasks      | elapsed:   12.9s
[Parallel(n_jobs=7)]: Done 186 tasks      | elapsed:   15.4s
[Parallel(n_jobs=7)]: Done 207 tasks      | elapsed:   16.7s
[Parallel(n_jobs=7)]: Done 228 tasks      | elapsed:   17.4s
[Parallel(n_jobs=7)]: Done 251 tasks      | elapsed:   18.7s
[Parallel(n_jobs=7)]: Done 274 tasks      | elapsed:   20.4s
[Parallel(n_jobs=7)]: Done 299 tasks      | elapsed:   21.9s
[Parallel(n_jobs=7)]: Done 324 tasks      | elapsed:   23.2s
[Parallel(n_jobs=7)]: Done 351 tasks      | elapsed:   26.4s
[Parallel(n_jobs=7)]: Done 378 tasks      | elapsed:   30.5s
[Parallel(n_jobs=7)]: Done 407 tasks      | elapsed:   32.1s
[Parallel(n_jobs=7)]: Done 436 tasks      | elapsed:   33.7s
[Parallel(n_jobs=7)]: Done 467 tasks      | elapsed:   36.8s
[Parallel(n_jobs=7)]: Done 498 tasks      | elapsed:   39.2s
[Parallel(n_jobs=7)]: Done 531 tasks      | elapsed:   40.8s
[Parallel(n_jobs=7)]: Done 564 tasks      | elapsed:   44.4s
[Parallel(n_jobs=7)]: Done 599 tasks      | elapsed:   46.7s
[Parallel(n_jobs=7)]: Done 634 tasks      | elapsed:   49.8s
[Parallel(n_jobs=7)]: Done 671 tasks      | elapsed:   55.9s
[Parallel(n_jobs=7)]: Done 708 tasks      | elapsed:   58.0s
[Parallel(n_jobs=7)]: Done 747 tasks      | elapsed:  1.0min
[Parallel(n_jobs=7)]: Done 786 tasks      | elapsed:  1.1min
[Parallel(n_jobs=7)]: Done 827 tasks      | elapsed:  1.1min
[Parallel(n_jobs=7)]: Done 868 tasks      | elapsed:  1.2min
[Parallel(n_jobs=7)]: Done 911 tasks      | elapsed:  1.2min
[Parallel(n_jobs=7)]: Done 954 tasks      | elapsed:  1.3min
[Parallel(n_jobs=7)]: Done 999 tasks      | elapsed:  1.3min
[Parallel(n_jobs=7)]: Done 1044 tasks      | elapsed:  1.4min
[Parallel(n_jobs=7)]: Done 1091 tasks      | elapsed:  1.4min
[Parallel(n_jobs=7)]: Done 1138 tasks      | elapsed:  1.5min
[Parallel(n_jobs=7)]: Done 1187 tasks      | elapsed:  1.5min
[Parallel(n_jobs=7)]: Done 1236 tasks      | elapsed:  1.6min
[Parallel(n_jobs=7)]: Done 1287 tasks      | elapsed:  1.7min
[Parallel(n_jobs=7)]: Done 1338 tasks      | elapsed:  1.7min
[Parallel(n_jobs=7)]: Done 1391 tasks      | elapsed:  1.8min
[Parallel(n_jobs=7)]: Done 1444 tasks      | elapsed:  1.9min
[Parallel(n_jobs=7)]: Done 1499 tasks      | elapsed:  1.9min
[Parallel(n_jobs=7)]: Done 1554 tasks      | elapsed:  2.0min
[Parallel(n_jobs=7)]: Done 1611 tasks      | elapsed:  2.0min
[Parallel(n_jobs=7)]: Done 1668 tasks      | elapsed:  2.0min
[Parallel(n_jobs=7)]: Done 1727 tasks      | elapsed:  2.1min
[Parallel(n_jobs=7)]: Done 1786 tasks      | elapsed:  2.2min
[Parallel(n_jobs=7)]: Done 1847 tasks      | elapsed:  2.2min
[Parallel(n_jobs=7)]: Done 1908 tasks      | elapsed:  2.3min
[Parallel(n_jobs=7)]: Done 1971 tasks      | elapsed:  2.4min
[Parallel(n_jobs=7)]: Done 2034 tasks      | elapsed:  2.4min
[Parallel(n_jobs=7)]: Done 2099 tasks      | elapsed:  2.5min
[Parallel(n_jobs=7)]: Done 2164 tasks      | elapsed:  2.6min
[Parallel(n_jobs=7)]: Done 2231 tasks      | elapsed:  2.7min
[Parallel(n_jobs=7)]: Done 2298 tasks      | elapsed:  2.8min
[Parallel(n_jobs=7)]: Done 2367 tasks      | elapsed:  2.8min
[Parallel(n_jobs=7)]: Done 2436 tasks      | elapsed:  2.9min
[Parallel(n_jobs=7)]: Done 2507 tasks      | elapsed:  3.1min
[Parallel(n_jobs=7)]: Done 2578 tasks      | elapsed:  3.2min
[Parallel(n_jobs=7)]: Done 2651 tasks      | elapsed:  3.2min
[Parallel(n_jobs=7)]: Done 2724 tasks      | elapsed:  3.3min
[Parallel(n_jobs=7)]: Done 2799 tasks      | elapsed:  3.5min
[Parallel(n_jobs=7)]: Done 2874 tasks      | elapsed:  3.6min
[Parallel(n_jobs=7)]: Done 2951 tasks      | elapsed:  3.6min
[Parallel(n_jobs=7)]: Done 3028 tasks      | elapsed:  3.7min
[Parallel(n_jobs=7)]: Done 3107 tasks      | elapsed:  3.8min
[Parallel(n_jobs=7)]: Done 3186 tasks      | elapsed:  3.9min
[Parallel(n_jobs=7)]: Done 3267 tasks      | elapsed:  4.1min
[Parallel(n_jobs=7)]: Done 3348 tasks      | elapsed:  4.1min
[Parallel(n_jobs=7)]: Done 3431 tasks      | elapsed:  4.3min
[Parallel(n_jobs=7)]: Done 3514 tasks      | elapsed:  4.4min
[Parallel(n_jobs=7)]: Done 3599 tasks      | elapsed:  4.5min
[Parallel(n_jobs=7)]: Done 3684 tasks      | elapsed:  4.6min
[Parallel(n_jobs=7)]: Done 3771 tasks      | elapsed:  4.8min
[Parallel(n_jobs=7)]: Done 3858 tasks      | elapsed:  4.9min
[Parallel(n_jobs=7)]: Done 3947 tasks      | elapsed:  5.0min
[Parallel(n_jobs=7)]: Done 4036 tasks      | elapsed:  5.1min
[Parallel(n_jobs=7)]: Done 4127 tasks      | elapsed:  5.2min
[Parallel(n_jobs=7)]: Done 4218 tasks      | elapsed:  5.3min
[Parallel(n_jobs=7)]: Done 4311 tasks      | elapsed:  5.4min
[Parallel(n_jobs=7)]: Done 4404 tasks      | elapsed:  5.5min
[Parallel(n_jobs=7)]: Done 4499 tasks      | elapsed:  5.6min
[Parallel(n_jobs=7)]: Done 4594 tasks      | elapsed:  5.8min
[Parallel(n_jobs=7)]: Done 4691 tasks      | elapsed:  5.9min
[Parallel(n_jobs=7)]: Done 4788 tasks      | elapsed:  6.0min
[Parallel(n_jobs=7)]: Done 4887 tasks      | elapsed:  6.1min
[Parallel(n_jobs=7)]: Done 4986 tasks      | elapsed:  6.2min
[Parallel(n_jobs=7)]: Done 5087 tasks      | elapsed:  6.3min
[Parallel(n_jobs=7)]: Done 5188 tasks      | elapsed:  6.4min
[Parallel(n_jobs=7)]: Done 5291 tasks      | elapsed:  6.5min
[Parallel(n_jobs=7)]: Done 5394 tasks      | elapsed:  6.6min
[Parallel(n_jobs=7)]: Done 5499 tasks      | elapsed:  6.7min
[Parallel(n_jobs=7)]: Done 5604 tasks      | elapsed:  6.9min
[Parallel(n_jobs=7)]: Done 5711 tasks      | elapsed:  7.0min
[Parallel(n_jobs=7)]: Done 5818 tasks      | elapsed:  7.2min
[Parallel(n_jobs=7)]: Done 5927 tasks      | elapsed:  7.3min
[Parallel(n_jobs=7)]: Done 6036 tasks      | elapsed:  7.4min
[Parallel(n_jobs=7)]: Done 6147 tasks      | elapsed:  7.5min
[Parallel(n_jobs=7)]: Done 6258 tasks      | elapsed:  7.7min
[Parallel(n_jobs=7)]: Done 6371 tasks      | elapsed:  7.9min
[Parallel(n_jobs=7)]: Done 6484 tasks      | elapsed:  8.1min
[Parallel(n_jobs=7)]: Done 6599 tasks      | elapsed:  8.3min
[Parallel(n_jobs=7)]: Done 6714 tasks      | elapsed:  8.5min
[Parallel(n_jobs=7)]: Done 6831 tasks      | elapsed:  8.6min
[Parallel(n_jobs=7)]: Done 6948 tasks      | elapsed:  8.7min
[Parallel(n_jobs=7)]: Done 7067 tasks      | elapsed:  8.9min
[Parallel(n_jobs=7)]: Done 7186 tasks      | elapsed:  9.0min
[Parallel(n_jobs=7)]: Done 7307 tasks      | elapsed:  9.2min
[Parallel(n_jobs=7)]: Done 7428 tasks      | elapsed:  9.3min
[Parallel(n_jobs=7)]: Done 7551 tasks      | elapsed:  9.5min
[Parallel(n_jobs=7)]: Done 7674 tasks      | elapsed:  9.7min
[Parallel(n_jobs=7)]: Done 7799 tasks      | elapsed:  9.8min
[Parallel(n_jobs=7)]: Done 7924 tasks      | elapsed: 10.0min
[Parallel(n_jobs=7)]: Done 8051 tasks      | elapsed: 10.2min
[Parallel(n_jobs=7)]: Done 8178 tasks      | elapsed: 10.4min
[Parallel(n_jobs=7)]: Done 8307 tasks      | elapsed: 10.6min
[Parallel(n_jobs=7)]: Done 8436 tasks      | elapsed: 10.9min
[Parallel(n_jobs=7)]: Done 8567 tasks      | elapsed: 11.0min
[Parallel(n_jobs=7)]: Done 8698 tasks      | elapsed: 11.2min
[Parallel(n_jobs=7)]: Done 8831 tasks      | elapsed: 11.5min
[Parallel(n_jobs=7)]: Done 8964 tasks      | elapsed: 11.7min
[Parallel(n_jobs=7)]: Done 9099 tasks      | elapsed: 11.9min
[Parallel(n_jobs=7)]: Done 9234 tasks      | elapsed: 12.1min
[Parallel(n_jobs=7)]: Done 9371 tasks      | elapsed: 12.3min
[Parallel(n_jobs=7)]: Done 9508 tasks      | elapsed: 12.6min
[Parallel(n_jobs=7)]: Done 9647 tasks      | elapsed: 12.8min
[Parallel(n_jobs=7)]: Done 9786 tasks      | elapsed: 12.9min
[Parallel(n_jobs=7)]: Done 9927 tasks      | elapsed: 13.1min
[Parallel(n_jobs=7)]: Done 10068 tasks      | elapsed: 13.3min
[Parallel(n_jobs=7)]: Done 10211 tasks      | elapsed: 13.5min
[Parallel(n_jobs=7)]: Done 10354 tasks      | elapsed: 13.6min
[Parallel(n_jobs=7)]: Done 10499 tasks      | elapsed: 13.7min
[Parallel(n_jobs=7)]: Done 10644 tasks      | elapsed: 13.9min
[Parallel(n_jobs=7)]: Done 10791 tasks      | elapsed: 14.1min
[Parallel(n_jobs=7)]: Done 10938 tasks      | elapsed: 14.3min
[Parallel(n_jobs=7)]: Done 11087 tasks      | elapsed: 14.5min
[Parallel(n_jobs=7)]: Done 11236 tasks      | elapsed: 14.8min
[Parallel(n_jobs=7)]: Done 11387 tasks      | elapsed: 15.0min
[Parallel(n_jobs=7)]: Done 11538 tasks      | elapsed: 15.1min
[Parallel(n_jobs=7)]: Done 11691 tasks      | elapsed: 15.3min
[Parallel(n_jobs=7)]: Done 11844 tasks      | elapsed: 15.5min
[Parallel(n_jobs=7)]: Done 11999 tasks      | elapsed: 15.7min
[Parallel(n_jobs=7)]: Done 12154 tasks      | elapsed: 15.8min
[Parallel(n_jobs=7)]: Done 12311 tasks      | elapsed: 16.0min
[Parallel(n_jobs=7)]: Done 12468 tasks      | elapsed: 16.3min
[Parallel(n_jobs=7)]: Done 12627 tasks      | elapsed: 16.5min
[Parallel(n_jobs=7)]: Done 12786 tasks      | elapsed: 16.7min
[Parallel(n_jobs=7)]: Done 12947 tasks      | elapsed: 17.0min
[Parallel(n_jobs=7)]: Done 13108 tasks      | elapsed: 17.2min
[Parallel(n_jobs=7)]: Done 13271 tasks      | elapsed: 17.4min
[Parallel(n_jobs=7)]: Done 13434 tasks      | elapsed: 17.6min
[Parallel(n_jobs=7)]: Done 13599 tasks      | elapsed: 17.9min
[Parallel(n_jobs=7)]: Done 13764 tasks      | elapsed: 18.2min
[Parallel(n_jobs=7)]: Done 13931 tasks      | elapsed: 18.4min
[Parallel(n_jobs=7)]: Done 14098 tasks      | elapsed: 18.7min
[Parallel(n_jobs=7)]: Done 14267 tasks      | elapsed: 19.0min
[Parallel(n_jobs=7)]: Done 14436 tasks      | elapsed: 19.3min
[Parallel(n_jobs=7)]: Done 14607 tasks      | elapsed: 19.6min
[Parallel(n_jobs=7)]: Done 14778 tasks      | elapsed: 20.0min
[Parallel(n_jobs=7)]: Done 14951 tasks      | elapsed: 20.3min
[Parallel(n_jobs=7)]: Done 15136 out of 15136 | elapsed: 20.7min finished

Phase 1 complete: 1241.1s  (0.08s/run)

Phase 2: Assembling results ...

================================================================================
Complete: 15,136 succeeded, 0 failed
Time: Phase 0=310s  Phase 1=1241s  Phase 2=42s  Total=1593s

In [8]:
# ══════════════════════════════════════════════════════════════════════════════
# CELL 8 — BUILD RESULTS DATAFRAME
# ══════════════════════════════════════════════════════════════════════════════

results_df = pd.DataFrame(all_results)

# Ordered columns for display
BASE_COLS = [
    'Portfolio', 'Period', 'Strategy', 'TLH',
    'Final NAV ($)', 'Total Return', 'CAGR', 'Volatility',
    'Sharpe Ratio', 'Max Drawdown', 'Tracking Error', 'Information Ratio',
    'Skewness', 'Kurtosis',
]
TAX_COLS = [
    'Tax Paid ($)', 'Losses Harvested ($)', 'TLH Events',
    'Exec Costs ($)', 'Tax Alpha 2 ($)', 'Loss CF ST ($)', 'Loss CF LT ($)',
]
display_cols = [c for c in BASE_COLS + TAX_COLS if c in results_df.columns]

print(f'Results table: {len(results_df)} rows × {len(results_df.columns)} columns')
print(f'Columns: {display_cols}')

Results table: 15136 rows × 35 columns
Columns: ['Portfolio', 'Period', 'Strategy', 'TLH', 'Final NAV ($)', 'Total Return', 'CAGR', 'Volatility', 'Sharpe Ratio', 'Max Drawdown', 'Tracking Error', 'Information Ratio', 'Skewness', 'Kurtosis', 'Tax Paid ($)', 'Losses Harvested ($)', 'TLH Events', 'Exec Costs ($)', 'Tax Alpha 2 ($)', 'Loss CF ST ($)', 'Loss CF LT ($)']

In [18]:
# ══════════════════════════════════════════════════════════════════════════════
# CELL 9 — FULL RESULTS TABLE (per combination)
# ══════════════════════════════════════════════════════════════════════════════

fmt_pct  = lambda x: f'{x:.2%}' if pd.notna(x) else '—'
fmt_usd  = lambda x: f'${x:,.0f}' if pd.notna(x) else '—'
fmt_num  = lambda x: f'{x:.3f}' if pd.notna(x) else '—'

for (port, period), grp in results_df.groupby(['Portfolio', 'Period'], sort=False):
    # print(f'\n{'='*90}')
    # print(f'  Portfolio: {port}   |   Period: {period}')
    # print(f'{'='*90}')

    disp = grp[display_cols].copy()
    for col in ['Total Return', 'CAGR', 'Volatility', 'Max Drawdown', 'Tracking Error']:
        if col in disp.columns:
            disp[col] = disp[col].apply(fmt_pct)
    for col in ['Final NAV ($)', 'Tax Paid ($)', 'Losses Harvested ($)',
                'Exec Costs ($)', 'Tax Alpha 2 ($)', 'Loss CF ST ($)', 'Loss CF LT ($)']:
        if col in disp.columns:
            disp[col] = disp[col].apply(lambda x: fmt_usd(x) if pd.notna(x) else '—')
    for col in ['Sharpe Ratio', 'Information Ratio', 'Skewness', 'Kurtosis']:
        if col in disp.columns:
            disp[col] = disp[col].apply(fmt_num)

    # display(disp.drop(columns=['Portfolio', 'Period']).reset_index(drop=True))

In [19]:
# ══════════════════════════════════════════════════════════════════════════════
# CELL 10 — TLH VALUE-ADD TABLE
# For each TLH run, compare to its no-TLH counterpart.
# Shows: CAGR delta, Tracking Error, Info Ratio, Tax Alpha 2.
# ══════════════════════════════════════════════════════════════════════════════

print('TLH VALUE-ADD vs No-TLH Benchmark (per strategy, period, portfolio)')
print('=' * 90)

tlh_on_df  = results_df[results_df['TLH'] == 'On (10%)'].copy()
tlh_off_df = results_df[results_df['TLH'] == 'Off'].copy()

merge_keys = ['Portfolio', 'Period', 'Rebal/Threshold']
merged = tlh_on_df.merge(
    tlh_off_df[merge_keys + ['CAGR', 'Sharpe Ratio', 'Max Drawdown', 'Final NAV ($)']],
    on=merge_keys,
    suffixes=('_TLH', '_BM'),
)

merged['CAGR Delta (TLH - BM)']   = merged['CAGR_TLH'] - merged['CAGR_BM']
merged['Sharpe Delta']             = merged['Sharpe Ratio_TLH'] - merged['Sharpe Ratio_BM']
merged['NAV Gain from TLH ($)']   = merged['Final NAV ($)_TLH'] - merged['Final NAV ($)_BM']

value_add_cols = [
    'Portfolio', 'Period', 'Strategy',
    'CAGR Delta (TLH - BM)', 'Tracking Error', 'Information Ratio',
    'Sharpe Delta', 'NAV Gain from TLH ($)', 'Tax Alpha 2 ($)',
    'Losses Harvested ($)', 'Tax Paid ($)', 'Exec Costs ($)',
]
va_disp = merged[[c for c in value_add_cols if c in merged.columns]].copy()

for col in ['CAGR Delta (TLH - BM)', 'Tracking Error', 'Information Ratio', 'Sharpe Delta']:
    if col in va_disp.columns:
        va_disp[col] = va_disp[col].apply(lambda x: f'{x:+.3f}' if pd.notna(x) else '—')
for col in ['NAV Gain from TLH ($)', 'Tax Alpha 2 ($)', 'Losses Harvested ($)',
            'Tax Paid ($)', 'Exec Costs ($)']:
    if col in va_disp.columns:
        va_disp[col] = va_disp[col].apply(lambda x: f'${x:+,.0f}' if pd.notna(x) else '—')

display(va_disp.reset_index(drop=True))

TLH VALUE-ADD vs No-TLH Benchmark (per strategy, period, portfolio)
==========================================================================================

,Portfolio,Period,Strategy,CAGR Delta (TLH - BM),Tracking Error,Information Ratio,Sharpe Delta,NAV Gain from TLH ($),Tax Alpha 2 ($),Losses Harvested ($),Tax Paid ($),Exec Costs ($)
0,FFG Qualified - 0-100,Bear (2007–2008),Monthly Rebal | TLH=10%,+0.000,+0.000,+0.000,+0.000,$+0,$+0,$+0,$+0,"$+1,199"
1,FFG Qualified - 0-100,Bear (2007–2008),Quarterly Rebal | TLH=10%,+0.000,+0.000,+0.000,+0.000,$+0,$+0,$+0,$+0,"$+1,199"
2,FFG Qualified - 0-100,Bear (2007–2008),Yearly Rebal | TLH=10%,+0.000,+0.000,+0.000,+0.000,$+0,$+0,$+0,$+0,"$+1,199"
3,FFG Qualified - 0-100,Bear (2007–2008),Abs Threshold 5% | TLH=10%,+0.000,+0.000,+0.000,+0.000,$+0,$+0,$+0,$+0,"$+1,199"
4,FFG Qualified - 0-100,Bear (2007–2008),Abs Threshold 10% | TLH=10%,+0.000,+0.000,+0.000,+0.000,$+0,$+0,$+0,$+0,"$+1,199"
...,...,...,...,...,...,...,...,...,...,...,...,...
7563,Target Allocation ETF - 90-10,Past 20Y (2006–2025),Abs Threshold 5% | TLH=10%,+0.002,+0.009,+0.037,+0.007,"$+1,860","$+1,860","$+95,879","$-1,050","$+2,767"
7564,Target Allocation ETF - 90-10,Past 20Y (2006–2025),Abs Threshold 10% | TLH=10%,+0.002,+0.009,+0.037,+0.007,"$+1,860","$+1,860","$+95,879","$-1,050","$+2,767"
7565,Target Allocation ETF - 90-10,Past 20Y (2006–2025),Abs Threshold 20% | TLH=10%,+0.002,+0.009,+0.037,+0.007,"$+1,860","$+1,860","$+95,879","$-1,050","$+2,767"
7566,Target Allocation ETF - 90-10,Past 20Y (2006–2025),Rel Threshold 25% | TLH=10%,-0.007,+0.012,-0.645,-0.026,"$-8,021","$-8,021","$+103,596","$-1,050","$+3,689"
7567,Target Allocation ETF - 90-10,Past 20Y (2006–2025),Rel Threshold 50% | TLH=10%,+0.002,+0.009,+0.037,+0.007,"$+1,860","$+1,860","$+95,879","$-1,050","$+2,767"

In [20]:
# ══════════════════════════════════════════════════════════════════════════════
# CELL 13 — SUMMARY: BEST STRATEGY PER COMBINATION
# Ranks strategies within each portfolio × period by Sharpe, CAGR, and
# (for TLH-on runs) Information Ratio. Prints ranked top-3 per combo.
# ══════════════════════════════════════════════════════════════════════════════

print('TOP 3 STRATEGIES PER COMBINATION — RANKED BY SHARPE RATIO')
print('=' * 90)

for (port, period), grp in results_df.groupby(['Portfolio', 'Period'], sort=False):
    print(f'\n{'─'*90}')
    print(f'  {port}  |  {period}')
    print(f'{'─'*90}')

    # Best overall by Sharpe
    top3 = grp.nlargest(3, 'Sharpe Ratio')[[
        'Strategy', 'TLH', 'CAGR', 'Sharpe Ratio', 'Max Drawdown',
        'Tracking Error', 'Information Ratio',
    ]].copy()
    for col in ['CAGR', 'Max Drawdown', 'Tracking Error']:
        if col in top3.columns:
            top3[col] = top3[col].apply(lambda x: f'{x:.2%}' if pd.notna(x) else '—')
    for col in ['Sharpe Ratio', 'Information Ratio']:
        if col in top3.columns:
            top3[col] = top3[col].apply(lambda x: f'{x:.3f}' if pd.notna(x) else '—')
    print('  Top 3 by Sharpe Ratio (all strategies):')
    display(top3.reset_index(drop=True))

    # Best TLH-on by Info Ratio (TLH value add)
    tlh_grp = grp[grp['TLH'] == 'On (10%)'].dropna(subset=['Information Ratio'])
    if not tlh_grp.empty:
        best_tlh = tlh_grp.nlargest(3, 'Information Ratio')[[
            'Strategy', 'CAGR', 'Sharpe Ratio', 'Tracking Error', 'Information Ratio', 'Tax Alpha 2 ($)'
        ]].copy()
        for col in ['CAGR', 'Tracking Error']:
            if col in best_tlh.columns:
                best_tlh[col] = best_tlh[col].apply(lambda x: f'{x:.2%}' if pd.notna(x) else '—')
        for col in ['Sharpe Ratio', 'Information Ratio']:
            if col in best_tlh.columns:
                best_tlh[col] = best_tlh[col].apply(lambda x: f'{x:.3f}' if pd.notna(x) else '—')
        if 'Tax Alpha 2 ($)' in best_tlh.columns:
            best_tlh['Tax Alpha 2 ($)'] = best_tlh['Tax Alpha 2 ($)'].apply(
                lambda x: f'${x:+,.0f}' if pd.notna(x) else '—')
        print('  Top 3 TLH strategies by Information Ratio (TLH value-add):')
        display(best_tlh.reset_index(drop=True))

TOP 3 STRATEGIES PER COMBINATION — RANKED BY SHARPE RATIO
==========================================================================================

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 0-100  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,7.66%,0.856,-7.77%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),7.66%,0.856,-7.77%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,7.66%,0.856,-7.77%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.66%,0.856,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,7.66%,0.856,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,7.66%,0.856,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 0-100  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,1.88%,0.702,-4.69%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,1.88%,0.702,-4.69%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,1.88%,0.702,-4.69%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,1.74%,0.560,2.07%,-0.055,"$-3,721"
1,Quarterly Rebal | TLH=10%,1.65%,0.516,2.33%,-0.097,"$-8,557"
2,Yearly Rebal | TLH=10%,1.62%,0.505,2.38%,-0.107,"$-9,780"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 0-100  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,1.33%,0.280,-5.23%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),1.33%,0.280,-5.23%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,1.33%,0.280,-5.23%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,1.24%,0.263,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,1.26%,0.265,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,1.27%,0.269,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 0-100  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,2.50%,0.572,-5.23%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),2.50%,0.572,-5.23%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,2.50%,0.572,-5.23%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.33%,0.534,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,2.35%,0.538,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,2.38%,0.546,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 0-100  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,2.50%,0.572,-5.23%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),2.50%,0.572,-5.23%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,2.50%,0.572,-5.23%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.33%,0.534,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,2.35%,0.538,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,2.38%,0.546,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 0-100  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,2.50%,0.572,-5.23%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),2.50%,0.572,-5.23%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,2.50%,0.572,-5.23%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.33%,0.534,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,2.35%,0.538,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,2.38%,0.546,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 10-90  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | No TLH,Off,-3.30%,-0.406,-12.89%,0.00%,0.000
1,Rel Threshold 50% | No TLH,Off,-3.83%,-0.408,-13.76%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-4.43%,-0.448,-15.29%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,-4.83%,-0.491,1.25%,-0.141,"$-1,618"
1,Monthly Rebal | TLH=10%,-5.39%,-0.553,0.91%,-0.304,"$-3,191"
2,Abs Threshold 5% | TLH=10%,-4.88%,-0.486,1.02%,-0.504,"$-6,860"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 10-90  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,7.10%,2.033,-1.39%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),7.10%,2.033,-1.39%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,7.06%,2.020,-1.38%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.07%,2.017,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,7.10%,2.033,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,7.06%,2.020,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 10-90  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,6.41%,1.167,-5.73%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),6.41%,1.167,-5.73%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,6.41%,1.167,-5.73%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.44%,1.029,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,5.56%,1.051,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,5.95%,1.104,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 10-90  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,6.88%,1.184,-6.72%,0.00%,0.000
1,Abs Threshold 10% | TLH=10%,On (10%),6.88%,1.184,-6.72%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,6.88%,1.184,-6.72%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.75%,1.081,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,5.83%,1.094,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.08%,1.130,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 10-90  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,6.88%,1.184,-6.72%,0.00%,0.000
1,Abs Threshold 10% | TLH=10%,On (10%),6.88%,1.184,-6.72%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,6.88%,1.184,-6.72%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.75%,1.081,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,5.83%,1.094,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.08%,1.130,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 10-90  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,6.88%,1.184,-6.72%,0.00%,0.000
1,Abs Threshold 10% | TLH=10%,On (10%),6.88%,1.184,-6.72%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,6.88%,1.184,-6.72%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.75%,1.081,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,5.83%,1.094,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.08%,1.130,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 100-0  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | TLH=10%,On (10%),-22.28%,-0.690,-54.56%,0.91%,0.347
1,Rel Threshold 25% | TLH=10%,On (10%),-22.46%,-0.694,-54.82%,0.93%,0.358
2,Abs Threshold 5% | TLH=10%,On (10%),-22.33%,-0.701,-54.52%,0.84%,0.384

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-22.33%,-0.701,0.84%,0.384,"$+5,719"
1,Abs Threshold 10% | TLH=10%,-22.33%,-0.701,0.84%,0.384,"$+5,719"
2,Abs Threshold 20% | TLH=10%,-22.33%,-0.701,0.84%,0.384,"$+5,719"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 100-0  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,38.35%,6.082,-1.76%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),38.35%,6.082,-1.76%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,38.35%,6.082,-1.76%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,38.35%,6.081,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,38.35%,6.082,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,38.35%,6.082,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 100-0  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-2.27%,-0.169,-4.68%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-2.27%,-0.169,-4.68%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-2.27%,-0.169,-4.68%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-2.38%,-0.177,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-2.27%,-0.169,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-2.27%,-0.169,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 100-0  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),15.03%,0.881,-17.63%,0.74%,1.147
1,Quarterly Rebal | TLH=10%,On (10%),14.65%,0.867,-17.51%,0.87%,0.272
2,Rel Threshold 25% | TLH=10%,On (10%),14.71%,0.859,-17.63%,0.95%,0.331

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,15.03%,0.881,0.74%,1.147,"$+11,675"
1,Rel Threshold 25% | TLH=10%,14.71%,0.859,0.95%,0.331,"$+5,221"
2,Quarterly Rebal | TLH=10%,14.65%,0.867,0.87%,0.272,"$+4,278"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 100-0  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),15.03%,0.881,-17.63%,0.74%,1.147
1,Quarterly Rebal | TLH=10%,On (10%),14.65%,0.867,-17.51%,0.87%,0.272
2,Rel Threshold 25% | TLH=10%,On (10%),14.71%,0.859,-17.63%,0.95%,0.331

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,15.03%,0.881,0.74%,1.147,"$+11,675"
1,Rel Threshold 25% | TLH=10%,14.71%,0.859,0.95%,0.331,"$+5,221"
2,Quarterly Rebal | TLH=10%,14.65%,0.867,0.87%,0.272,"$+4,278"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 100-0  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),15.03%,0.881,-17.63%,0.74%,1.147
1,Quarterly Rebal | TLH=10%,On (10%),14.65%,0.867,-17.51%,0.87%,0.272
2,Rel Threshold 25% | TLH=10%,On (10%),14.71%,0.859,-17.63%,0.95%,0.331

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,15.03%,0.881,0.74%,1.147,"$+11,675"
1,Rel Threshold 25% | TLH=10%,14.71%,0.859,0.95%,0.331,"$+5,221"
2,Quarterly Rebal | TLH=10%,14.65%,0.867,0.87%,0.272,"$+4,278"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 20-80  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | TLH=10%,On (10%),-13.43%,-0.745,-30.06%,1.20%,0.027
1,Abs Threshold 20% | TLH=10%,On (10%),-12.23%,-0.752,-28.28%,0.97%,-0.148
2,Abs Threshold 20% | No TLH,Off,-12.15%,-0.753,-28.01%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,-13.43%,-0.745,1.20%,0.027,"$+1,426"
1,Abs Threshold 5% | TLH=10%,-15.38%,-0.806,1.01%,-0.120,$-825
2,Rel Threshold 25% | TLH=10%,-15.18%,-0.800,1.04%,-0.131,"$-1,047"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 20-80  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,13.52%,5.069,-0.74%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),13.52%,5.069,-0.74%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,13.52%,5.069,-0.74%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,13.28%,5.010,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,13.52%,5.069,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,13.52%,5.069,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 20-80  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,9.50%,1.491,-6.47%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),9.50%,1.491,-6.47%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,9.50%,1.491,-6.47%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.31%,1.378,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,8.46%,1.401,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,8.94%,1.440,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 20-80  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,9.33%,1.293,-8.72%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),9.33%,1.293,-8.72%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,9.33%,1.293,-8.72%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.03%,1.237,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,8.13%,1.249,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,8.42%,1.277,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 20-80  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,9.33%,1.293,-8.72%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),9.33%,1.293,-8.72%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,9.33%,1.293,-8.72%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.03%,1.237,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,8.13%,1.249,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,8.42%,1.277,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 20-80  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,9.33%,1.293,-8.72%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),9.33%,1.293,-8.72%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,9.33%,1.293,-8.72%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.03%,1.237,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,8.13%,1.249,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,8.42%,1.277,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 30-70  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | TLH=10%,On (10%),-15.99%,-0.775,-34.68%,0.87%,-0.108
1,Abs Threshold 20% | No TLH,Off,-15.96%,-0.778,-34.45%,0.00%,0.000
2,Rel Threshold 25% | TLH=10%,On (10%),-19.70%,-0.840,-39.33%,0.94%,-0.142

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-20.26%,-0.873,0.84%,-0.042,$+341
1,Abs Threshold 20% | TLH=10%,-15.99%,-0.775,0.87%,-0.108,$-441
2,Rel Threshold 25% | TLH=10%,-19.70%,-0.840,0.94%,-0.142,"$-1,015"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 30-70  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,16.67%,5.462,-0.87%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),16.67%,5.462,-0.87%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,16.67%,5.462,-0.87%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,16.43%,5.431,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,16.67%,5.462,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,16.67%,5.462,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 30-70  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,-4.59%,-0.591,-3.35%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),-4.59%,-0.591,-3.35%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,-4.63%,-0.593,-3.37%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-4.59%,-0.591,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-4.63%,-0.593,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-4.63%,-0.593,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 30-70  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),7.35%,0.829,-9.67%,0.54%,0.213
1,Abs Threshold 5% | No TLH,Off,7.22%,0.805,-9.71%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,7.22%,0.805,-9.71%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,7.35%,0.829,0.54%,0.213,"$+2,675"
1,Monthly Rebal | TLH=10%,7.03%,0.788,0.00%,0.000,$+0
2,Rel Threshold 25% | TLH=10%,7.12%,0.793,0.51%,-0.022,"$+1,165"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 30-70  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),7.35%,0.829,-9.67%,0.54%,0.213
1,Abs Threshold 5% | No TLH,Off,7.22%,0.805,-9.71%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,7.22%,0.805,-9.71%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,7.35%,0.829,0.54%,0.213,"$+2,675"
1,Monthly Rebal | TLH=10%,7.03%,0.788,0.00%,0.000,$+0
2,Rel Threshold 25% | TLH=10%,7.12%,0.793,0.51%,-0.022,"$+1,165"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 30-70  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),7.35%,0.829,-9.67%,0.54%,0.213
1,Abs Threshold 5% | No TLH,Off,7.22%,0.805,-9.71%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,7.22%,0.805,-9.71%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,7.35%,0.829,0.54%,0.213,"$+2,675"
1,Monthly Rebal | TLH=10%,7.03%,0.788,0.00%,0.000,$+0
2,Rel Threshold 25% | TLH=10%,7.12%,0.793,0.51%,-0.022,"$+1,165"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 35-65  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | TLH=10%,On (10%),-16.65%,-0.784,-35.66%,0.84%,-0.095
1,Abs Threshold 20% | No TLH,Off,-16.63%,-0.787,-35.45%,0.00%,0.000
2,Rel Threshold 25% | TLH=10%,On (10%),-20.25%,-0.844,-40.15%,0.90%,-0.129

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-20.79%,-0.874,0.80%,-0.032,$+467
1,Abs Threshold 20% | TLH=10%,-16.65%,-0.784,0.84%,-0.095,$-240
2,Rel Threshold 25% | TLH=10%,-20.25%,-0.844,0.90%,-0.129,$-780

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 35-65  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,18.83%,5.677,-0.96%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),18.83%,5.677,-0.96%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,18.83%,5.677,-0.96%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,18.60%,5.655,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,18.83%,5.677,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,18.83%,5.677,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 35-65  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,-4.61%,-0.568,-3.44%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),-4.61%,-0.568,-3.44%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,-4.66%,-0.570,-3.46%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-4.61%,-0.568,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-4.66%,-0.570,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-4.66%,-0.570,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 35-65  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),7.77%,0.823,-10.31%,0.53%,0.241
1,Abs Threshold 5% | No TLH,Off,7.63%,0.800,-10.34%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,7.63%,0.800,-10.34%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,7.77%,0.823,0.53%,0.241,"$+2,851"
1,Rel Threshold 25% | TLH=10%,7.56%,0.789,0.54%,0.021,"$+1,441"
2,Monthly Rebal | TLH=10%,7.44%,0.784,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 35-65  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),7.77%,0.823,-10.31%,0.53%,0.241
1,Abs Threshold 5% | No TLH,Off,7.63%,0.800,-10.34%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,7.63%,0.800,-10.34%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,7.77%,0.823,0.53%,0.241,"$+2,851"
1,Rel Threshold 25% | TLH=10%,7.56%,0.789,0.54%,0.021,"$+1,441"
2,Monthly Rebal | TLH=10%,7.44%,0.784,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 35-65  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),7.77%,0.823,-10.31%,0.53%,0.241
1,Abs Threshold 5% | No TLH,Off,7.63%,0.800,-10.34%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,7.63%,0.800,-10.34%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,7.77%,0.823,0.53%,0.241,"$+2,851"
1,Rel Threshold 25% | TLH=10%,7.56%,0.789,0.54%,0.021,"$+1,441"
2,Monthly Rebal | TLH=10%,7.44%,0.784,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 40-60  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | TLH=10%,On (10%),-15.87%,-0.775,-34.56%,0.78%,-0.057
1,Abs Threshold 20% | No TLH,Off,-15.89%,-0.779,-34.37%,0.00%,0.000
2,Rel Threshold 25% | TLH=10%,On (10%),-19.55%,-0.840,-39.18%,0.83%,-0.097

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-20.13%,-0.874,0.75%,0.002,$+862
1,Abs Threshold 20% | TLH=10%,-15.87%,-0.775,0.78%,-0.057,$+270
2,Rel Threshold 25% | TLH=10%,-19.55%,-0.840,0.83%,-0.097,$-286

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 40-60  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,21.65%,5.773,-1.09%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),21.65%,5.773,-1.09%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,21.65%,5.773,-1.09%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,21.41%,5.756,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,21.65%,5.773,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,21.65%,5.773,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 40-60  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,-4.81%,-0.554,-3.62%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),-4.81%,-0.554,-3.62%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,-4.85%,-0.556,-3.64%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-4.81%,-0.554,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-4.85%,-0.556,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-4.85%,-0.556,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 40-60  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),8.28%,0.796,-11.31%,0.42%,0.716
1,Quarterly Rebal | TLH=10%,On (10%),8.22%,0.793,-11.30%,0.53%,0.263
2,Abs Threshold 5% | No TLH,Off,8.06%,0.773,-11.33%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.28%,0.796,0.42%,0.716,"$+4,946"
1,Quarterly Rebal | TLH=10%,8.22%,0.793,0.53%,0.263,"$+2,972"
2,Rel Threshold 25% | TLH=10%,8.09%,0.768,0.59%,0.178,"$+2,582"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 40-60  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),8.28%,0.796,-11.31%,0.42%,0.716
1,Quarterly Rebal | TLH=10%,On (10%),8.22%,0.793,-11.30%,0.53%,0.263
2,Abs Threshold 5% | No TLH,Off,8.06%,0.773,-11.33%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.28%,0.796,0.42%,0.716,"$+4,946"
1,Quarterly Rebal | TLH=10%,8.22%,0.793,0.53%,0.263,"$+2,972"
2,Rel Threshold 25% | TLH=10%,8.09%,0.768,0.59%,0.178,"$+2,582"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 40-60  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),8.28%,0.796,-11.31%,0.42%,0.716
1,Quarterly Rebal | TLH=10%,On (10%),8.22%,0.793,-11.30%,0.53%,0.263
2,Abs Threshold 5% | No TLH,Off,8.06%,0.773,-11.33%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.28%,0.796,0.42%,0.716,"$+4,946"
1,Quarterly Rebal | TLH=10%,8.22%,0.793,0.53%,0.263,"$+2,972"
2,Rel Threshold 25% | TLH=10%,8.09%,0.768,0.59%,0.178,"$+2,582"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 45-55  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | No TLH,Off,-16.23%,-0.783,-34.87%,0.00%,0.000
1,Abs Threshold 20% | TLH=10%,On (10%),-16.34%,-0.783,-35.23%,0.97%,-0.177
2,Rel Threshold 25% | No TLH,Off,-19.70%,-0.842,-39.17%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-20.46%,-0.875,0.92%,-0.168,"$-1,318"
1,Abs Threshold 20% | TLH=10%,-16.34%,-0.783,0.97%,-0.177,"$-1,557"
2,Quarterly Rebal | TLH=10%,-20.55%,-0.920,1.07%,-0.193,"$-2,038"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 45-55  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,21.63%,5.707,-1.10%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),21.63%,5.707,-1.10%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,21.63%,5.707,-1.10%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,21.38%,5.691,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,21.63%,5.707,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,21.63%,5.707,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 45-55  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-4.08%,-0.445,-3.63%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-4.08%,-0.445,-3.63%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-4.08%,-0.445,-3.63%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-4.07%,-0.446,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-4.08%,-0.445,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-4.08%,-0.445,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 45-55  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),9.38%,0.861,-11.55%,0.47%,0.814
1,Quarterly Rebal | TLH=10%,On (10%),9.29%,0.859,-11.52%,0.67%,0.197
2,Yearly Rebal | No TLH,Off,9.17%,0.848,-11.40%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.38%,0.861,0.47%,0.814,"$+5,947"
1,Rel Threshold 25% | TLH=10%,9.32%,0.847,0.59%,0.292,"$+3,409"
2,Rel Threshold 50% | TLH=10%,9.27%,0.843,0.68%,0.224,"$+3,163"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 45-55  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),9.38%,0.861,-11.55%,0.47%,0.814
1,Quarterly Rebal | TLH=10%,On (10%),9.29%,0.859,-11.52%,0.67%,0.197
2,Yearly Rebal | No TLH,Off,9.17%,0.848,-11.40%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.38%,0.861,0.47%,0.814,"$+5,947"
1,Rel Threshold 25% | TLH=10%,9.32%,0.847,0.59%,0.292,"$+3,409"
2,Rel Threshold 50% | TLH=10%,9.27%,0.843,0.68%,0.224,"$+3,163"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 45-55  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),9.38%,0.861,-11.55%,0.47%,0.814
1,Quarterly Rebal | TLH=10%,On (10%),9.29%,0.859,-11.52%,0.67%,0.197
2,Yearly Rebal | No TLH,Off,9.17%,0.848,-11.40%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.38%,0.861,0.47%,0.814,"$+5,947"
1,Rel Threshold 25% | TLH=10%,9.32%,0.847,0.59%,0.292,"$+3,409"
2,Rel Threshold 50% | TLH=10%,9.27%,0.843,0.68%,0.224,"$+3,163"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 50-50  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | TLH=10%,On (10%),-16.88%,-0.789,-36.02%,0.94%,-0.166
1,Abs Threshold 20% | No TLH,Off,-16.78%,-0.790,-35.69%,0.00%,0.000
2,Rel Threshold 25% | No TLH,Off,-20.17%,-0.846,-39.87%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-20.89%,-0.875,0.89%,-0.160,"$-1,143"
1,Abs Threshold 20% | TLH=10%,-16.88%,-0.789,0.94%,-0.166,"$-1,340"
2,Abs Threshold 10% | TLH=10%,-20.23%,-0.908,0.85%,-0.172,"$-1,211"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 50-50  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,23.27%,5.718,-1.18%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),23.27%,5.718,-1.18%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,23.27%,5.718,-1.18%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,22.98%,5.700,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,23.27%,5.718,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,23.27%,5.718,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 50-50  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-4.16%,-0.427,-3.74%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-4.16%,-0.427,-3.74%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-4.16%,-0.427,-3.74%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-4.17%,-0.430,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-4.16%,-0.427,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-4.16%,-0.427,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 50-50  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),10.53%,0.911,-12.01%,0.72%,0.296
1,Monthly Rebal | TLH=10%,On (10%),10.59%,0.910,-12.07%,0.53%,0.857
2,Yearly Rebal | No TLH,Off,10.47%,0.905,-11.89%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,10.59%,0.910,0.53%,0.857,"$+6,853"
1,Quarterly Rebal | TLH=10%,10.53%,0.911,0.72%,0.296,"$+3,902"
2,Rel Threshold 25% | TLH=10%,10.10%,0.863,0.79%,-0.379,"$-2,266"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 50-50  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),10.53%,0.911,-12.01%,0.72%,0.296
1,Monthly Rebal | TLH=10%,On (10%),10.59%,0.910,-12.07%,0.53%,0.857
2,Yearly Rebal | No TLH,Off,10.47%,0.905,-11.89%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,10.59%,0.910,0.53%,0.857,"$+6,853"
1,Quarterly Rebal | TLH=10%,10.53%,0.911,0.72%,0.296,"$+3,902"
2,Rel Threshold 25% | TLH=10%,10.10%,0.863,0.79%,-0.379,"$-2,266"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 50-50  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),10.53%,0.911,-12.01%,0.72%,0.296
1,Monthly Rebal | TLH=10%,On (10%),10.59%,0.910,-12.07%,0.53%,0.857
2,Yearly Rebal | No TLH,Off,10.47%,0.905,-11.89%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,10.59%,0.910,0.53%,0.857,"$+6,853"
1,Quarterly Rebal | TLH=10%,10.53%,0.911,0.72%,0.296,"$+3,902"
2,Rel Threshold 25% | TLH=10%,10.10%,0.863,0.79%,-0.379,"$-2,266"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 55-45  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,-23.56%,-0.869,-44.68%,0.00%,0.000
1,Rel Threshold 25% | TLH=10%,On (10%),-23.85%,-0.873,-45.09%,1.09%,-0.314
2,Abs Threshold 5% | No TLH,Off,-23.71%,-0.878,-44.52%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-24.11%,-0.911,1.29%,-0.211,"$-2,902"
1,Abs Threshold 5% | TLH=10%,-23.99%,-0.882,1.12%,-0.300,"$-3,772"
2,Rel Threshold 25% | TLH=10%,-23.85%,-0.873,1.09%,-0.314,"$-3,864"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 55-45  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,27.09%,5.882,-1.33%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),27.09%,5.882,-1.33%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,27.09%,5.882,-1.33%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,26.87%,5.871,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,27.09%,5.882,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,27.09%,5.882,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 55-45  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-3.19%,-0.297,-3.93%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-3.19%,-0.297,-3.93%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-3.19%,-0.297,-3.93%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-3.23%,-0.302,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-3.19%,-0.297,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-3.19%,-0.297,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 55-45  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),11.73%,0.895,-13.69%,0.61%,0.919
1,Quarterly Rebal | TLH=10%,On (10%),11.54%,0.890,-13.61%,0.85%,0.178
2,Rel Threshold 25% | TLH=10%,On (10%),11.67%,0.885,-13.76%,0.74%,0.441

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.73%,0.895,0.61%,0.919,"$+8,112"
1,Rel Threshold 25% | TLH=10%,11.67%,0.885,0.74%,0.441,"$+5,291"
2,Quarterly Rebal | TLH=10%,11.54%,0.890,0.85%,0.178,"$+3,176"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 55-45  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),11.73%,0.895,-13.69%,0.61%,0.919
1,Quarterly Rebal | TLH=10%,On (10%),11.54%,0.890,-13.61%,0.85%,0.178
2,Rel Threshold 25% | TLH=10%,On (10%),11.67%,0.885,-13.76%,0.74%,0.441

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.73%,0.895,0.61%,0.919,"$+8,112"
1,Rel Threshold 25% | TLH=10%,11.67%,0.885,0.74%,0.441,"$+5,291"
2,Quarterly Rebal | TLH=10%,11.54%,0.890,0.85%,0.178,"$+3,176"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 55-45  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),11.73%,0.895,-13.69%,0.61%,0.919
1,Quarterly Rebal | TLH=10%,On (10%),11.54%,0.890,-13.61%,0.85%,0.178
2,Rel Threshold 25% | TLH=10%,On (10%),11.67%,0.885,-13.76%,0.74%,0.441

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.73%,0.895,0.61%,0.919,"$+8,112"
1,Rel Threshold 25% | TLH=10%,11.67%,0.885,0.74%,0.441,"$+5,291"
2,Quarterly Rebal | TLH=10%,11.54%,0.890,0.85%,0.178,"$+3,176"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 60-40  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),-27.37%,-0.873,-50.20%,1.18%,-0.189
1,Rel Threshold 25% | No TLH,Off,-27.20%,-0.874,-49.96%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-26.64%,-0.875,-49.33%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,-27.37%,-0.873,1.18%,-0.189,"$-2,239"
1,Monthly Rebal | TLH=10%,-27.94%,-0.906,1.34%,-0.231,"$-3,359"
2,Abs Threshold 20% | TLH=10%,-26.54%,-0.933,1.27%,-0.260,"$-3,648"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 60-40  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,30.17%,5.958,-1.47%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),30.17%,5.958,-1.47%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,30.17%,5.958,-1.47%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,29.94%,5.950,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,30.17%,5.958,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,30.17%,5.958,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 60-40  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-2.41%,-0.208,-4.13%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-2.41%,-0.208,-4.13%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-2.41%,-0.208,-4.13%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-2.48%,-0.215,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-2.41%,-0.208,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-2.41%,-0.208,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 60-40  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),12.42%,0.876,-14.75%,0.62%,0.931
1,Rel Threshold 25% | TLH=10%,On (10%),12.43%,0.871,-14.81%,0.75%,0.522
2,Quarterly Rebal | TLH=10%,On (10%),12.23%,0.871,-14.67%,0.84%,0.195

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.42%,0.876,0.62%,0.931,"$+8,364"
1,Rel Threshold 25% | TLH=10%,12.43%,0.871,0.75%,0.522,"$+6,095"
2,Quarterly Rebal | TLH=10%,12.23%,0.871,0.84%,0.195,"$+3,348"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 60-40  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),12.42%,0.876,-14.75%,0.62%,0.931
1,Rel Threshold 25% | TLH=10%,On (10%),12.43%,0.871,-14.81%,0.75%,0.522
2,Quarterly Rebal | TLH=10%,On (10%),12.23%,0.871,-14.67%,0.84%,0.195

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.42%,0.876,0.62%,0.931,"$+8,364"
1,Rel Threshold 25% | TLH=10%,12.43%,0.871,0.75%,0.522,"$+6,095"
2,Quarterly Rebal | TLH=10%,12.23%,0.871,0.84%,0.195,"$+3,348"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 60-40  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),12.42%,0.876,-14.75%,0.62%,0.931
1,Rel Threshold 25% | TLH=10%,On (10%),12.43%,0.871,-14.81%,0.75%,0.522
2,Quarterly Rebal | TLH=10%,On (10%),12.23%,0.871,-14.67%,0.84%,0.195

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.42%,0.876,0.62%,0.931,"$+8,364"
1,Rel Threshold 25% | TLH=10%,12.43%,0.871,0.75%,0.522,"$+6,095"
2,Quarterly Rebal | TLH=10%,12.23%,0.871,0.84%,0.195,"$+3,348"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 65-35  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),-27.61%,-0.873,-50.52%,1.10%,-0.185
1,Rel Threshold 25% | No TLH,Off,-27.46%,-0.874,-50.29%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,-26.03%,-0.878,-48.64%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,-27.61%,-0.873,1.10%,-0.185,"$-1,957"
1,Monthly Rebal | TLH=10%,-28.14%,-0.903,1.24%,-0.244,"$-3,264"
2,Abs Threshold 20% | TLH=10%,-26.84%,-0.929,1.18%,-0.253,"$-3,235"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 65-35  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,30.62%,5.949,-1.48%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),30.62%,5.949,-1.48%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,30.62%,5.949,-1.48%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,30.40%,5.942,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,30.62%,5.949,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,30.62%,5.949,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 65-35  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-2.71%,-0.231,-4.21%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-2.71%,-0.231,-4.21%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-2.71%,-0.231,-4.21%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-2.78%,-0.238,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-2.71%,-0.231,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-2.71%,-0.231,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 65-35  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),12.60%,0.872,-15.04%,0.65%,0.908
1,Quarterly Rebal | TLH=10%,On (10%),12.42%,0.868,-14.96%,0.83%,0.225
2,Rel Threshold 25% | TLH=10%,On (10%),12.54%,0.864,-15.09%,0.77%,0.442

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.60%,0.872,0.65%,0.908,"$+8,457"
1,Rel Threshold 25% | TLH=10%,12.54%,0.864,0.77%,0.442,"$+5,493"
2,Quarterly Rebal | TLH=10%,12.42%,0.868,0.83%,0.225,"$+3,641"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 65-35  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),12.60%,0.872,-15.04%,0.65%,0.908
1,Quarterly Rebal | TLH=10%,On (10%),12.42%,0.868,-14.96%,0.83%,0.225
2,Rel Threshold 25% | TLH=10%,On (10%),12.54%,0.864,-15.09%,0.77%,0.442

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.60%,0.872,0.65%,0.908,"$+8,457"
1,Rel Threshold 25% | TLH=10%,12.54%,0.864,0.77%,0.442,"$+5,493"
2,Quarterly Rebal | TLH=10%,12.42%,0.868,0.83%,0.225,"$+3,641"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 65-35  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),12.60%,0.872,-15.04%,0.65%,0.908
1,Quarterly Rebal | TLH=10%,On (10%),12.42%,0.868,-14.96%,0.83%,0.225
2,Rel Threshold 25% | TLH=10%,On (10%),12.54%,0.864,-15.09%,0.77%,0.442

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.60%,0.872,0.65%,0.908,"$+8,457"
1,Rel Threshold 25% | TLH=10%,12.54%,0.864,0.77%,0.442,"$+5,493"
2,Quarterly Rebal | TLH=10%,12.42%,0.868,0.83%,0.225,"$+3,641"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 70-30  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,-28.57%,-0.883,-51.73%,0.00%,0.000
1,Rel Threshold 25% | No TLH,Off,-29.20%,-0.887,-52.37%,0.00%,0.000
2,Rel Threshold 50% | No TLH,Off,-28.79%,-0.888,-51.76%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,-29.40%,-0.888,1.13%,-0.219,"$-2,535"
1,Abs Threshold 10% | TLH=10%,-28.59%,-0.917,1.17%,-0.246,"$-3,050"
2,Abs Threshold 20% | TLH=10%,-28.59%,-0.917,1.17%,-0.246,"$-3,050"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 70-30  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,32.56%,5.978,-1.56%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),32.56%,5.978,-1.56%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,32.56%,5.978,-1.56%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,32.37%,5.972,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,32.56%,5.978,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,32.56%,5.978,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 70-30  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-2.66%,-0.220,-4.33%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-2.66%,-0.220,-4.33%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-2.66%,-0.220,-4.33%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-2.73%,-0.227,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-2.66%,-0.220,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-2.66%,-0.220,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 70-30  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),12.90%,0.860,-15.64%,0.66%,0.900
1,Quarterly Rebal | TLH=10%,On (10%),12.73%,0.856,-15.56%,0.81%,0.253
2,Rel Threshold 25% | TLH=10%,On (10%),12.82%,0.850,-15.69%,0.79%,0.421

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.90%,0.860,0.66%,0.900,"$+8,512"
1,Rel Threshold 25% | TLH=10%,12.82%,0.850,0.79%,0.421,"$+5,412"
2,Quarterly Rebal | TLH=10%,12.73%,0.856,0.81%,0.253,"$+3,855"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 70-30  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),12.90%,0.860,-15.64%,0.66%,0.900
1,Quarterly Rebal | TLH=10%,On (10%),12.73%,0.856,-15.56%,0.81%,0.253
2,Rel Threshold 25% | TLH=10%,On (10%),12.82%,0.850,-15.69%,0.79%,0.421

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.90%,0.860,0.66%,0.900,"$+8,512"
1,Rel Threshold 25% | TLH=10%,12.82%,0.850,0.79%,0.421,"$+5,412"
2,Quarterly Rebal | TLH=10%,12.73%,0.856,0.81%,0.253,"$+3,855"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 70-30  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),12.90%,0.860,-15.64%,0.66%,0.900
1,Quarterly Rebal | TLH=10%,On (10%),12.73%,0.856,-15.56%,0.81%,0.253
2,Rel Threshold 25% | TLH=10%,On (10%),12.82%,0.850,-15.69%,0.79%,0.421

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.90%,0.860,0.66%,0.900,"$+8,512"
1,Rel Threshold 25% | TLH=10%,12.82%,0.850,0.79%,0.421,"$+5,412"
2,Quarterly Rebal | TLH=10%,12.73%,0.856,0.81%,0.253,"$+3,855"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 75-25  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,-28.64%,-0.883,-51.82%,0.00%,0.000
1,Rel Threshold 25% | No TLH,Off,-29.24%,-0.885,-52.42%,0.00%,0.000
2,Rel Threshold 25% | TLH=10%,On (10%),-29.41%,-0.886,-52.51%,1.10%,-0.200

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,-29.41%,-0.886,1.10%,-0.200,"$-2,176"
1,Abs Threshold 10% | TLH=10%,-28.66%,-0.916,1.13%,-0.243,"$-2,878"
2,Abs Threshold 20% | TLH=10%,-28.66%,-0.916,1.13%,-0.243,"$-2,878"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 75-25  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,33.46%,5.992,-1.59%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),33.46%,5.992,-1.59%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,33.46%,5.992,-1.59%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,33.29%,5.987,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,33.46%,5.992,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,33.46%,5.992,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 75-25  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-2.57%,-0.207,-4.40%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-2.57%,-0.207,-4.40%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-2.57%,-0.207,-4.40%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-2.66%,-0.215,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-2.57%,-0.207,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-2.57%,-0.207,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 75-25  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),13.29%,0.860,-16.10%,0.67%,0.888
1,Quarterly Rebal | TLH=10%,On (10%),13.12%,0.856,-16.02%,0.81%,0.260
2,Rel Threshold 25% | TLH=10%,On (10%),13.18%,0.849,-16.14%,0.84%,0.372

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,13.29%,0.860,0.67%,0.888,"$+8,558"
1,Rel Threshold 25% | TLH=10%,13.18%,0.849,0.84%,0.372,"$+5,149"
2,Quarterly Rebal | TLH=10%,13.12%,0.856,0.81%,0.260,"$+3,937"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 75-25  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),13.29%,0.860,-16.10%,0.67%,0.888
1,Quarterly Rebal | TLH=10%,On (10%),13.12%,0.856,-16.02%,0.81%,0.260
2,Rel Threshold 25% | TLH=10%,On (10%),13.18%,0.849,-16.14%,0.84%,0.372

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,13.29%,0.860,0.67%,0.888,"$+8,558"
1,Rel Threshold 25% | TLH=10%,13.18%,0.849,0.84%,0.372,"$+5,149"
2,Quarterly Rebal | TLH=10%,13.12%,0.856,0.81%,0.260,"$+3,937"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 75-25  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),13.29%,0.860,-16.10%,0.67%,0.888
1,Quarterly Rebal | TLH=10%,On (10%),13.12%,0.856,-16.02%,0.81%,0.260
2,Rel Threshold 25% | TLH=10%,On (10%),13.18%,0.849,-16.14%,0.84%,0.372

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,13.29%,0.860,0.67%,0.888,"$+8,558"
1,Rel Threshold 25% | TLH=10%,13.18%,0.849,0.84%,0.372,"$+5,149"
2,Quarterly Rebal | TLH=10%,13.12%,0.856,0.81%,0.260,"$+3,937"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 80-20  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,-30.20%,-0.882,-53.79%,0.00%,0.000
1,Monthly Rebal | No TLH,Off,-30.21%,-0.886,-53.88%,0.00%,0.000
2,Rel Threshold 25% | TLH=10%,On (10%),-30.54%,-0.886,-54.01%,1.23%,-0.321

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-30.08%,-0.902,1.34%,-0.284,"$-4,223"
1,Abs Threshold 10% | TLH=10%,-30.08%,-0.902,1.34%,-0.284,"$-4,223"
2,Abs Threshold 20% | TLH=10%,-30.08%,-0.902,1.34%,-0.284,"$-4,223"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 80-20  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,35.20%,6.040,-1.65%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),35.20%,6.040,-1.65%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,35.20%,6.040,-1.65%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,35.07%,6.036,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,35.20%,6.040,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,35.20%,6.040,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 80-20  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-2.08%,-0.162,-4.47%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-2.08%,-0.162,-4.47%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-2.08%,-0.162,-4.47%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-2.19%,-0.170,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-2.08%,-0.162,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-2.08%,-0.162,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 80-20  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),13.96%,0.862,-16.87%,0.68%,0.880
1,Quarterly Rebal | TLH=10%,On (10%),13.79%,0.858,-16.79%,0.81%,0.265
2,Rel Threshold 25% | TLH=10%,On (10%),13.76%,0.846,-16.91%,0.88%,0.243

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,13.96%,0.862,0.68%,0.880,"$+8,612"
1,Quarterly Rebal | TLH=10%,13.79%,0.858,0.81%,0.265,"$+3,998"
2,Rel Threshold 25% | TLH=10%,13.76%,0.846,0.88%,0.243,"$+3,984"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 80-20  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),13.96%,0.862,-16.87%,0.68%,0.880
1,Quarterly Rebal | TLH=10%,On (10%),13.79%,0.858,-16.79%,0.81%,0.265
2,Rel Threshold 25% | TLH=10%,On (10%),13.76%,0.846,-16.91%,0.88%,0.243

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,13.96%,0.862,0.68%,0.880,"$+8,612"
1,Quarterly Rebal | TLH=10%,13.79%,0.858,0.81%,0.265,"$+3,998"
2,Rel Threshold 25% | TLH=10%,13.76%,0.846,0.88%,0.243,"$+3,984"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 80-20  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),13.96%,0.862,-16.87%,0.68%,0.880
1,Quarterly Rebal | TLH=10%,On (10%),13.79%,0.858,-16.79%,0.81%,0.265
2,Rel Threshold 25% | TLH=10%,On (10%),13.76%,0.846,-16.91%,0.88%,0.243

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,13.96%,0.862,0.68%,0.880,"$+8,612"
1,Quarterly Rebal | TLH=10%,13.79%,0.858,0.81%,0.265,"$+3,998"
2,Rel Threshold 25% | TLH=10%,13.76%,0.846,0.88%,0.243,"$+3,984"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 90-10  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | TLH=10%,On (10%),-22.26%,-0.688,-54.49%,0.99%,0.345
1,Rel Threshold 25% | TLH=10%,On (10%),-22.46%,-0.693,-54.77%,1.01%,0.353
2,Abs Threshold 5% | TLH=10%,On (10%),-22.31%,-0.700,-54.45%,0.92%,0.376

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-22.31%,-0.700,0.92%,0.376,"$+6,069"
1,Abs Threshold 10% | TLH=10%,-22.31%,-0.700,0.92%,0.376,"$+6,069"
2,Abs Threshold 20% | TLH=10%,-22.31%,-0.700,0.92%,0.376,"$+6,069"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 90-10  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,37.05%,6.078,-1.72%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),37.05%,6.078,-1.72%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,37.05%,6.078,-1.72%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,36.95%,6.074,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,37.05%,6.078,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,37.05%,6.078,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 90-10  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-1.84%,-0.139,-4.58%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-1.84%,-0.139,-4.58%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-1.84%,-0.139,-4.58%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-1.97%,-0.149,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-1.84%,-0.139,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-1.84%,-0.139,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 90-10  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),14.42%,0.859,-17.54%,0.71%,1.156
1,Quarterly Rebal | TLH=10%,On (10%),13.99%,0.842,-17.44%,0.87%,0.187
2,Rel Threshold 25% | TLH=10%,On (10%),14.12%,0.839,-17.57%,0.92%,0.355

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,14.42%,0.859,0.71%,1.156,"$+11,267"
1,Rel Threshold 25% | TLH=10%,14.12%,0.839,0.92%,0.355,"$+5,346"
2,Quarterly Rebal | TLH=10%,13.99%,0.842,0.87%,0.187,"$+3,380"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 90-10  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),14.42%,0.859,-17.54%,0.71%,1.156
1,Quarterly Rebal | TLH=10%,On (10%),13.99%,0.842,-17.44%,0.87%,0.187
2,Rel Threshold 25% | TLH=10%,On (10%),14.12%,0.839,-17.57%,0.92%,0.355

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,14.42%,0.859,0.71%,1.156,"$+11,267"
1,Rel Threshold 25% | TLH=10%,14.12%,0.839,0.92%,0.355,"$+5,346"
2,Quarterly Rebal | TLH=10%,13.99%,0.842,0.87%,0.187,"$+3,380"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Qualified - 90-10  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),14.42%,0.859,-17.54%,0.71%,1.156
1,Quarterly Rebal | TLH=10%,On (10%),13.99%,0.842,-17.44%,0.87%,0.187
2,Rel Threshold 25% | TLH=10%,On (10%),14.12%,0.839,-17.57%,0.92%,0.355

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,14.42%,0.859,0.71%,1.156,"$+11,267"
1,Rel Threshold 25% | TLH=10%,14.12%,0.839,0.92%,0.355,"$+5,346"
2,Quarterly Rebal | TLH=10%,13.99%,0.842,0.87%,0.187,"$+3,380"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 0-100  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,7.66%,0.856,-7.77%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),7.66%,0.856,-7.77%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,7.66%,0.856,-7.77%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.66%,0.856,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,7.66%,0.856,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,7.66%,0.856,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 0-100  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,1.35%,0.556,-5.08%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),1.35%,0.556,-5.08%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,1.35%,0.556,-5.08%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,1.34%,0.553,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,1.34%,0.554,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,1.34%,0.555,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 0-100  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,-0.78%,-0.228,-2.86%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),-0.78%,-0.228,-2.86%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,-0.78%,-0.229,-2.86%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-0.78%,-0.228,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-0.78%,-0.229,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-0.78%,-0.230,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 0-100  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,0.38%,0.100,-3.85%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),0.38%,0.100,-3.85%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,0.38%,0.100,-3.85%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.37%,0.097,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.37%,0.097,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,0.38%,0.100,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 0-100  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,0.38%,0.100,-3.85%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),0.38%,0.100,-3.85%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,0.38%,0.100,-3.85%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.37%,0.097,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.37%,0.097,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,0.38%,0.100,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 0-100  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,0.38%,0.100,-3.85%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),0.38%,0.100,-3.85%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,0.38%,0.100,-3.85%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.37%,0.097,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.37%,0.097,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,0.38%,0.100,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 10-90  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | No TLH,Off,-2.12%,-0.275,-11.82%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,-2.61%,-0.301,-11.46%,0.00%,0.000
2,Rel Threshold 50% | No TLH,Off,-2.61%,-0.301,-11.46%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,-3.53%,-0.393,0.89%,-0.126,$-615
1,Monthly Rebal | TLH=10%,-4.05%,-0.451,0.66%,-0.272,"$-1,654"
2,Abs Threshold 5% | TLH=10%,-3.86%,-0.428,0.69%,-0.444,"$-3,679"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 10-90  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,6.61%,2.764,-1.08%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),6.61%,2.764,-1.08%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,6.61%,2.747,-1.08%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,6.59%,2.737,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,6.61%,2.764,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.61%,2.747,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 10-90  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,2.45%,0.669,-2.43%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),2.45%,0.669,-2.43%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,2.45%,0.669,-2.43%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.14%,0.594,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,2.19%,0.610,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,2.45%,0.669,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 10-90  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),2.13%,0.525,-5.03%,0.20%,-0.630
1,Abs Threshold 5% | TLH=10%,On (10%),2.13%,0.525,-5.03%,0.20%,-0.630
2,Abs Threshold 10% | TLH=10%,On (10%),2.13%,0.525,-5.03%,0.20%,-0.630

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.06%,0.506,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,2.13%,0.525,0.20%,-0.630,$+125
2,Abs Threshold 5% | TLH=10%,2.13%,0.525,0.20%,-0.630,$+125

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 10-90  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),2.13%,0.525,-5.03%,0.20%,-0.630
1,Abs Threshold 5% | TLH=10%,On (10%),2.13%,0.525,-5.03%,0.20%,-0.630
2,Abs Threshold 10% | TLH=10%,On (10%),2.13%,0.525,-5.03%,0.20%,-0.630

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.06%,0.506,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,2.13%,0.525,0.20%,-0.630,$+125
2,Abs Threshold 5% | TLH=10%,2.13%,0.525,0.20%,-0.630,$+125

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 10-90  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),2.13%,0.525,-5.03%,0.20%,-0.630
1,Abs Threshold 5% | TLH=10%,On (10%),2.13%,0.525,-5.03%,0.20%,-0.630
2,Abs Threshold 10% | TLH=10%,On (10%),2.13%,0.525,-5.03%,0.20%,-0.630

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.06%,0.506,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,2.13%,0.525,0.20%,-0.630,$+125
2,Abs Threshold 5% | TLH=10%,2.13%,0.525,0.20%,-0.630,$+125

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 100-0  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | TLH=10%,On (10%),-21.51%,-0.674,-53.44%,1.35%,0.324
1,Rel Threshold 25% | TLH=10%,On (10%),-21.77%,-0.681,-53.76%,1.37%,0.300
2,Abs Threshold 5% | TLH=10%,On (10%),-21.57%,-0.686,-53.36%,1.32%,0.339

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-21.57%,-0.686,1.32%,0.339,"$+7,707"
1,Abs Threshold 10% | TLH=10%,-21.57%,-0.686,1.32%,0.339,"$+7,707"
2,Abs Threshold 20% | TLH=10%,-21.57%,-0.686,1.32%,0.339,"$+7,707"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 100-0  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,38.39%,6.025,-1.80%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),38.39%,6.025,-1.80%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,38.38%,6.025,-1.79%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,38.39%,6.025,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,38.38%,6.025,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,38.38%,6.025,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 100-0  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-4.00%,-0.305,-4.52%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-4.00%,-0.305,-4.52%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-4.00%,-0.305,-4.52%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-4.19%,-0.320,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-4.00%,-0.305,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-4.00%,-0.305,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 100-0  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),15.19%,0.895,-17.57%,0.68%,0.778
1,Quarterly Rebal | TLH=10%,On (10%),15.03%,0.893,-17.46%,0.83%,0.148
2,Yearly Rebal | No TLH,Off,14.92%,0.887,-17.39%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,15.19%,0.895,0.68%,0.778,"$+7,866"
1,Rel Threshold 25% | TLH=10%,15.00%,0.883,0.88%,0.179,"$+3,319"
2,Quarterly Rebal | TLH=10%,15.03%,0.893,0.83%,0.148,"$+2,906"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 100-0  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),15.19%,0.895,-17.57%,0.68%,0.778
1,Quarterly Rebal | TLH=10%,On (10%),15.03%,0.893,-17.46%,0.83%,0.148
2,Yearly Rebal | No TLH,Off,14.92%,0.887,-17.39%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,15.19%,0.895,0.68%,0.778,"$+7,866"
1,Rel Threshold 25% | TLH=10%,15.00%,0.883,0.88%,0.179,"$+3,319"
2,Quarterly Rebal | TLH=10%,15.03%,0.893,0.83%,0.148,"$+2,906"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 100-0  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),15.19%,0.895,-17.57%,0.68%,0.778
1,Quarterly Rebal | TLH=10%,On (10%),15.03%,0.893,-17.46%,0.83%,0.148
2,Yearly Rebal | No TLH,Off,14.92%,0.887,-17.39%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,15.19%,0.895,0.68%,0.778,"$+7,866"
1,Rel Threshold 25% | TLH=10%,15.00%,0.883,0.88%,0.179,"$+3,319"
2,Quarterly Rebal | TLH=10%,15.03%,0.893,0.83%,0.148,"$+2,906"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 20-80  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,-7.17%,-0.603,-19.54%,0.00%,0.000
1,Abs Threshold 10% | TLH=10%,On (10%),-7.32%,-0.611,-19.85%,0.85%,-0.259
2,Abs Threshold 5% | TLH=10%,On (10%),-8.09%,-0.626,-21.08%,1.02%,0.391

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-8.09%,-0.626,1.02%,0.391,"$+7,083"
1,Rel Threshold 25% | TLH=10%,-8.64%,-0.681,1.01%,0.115,"$+2,786"
2,Rel Threshold 50% | TLH=10%,-7.48%,-0.628,0.92%,-0.149,"$-1,032"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 20-80  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,10.50%,4.922,-0.55%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),10.50%,4.922,-0.55%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,10.50%,4.922,-0.55%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,10.28%,4.854,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,10.50%,4.922,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,10.50%,4.922,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 20-80  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,4.37%,0.985,-2.76%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),4.37%,0.985,-2.76%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,4.37%,0.985,-2.76%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,3.96%,0.920,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,4.04%,0.941,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,4.37%,0.985,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 20-80  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),3.47%,0.681,-6.19%,0.19%,0.315
1,Yearly Rebal | No TLH,Off,3.37%,0.669,-6.07%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,3.37%,0.669,-6.07%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,3.47%,0.681,0.19%,0.315,"$+1,777"
1,Yearly Rebal | TLH=10%,3.38%,0.665,0.28%,-0.449,$+107
2,Abs Threshold 5% | TLH=10%,3.38%,0.665,0.28%,-0.449,$+107

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 20-80  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),3.47%,0.681,-6.19%,0.19%,0.315
1,Yearly Rebal | No TLH,Off,3.37%,0.669,-6.07%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,3.37%,0.669,-6.07%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,3.47%,0.681,0.19%,0.315,"$+1,777"
1,Yearly Rebal | TLH=10%,3.38%,0.665,0.28%,-0.449,$+107
2,Abs Threshold 5% | TLH=10%,3.38%,0.665,0.28%,-0.449,$+107

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 20-80  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),3.47%,0.681,-6.19%,0.19%,0.315
1,Yearly Rebal | No TLH,Off,3.37%,0.669,-6.07%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,3.37%,0.669,-6.07%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,3.47%,0.681,0.19%,0.315,"$+1,777"
1,Yearly Rebal | TLH=10%,3.38%,0.665,0.28%,-0.449,$+107
2,Abs Threshold 5% | TLH=10%,3.38%,0.665,0.28%,-0.449,$+107

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 30-70  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | No TLH,Off,-11.06%,-0.683,-26.88%,0.00%,0.000
1,Abs Threshold 20% | TLH=10%,On (10%),-11.18%,-0.685,-27.27%,1.00%,-0.191
2,Rel Threshold 50% | TLH=10%,On (10%),-13.42%,-0.744,-30.10%,1.25%,-0.018

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-14.82%,-0.770,1.22%,0.321,"$+6,592"
1,Rel Threshold 50% | TLH=10%,-13.42%,-0.744,1.25%,-0.018,$+627
2,Rel Threshold 25% | TLH=10%,-15.01%,-0.792,1.12%,-0.125,"$-1,109"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 30-70  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,16.10%,5.622,-0.80%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),16.10%,5.622,-0.80%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,16.10%,5.622,-0.80%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,15.87%,5.596,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,16.10%,5.622,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,16.10%,5.622,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 30-70  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,6.66%,1.219,-3.09%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),6.66%,1.219,-3.09%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,6.66%,1.219,-3.09%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,6.14%,1.170,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,6.26%,1.192,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.66%,1.219,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 30-70  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),5.11%,0.775,-7.87%,0.30%,0.486
1,Yearly Rebal | No TLH,Off,4.97%,0.763,-7.76%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,4.97%,0.763,-7.76%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.11%,0.775,0.30%,0.486,"$+2,524"
1,Yearly Rebal | TLH=10%,4.83%,0.735,0.38%,-0.736,"$-1,219"
2,Abs Threshold 5% | TLH=10%,4.83%,0.735,0.38%,-0.736,"$-1,219"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 30-70  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),5.11%,0.775,-7.87%,0.30%,0.486
1,Yearly Rebal | No TLH,Off,4.97%,0.763,-7.76%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,4.97%,0.763,-7.76%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.11%,0.775,0.30%,0.486,"$+2,524"
1,Yearly Rebal | TLH=10%,4.83%,0.735,0.38%,-0.736,"$-1,219"
2,Abs Threshold 5% | TLH=10%,4.83%,0.735,0.38%,-0.736,"$-1,219"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 30-70  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),5.11%,0.775,-7.87%,0.30%,0.486
1,Yearly Rebal | No TLH,Off,4.97%,0.763,-7.76%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,4.97%,0.763,-7.76%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.11%,0.775,0.30%,0.486,"$+2,524"
1,Yearly Rebal | TLH=10%,4.83%,0.735,0.38%,-0.736,"$-1,219"
2,Abs Threshold 5% | TLH=10%,4.83%,0.735,0.38%,-0.736,"$-1,219"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 35-65  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | No TLH,Off,-14.15%,-0.750,-31.83%,0.00%,0.000
1,Abs Threshold 20% | TLH=10%,On (10%),-14.38%,-0.755,-32.36%,1.19%,-0.247
2,Abs Threshold 10% | No TLH,Off,-16.79%,-0.822,-35.15%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,-17.66%,-0.885,1.43%,-0.056,$-247
1,Abs Threshold 5% | TLH=10%,-18.50%,-0.858,1.05%,-0.113,$-808
2,Quarterly Rebal | TLH=10%,-18.72%,-0.914,1.38%,-0.211,"$-3,241"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 35-65  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,18.85%,5.738,-0.94%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),18.85%,5.738,-0.94%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,18.85%,5.738,-0.94%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,18.61%,5.721,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,18.85%,5.738,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,18.85%,5.738,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 35-65  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-5.29%,-0.812,-3.16%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-5.29%,-0.812,-3.16%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-5.29%,-0.812,-3.16%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-5.29%,-0.817,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-5.29%,-0.812,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-5.29%,-0.812,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 35-65  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),6.23%,0.791,-9.19%,0.35%,0.988
1,Rel Threshold 25% | No TLH,Off,6.10%,0.769,-9.28%,0.00%,0.000
2,Rel Threshold 25% | TLH=10%,On (10%),6.03%,0.769,-9.23%,0.41%,-0.544

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,6.23%,0.791,0.35%,0.988,"$+4,333"
1,Quarterly Rebal | TLH=10%,5.97%,0.766,0.43%,-0.319,$+57
2,Yearly Rebal | TLH=10%,5.78%,0.741,0.44%,-0.365,$-150

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 35-65  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),6.23%,0.791,-9.19%,0.35%,0.988
1,Rel Threshold 25% | No TLH,Off,6.10%,0.769,-9.28%,0.00%,0.000
2,Rel Threshold 25% | TLH=10%,On (10%),6.03%,0.769,-9.23%,0.41%,-0.544

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,6.23%,0.791,0.35%,0.988,"$+4,333"
1,Quarterly Rebal | TLH=10%,5.97%,0.766,0.43%,-0.319,$+57
2,Yearly Rebal | TLH=10%,5.78%,0.741,0.44%,-0.365,$-150

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 35-65  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),6.23%,0.791,-9.19%,0.35%,0.988
1,Rel Threshold 25% | No TLH,Off,6.10%,0.769,-9.28%,0.00%,0.000
2,Rel Threshold 25% | TLH=10%,On (10%),6.03%,0.769,-9.23%,0.41%,-0.544

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,6.23%,0.791,0.35%,0.988,"$+4,333"
1,Quarterly Rebal | TLH=10%,5.97%,0.766,0.43%,-0.319,$+57
2,Yearly Rebal | TLH=10%,5.78%,0.741,0.44%,-0.365,$-150

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 40-60  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | No TLH,Off,-15.13%,-0.764,-33.35%,0.00%,0.000
1,Abs Threshold 20% | TLH=10%,On (10%),-15.45%,-0.772,-34.00%,1.34%,-0.283
2,Rel Threshold 25% | No TLH,Off,-18.48%,-0.828,-37.55%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,-18.49%,-0.883,1.62%,-0.082,"$-1,004"
1,Abs Threshold 5% | TLH=10%,-19.33%,-0.860,1.17%,-0.173,"$-1,978"
2,Quarterly Rebal | TLH=10%,-19.49%,-0.908,1.57%,-0.215,"$-3,868"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 40-60  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,21.05%,5.790,-1.04%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),21.05%,5.790,-1.04%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,21.05%,5.790,-1.04%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,20.81%,5.776,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,21.05%,5.790,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,21.05%,5.790,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 40-60  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-4.48%,-0.616,-3.25%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-4.48%,-0.616,-3.25%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-4.48%,-0.616,-3.25%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-4.51%,-0.624,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-4.48%,-0.616,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-4.48%,-0.616,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 40-60  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),7.23%,0.812,-10.13%,0.44%,1.185
1,Rel Threshold 25% | No TLH,Off,7.31%,0.807,-10.23%,0.00%,0.000
2,Quarterly Rebal | TLH=10%,On (10%),6.85%,0.781,-10.19%,0.50%,-0.270

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.23%,0.812,0.44%,1.185,"$+5,829"
1,Quarterly Rebal | TLH=10%,6.85%,0.781,0.50%,-0.270,$+90
2,Yearly Rebal | TLH=10%,6.55%,0.747,0.50%,-0.375,$-380

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 40-60  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),7.23%,0.812,-10.13%,0.44%,1.185
1,Rel Threshold 25% | No TLH,Off,7.31%,0.807,-10.23%,0.00%,0.000
2,Quarterly Rebal | TLH=10%,On (10%),6.85%,0.781,-10.19%,0.50%,-0.270

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.23%,0.812,0.44%,1.185,"$+5,829"
1,Quarterly Rebal | TLH=10%,6.85%,0.781,0.50%,-0.270,$+90
2,Yearly Rebal | TLH=10%,6.55%,0.747,0.50%,-0.375,$-380

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 40-60  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),7.23%,0.812,-10.13%,0.44%,1.185
1,Rel Threshold 25% | No TLH,Off,7.31%,0.807,-10.23%,0.00%,0.000
2,Quarterly Rebal | TLH=10%,On (10%),6.85%,0.781,-10.19%,0.50%,-0.270

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.23%,0.812,0.44%,1.185,"$+5,829"
1,Quarterly Rebal | TLH=10%,6.85%,0.781,0.50%,-0.270,$+90
2,Yearly Rebal | TLH=10%,6.55%,0.747,0.50%,-0.375,$-380

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 45-55  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | No TLH,Off,-16.84%,-0.788,-35.88%,0.00%,0.000
1,Abs Threshold 20% | TLH=10%,On (10%),-17.17%,-0.795,-36.53%,1.36%,-0.291
2,Rel Threshold 25% | No TLH,Off,-20.10%,-0.843,-39.88%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-20.95%,-0.909,1.57%,-0.215,"$-3,869"
1,Abs Threshold 20% | TLH=10%,-17.17%,-0.795,1.36%,-0.291,"$-4,752"
2,Abs Threshold 5% | TLH=10%,-21.03%,-0.886,1.36%,-0.346,"$-5,706"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 45-55  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,23.41%,5.836,-1.15%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),23.41%,5.836,-1.15%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,23.41%,5.836,-1.15%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,23.18%,5.826,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,23.41%,5.836,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,23.41%,5.836,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 45-55  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-4.49%,-0.564,-3.40%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-4.49%,-0.564,-3.40%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-4.49%,-0.564,-3.40%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-4.52%,-0.570,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-4.49%,-0.564,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-4.49%,-0.564,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 45-55  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),8.57%,0.875,-10.74%,0.48%,1.230
1,Rel Threshold 25% | No TLH,Off,8.60%,0.865,-10.83%,0.00%,0.000
2,Quarterly Rebal | TLH=10%,On (10%),8.24%,0.852,-10.81%,0.54%,-0.033

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.57%,0.875,0.48%,1.230,"$+6,523"
1,Quarterly Rebal | TLH=10%,8.24%,0.852,0.54%,-0.033,"$+1,127"
2,Yearly Rebal | TLH=10%,7.93%,0.818,0.54%,-0.419,$-706

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 45-55  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),8.57%,0.875,-10.74%,0.48%,1.230
1,Rel Threshold 25% | No TLH,Off,8.60%,0.865,-10.83%,0.00%,0.000
2,Quarterly Rebal | TLH=10%,On (10%),8.24%,0.852,-10.81%,0.54%,-0.033

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.57%,0.875,0.48%,1.230,"$+6,523"
1,Quarterly Rebal | TLH=10%,8.24%,0.852,0.54%,-0.033,"$+1,127"
2,Yearly Rebal | TLH=10%,7.93%,0.818,0.54%,-0.419,$-706

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 45-55  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),8.57%,0.875,-10.74%,0.48%,1.230
1,Rel Threshold 25% | No TLH,Off,8.60%,0.865,-10.83%,0.00%,0.000
2,Quarterly Rebal | TLH=10%,On (10%),8.24%,0.852,-10.81%,0.54%,-0.033

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.57%,0.875,0.48%,1.230,"$+6,523"
1,Quarterly Rebal | TLH=10%,8.24%,0.852,0.54%,-0.033,"$+1,127"
2,Yearly Rebal | TLH=10%,7.93%,0.818,0.54%,-0.419,$-706

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 50-50  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,-20.91%,-0.848,-40.99%,0.00%,0.000
1,Rel Threshold 25% | No TLH,Off,-20.97%,-0.851,-41.13%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),-21.29%,-0.856,-41.59%,1.29%,-0.345

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-21.77%,-0.912,1.46%,-0.207,"$-3,368"
1,Abs Threshold 5% | TLH=10%,-21.29%,-0.856,1.29%,-0.345,"$-5,342"
2,Abs Threshold 20% | TLH=10%,-19.90%,-0.942,1.23%,-0.379,"$-5,668"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 50-50  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,24.44%,5.828,-1.20%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),24.44%,5.828,-1.20%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,24.44%,5.828,-1.20%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,24.22%,5.819,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,24.44%,5.828,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,24.44%,5.828,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 50-50  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-4.86%,-0.572,-3.54%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-4.86%,-0.572,-3.54%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-4.86%,-0.572,-3.54%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-4.88%,-0.577,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-4.86%,-0.572,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-4.86%,-0.572,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 50-50  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),9.60%,0.921,-11.03%,0.54%,1.265
1,Rel Threshold 25% | No TLH,Off,9.56%,0.906,-11.11%,0.00%,0.000
2,Quarterly Rebal | TLH=10%,On (10%),9.30%,0.903,-11.12%,0.59%,0.154

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.60%,0.921,0.54%,1.265,"$+7,330"
1,Quarterly Rebal | TLH=10%,9.30%,0.903,0.59%,0.154,"$+2,103"
2,Yearly Rebal | TLH=10%,9.07%,0.877,0.56%,-0.293,$-147

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 50-50  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),9.60%,0.921,-11.03%,0.54%,1.265
1,Rel Threshold 25% | No TLH,Off,9.56%,0.906,-11.11%,0.00%,0.000
2,Quarterly Rebal | TLH=10%,On (10%),9.30%,0.903,-11.12%,0.59%,0.154

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.60%,0.921,0.54%,1.265,"$+7,330"
1,Quarterly Rebal | TLH=10%,9.30%,0.903,0.59%,0.154,"$+2,103"
2,Yearly Rebal | TLH=10%,9.07%,0.877,0.56%,-0.293,$-147

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 50-50  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),9.60%,0.921,-11.03%,0.54%,1.265
1,Rel Threshold 25% | No TLH,Off,9.56%,0.906,-11.11%,0.00%,0.000
2,Quarterly Rebal | TLH=10%,On (10%),9.30%,0.903,-11.12%,0.59%,0.154

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.60%,0.921,0.54%,1.265,"$+7,330"
1,Quarterly Rebal | TLH=10%,9.30%,0.903,0.59%,0.154,"$+2,103"
2,Yearly Rebal | TLH=10%,9.07%,0.877,0.56%,-0.293,$-147

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 55-45  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,-21.44%,-0.847,-41.89%,0.00%,0.000
1,Rel Threshold 25% | No TLH,Off,-21.73%,-0.862,-42.15%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),-22.09%,-0.862,-42.79%,1.55%,-0.453

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-22.33%,-0.902,1.82%,-0.215,"$-4,568"
1,Rel Threshold 25% | TLH=10%,-22.37%,-0.875,1.61%,-0.433,"$-8,773"
2,Abs Threshold 5% | TLH=10%,-22.09%,-0.862,1.55%,-0.453,"$-8,857"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 55-45  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,26.37%,5.838,-1.30%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),26.37%,5.838,-1.30%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,26.37%,5.838,-1.30%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,26.16%,5.831,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,26.37%,5.838,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,26.37%,5.838,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 55-45  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-4.34%,-0.472,-3.63%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-4.34%,-0.472,-3.63%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-4.34%,-0.472,-3.63%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-4.40%,-0.481,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-4.34%,-0.472,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-4.34%,-0.472,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 55-45  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),10.79%,0.933,-12.03%,0.59%,1.349
1,Rel Threshold 25% | No TLH,Off,10.74%,0.918,-12.15%,0.00%,0.000
2,Quarterly Rebal | TLH=10%,On (10%),10.40%,0.911,-12.15%,0.68%,0.091

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,10.79%,0.933,0.59%,1.349,"$+8,307"
1,Quarterly Rebal | TLH=10%,10.40%,0.911,0.68%,0.091,"$+1,853"
2,Yearly Rebal | TLH=10%,10.04%,0.879,0.62%,-0.396,$-868

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 55-45  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),10.79%,0.933,-12.03%,0.59%,1.349
1,Rel Threshold 25% | No TLH,Off,10.74%,0.918,-12.15%,0.00%,0.000
2,Quarterly Rebal | TLH=10%,On (10%),10.40%,0.911,-12.15%,0.68%,0.091

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,10.79%,0.933,0.59%,1.349,"$+8,307"
1,Quarterly Rebal | TLH=10%,10.40%,0.911,0.68%,0.091,"$+1,853"
2,Yearly Rebal | TLH=10%,10.04%,0.879,0.62%,-0.396,$-868

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 55-45  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),10.79%,0.933,-12.03%,0.59%,1.349
1,Rel Threshold 25% | No TLH,Off,10.74%,0.918,-12.15%,0.00%,0.000
2,Quarterly Rebal | TLH=10%,On (10%),10.40%,0.911,-12.15%,0.68%,0.091

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,10.79%,0.933,0.59%,1.349,"$+8,307"
1,Quarterly Rebal | TLH=10%,10.40%,0.911,0.68%,0.091,"$+1,853"
2,Yearly Rebal | TLH=10%,10.04%,0.879,0.62%,-0.396,$-868

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 60-40  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,-22.72%,-0.859,-43.64%,0.00%,0.000
1,Rel Threshold 25% | No TLH,Off,-22.90%,-0.863,-43.76%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),-23.27%,-0.871,-44.33%,1.53%,-0.397

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-23.65%,-0.914,1.77%,-0.244,"$-5,089"
1,Rel Threshold 25% | TLH=10%,-23.35%,-0.871,1.49%,-0.340,"$-6,127"
2,Abs Threshold 5% | TLH=10%,-23.27%,-0.871,1.53%,-0.397,"$-7,479"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 60-40  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,28.94%,5.881,-1.43%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),28.94%,5.881,-1.43%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,28.94%,5.881,-1.43%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,28.74%,5.876,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,28.94%,5.881,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,28.94%,5.881,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 60-40  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-3.90%,-0.393,-3.77%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-3.90%,-0.393,-3.77%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-3.90%,-0.393,-3.77%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-3.97%,-0.402,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-3.90%,-0.393,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-3.90%,-0.393,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 60-40  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),11.20%,0.898,-12.81%,0.60%,1.355
1,Rel Threshold 25% | No TLH,Off,11.12%,0.884,-12.92%,0.00%,0.000
2,Quarterly Rebal | TLH=10%,On (10%),10.66%,0.864,-12.89%,0.70%,-0.091

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.20%,0.898,0.60%,1.355,"$+8,481"
1,Quarterly Rebal | TLH=10%,10.66%,0.864,0.70%,-0.091,$+754
2,Yearly Rebal | TLH=10%,10.27%,0.832,0.68%,-0.577,"$-2,124"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 60-40  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),11.20%,0.898,-12.81%,0.60%,1.355
1,Rel Threshold 25% | No TLH,Off,11.12%,0.884,-12.92%,0.00%,0.000
2,Quarterly Rebal | TLH=10%,On (10%),10.66%,0.864,-12.89%,0.70%,-0.091

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.20%,0.898,0.60%,1.355,"$+8,481"
1,Quarterly Rebal | TLH=10%,10.66%,0.864,0.70%,-0.091,$+754
2,Yearly Rebal | TLH=10%,10.27%,0.832,0.68%,-0.577,"$-2,124"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 60-40  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),11.20%,0.898,-12.81%,0.60%,1.355
1,Rel Threshold 25% | No TLH,Off,11.12%,0.884,-12.92%,0.00%,0.000
2,Quarterly Rebal | TLH=10%,On (10%),10.66%,0.864,-12.89%,0.70%,-0.091

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.20%,0.898,0.60%,1.355,"$+8,481"
1,Quarterly Rebal | TLH=10%,10.66%,0.864,0.70%,-0.091,$+754
2,Yearly Rebal | TLH=10%,10.27%,0.832,0.68%,-0.577,"$-2,124"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 65-35  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,-23.21%,-0.861,-44.31%,0.00%,0.000
1,Rel Threshold 25% | No TLH,Off,-23.38%,-0.864,-44.43%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),-23.71%,-0.871,-44.95%,1.45%,-0.383

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-24.08%,-0.912,1.67%,-0.241,"$-4,673"
1,Rel Threshold 25% | TLH=10%,-23.79%,-0.872,1.41%,-0.334,"$-5,605"
2,Abs Threshold 5% | TLH=10%,-23.71%,-0.871,1.45%,-0.383,"$-6,755"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 65-35  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,30.55%,5.886,-1.50%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),30.55%,5.886,-1.50%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,30.55%,5.886,-1.50%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,30.37%,5.883,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,30.55%,5.886,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,30.55%,5.886,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 65-35  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-4.13%,-0.398,-3.88%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-4.13%,-0.398,-3.88%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-4.13%,-0.398,-3.88%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-4.21%,-0.407,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-4.13%,-0.398,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-4.13%,-0.398,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 65-35  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),11.95%,0.899,-13.43%,0.65%,1.324
1,Rel Threshold 25% | No TLH,Off,11.80%,0.882,-13.56%,0.00%,0.000
2,Quarterly Rebal | TLH=10%,On (10%),11.39%,0.865,-13.52%,0.73%,-0.045

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.95%,0.899,0.65%,1.324,"$+8,837"
1,Quarterly Rebal | TLH=10%,11.39%,0.865,0.73%,-0.045,"$+1,029"
2,Yearly Rebal | TLH=10%,10.92%,0.828,0.73%,-0.599,"$-2,510"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 65-35  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),11.95%,0.899,-13.43%,0.65%,1.324
1,Rel Threshold 25% | No TLH,Off,11.80%,0.882,-13.56%,0.00%,0.000
2,Quarterly Rebal | TLH=10%,On (10%),11.39%,0.865,-13.52%,0.73%,-0.045

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.95%,0.899,0.65%,1.324,"$+8,837"
1,Quarterly Rebal | TLH=10%,11.39%,0.865,0.73%,-0.045,"$+1,029"
2,Yearly Rebal | TLH=10%,10.92%,0.828,0.73%,-0.599,"$-2,510"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 65-35  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),11.95%,0.899,-13.43%,0.65%,1.324
1,Rel Threshold 25% | No TLH,Off,11.80%,0.882,-13.56%,0.00%,0.000
2,Quarterly Rebal | TLH=10%,On (10%),11.39%,0.865,-13.52%,0.73%,-0.045

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.95%,0.899,0.65%,1.324,"$+8,837"
1,Quarterly Rebal | TLH=10%,11.39%,0.865,0.73%,-0.045,"$+1,029"
2,Yearly Rebal | TLH=10%,10.92%,0.828,0.73%,-0.599,"$-2,510"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 70-30  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,-24.37%,-0.862,-46.05%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,-23.71%,-0.865,-44.88%,0.00%,0.000
2,Rel Threshold 25% | TLH=10%,On (10%),-24.86%,-0.872,-46.63%,1.51%,-0.362

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-25.18%,-0.907,1.84%,-0.243,"$-5,247"
1,Rel Threshold 25% | TLH=10%,-24.86%,-0.872,1.51%,-0.362,"$-6,582"
2,Abs Threshold 5% | TLH=10%,-24.83%,-0.884,1.54%,-0.394,"$-7,410"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 70-30  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,31.78%,5.928,-1.54%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),31.78%,5.928,-1.54%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,31.78%,5.928,-1.54%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,31.62%,5.925,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,31.78%,5.928,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,31.78%,5.928,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 70-30  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-3.67%,-0.337,-3.96%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-3.67%,-0.337,-3.96%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-3.67%,-0.337,-3.96%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-3.75%,-0.345,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-3.67%,-0.337,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-3.67%,-0.337,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 70-30  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),12.49%,0.887,-14.15%,0.65%,1.331
1,Rel Threshold 25% | No TLH,Off,12.31%,0.870,-14.27%,0.00%,0.000
2,Quarterly Rebal | TLH=10%,On (10%),11.83%,0.850,-14.24%,0.75%,-0.144

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.49%,0.887,0.65%,1.331,"$+8,947"
1,Quarterly Rebal | TLH=10%,11.83%,0.850,0.75%,-0.144,$+382
2,Yearly Rebal | TLH=10%,11.29%,0.808,0.77%,-0.757,"$-3,797"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 70-30  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),12.49%,0.887,-14.15%,0.65%,1.331
1,Rel Threshold 25% | No TLH,Off,12.31%,0.870,-14.27%,0.00%,0.000
2,Quarterly Rebal | TLH=10%,On (10%),11.83%,0.850,-14.24%,0.75%,-0.144

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.49%,0.887,0.65%,1.331,"$+8,947"
1,Quarterly Rebal | TLH=10%,11.83%,0.850,0.75%,-0.144,$+382
2,Yearly Rebal | TLH=10%,11.29%,0.808,0.77%,-0.757,"$-3,797"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 70-30  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),12.49%,0.887,-14.15%,0.65%,1.331
1,Rel Threshold 25% | No TLH,Off,12.31%,0.870,-14.27%,0.00%,0.000
2,Quarterly Rebal | TLH=10%,On (10%),11.83%,0.850,-14.24%,0.75%,-0.144

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.49%,0.887,0.65%,1.331,"$+8,947"
1,Quarterly Rebal | TLH=10%,11.83%,0.850,0.75%,-0.144,$+382
2,Yearly Rebal | TLH=10%,11.29%,0.808,0.77%,-0.757,"$-3,797"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 75-25  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,-25.75%,-0.877,-47.57%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,-24.76%,-0.882,-46.40%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-25.29%,-0.884,-47.17%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-26.18%,-0.903,1.84%,-0.251,"$-5,431"
1,Abs Threshold 5% | TLH=10%,-25.80%,-0.893,1.61%,-0.351,"$-6,800"
2,Rel Threshold 25% | TLH=10%,-26.31%,-0.887,1.51%,-0.403,"$-7,395"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 75-25  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,32.82%,5.942,-1.58%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),32.82%,5.942,-1.58%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,32.90%,5.942,-1.58%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,32.82%,5.942,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,32.90%,5.942,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,32.90%,5.942,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 75-25  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-4.28%,-0.384,-4.04%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-4.28%,-0.384,-4.04%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-4.28%,-0.384,-4.04%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-4.34%,-0.391,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-4.28%,-0.384,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-4.28%,-0.384,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 75-25  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),12.88%,0.887,-14.55%,0.67%,1.290
1,Rel Threshold 25% | No TLH,Off,12.69%,0.870,-14.66%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,12.12%,0.846,-14.59%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.88%,0.887,0.67%,1.290,"$+8,866"
1,Quarterly Rebal | TLH=10%,12.02%,0.838,0.75%,-0.423,"$-1,460"
2,Yearly Rebal | TLH=10%,11.73%,0.813,0.79%,-0.692,"$-3,444"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 75-25  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),12.88%,0.887,-14.55%,0.67%,1.290
1,Rel Threshold 25% | No TLH,Off,12.69%,0.870,-14.66%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,12.12%,0.846,-14.59%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.88%,0.887,0.67%,1.290,"$+8,866"
1,Quarterly Rebal | TLH=10%,12.02%,0.838,0.75%,-0.423,"$-1,460"
2,Yearly Rebal | TLH=10%,11.73%,0.813,0.79%,-0.692,"$-3,444"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 75-25  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),12.88%,0.887,-14.55%,0.67%,1.290
1,Rel Threshold 25% | No TLH,Off,12.69%,0.870,-14.66%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,12.12%,0.846,-14.59%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.88%,0.887,0.67%,1.290,"$+8,866"
1,Quarterly Rebal | TLH=10%,12.02%,0.838,0.75%,-0.423,"$-1,460"
2,Yearly Rebal | TLH=10%,11.73%,0.813,0.79%,-0.692,"$-3,444"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 80-20  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,-25.02%,-0.864,-47.25%,0.00%,0.000
1,Rel Threshold 25% | No TLH,Off,-26.59%,-0.872,-48.82%,0.00%,0.000
2,Abs Threshold 10% | TLH=10%,On (10%),-25.74%,-0.878,-48.12%,1.92%,-0.405

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-27.09%,-0.892,2.16%,-0.258,"$-6,649"
1,Abs Threshold 5% | TLH=10%,-26.93%,-0.902,1.78%,-0.365,"$-7,900"
2,Monthly Rebal | TLH=10%,-27.35%,-0.897,1.77%,-0.397,"$-8,594"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 80-20  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,34.02%,5.960,-1.63%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),34.02%,5.960,-1.63%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,34.02%,5.960,-1.63%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,33.90%,5.959,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,34.02%,5.960,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,34.02%,5.960,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 80-20  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-4.19%,-0.365,-4.07%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-4.19%,-0.365,-4.07%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-4.19%,-0.365,-4.07%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-4.29%,-0.375,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-4.19%,-0.365,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-4.19%,-0.365,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 80-20  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),13.74%,0.896,-15.21%,0.68%,1.364
1,Rel Threshold 25% | No TLH,Off,13.44%,0.875,-15.31%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,12.91%,0.853,-15.27%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,13.74%,0.896,0.68%,1.364,"$+9,505"
1,Quarterly Rebal | TLH=10%,12.85%,0.851,0.80%,-0.326,$-949
2,Rel Threshold 25% | TLH=10%,12.96%,0.844,0.85%,-0.743,"$-4,182"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 80-20  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),13.74%,0.896,-15.21%,0.68%,1.364
1,Rel Threshold 25% | No TLH,Off,13.44%,0.875,-15.31%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,12.91%,0.853,-15.27%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,13.74%,0.896,0.68%,1.364,"$+9,505"
1,Quarterly Rebal | TLH=10%,12.85%,0.851,0.80%,-0.326,$-949
2,Rel Threshold 25% | TLH=10%,12.96%,0.844,0.85%,-0.743,"$-4,182"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 80-20  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),13.74%,0.896,-15.21%,0.68%,1.364
1,Rel Threshold 25% | No TLH,Off,13.44%,0.875,-15.31%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,12.91%,0.853,-15.27%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,13.74%,0.896,0.68%,1.364,"$+9,505"
1,Quarterly Rebal | TLH=10%,12.85%,0.851,0.80%,-0.326,$-949
2,Rel Threshold 25% | TLH=10%,12.96%,0.844,0.85%,-0.743,"$-4,182"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 90-10  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | No TLH,Off,-28.94%,-0.861,-52.45%,0.00%,0.000
1,Rel Threshold 25% | No TLH,Off,-29.38%,-0.872,-52.82%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,-29.43%,-0.876,-52.91%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-29.91%,-0.879,2.24%,-0.265,"$-7,005"
1,Monthly Rebal | TLH=10%,-30.12%,-0.890,1.79%,-0.418,"$-8,980"
2,Yearly Rebal | TLH=10%,-30.11%,-0.901,1.83%,-0.470,"$-10,441"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 90-10  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,36.49%,6.032,-1.71%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),36.49%,6.032,-1.71%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,36.56%,6.030,-1.72%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,36.49%,6.032,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,36.56%,6.030,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,36.56%,6.030,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 90-10  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-3.49%,-0.280,-4.27%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-3.49%,-0.280,-4.27%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-3.49%,-0.280,-4.27%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-3.63%,-0.292,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-3.49%,-0.280,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-3.49%,-0.280,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 90-10  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,14.39%,0.857,-16.61%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),14.14%,0.843,-16.49%,0.75%,0.716
2,Quarterly Rebal | TLH=10%,On (10%),13.72%,0.830,-16.61%,0.82%,-0.217

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,14.14%,0.843,0.75%,0.716,"$+6,022"
1,Quarterly Rebal | TLH=10%,13.72%,0.830,0.82%,-0.217,$-211
2,Yearly Rebal | TLH=10%,13.16%,0.788,0.90%,-0.718,"$-4,334"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 90-10  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,14.39%,0.857,-16.61%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),14.14%,0.843,-16.49%,0.75%,0.716
2,Quarterly Rebal | TLH=10%,On (10%),13.72%,0.830,-16.61%,0.82%,-0.217

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,14.14%,0.843,0.75%,0.716,"$+6,022"
1,Quarterly Rebal | TLH=10%,13.72%,0.830,0.82%,-0.217,$-211
2,Yearly Rebal | TLH=10%,13.16%,0.788,0.90%,-0.718,"$-4,334"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable High - 90-10  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,14.39%,0.857,-16.61%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),14.14%,0.843,-16.49%,0.75%,0.716
2,Quarterly Rebal | TLH=10%,On (10%),13.72%,0.830,-16.61%,0.82%,-0.217

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,14.14%,0.843,0.75%,0.716,"$+6,022"
1,Quarterly Rebal | TLH=10%,13.72%,0.830,0.82%,-0.217,$-211
2,Yearly Rebal | TLH=10%,13.16%,0.788,0.90%,-0.718,"$-4,334"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 0-100  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,7.66%,0.856,-7.77%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),7.66%,0.856,-7.77%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,7.66%,0.856,-7.77%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.66%,0.856,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,7.66%,0.856,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,7.66%,0.856,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 0-100  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,1.35%,0.556,-5.08%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),1.35%,0.556,-5.08%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,1.35%,0.556,-5.08%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,1.34%,0.553,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,1.34%,0.554,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,1.34%,0.555,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 0-100  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,0.53%,0.148,-4.32%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),0.53%,0.148,-4.32%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,0.53%,0.147,-4.33%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.53%,0.146,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.53%,0.148,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,0.53%,0.145,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 0-100  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,0.89%,0.256,-4.32%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),0.89%,0.256,-4.32%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,0.88%,0.255,-4.32%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.88%,0.255,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.89%,0.256,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,0.88%,0.254,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 0-100  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,0.89%,0.256,-4.32%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),0.89%,0.256,-4.32%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,0.88%,0.255,-4.32%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.88%,0.255,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.89%,0.256,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,0.88%,0.254,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 0-100  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,0.89%,0.256,-4.32%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),0.89%,0.256,-4.32%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,0.88%,0.255,-4.32%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.88%,0.255,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.89%,0.256,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,0.88%,0.254,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 10-90  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | No TLH,Off,-2.12%,-0.275,-11.82%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,-2.61%,-0.301,-11.46%,0.00%,0.000
2,Rel Threshold 50% | No TLH,Off,-2.61%,-0.301,-11.46%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,-3.53%,-0.393,0.89%,-0.126,$-615
1,Monthly Rebal | TLH=10%,-4.05%,-0.451,0.66%,-0.272,"$-1,654"
2,Abs Threshold 5% | TLH=10%,-3.86%,-0.428,0.69%,-0.444,"$-3,679"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 10-90  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,6.61%,2.764,-1.08%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),6.61%,2.764,-1.08%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,6.61%,2.747,-1.08%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,6.59%,2.737,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,6.61%,2.764,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.61%,2.747,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 10-90  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,5.41%,1.238,-5.14%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),5.41%,1.238,-5.14%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,5.41%,1.238,-5.14%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,4.57%,1.094,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,4.66%,1.116,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,5.02%,1.174,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 10-90  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,5.34%,1.143,-6.45%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),5.34%,1.143,-6.45%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,5.34%,1.143,-6.45%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,4.36%,1.031,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,4.42%,1.043,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,4.64%,1.081,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 10-90  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,5.34%,1.143,-6.45%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),5.34%,1.143,-6.45%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,5.34%,1.143,-6.45%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,4.36%,1.031,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,4.42%,1.043,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,4.64%,1.081,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 10-90  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,5.34%,1.143,-6.45%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),5.34%,1.143,-6.45%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,5.34%,1.143,-6.45%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,4.36%,1.031,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,4.42%,1.043,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,4.64%,1.081,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 100-0  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | TLH=10%,On (10%),-21.53%,-0.675,-53.46%,1.36%,0.326
1,Rel Threshold 25% | TLH=10%,On (10%),-21.78%,-0.681,-53.77%,1.37%,0.299
2,Abs Threshold 5% | TLH=10%,On (10%),-21.58%,-0.687,-53.38%,1.32%,0.339

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-21.58%,-0.687,1.32%,0.339,"$+7,725"
1,Abs Threshold 10% | TLH=10%,-21.58%,-0.687,1.32%,0.339,"$+7,725"
2,Abs Threshold 20% | TLH=10%,-21.58%,-0.687,1.32%,0.339,"$+7,725"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 100-0  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,38.39%,6.025,-1.80%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),38.39%,6.025,-1.80%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,38.37%,6.023,-1.79%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,38.39%,6.025,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,38.37%,6.023,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,38.37%,6.023,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 100-0  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-4.04%,-0.307,-4.52%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-4.04%,-0.307,-4.52%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-4.04%,-0.307,-4.52%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-4.20%,-0.320,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-4.04%,-0.307,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-4.04%,-0.307,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 100-0  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),15.19%,0.895,-17.57%,0.68%,0.777
1,Quarterly Rebal | TLH=10%,On (10%),15.02%,0.892,-17.46%,0.83%,0.146
2,Yearly Rebal | No TLH,Off,14.91%,0.887,-17.39%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,15.19%,0.895,0.68%,0.777,"$+7,859"
1,Rel Threshold 25% | TLH=10%,15.00%,0.883,0.88%,0.176,"$+3,293"
2,Quarterly Rebal | TLH=10%,15.02%,0.892,0.83%,0.146,"$+2,891"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 100-0  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),15.19%,0.895,-17.57%,0.68%,0.777
1,Quarterly Rebal | TLH=10%,On (10%),15.02%,0.892,-17.46%,0.83%,0.146
2,Yearly Rebal | No TLH,Off,14.91%,0.887,-17.39%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,15.19%,0.895,0.68%,0.777,"$+7,859"
1,Rel Threshold 25% | TLH=10%,15.00%,0.883,0.88%,0.176,"$+3,293"
2,Quarterly Rebal | TLH=10%,15.02%,0.892,0.83%,0.146,"$+2,891"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 100-0  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),15.19%,0.895,-17.57%,0.68%,0.777
1,Quarterly Rebal | TLH=10%,On (10%),15.02%,0.892,-17.46%,0.83%,0.146
2,Yearly Rebal | No TLH,Off,14.91%,0.887,-17.39%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,15.19%,0.895,0.68%,0.777,"$+7,859"
1,Rel Threshold 25% | TLH=10%,15.00%,0.883,0.88%,0.176,"$+3,293"
2,Quarterly Rebal | TLH=10%,15.02%,0.892,0.83%,0.146,"$+2,891"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 20-80  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,-7.17%,-0.603,-19.54%,0.00%,0.000
1,Abs Threshold 10% | TLH=10%,On (10%),-7.32%,-0.611,-19.85%,0.85%,-0.259
2,Abs Threshold 5% | TLH=10%,On (10%),-8.09%,-0.626,-21.08%,1.02%,0.391

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-8.09%,-0.626,1.02%,0.391,"$+7,083"
1,Rel Threshold 25% | TLH=10%,-8.64%,-0.681,1.01%,0.115,"$+2,786"
2,Rel Threshold 50% | TLH=10%,-7.48%,-0.628,0.92%,-0.149,"$-1,032"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 20-80  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,10.50%,4.922,-0.55%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),10.50%,4.922,-0.55%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,10.50%,4.922,-0.55%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,10.28%,4.854,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,10.50%,4.922,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,10.50%,4.922,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 20-80  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,8.07%,1.482,-5.96%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),8.07%,1.482,-5.96%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,8.07%,1.482,-5.96%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,6.95%,1.363,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,7.09%,1.389,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,7.54%,1.428,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 20-80  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,7.78%,1.258,-8.38%,0.00%,0.000
1,Abs Threshold 10% | TLH=10%,On (10%),7.78%,1.258,-8.38%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,7.78%,1.258,-8.38%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,6.62%,1.210,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,6.92%,1.241,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,7.30%,1.196,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 20-80  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,7.78%,1.258,-8.38%,0.00%,0.000
1,Abs Threshold 10% | TLH=10%,On (10%),7.78%,1.258,-8.38%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,7.78%,1.258,-8.38%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,6.62%,1.210,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,6.92%,1.241,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,7.30%,1.196,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 20-80  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,7.78%,1.258,-8.38%,0.00%,0.000
1,Abs Threshold 10% | TLH=10%,On (10%),7.78%,1.258,-8.38%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,7.78%,1.258,-8.38%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,6.62%,1.210,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,6.92%,1.241,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,7.30%,1.196,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 30-70  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | No TLH,Off,-11.06%,-0.683,-26.88%,0.00%,0.000
1,Abs Threshold 20% | TLH=10%,On (10%),-11.18%,-0.685,-27.27%,1.00%,-0.191
2,Rel Threshold 50% | TLH=10%,On (10%),-13.42%,-0.744,-30.10%,1.25%,-0.018

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-14.82%,-0.770,1.22%,0.321,"$+6,592"
1,Rel Threshold 50% | TLH=10%,-13.42%,-0.744,1.25%,-0.018,$+627
2,Rel Threshold 25% | TLH=10%,-15.01%,-0.792,1.12%,-0.125,"$-1,109"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 30-70  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,16.10%,5.622,-0.80%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),16.10%,5.622,-0.80%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,16.10%,5.622,-0.80%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,15.87%,5.596,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,16.10%,5.622,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,16.10%,5.622,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 30-70  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,10.88%,1.643,-6.96%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),10.88%,1.643,-6.96%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,10.88%,1.643,-6.96%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.59%,1.550,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,9.76%,1.574,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,10.29%,1.601,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 30-70  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,10.40%,1.338,-10.35%,0.00%,0.000
1,Abs Threshold 10% | TLH=10%,On (10%),10.40%,1.338,-10.35%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,10.40%,1.338,-10.35%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,9.07%,1.310,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,9.44%,1.337,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,9.78%,1.276,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 30-70  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,10.40%,1.338,-10.35%,0.00%,0.000
1,Abs Threshold 10% | TLH=10%,On (10%),10.40%,1.338,-10.35%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,10.40%,1.338,-10.35%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,9.07%,1.310,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,9.44%,1.337,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,9.78%,1.276,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 30-70  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,10.40%,1.338,-10.35%,0.00%,0.000
1,Abs Threshold 10% | TLH=10%,On (10%),10.40%,1.338,-10.35%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,10.40%,1.338,-10.35%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,9.07%,1.310,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,9.44%,1.337,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,9.78%,1.276,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 35-65  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | No TLH,Off,-14.15%,-0.750,-31.83%,0.00%,0.000
1,Abs Threshold 20% | TLH=10%,On (10%),-14.38%,-0.755,-32.36%,1.19%,-0.247
2,Abs Threshold 10% | No TLH,Off,-16.79%,-0.822,-35.15%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,-17.66%,-0.885,1.43%,-0.056,$-247
1,Abs Threshold 5% | TLH=10%,-18.50%,-0.858,1.05%,-0.113,$-808
2,Quarterly Rebal | TLH=10%,-18.72%,-0.914,1.38%,-0.211,"$-3,241"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 35-65  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,18.85%,5.738,-0.94%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),18.85%,5.738,-0.94%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,18.85%,5.738,-0.94%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,18.61%,5.721,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,18.85%,5.738,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,18.85%,5.738,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 35-65  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-5.42%,-0.725,-3.41%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-5.42%,-0.725,-3.41%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-5.42%,-0.725,-3.41%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-5.43%,-0.732,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-5.42%,-0.725,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-5.42%,-0.725,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 35-65  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),7.23%,0.787,-10.73%,0.51%,0.107
1,Yearly Rebal | No TLH,Off,7.14%,0.775,-10.63%,0.00%,0.000
2,Rel Threshold 25% | TLH=10%,On (10%),7.16%,0.775,-10.90%,0.51%,0.198

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,7.16%,0.775,0.51%,0.198,"$+2,503"
1,Quarterly Rebal | TLH=10%,7.23%,0.787,0.51%,0.107,"$+1,954"
2,Monthly Rebal | TLH=10%,7.03%,0.762,0.18%,-0.138,"$+1,003"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 35-65  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),7.23%,0.787,-10.73%,0.51%,0.107
1,Yearly Rebal | No TLH,Off,7.14%,0.775,-10.63%,0.00%,0.000
2,Rel Threshold 25% | TLH=10%,On (10%),7.16%,0.775,-10.90%,0.51%,0.198

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,7.16%,0.775,0.51%,0.198,"$+2,503"
1,Quarterly Rebal | TLH=10%,7.23%,0.787,0.51%,0.107,"$+1,954"
2,Monthly Rebal | TLH=10%,7.03%,0.762,0.18%,-0.138,"$+1,003"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 35-65  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),7.23%,0.787,-10.73%,0.51%,0.107
1,Yearly Rebal | No TLH,Off,7.14%,0.775,-10.63%,0.00%,0.000
2,Rel Threshold 25% | TLH=10%,On (10%),7.16%,0.775,-10.90%,0.51%,0.198

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,7.16%,0.775,0.51%,0.198,"$+2,503"
1,Quarterly Rebal | TLH=10%,7.23%,0.787,0.51%,0.107,"$+1,954"
2,Monthly Rebal | TLH=10%,7.03%,0.762,0.18%,-0.138,"$+1,003"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 40-60  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | No TLH,Off,-15.13%,-0.764,-33.35%,0.00%,0.000
1,Abs Threshold 20% | TLH=10%,On (10%),-15.45%,-0.772,-34.00%,1.34%,-0.283
2,Rel Threshold 25% | No TLH,Off,-18.48%,-0.828,-37.55%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,-18.49%,-0.883,1.62%,-0.082,"$-1,004"
1,Abs Threshold 5% | TLH=10%,-19.33%,-0.860,1.17%,-0.173,"$-1,978"
2,Quarterly Rebal | TLH=10%,-19.49%,-0.908,1.57%,-0.215,"$-3,868"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 40-60  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,21.05%,5.790,-1.04%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),21.05%,5.790,-1.04%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,21.05%,5.790,-1.04%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,20.81%,5.776,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,21.05%,5.790,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,21.05%,5.790,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 40-60  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-4.49%,-0.538,-3.49%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-4.49%,-0.538,-3.49%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-4.49%,-0.538,-3.49%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-4.53%,-0.547,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-4.49%,-0.538,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-4.49%,-0.538,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 40-60  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),8.37%,0.808,-11.79%,0.43%,0.614
1,Quarterly Rebal | TLH=10%,On (10%),8.27%,0.805,-11.78%,0.65%,-0.013
2,Yearly Rebal | No TLH,Off,8.19%,0.795,-11.66%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.37%,0.808,0.43%,0.614,"$+4,448"
1,Rel Threshold 25% | TLH=10%,8.20%,0.792,0.59%,0.098,"$+2,008"
2,Quarterly Rebal | TLH=10%,8.27%,0.805,0.65%,-0.013,"$+1,217"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 40-60  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),8.37%,0.808,-11.79%,0.43%,0.614
1,Quarterly Rebal | TLH=10%,On (10%),8.27%,0.805,-11.78%,0.65%,-0.013
2,Yearly Rebal | No TLH,Off,8.19%,0.795,-11.66%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.37%,0.808,0.43%,0.614,"$+4,448"
1,Rel Threshold 25% | TLH=10%,8.20%,0.792,0.59%,0.098,"$+2,008"
2,Quarterly Rebal | TLH=10%,8.27%,0.805,0.65%,-0.013,"$+1,217"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 40-60  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),8.37%,0.808,-11.79%,0.43%,0.614
1,Quarterly Rebal | TLH=10%,On (10%),8.27%,0.805,-11.78%,0.65%,-0.013
2,Yearly Rebal | No TLH,Off,8.19%,0.795,-11.66%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.37%,0.808,0.43%,0.614,"$+4,448"
1,Rel Threshold 25% | TLH=10%,8.20%,0.792,0.59%,0.098,"$+2,008"
2,Quarterly Rebal | TLH=10%,8.27%,0.805,0.65%,-0.013,"$+1,217"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 45-55  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | No TLH,Off,-16.84%,-0.788,-35.88%,0.00%,0.000
1,Abs Threshold 20% | TLH=10%,On (10%),-17.17%,-0.795,-36.53%,1.36%,-0.291
2,Rel Threshold 25% | No TLH,Off,-20.10%,-0.843,-39.88%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-20.95%,-0.909,1.57%,-0.215,"$-3,869"
1,Abs Threshold 20% | TLH=10%,-17.17%,-0.795,1.36%,-0.291,"$-4,752"
2,Abs Threshold 5% | TLH=10%,-21.03%,-0.886,1.36%,-0.346,"$-5,706"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 45-55  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,23.41%,5.836,-1.15%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),23.41%,5.836,-1.15%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,23.41%,5.836,-1.15%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,23.18%,5.826,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,23.41%,5.836,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,23.41%,5.836,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 45-55  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-4.52%,-0.499,-3.62%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-4.52%,-0.499,-3.62%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-4.52%,-0.499,-3.62%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-4.56%,-0.507,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-4.52%,-0.499,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-4.52%,-0.499,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 45-55  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),9.83%,0.868,-12.40%,0.63%,0.380
1,Quarterly Rebal | TLH=10%,On (10%),9.68%,0.867,-12.33%,0.68%,0.117
2,Monthly Rebal | TLH=10%,On (10%),9.75%,0.867,-12.37%,0.48%,0.691

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.75%,0.867,0.48%,0.691,"$+5,315"
1,Rel Threshold 25% | TLH=10%,9.83%,0.868,0.63%,0.380,"$+4,218"
2,Rel Threshold 50% | TLH=10%,9.70%,0.861,0.69%,0.201,"$+3,011"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 45-55  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),9.83%,0.868,-12.40%,0.63%,0.380
1,Quarterly Rebal | TLH=10%,On (10%),9.68%,0.867,-12.33%,0.68%,0.117
2,Monthly Rebal | TLH=10%,On (10%),9.75%,0.867,-12.37%,0.48%,0.691

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.75%,0.867,0.48%,0.691,"$+5,315"
1,Rel Threshold 25% | TLH=10%,9.83%,0.868,0.63%,0.380,"$+4,218"
2,Rel Threshold 50% | TLH=10%,9.70%,0.861,0.69%,0.201,"$+3,011"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 45-55  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),9.83%,0.868,-12.40%,0.63%,0.380
1,Quarterly Rebal | TLH=10%,On (10%),9.68%,0.867,-12.33%,0.68%,0.117
2,Monthly Rebal | TLH=10%,On (10%),9.75%,0.867,-12.37%,0.48%,0.691

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.75%,0.867,0.48%,0.691,"$+5,315"
1,Rel Threshold 25% | TLH=10%,9.83%,0.868,0.63%,0.380,"$+4,218"
2,Rel Threshold 50% | TLH=10%,9.70%,0.861,0.69%,0.201,"$+3,011"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 50-50  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,-20.91%,-0.848,-40.99%,0.00%,0.000
1,Rel Threshold 25% | No TLH,Off,-20.97%,-0.851,-41.13%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),-21.29%,-0.856,-41.59%,1.29%,-0.345

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-21.77%,-0.912,1.46%,-0.207,"$-3,368"
1,Abs Threshold 5% | TLH=10%,-21.29%,-0.856,1.29%,-0.345,"$-5,342"
2,Abs Threshold 20% | TLH=10%,-19.90%,-0.942,1.23%,-0.379,"$-5,668"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 50-50  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,24.44%,5.828,-1.20%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),24.44%,5.828,-1.20%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,24.44%,5.828,-1.20%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,24.22%,5.819,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,24.44%,5.828,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,24.44%,5.828,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 50-50  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-4.96%,-0.528,-3.74%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-4.96%,-0.528,-3.74%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-4.96%,-0.528,-3.74%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-5.00%,-0.534,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-4.96%,-0.528,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-4.96%,-0.528,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 50-50  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),10.48%,0.907,-12.36%,0.70%,0.249
1,Yearly Rebal | No TLH,Off,10.49%,0.905,-12.24%,0.00%,0.000
2,Monthly Rebal | TLH=10%,On (10%),10.49%,0.903,-12.43%,0.52%,0.745

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,10.49%,0.903,0.52%,0.745,"$+6,044"
1,Quarterly Rebal | TLH=10%,10.48%,0.907,0.70%,0.249,"$+3,443"
2,Rel Threshold 25% | TLH=10%,10.21%,0.880,0.76%,-0.202,$-511

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 50-50  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),10.48%,0.907,-12.36%,0.70%,0.249
1,Yearly Rebal | No TLH,Off,10.49%,0.905,-12.24%,0.00%,0.000
2,Monthly Rebal | TLH=10%,On (10%),10.49%,0.903,-12.43%,0.52%,0.745

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,10.49%,0.903,0.52%,0.745,"$+6,044"
1,Quarterly Rebal | TLH=10%,10.48%,0.907,0.70%,0.249,"$+3,443"
2,Rel Threshold 25% | TLH=10%,10.21%,0.880,0.76%,-0.202,$-511

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 50-50  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),10.48%,0.907,-12.36%,0.70%,0.249
1,Yearly Rebal | No TLH,Off,10.49%,0.905,-12.24%,0.00%,0.000
2,Monthly Rebal | TLH=10%,On (10%),10.49%,0.903,-12.43%,0.52%,0.745

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,10.49%,0.903,0.52%,0.745,"$+6,044"
1,Quarterly Rebal | TLH=10%,10.48%,0.907,0.70%,0.249,"$+3,443"
2,Rel Threshold 25% | TLH=10%,10.21%,0.880,0.76%,-0.202,$-511

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 55-45  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,-21.44%,-0.847,-41.89%,0.00%,0.000
1,Rel Threshold 25% | No TLH,Off,-21.73%,-0.862,-42.15%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),-22.09%,-0.862,-42.79%,1.55%,-0.453

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-22.33%,-0.902,1.82%,-0.215,"$-4,568"
1,Rel Threshold 25% | TLH=10%,-22.37%,-0.875,1.61%,-0.433,"$-8,773"
2,Abs Threshold 5% | TLH=10%,-22.09%,-0.862,1.55%,-0.453,"$-8,857"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 55-45  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,26.37%,5.838,-1.30%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),26.37%,5.838,-1.30%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,26.37%,5.838,-1.30%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,26.16%,5.831,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,26.37%,5.838,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,26.37%,5.838,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 55-45  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-4.35%,-0.429,-3.82%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-4.35%,-0.429,-3.82%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-4.35%,-0.429,-3.82%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-4.43%,-0.439,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-4.35%,-0.429,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-4.35%,-0.429,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 55-45  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),11.49%,0.913,-13.48%,0.80%,0.108
1,Rel Threshold 25% | TLH=10%,On (10%),11.63%,0.913,-13.55%,0.71%,0.385
2,Yearly Rebal | No TLH,Off,11.52%,0.912,-13.35%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.57%,0.911,0.55%,0.727,"$+6,188"
1,Rel Threshold 25% | TLH=10%,11.63%,0.913,0.71%,0.385,"$+4,668"
2,Quarterly Rebal | TLH=10%,11.49%,0.913,0.80%,0.108,"$+2,408"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 55-45  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),11.49%,0.913,-13.48%,0.80%,0.108
1,Rel Threshold 25% | TLH=10%,On (10%),11.63%,0.913,-13.55%,0.71%,0.385
2,Yearly Rebal | No TLH,Off,11.52%,0.912,-13.35%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.57%,0.911,0.55%,0.727,"$+6,188"
1,Rel Threshold 25% | TLH=10%,11.63%,0.913,0.71%,0.385,"$+4,668"
2,Quarterly Rebal | TLH=10%,11.49%,0.913,0.80%,0.108,"$+2,408"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 55-45  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),11.49%,0.913,-13.48%,0.80%,0.108
1,Rel Threshold 25% | TLH=10%,On (10%),11.63%,0.913,-13.55%,0.71%,0.385
2,Yearly Rebal | No TLH,Off,11.52%,0.912,-13.35%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.57%,0.911,0.55%,0.727,"$+6,188"
1,Rel Threshold 25% | TLH=10%,11.63%,0.913,0.71%,0.385,"$+4,668"
2,Quarterly Rebal | TLH=10%,11.49%,0.913,0.80%,0.108,"$+2,408"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 60-40  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,-22.72%,-0.859,-43.64%,0.00%,0.000
1,Rel Threshold 25% | No TLH,Off,-22.90%,-0.863,-43.76%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),-23.27%,-0.871,-44.33%,1.53%,-0.397

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-23.65%,-0.914,1.77%,-0.244,"$-5,089"
1,Rel Threshold 25% | TLH=10%,-23.35%,-0.871,1.49%,-0.340,"$-6,127"
2,Abs Threshold 5% | TLH=10%,-23.27%,-0.871,1.53%,-0.397,"$-7,479"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 60-40  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,28.94%,5.881,-1.43%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),28.94%,5.881,-1.43%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,28.94%,5.881,-1.43%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,28.74%,5.876,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,28.94%,5.881,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,28.94%,5.881,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 60-40  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-3.89%,-0.360,-3.94%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-3.89%,-0.360,-3.94%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-3.89%,-0.360,-3.94%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-3.98%,-0.370,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-3.89%,-0.360,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-3.89%,-0.360,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 60-40  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),12.19%,0.901,-14.28%,0.59%,0.801
1,Quarterly Rebal | TLH=10%,On (10%),12.05%,0.899,-14.21%,0.79%,0.127
2,Yearly Rebal | No TLH,Off,12.04%,0.896,-14.09%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.19%,0.901,0.59%,0.801,"$+7,122"
1,Rel Threshold 25% | TLH=10%,12.14%,0.896,0.71%,0.339,"$+4,261"
2,Quarterly Rebal | TLH=10%,12.05%,0.899,0.79%,0.127,"$+2,582"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 60-40  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),12.19%,0.901,-14.28%,0.59%,0.801
1,Quarterly Rebal | TLH=10%,On (10%),12.05%,0.899,-14.21%,0.79%,0.127
2,Yearly Rebal | No TLH,Off,12.04%,0.896,-14.09%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.19%,0.901,0.59%,0.801,"$+7,122"
1,Rel Threshold 25% | TLH=10%,12.14%,0.896,0.71%,0.339,"$+4,261"
2,Quarterly Rebal | TLH=10%,12.05%,0.899,0.79%,0.127,"$+2,582"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 60-40  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),12.19%,0.901,-14.28%,0.59%,0.801
1,Quarterly Rebal | TLH=10%,On (10%),12.05%,0.899,-14.21%,0.79%,0.127
2,Yearly Rebal | No TLH,Off,12.04%,0.896,-14.09%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.19%,0.901,0.59%,0.801,"$+7,122"
1,Rel Threshold 25% | TLH=10%,12.14%,0.896,0.71%,0.339,"$+4,261"
2,Quarterly Rebal | TLH=10%,12.05%,0.899,0.79%,0.127,"$+2,582"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 65-35  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,-23.19%,-0.860,-44.28%,0.00%,0.000
1,Rel Threshold 25% | No TLH,Off,-23.36%,-0.864,-44.40%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),-23.68%,-0.870,-44.92%,1.45%,-0.383

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-24.07%,-0.912,1.67%,-0.242,"$-4,685"
1,Rel Threshold 25% | TLH=10%,-23.77%,-0.871,1.41%,-0.332,"$-5,576"
2,Abs Threshold 5% | TLH=10%,-23.68%,-0.870,1.45%,-0.383,"$-6,747"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 65-35  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,30.54%,5.885,-1.50%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),30.54%,5.885,-1.50%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,30.54%,5.885,-1.50%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,30.37%,5.883,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,30.54%,5.885,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,30.54%,5.885,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 65-35  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-4.11%,-0.364,-4.06%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-4.11%,-0.364,-4.06%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-4.11%,-0.364,-4.06%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-4.20%,-0.374,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-4.11%,-0.364,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-4.11%,-0.364,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 65-35  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),12.75%,0.899,-14.87%,0.63%,0.795
1,Quarterly Rebal | TLH=10%,On (10%),12.60%,0.896,-14.80%,0.80%,0.152
2,Yearly Rebal | No TLH,Off,12.53%,0.891,-14.69%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.75%,0.899,0.63%,0.795,"$+7,385"
1,Rel Threshold 25% | TLH=10%,12.62%,0.888,0.73%,0.267,"$+3,736"
2,Quarterly Rebal | TLH=10%,12.60%,0.896,0.80%,0.152,"$+2,844"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 65-35  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),12.75%,0.899,-14.87%,0.63%,0.795
1,Quarterly Rebal | TLH=10%,On (10%),12.60%,0.896,-14.80%,0.80%,0.152
2,Yearly Rebal | No TLH,Off,12.53%,0.891,-14.69%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.75%,0.899,0.63%,0.795,"$+7,385"
1,Rel Threshold 25% | TLH=10%,12.62%,0.888,0.73%,0.267,"$+3,736"
2,Quarterly Rebal | TLH=10%,12.60%,0.896,0.80%,0.152,"$+2,844"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 65-35  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),12.75%,0.899,-14.87%,0.63%,0.795
1,Quarterly Rebal | TLH=10%,On (10%),12.60%,0.896,-14.80%,0.80%,0.152
2,Yearly Rebal | No TLH,Off,12.53%,0.891,-14.69%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.75%,0.899,0.63%,0.795,"$+7,385"
1,Rel Threshold 25% | TLH=10%,12.62%,0.888,0.73%,0.267,"$+3,736"
2,Quarterly Rebal | TLH=10%,12.60%,0.896,0.80%,0.152,"$+2,844"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 70-30  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,-24.37%,-0.862,-46.05%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,-23.71%,-0.865,-44.88%,0.00%,0.000
2,Rel Threshold 25% | TLH=10%,On (10%),-24.86%,-0.872,-46.63%,1.51%,-0.362

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-25.18%,-0.907,1.84%,-0.243,"$-5,247"
1,Rel Threshold 25% | TLH=10%,-24.86%,-0.872,1.51%,-0.362,"$-6,582"
2,Abs Threshold 5% | TLH=10%,-24.83%,-0.884,1.54%,-0.394,"$-7,410"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 70-30  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,31.78%,5.928,-1.54%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),31.78%,5.928,-1.54%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,31.78%,5.928,-1.54%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,31.62%,5.925,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,31.78%,5.928,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,31.78%,5.928,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 70-30  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-3.67%,-0.318,-4.08%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-3.67%,-0.318,-4.08%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-3.67%,-0.318,-4.08%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-3.76%,-0.327,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-3.67%,-0.318,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-3.67%,-0.318,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 70-30  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),13.03%,0.893,-15.33%,0.62%,0.799
1,Quarterly Rebal | TLH=10%,On (10%),12.89%,0.891,-15.25%,0.77%,0.170
2,Yearly Rebal | No TLH,Off,12.81%,0.885,-15.15%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,13.03%,0.893,0.62%,0.799,"$+7,332"
1,Quarterly Rebal | TLH=10%,12.89%,0.891,0.77%,0.170,"$+2,965"
2,Rel Threshold 25% | TLH=10%,12.78%,0.875,0.74%,0.105,"$+2,318"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 70-30  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),13.03%,0.893,-15.33%,0.62%,0.799
1,Quarterly Rebal | TLH=10%,On (10%),12.89%,0.891,-15.25%,0.77%,0.170
2,Yearly Rebal | No TLH,Off,12.81%,0.885,-15.15%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,13.03%,0.893,0.62%,0.799,"$+7,332"
1,Quarterly Rebal | TLH=10%,12.89%,0.891,0.77%,0.170,"$+2,965"
2,Rel Threshold 25% | TLH=10%,12.78%,0.875,0.74%,0.105,"$+2,318"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 70-30  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),13.03%,0.893,-15.33%,0.62%,0.799
1,Quarterly Rebal | TLH=10%,On (10%),12.89%,0.891,-15.25%,0.77%,0.170
2,Yearly Rebal | No TLH,Off,12.81%,0.885,-15.15%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,13.03%,0.893,0.62%,0.799,"$+7,332"
1,Quarterly Rebal | TLH=10%,12.89%,0.891,0.77%,0.170,"$+2,965"
2,Rel Threshold 25% | TLH=10%,12.78%,0.875,0.74%,0.105,"$+2,318"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 75-25  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,-25.78%,-0.877,-47.59%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,-24.82%,-0.883,-46.47%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-25.33%,-0.884,-47.22%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-26.18%,-0.903,1.84%,-0.251,"$-5,420"
1,Abs Threshold 5% | TLH=10%,-25.82%,-0.892,1.59%,-0.339,"$-6,476"
2,Rel Threshold 25% | TLH=10%,-26.33%,-0.887,1.51%,-0.405,"$-7,423"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 75-25  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,32.98%,5.944,-1.59%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),32.98%,5.944,-1.59%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,32.98%,5.944,-1.59%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,32.84%,5.943,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,32.98%,5.944,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,32.98%,5.944,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 75-25  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-4.29%,-0.369,-4.14%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-4.29%,-0.369,-4.14%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-4.29%,-0.369,-4.14%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-4.39%,-0.379,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-4.29%,-0.369,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-4.29%,-0.369,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 75-25  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),13.12%,0.885,-15.59%,0.62%,0.761
1,Quarterly Rebal | TLH=10%,On (10%),12.98%,0.883,-15.51%,0.76%,0.160
2,Yearly Rebal | No TLH,Off,12.90%,0.878,-15.42%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,13.12%,0.885,0.62%,0.761,"$+7,065"
1,Quarterly Rebal | TLH=10%,12.98%,0.883,0.76%,0.160,"$+2,851"
2,Rel Threshold 25% | TLH=10%,12.91%,0.870,0.74%,0.143,"$+2,667"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 75-25  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),13.12%,0.885,-15.59%,0.62%,0.761
1,Quarterly Rebal | TLH=10%,On (10%),12.98%,0.883,-15.51%,0.76%,0.160
2,Yearly Rebal | No TLH,Off,12.90%,0.878,-15.42%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,13.12%,0.885,0.62%,0.761,"$+7,065"
1,Quarterly Rebal | TLH=10%,12.98%,0.883,0.76%,0.160,"$+2,851"
2,Rel Threshold 25% | TLH=10%,12.91%,0.870,0.74%,0.143,"$+2,667"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 75-25  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),13.12%,0.885,-15.59%,0.62%,0.761
1,Quarterly Rebal | TLH=10%,On (10%),12.98%,0.883,-15.51%,0.76%,0.160
2,Yearly Rebal | No TLH,Off,12.90%,0.878,-15.42%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,13.12%,0.885,0.62%,0.761,"$+7,065"
1,Quarterly Rebal | TLH=10%,12.98%,0.883,0.76%,0.160,"$+2,851"
2,Rel Threshold 25% | TLH=10%,12.91%,0.870,0.74%,0.143,"$+2,667"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 80-20  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,-24.94%,-0.863,-47.16%,0.00%,0.000
1,Rel Threshold 25% | No TLH,Off,-26.56%,-0.872,-48.79%,0.00%,0.000
2,Abs Threshold 10% | TLH=10%,On (10%),-25.66%,-0.877,-48.03%,1.92%,-0.404

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-27.09%,-0.892,2.16%,-0.258,"$-6,660"
1,Abs Threshold 5% | TLH=10%,-26.89%,-0.902,1.78%,-0.365,"$-7,910"
2,Monthly Rebal | TLH=10%,-27.35%,-0.897,1.77%,-0.397,"$-8,594"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 80-20  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,33.96%,5.961,-1.63%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),33.96%,5.961,-1.63%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,33.96%,5.961,-1.63%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,33.89%,5.958,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,33.96%,5.961,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,33.96%,5.961,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 80-20  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-4.16%,-0.348,-4.15%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-4.16%,-0.348,-4.15%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-4.16%,-0.348,-4.15%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-4.31%,-0.362,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-4.16%,-0.348,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-4.16%,-0.348,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 80-20  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),13.65%,0.890,-16.13%,0.62%,0.730
1,Quarterly Rebal | TLH=10%,On (10%),13.53%,0.889,-16.05%,0.74%,0.154
2,Yearly Rebal | No TLH,Off,13.43%,0.883,-15.96%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,13.65%,0.890,0.62%,0.730,"$+6,861"
1,Quarterly Rebal | TLH=10%,13.53%,0.889,0.74%,0.154,"$+2,780"
2,Rel Threshold 25% | TLH=10%,13.36%,0.872,0.79%,0.018,"$+1,565"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 80-20  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),13.65%,0.890,-16.13%,0.62%,0.730
1,Quarterly Rebal | TLH=10%,On (10%),13.53%,0.889,-16.05%,0.74%,0.154
2,Yearly Rebal | No TLH,Off,13.43%,0.883,-15.96%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,13.65%,0.890,0.62%,0.730,"$+6,861"
1,Quarterly Rebal | TLH=10%,13.53%,0.889,0.74%,0.154,"$+2,780"
2,Rel Threshold 25% | TLH=10%,13.36%,0.872,0.79%,0.018,"$+1,565"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 80-20  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),13.65%,0.890,-16.13%,0.62%,0.730
1,Quarterly Rebal | TLH=10%,On (10%),13.53%,0.889,-16.05%,0.74%,0.154
2,Yearly Rebal | No TLH,Off,13.43%,0.883,-15.96%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,13.65%,0.890,0.62%,0.730,"$+6,861"
1,Quarterly Rebal | TLH=10%,13.53%,0.889,0.74%,0.154,"$+2,780"
2,Rel Threshold 25% | TLH=10%,13.36%,0.872,0.79%,0.018,"$+1,565"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 90-10  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | No TLH,Off,-28.91%,-0.860,-52.43%,0.00%,0.000
1,Rel Threshold 25% | No TLH,Off,-29.36%,-0.871,-52.80%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,-29.43%,-0.876,-52.91%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-29.91%,-0.879,2.24%,-0.265,"$-7,006"
1,Monthly Rebal | TLH=10%,-30.12%,-0.890,1.79%,-0.418,"$-8,980"
2,Yearly Rebal | TLH=10%,-30.10%,-0.901,1.83%,-0.469,"$-10,422"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 90-10  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,36.48%,6.031,-1.71%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),36.48%,6.031,-1.71%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,36.50%,6.029,-1.72%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,36.48%,6.031,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,36.50%,6.029,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,36.50%,6.029,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 90-10  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-3.61%,-0.290,-4.28%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-3.61%,-0.290,-4.28%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-3.61%,-0.290,-4.28%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-3.69%,-0.296,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-3.61%,-0.290,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-3.61%,-0.290,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 90-10  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),14.15%,0.876,-17.05%,0.63%,0.745
1,Quarterly Rebal | TLH=10%,On (10%),13.96%,0.872,-16.97%,0.81%,0.066
2,Yearly Rebal | No TLH,Off,13.87%,0.866,-16.89%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,14.15%,0.876,0.63%,0.745,"$+7,052"
1,Quarterly Rebal | TLH=10%,13.96%,0.872,0.81%,0.066,"$+2,043"
2,Rel Threshold 25% | TLH=10%,13.92%,0.862,0.84%,0.064,"$+2,046"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 90-10  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),14.15%,0.876,-17.05%,0.63%,0.745
1,Quarterly Rebal | TLH=10%,On (10%),13.96%,0.872,-16.97%,0.81%,0.066
2,Yearly Rebal | No TLH,Off,13.87%,0.866,-16.89%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,14.15%,0.876,0.63%,0.745,"$+7,052"
1,Quarterly Rebal | TLH=10%,13.96%,0.872,0.81%,0.066,"$+2,043"
2,Rel Threshold 25% | TLH=10%,13.92%,0.862,0.84%,0.064,"$+2,046"

──────────────────────────────────────────────────────────────────────────────────────────
  FFG Taxable Medium - 90-10  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),14.15%,0.876,-17.05%,0.63%,0.745
1,Quarterly Rebal | TLH=10%,On (10%),13.96%,0.872,-16.97%,0.81%,0.066
2,Yearly Rebal | No TLH,Off,13.87%,0.866,-16.89%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,14.15%,0.876,0.63%,0.745,"$+7,052"
1,Quarterly Rebal | TLH=10%,13.96%,0.872,0.81%,0.066,"$+2,043"
2,Rel Threshold 25% | TLH=10%,13.92%,0.862,0.84%,0.064,"$+2,046"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 0-100  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,1.23%,0.144,-12.17%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,0.94%,0.117,-11.91%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,0.94%,0.117,-11.91%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 10% | TLH=10%,-0.43%,-0.053,5.35%,-0.268,"$-24,644"
1,Abs Threshold 20% | TLH=10%,-0.43%,-0.053,5.35%,-0.268,"$-24,644"
2,Rel Threshold 25% | TLH=10%,-0.43%,-0.053,5.35%,-0.268,"$-24,644"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 0-100  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-3.33%,-0.846,-1.38%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-3.33%,-0.846,-1.38%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-3.33%,-0.846,-1.38%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-3.36%,-0.851,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-3.33%,-0.846,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-3.33%,-0.846,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 0-100  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),-0.89%,-0.140,-7.49%,0.28%,0.539
1,Quarterly Rebal | No TLH,Off,-1.06%,-0.163,-7.44%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,-1.08%,-0.166,-7.46%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,-0.89%,-0.140,0.28%,0.539,"$+3,560"
1,Quarterly Rebal | TLH=10%,-1.07%,-0.171,0.30%,-0.288,$-203
2,Monthly Rebal | TLH=10%,-1.10%,-0.176,0.30%,-0.314,$-306

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 0-100  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),0.54%,0.094,-7.49%,0.26%,0.229
1,Quarterly Rebal | No TLH,Off,0.47%,0.079,-7.44%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,0.46%,0.077,-7.46%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,0.54%,0.094,0.26%,0.229,"$+2,802"
1,Quarterly Rebal | TLH=10%,0.43%,0.075,0.28%,-0.317,"$-1,062"
2,Monthly Rebal | TLH=10%,0.42%,0.073,0.27%,-0.330,"$-1,088"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 0-100  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),0.54%,0.094,-7.49%,0.26%,0.229
1,Quarterly Rebal | No TLH,Off,0.47%,0.079,-7.44%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,0.46%,0.077,-7.46%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,0.54%,0.094,0.26%,0.229,"$+2,802"
1,Quarterly Rebal | TLH=10%,0.43%,0.075,0.28%,-0.317,"$-1,062"
2,Monthly Rebal | TLH=10%,0.42%,0.073,0.27%,-0.330,"$-1,088"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 0-100  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),0.54%,0.094,-7.49%,0.26%,0.229
1,Quarterly Rebal | No TLH,Off,0.47%,0.079,-7.44%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,0.46%,0.077,-7.46%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,0.54%,0.094,0.26%,0.229,"$+2,802"
1,Quarterly Rebal | TLH=10%,0.43%,0.075,0.28%,-0.317,"$-1,062"
2,Monthly Rebal | TLH=10%,0.42%,0.073,0.27%,-0.330,"$-1,088"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 10-90  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,0.70%,0.077,-13.18%,0.00%,0.000
1,Monthly Rebal | No TLH,Off,0.42%,0.047,-13.54%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,0.40%,0.047,-12.95%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 10% | TLH=10%,-1.08%,-0.127,5.81%,-0.266,"$-26,489"
1,Abs Threshold 20% | TLH=10%,-1.08%,-0.127,5.81%,-0.266,"$-26,489"
2,Rel Threshold 25% | TLH=10%,-1.08%,-0.127,5.81%,-0.266,"$-26,489"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 10-90  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-1.62%,-0.422,-1.32%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-1.62%,-0.422,-1.32%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-1.62%,-0.422,-1.32%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-1.73%,-0.449,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-1.62%,-0.422,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-1.62%,-0.422,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 10-90  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),0.29%,0.046,-7.55%,0.30%,0.607
1,Rel Threshold 50% | TLH=10%,On (10%),0.27%,0.041,-7.55%,0.20%,0.317
2,Abs Threshold 5% | No TLH,Off,0.23%,0.035,-7.48%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,0.29%,0.046,0.30%,0.607,"$+4,091"
1,Rel Threshold 25% | TLH=10%,0.15%,0.024,0.30%,0.404,"$+3,124"
2,Rel Threshold 50% | TLH=10%,0.27%,0.041,0.20%,0.317,"$+2,239"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 10-90  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,-2.91%,-0.799,-1.74%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),-2.91%,-0.799,-1.74%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-2.91%,-0.799,-1.74%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-2.93%,-0.804,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-2.93%,-0.803,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-2.91%,-0.799,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 10-90  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,-2.91%,-0.799,-1.74%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),-2.91%,-0.799,-1.74%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-2.91%,-0.799,-1.74%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-2.93%,-0.804,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-2.93%,-0.803,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-2.91%,-0.799,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 10-90  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,-2.91%,-0.799,-1.74%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),-2.91%,-0.799,-1.74%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-2.91%,-0.799,-1.74%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-2.93%,-0.804,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-2.93%,-0.803,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-2.91%,-0.799,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 100-0  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | TLH=10%,On (10%),-26.71%,-0.735,-57.34%,3.81%,-0.036
1,Rel Threshold 50% | No TLH,Off,-26.62%,-0.750,-57.21%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-27.33%,-0.772,-58.11%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-27.56%,-0.809,5.34%,0.025,"$+2,484"
1,Rel Threshold 50% | TLH=10%,-26.71%,-0.735,3.81%,-0.036,"$-1,253"
2,Quarterly Rebal | TLH=10%,-27.83%,-0.789,4.17%,-0.073,"$-3,537"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 100-0  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,10.13%,0.692,-20.50%,0.00%,0.000
1,Rel Threshold 25% | TLH=10%,On (10%),10.07%,0.691,-20.59%,0.86%,-0.173
2,Quarterly Rebal | No TLH,Off,10.00%,0.684,-20.43%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,10.07%,0.691,0.86%,-0.173,"$-1,019"
1,Monthly Rebal | TLH=10%,9.35%,0.646,1.17%,-0.624,"$-10,368"
2,Quarterly Rebal | TLH=10%,9.34%,0.650,1.19%,-0.627,"$-10,607"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 100-0  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | TLH=10%,On (10%),22.69%,1.700,-9.38%,0.36%,-0.013
1,Abs Threshold 20% | TLH=10%,On (10%),22.69%,1.700,-9.38%,0.36%,-0.013
2,Rel Threshold 50% | TLH=10%,On (10%),22.69%,1.700,-9.38%,0.36%,-0.013

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,22.49%,1.699,0.38%,0.244,"$+2,826"
1,Rel Threshold 25% | TLH=10%,22.31%,1.673,0.37%,0.130,"$+2,212"
2,Yearly Rebal | TLH=10%,22.62%,1.696,0.37%,0.094,"$+2,044"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 100-0  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,11.11%,0.908,-5.41%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),11.11%,0.908,-5.41%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,11.05%,0.900,-5.50%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.11%,0.908,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,11.05%,0.900,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,11.05%,0.900,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 100-0  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,11.11%,0.908,-5.41%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),11.11%,0.908,-5.41%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,11.05%,0.900,-5.50%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.11%,0.908,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,11.05%,0.900,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,11.05%,0.900,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 100-0  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,11.11%,0.908,-5.41%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),11.11%,0.908,-5.41%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,11.05%,0.900,-5.50%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.11%,0.908,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,11.05%,0.900,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,11.05%,0.900,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 20-80  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,0.82%,0.092,-12.93%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,0.53%,0.062,-12.71%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,0.53%,0.062,-12.71%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 10% | TLH=10%,-0.91%,-0.108,5.65%,-0.266,"$-25,813"
1,Abs Threshold 20% | TLH=10%,-0.91%,-0.108,5.65%,-0.266,"$-25,813"
2,Rel Threshold 25% | TLH=10%,-0.91%,-0.108,5.65%,-0.266,"$-25,813"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 20-80  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,3.43%,1.050,-0.94%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),3.43%,1.050,-0.94%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,3.43%,1.050,-0.94%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,3.13%,0.950,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,3.43%,1.050,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,3.43%,1.050,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 20-80  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,2.60%,0.401,-7.62%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,2.60%,0.401,-7.62%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,2.60%,0.401,-7.62%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,2.48%,0.389,0.30%,0.626,"$+4,350"
1,Rel Threshold 25% | TLH=10%,2.32%,0.364,0.31%,0.430,"$+3,396"
2,Monthly Rebal | TLH=10%,1.94%,0.310,0.36%,0.014,"$+1,319"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 20-80  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,-1.82%,-0.434,-2.14%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),-1.82%,-0.434,-2.14%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-1.82%,-0.434,-2.14%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-1.84%,-0.441,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-1.84%,-0.441,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-1.82%,-0.434,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 20-80  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,-1.82%,-0.434,-2.14%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),-1.82%,-0.434,-2.14%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-1.82%,-0.434,-2.14%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-1.84%,-0.441,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-1.84%,-0.441,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-1.82%,-0.434,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 20-80  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,-1.82%,-0.434,-2.14%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),-1.82%,-0.434,-2.14%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-1.82%,-0.434,-2.14%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-1.84%,-0.441,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-1.84%,-0.441,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-1.82%,-0.434,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 30-70  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,0.74%,0.082,-13.04%,0.00%,0.000
1,Monthly Rebal | No TLH,Off,0.46%,0.052,-13.40%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,0.44%,0.051,-12.82%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 10% | TLH=10%,-1.02%,-0.121,5.72%,-0.266,"$-26,111"
1,Abs Threshold 20% | TLH=10%,-1.02%,-0.121,5.72%,-0.266,"$-26,111"
2,Rel Threshold 25% | TLH=10%,-1.02%,-0.121,5.72%,-0.266,"$-26,111"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 30-70  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,10.42%,3.360,-0.80%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),10.42%,3.360,-0.80%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,10.42%,3.360,-0.80%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.91%,3.171,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,10.42%,3.360,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,10.42%,3.360,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 30-70  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,5.56%,0.797,-8.01%,0.00%,0.000
1,Abs Threshold 20% | No TLH,Off,5.56%,0.797,-8.01%,0.00%,0.000
2,Rel Threshold 50% | No TLH,Off,5.56%,0.797,-8.01%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,5.29%,0.777,0.36%,0.860,"$+6,347"
1,Rel Threshold 25% | TLH=10%,5.10%,0.750,0.38%,0.781,"$+6,169"
2,Abs Threshold 5% | TLH=10%,5.19%,0.757,0.31%,0.744,"$+5,095"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 30-70  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,-0.38%,-0.074,-2.66%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),-0.38%,-0.074,-2.66%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-0.38%,-0.074,-2.66%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-0.41%,-0.080,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-0.42%,-0.082,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-0.38%,-0.074,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 30-70  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,-0.38%,-0.074,-2.66%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),-0.38%,-0.074,-2.66%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-0.38%,-0.074,-2.66%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-0.41%,-0.080,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-0.42%,-0.082,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-0.38%,-0.074,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 30-70  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,-0.38%,-0.074,-2.66%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),-0.38%,-0.074,-2.66%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-0.38%,-0.074,-2.66%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-0.41%,-0.080,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-0.42%,-0.082,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-0.38%,-0.074,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 40-60  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,0.82%,0.090,-13.17%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,0.53%,0.062,-12.95%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,0.53%,0.062,-12.95%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 10% | TLH=10%,-0.95%,-0.111,5.81%,-0.266,"$-26,514"
1,Abs Threshold 20% | TLH=10%,-0.95%,-0.111,5.81%,-0.266,"$-26,514"
2,Rel Threshold 25% | TLH=10%,-0.95%,-0.111,5.81%,-0.266,"$-26,514"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 40-60  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,17.36%,5.270,-0.92%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),17.36%,5.270,-0.92%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,17.36%,5.270,-0.92%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,16.73%,5.079,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,17.36%,5.270,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,17.36%,5.270,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 40-60  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,8.36%,1.081,-8.57%,0.00%,0.000
1,Abs Threshold 20% | No TLH,Off,8.36%,1.081,-8.57%,0.00%,0.000
2,Rel Threshold 50% | No TLH,Off,8.36%,1.081,-8.57%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,7.96%,1.059,0.37%,0.906,"$+6,900"
1,Abs Threshold 5% | TLH=10%,7.67%,1.025,0.40%,0.589,"$+5,268"
2,Quarterly Rebal | TLH=10%,7.28%,0.997,0.36%,0.565,"$+4,724"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 40-60  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,0.94%,0.148,-3.20%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),0.94%,0.148,-3.20%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,0.94%,0.148,-3.20%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.91%,0.145,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.90%,0.142,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,0.94%,0.148,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 40-60  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,0.94%,0.148,-3.20%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),0.94%,0.148,-3.20%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,0.94%,0.148,-3.20%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.91%,0.145,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.90%,0.142,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,0.94%,0.148,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 40-60  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,0.94%,0.148,-3.20%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),0.94%,0.148,-3.20%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,0.94%,0.148,-3.20%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.91%,0.145,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.90%,0.142,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,0.94%,0.148,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 50-50  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | No TLH,Off,-5.59%,-0.523,-20.46%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,-6.01%,-0.583,-20.81%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,-5.55%,-0.607,-19.77%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,-6.90%,-0.775,4.58%,-0.229,"$-16,743"
1,Rel Threshold 25% | TLH=10%,-7.73%,-0.753,4.50%,-0.234,"$-16,696"
2,Abs Threshold 10% | TLH=10%,-6.57%,-0.762,4.46%,-0.242,"$-17,343"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 50-50  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,26.31%,6.671,-1.13%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),26.31%,6.671,-1.13%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,26.31%,6.671,-1.13%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,25.59%,6.541,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,26.31%,6.671,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,26.31%,6.671,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 50-50  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,11.69%,1.335,-9.16%,0.00%,0.000
1,Abs Threshold 20% | No TLH,Off,11.69%,1.335,-9.16%,0.00%,0.000
2,Rel Threshold 50% | No TLH,Off,11.69%,1.335,-9.16%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,11.22%,1.318,0.38%,0.959,"$+7,586"
1,Rel Threshold 25% | TLH=10%,11.10%,1.311,0.32%,0.737,"$+5,419"
2,Abs Threshold 5% | TLH=10%,10.91%,1.287,0.38%,0.728,"$+6,183"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 50-50  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,2.28%,0.306,-3.62%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),2.28%,0.306,-3.62%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,2.29%,0.305,-3.69%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.28%,0.306,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,2.25%,0.300,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,2.29%,0.305,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 50-50  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,2.28%,0.306,-3.62%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),2.28%,0.306,-3.62%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,2.29%,0.305,-3.69%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.28%,0.306,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,2.25%,0.300,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,2.29%,0.305,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 50-50  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,2.28%,0.306,-3.62%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),2.28%,0.306,-3.62%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,2.29%,0.305,-3.69%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.28%,0.306,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,2.25%,0.300,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,2.29%,0.305,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 60-40  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,-12.28%,-0.712,-33.73%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,-12.77%,-0.773,-33.31%,0.00%,0.000
2,Rel Threshold 50% | No TLH,Off,-12.48%,-0.790,-32.34%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,-13.31%,-0.846,4.12%,-0.217,"$-13,404"
1,Yearly Rebal | TLH=10%,-12.93%,-0.900,4.24%,-0.237,"$-15,238"
2,Rel Threshold 25% | TLH=10%,-13.30%,-0.793,4.10%,-0.263,"$-16,368"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 60-40  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,35.77%,7.649,-1.30%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),35.77%,7.649,-1.30%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,35.77%,7.649,-1.30%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,35.09%,7.574,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,35.77%,7.649,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,35.77%,7.649,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 60-40  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,14.71%,1.484,-9.57%,0.00%,0.000
1,Abs Threshold 20% | No TLH,Off,14.71%,1.484,-9.57%,0.00%,0.000
2,Rel Threshold 50% | No TLH,Off,14.71%,1.484,-9.57%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,13.98%,1.450,0.33%,0.727,"$+5,623"
1,Yearly Rebal | TLH=10%,14.01%,1.437,0.27%,0.543,"$+3,997"
2,Abs Threshold 5% | TLH=10%,13.94%,1.445,0.27%,0.540,"$+3,970"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 60-40  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,5.12%,0.585,-3.90%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),5.12%,0.585,-3.90%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,5.12%,0.585,-3.90%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.03%,0.580,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,4.99%,0.575,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,5.12%,0.585,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 60-40  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,5.12%,0.585,-3.90%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),5.12%,0.585,-3.90%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,5.12%,0.585,-3.90%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.03%,0.580,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,4.99%,0.575,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,5.12%,0.585,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 60-40  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,5.12%,0.585,-3.90%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),5.12%,0.585,-3.90%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,5.12%,0.585,-3.90%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.03%,0.580,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,4.99%,0.575,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,5.12%,0.585,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 70-30  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,-11.83%,-0.681,-34.00%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,-13.98%,-0.738,-36.78%,0.00%,0.000
2,Rel Threshold 25% | No TLH,Off,-14.31%,-0.751,-37.10%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-14.67%,-0.799,3.50%,-0.214,"$-10,984"
1,Rel Threshold 50% | TLH=10%,-14.97%,-0.827,3.68%,-0.217,"$-11,675"
2,Yearly Rebal | TLH=10%,-14.62%,-0.887,3.75%,-0.241,"$-13,450"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 70-30  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,40.54%,7.732,-1.44%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),40.54%,7.732,-1.44%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,40.54%,7.732,-1.44%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,39.91%,7.676,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,40.54%,7.732,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,40.54%,7.732,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 70-30  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,16.61%,1.524,-10.13%,0.00%,0.000
1,Abs Threshold 20% | No TLH,Off,16.61%,1.524,-10.13%,0.00%,0.000
2,Rel Threshold 50% | No TLH,Off,16.61%,1.524,-10.13%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,15.77%,1.490,0.36%,0.761,"$+6,297"
1,Abs Threshold 5% | TLH=10%,15.85%,1.488,0.29%,0.587,"$+4,544"
2,Yearly Rebal | TLH=10%,15.91%,1.480,0.29%,0.559,"$+4,357"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 70-30  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,5.91%,0.606,-4.29%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),5.91%,0.606,-4.29%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,5.91%,0.606,-4.29%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.83%,0.603,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,5.79%,0.597,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,5.91%,0.606,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 70-30  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,5.91%,0.606,-4.29%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),5.91%,0.606,-4.29%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,5.91%,0.606,-4.29%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.83%,0.603,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,5.79%,0.597,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,5.91%,0.606,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 70-30  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,5.91%,0.606,-4.29%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),5.91%,0.606,-4.29%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,5.91%,0.606,-4.29%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.83%,0.603,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,5.79%,0.597,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,5.91%,0.606,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 80-20  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | No TLH,Off,-17.14%,-0.780,-41.43%,0.00%,0.000
1,Rel Threshold 25% | No TLH,Off,-17.78%,-0.781,-42.90%,0.00%,0.000
2,Rel Threshold 50% | TLH=10%,On (10%),-17.71%,-0.793,-41.64%,3.42%,-0.183

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-18.51%,-0.848,3.32%,-0.169,"$-7,705"
1,Rel Threshold 50% | TLH=10%,-17.71%,-0.793,3.42%,-0.183,"$-8,761"
2,Abs Threshold 5% | TLH=10%,-18.58%,-0.842,3.41%,-0.223,"$-10,776"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 80-20  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,44.77%,7.782,-1.57%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),44.77%,7.782,-1.57%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,44.77%,7.782,-1.57%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,44.28%,7.753,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,44.77%,7.782,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,44.77%,7.782,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 80-20  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | No TLH,Off,21.15%,1.720,-10.41%,0.00%,0.000
1,Abs Threshold 20% | TLH=10%,On (10%),21.10%,1.715,-10.49%,0.13%,-1.011
2,Abs Threshold 10% | No TLH,Off,20.00%,1.678,-10.41%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,18.37%,1.575,0.21%,0.036,"$+1,856"
1,Yearly Rebal | TLH=10%,19.51%,1.634,0.16%,-0.226,$+853
2,Quarterly Rebal | TLH=10%,18.73%,1.605,0.20%,-0.273,$+427

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 80-20  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,6.86%,0.660,-4.56%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),6.86%,0.660,-4.56%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,6.86%,0.660,-4.56%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,6.81%,0.660,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,6.76%,0.653,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.86%,0.660,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 80-20  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,6.86%,0.660,-4.56%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),6.86%,0.660,-4.56%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,6.86%,0.660,-4.56%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,6.81%,0.660,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,6.76%,0.653,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.86%,0.660,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 80-20  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,6.86%,0.660,-4.56%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),6.86%,0.660,-4.56%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,6.86%,0.660,-4.56%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,6.81%,0.660,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,6.76%,0.653,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.86%,0.660,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 90-10  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,-21.43%,-0.744,-50.15%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,-21.28%,-0.758,-49.30%,0.00%,0.000
2,Rel Threshold 50% | No TLH,Off,-21.28%,-0.758,-49.30%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-22.53%,-0.820,4.09%,-0.058,"$-2,733"
1,Quarterly Rebal | TLH=10%,-22.52%,-0.820,3.32%,-0.181,"$-8,042"
2,Abs Threshold 10% | TLH=10%,-21.88%,-0.767,3.36%,-0.196,"$-8,964"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 90-10  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),9.48%,0.722,-18.94%,0.72%,0.026
1,Rel Threshold 25% | No TLH,Off,9.38%,0.714,-18.82%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,9.32%,0.713,-18.68%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,9.48%,0.722,0.72%,0.026,"$+1,671"
1,Monthly Rebal | TLH=10%,9.28%,0.711,0.96%,-0.071,$+279
2,Quarterly Rebal | TLH=10%,8.69%,0.674,1.13%,-0.640,"$-10,182"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 90-10  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,19.99%,1.598,-8.41%,0.00%,0.000
1,Abs Threshold 20% | No TLH,Off,19.99%,1.598,-8.41%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,19.94%,1.598,-8.38%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,19.60%,1.563,0.38%,0.064,"$+1,845"
1,Yearly Rebal | TLH=10%,19.95%,1.591,0.38%,-0.004,"$+1,496"
2,Abs Threshold 10% | TLH=10%,20.05%,1.596,0.38%,-0.134,$+825

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 90-10  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,8.84%,0.784,-5.01%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),8.84%,0.784,-5.01%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,8.86%,0.781,-5.08%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.84%,0.784,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,8.73%,0.773,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,8.86%,0.781,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 90-10  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,8.84%,0.784,-5.01%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),8.84%,0.784,-5.01%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,8.86%,0.781,-5.08%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.84%,0.784,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,8.73%,0.773,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,8.86%,0.781,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator - 90-10  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,8.84%,0.784,-5.01%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),8.84%,0.784,-5.01%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,8.86%,0.781,-5.08%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.84%,0.784,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,8.73%,0.773,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,8.86%,0.781,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 0-100  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,-7.73%,-0.792,-17.55%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,-7.73%,-0.792,-17.55%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,-7.73%,-0.792,-17.55%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,-11.89%,-1.029,6.82%,-0.627,"$-41,201"
1,Abs Threshold 5% | TLH=10%,-11.89%,-1.029,6.82%,-0.627,"$-41,201"
2,Abs Threshold 10% | TLH=10%,-11.89%,-1.029,6.82%,-0.627,"$-41,201"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 0-100  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,1.29%,0.463,-8.34%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),1.29%,0.463,-8.34%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,1.28%,0.460,-8.35%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,1.27%,0.459,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,1.28%,0.460,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,1.29%,0.463,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 0-100  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,-1.71%,-0.414,-3.35%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),-1.71%,-0.414,-3.35%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,-1.71%,-0.414,-3.35%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-1.71%,-0.414,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-1.71%,-0.414,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-1.72%,-0.416,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 0-100  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-0.40%,-0.097,-6.17%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-0.40%,-0.097,-6.17%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,-0.40%,-0.098,-6.17%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-0.40%,-0.098,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-0.40%,-0.097,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-0.41%,-0.099,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 0-100  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-0.40%,-0.097,-6.17%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-0.40%,-0.097,-6.17%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,-0.40%,-0.098,-6.17%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-0.40%,-0.098,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-0.40%,-0.097,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-0.41%,-0.099,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 0-100  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-0.40%,-0.097,-6.17%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-0.40%,-0.097,-6.17%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,-0.40%,-0.098,-6.17%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-0.40%,-0.098,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-0.40%,-0.097,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-0.41%,-0.099,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 10-90  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,-8.21%,-0.828,-17.76%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,-8.21%,-0.828,-17.76%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,-8.21%,-0.828,-17.76%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,-11.19%,-0.975,6.97%,-0.444,"$-29,512"
1,Abs Threshold 5% | TLH=10%,-11.19%,-0.975,6.97%,-0.444,"$-29,512"
2,Abs Threshold 10% | TLH=10%,-11.19%,-0.975,6.97%,-0.444,"$-29,512"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 10-90  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,1.98%,0.728,-7.25%,0.00%,0.000
1,Abs Threshold 10% | TLH=10%,On (10%),1.98%,0.728,-7.25%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,1.98%,0.728,-7.25%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,1.83%,0.674,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,1.87%,0.688,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,1.89%,0.694,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 10-90  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,-0.61%,-0.144,-3.10%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),-0.61%,-0.144,-3.10%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-0.61%,-0.144,-3.10%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-0.74%,-0.173,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-0.71%,-0.167,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-0.61%,-0.144,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 10-90  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,-0.27%,-0.099,-1.35%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),-0.27%,-0.099,-1.35%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-0.27%,-0.099,-1.35%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-0.28%,-0.104,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-0.29%,-0.104,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-0.27%,-0.099,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 10-90  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,-0.27%,-0.099,-1.35%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),-0.27%,-0.099,-1.35%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-0.27%,-0.099,-1.35%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-0.28%,-0.104,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-0.29%,-0.104,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-0.27%,-0.099,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 10-90  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,-0.27%,-0.099,-1.35%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),-0.27%,-0.099,-1.35%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-0.27%,-0.099,-1.35%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-0.28%,-0.104,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-0.29%,-0.104,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-0.27%,-0.099,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 20-80  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,-8.32%,-0.832,-17.95%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),-9.89%,-0.837,-19.82%,6.98%,-0.241
2,Yearly Rebal | No TLH,Off,-8.72%,-0.883,-17.95%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-9.89%,-0.837,6.98%,-0.241,"$-15,558"
1,Yearly Rebal | TLH=10%,-11.29%,-0.996,7.08%,-0.380,"$-25,472"
2,Abs Threshold 10% | TLH=10%,-11.29%,-0.996,7.08%,-0.380,"$-25,472"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 20-80  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,3.44%,1.096,-6.05%,0.00%,0.000
1,Abs Threshold 10% | TLH=10%,On (10%),3.44%,1.096,-6.05%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,3.44%,1.096,-6.05%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,3.10%,1.078,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,3.18%,1.089,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,3.26%,1.085,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 20-80  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,1.45%,0.327,-3.06%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),1.45%,0.327,-3.06%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,1.45%,0.327,-3.06%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,1.16%,0.263,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,1.22%,0.278,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,1.45%,0.327,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 20-80  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,0.57%,0.159,-1.80%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),0.57%,0.159,-1.80%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,0.57%,0.159,-1.80%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.56%,0.156,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.55%,0.154,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,0.57%,0.159,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 20-80  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,0.57%,0.159,-1.80%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),0.57%,0.159,-1.80%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,0.57%,0.159,-1.80%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.56%,0.156,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.55%,0.154,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,0.57%,0.159,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 20-80  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,0.57%,0.159,-1.80%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),0.57%,0.159,-1.80%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,0.57%,0.159,-1.80%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.56%,0.156,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.55%,0.154,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,0.57%,0.159,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 30-70  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),-9.15%,-0.764,-19.71%,7.35%,-0.018
1,Abs Threshold 5% | No TLH,Off,-9.12%,-0.881,-18.39%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-9.50%,-0.930,-18.39%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-9.15%,-0.764,7.35%,-0.018,$-256
1,Yearly Rebal | TLH=10%,-10.77%,-0.945,7.50%,-0.183,"$-12,525"
2,Abs Threshold 10% | TLH=10%,-10.77%,-0.945,7.50%,-0.183,"$-12,525"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 30-70  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),4.62%,1.082,-7.56%,0.18%,0.061
1,Abs Threshold 5% | TLH=10%,On (10%),4.52%,1.079,-7.47%,0.19%,0.043
2,Rel Threshold 25% | No TLH,Off,4.58%,1.079,-7.44%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,4.34%,1.065,0.16%,0.171,"$+2,804"
1,Yearly Rebal | TLH=10%,4.50%,1.072,0.20%,0.085,"$+2,306"
2,Quarterly Rebal | TLH=10%,4.39%,1.070,0.19%,0.073,"$+2,155"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 30-70  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,3.77%,0.716,-3.25%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),3.77%,0.716,-3.25%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,3.77%,0.716,-3.25%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,3.27%,0.638,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,3.40%,0.665,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,3.77%,0.716,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 30-70  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,1.65%,0.339,-2.36%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),1.65%,0.339,-2.36%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,1.65%,0.339,-2.36%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,1.63%,0.338,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,1.62%,0.334,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,1.65%,0.339,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 30-70  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,1.65%,0.339,-2.36%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),1.65%,0.339,-2.36%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,1.65%,0.339,-2.36%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,1.63%,0.338,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,1.62%,0.334,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,1.65%,0.339,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 30-70  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,1.65%,0.339,-2.36%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),1.65%,0.339,-2.36%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,1.65%,0.339,-2.36%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,1.63%,0.338,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,1.62%,0.334,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,1.65%,0.339,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 40-60  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),-12.09%,-0.954,-20.20%,8.28%,-0.114
1,Abs Threshold 5% | No TLH,Off,-10.74%,-0.958,-19.46%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),-12.40%,-0.978,-20.63%,7.32%,-0.242

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-11.06%,-0.993,5.97%,0.038,"$+3,300"
1,Quarterly Rebal | TLH=10%,-12.09%,-0.954,8.28%,-0.114,"$-8,286"
2,Yearly Rebal | TLH=10%,-12.64%,-1.005,7.41%,-0.218,"$-14,964"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 40-60  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),4.83%,0.839,-9.67%,0.17%,0.528
1,Rel Threshold 25% | No TLH,Off,4.72%,0.821,-9.77%,0.00%,0.000
2,Abs Threshold 20% | TLH=10%,On (10%),5.02%,0.812,-10.99%,0.17%,0.436

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,4.63%,0.802,0.18%,0.621,"$+9,047"
1,Abs Threshold 5% | TLH=10%,4.59%,0.789,0.18%,0.619,"$+8,966"
2,Abs Threshold 10% | TLH=10%,4.80%,0.775,0.18%,0.564,"$+8,347"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 40-60  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,6.08%,0.953,-3.52%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),6.08%,0.953,-3.52%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,6.08%,0.953,-3.52%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.45%,0.886,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,5.62%,0.916,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.08%,0.953,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 40-60  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,2.62%,0.424,-2.90%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),2.62%,0.424,-2.90%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,2.63%,0.422,-2.95%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.62%,0.424,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,2.60%,0.419,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,2.63%,0.422,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 40-60  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,2.62%,0.424,-2.90%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),2.62%,0.424,-2.90%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,2.63%,0.422,-2.95%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.62%,0.424,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,2.60%,0.419,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,2.63%,0.422,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 40-60  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,2.62%,0.424,-2.90%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),2.62%,0.424,-2.90%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,2.63%,0.422,-2.95%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.62%,0.424,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,2.60%,0.419,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,2.63%,0.422,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 50-50  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),-20.80%,-1.341,-27.29%,6.56%,-0.188
1,Monthly Rebal | TLH=10%,On (10%),-20.84%,-1.375,-27.43%,7.13%,-0.088
2,Rel Threshold 50% | TLH=10%,On (10%),-21.04%,-1.380,-27.55%,6.80%,-0.209

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-20.54%,-1.404,7.87%,-0.067,"$-4,237"
1,Monthly Rebal | TLH=10%,-20.84%,-1.375,7.13%,-0.088,"$-5,264"
2,Rel Threshold 25% | TLH=10%,-20.80%,-1.341,6.56%,-0.188,"$-11,279"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 50-50  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | TLH=10%,On (10%),6.51%,0.788,-14.30%,0.41%,1.023
1,Abs Threshold 20% | TLH=10%,On (10%),6.51%,0.788,-14.30%,0.41%,1.023
2,Abs Threshold 5% | TLH=10%,On (10%),6.12%,0.781,-13.08%,0.42%,1.110

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,6.12%,0.781,0.42%,1.110,"$+35,129"
1,Rel Threshold 50% | TLH=10%,6.23%,0.763,0.42%,1.071,"$+34,219"
2,Yearly Rebal | TLH=10%,6.01%,0.770,0.41%,1.066,"$+32,997"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 50-50  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,8.79%,1.131,-4.57%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),8.79%,1.131,-4.57%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,8.79%,1.131,-4.57%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.09%,1.079,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,8.32%,1.111,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,8.79%,1.131,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 50-50  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,3.63%,0.490,-3.43%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),3.63%,0.490,-3.43%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,3.62%,0.485,-3.49%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,3.63%,0.490,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,3.59%,0.483,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,3.62%,0.485,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 50-50  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,3.63%,0.490,-3.43%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),3.63%,0.490,-3.43%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,3.62%,0.485,-3.49%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,3.63%,0.490,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,3.59%,0.483,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,3.62%,0.485,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 50-50  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,3.63%,0.490,-3.43%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),3.63%,0.490,-3.43%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,3.62%,0.485,-3.49%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,3.63%,0.490,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,3.59%,0.483,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,3.62%,0.485,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 60-40  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),-25.68%,-1.240,-31.21%,6.14%,-0.100
1,Abs Threshold 5% | TLH=10%,On (10%),-25.89%,-1.294,-31.73%,6.29%,-0.130
2,Rel Threshold 25% | No TLH,Off,-25.15%,-1.298,-30.77%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-25.83%,-1.377,7.43%,0.013,"$+1,884"
1,Monthly Rebal | TLH=10%,-26.10%,-1.361,6.57%,-0.006,$+471
2,Rel Threshold 25% | TLH=10%,-25.68%,-1.240,6.14%,-0.100,"$-5,192"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 60-40  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | TLH=10%,On (10%),7.37%,0.792,-14.40%,0.55%,1.133
1,Abs Threshold 10% | TLH=10%,On (10%),7.59%,0.775,-16.06%,0.53%,1.003
2,Abs Threshold 20% | TLH=10%,On (10%),7.59%,0.775,-16.06%,0.53%,1.003

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,7.37%,0.792,0.55%,1.133,"$+48,824"
1,Yearly Rebal | TLH=10%,7.15%,0.766,0.53%,1.112,"$+46,067"
2,Abs Threshold 5% | TLH=10%,7.22%,0.771,0.55%,1.111,"$+47,945"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 60-40  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,11.44%,1.233,-5.76%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),11.44%,1.233,-5.76%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,11.44%,1.233,-5.76%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,10.71%,1.191,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,10.98%,1.223,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,11.44%,1.233,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 60-40  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,6.20%,0.715,-3.75%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),6.20%,0.715,-3.75%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,6.20%,0.715,-3.75%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,6.13%,0.712,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,6.09%,0.706,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.20%,0.715,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 60-40  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,6.20%,0.715,-3.75%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),6.20%,0.715,-3.75%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,6.20%,0.715,-3.75%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,6.13%,0.712,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,6.09%,0.706,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.20%,0.715,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 60-40  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,6.20%,0.715,-3.75%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),6.20%,0.715,-3.75%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,6.20%,0.715,-3.75%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,6.13%,0.712,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,6.09%,0.706,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.20%,0.715,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 70-30  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),-27.99%,-1.234,-33.21%,6.07%,-0.120
1,Rel Threshold 25% | No TLH,Off,-27.35%,-1.295,-32.75%,0.00%,0.000
2,Rel Threshold 50% | TLH=10%,On (10%),-28.11%,-1.302,-33.10%,6.34%,-0.157

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-27.62%,-1.347,7.38%,0.027,"$+2,852"
1,Monthly Rebal | TLH=10%,-27.92%,-1.326,6.52%,0.006,"$+1,260"
2,Rel Threshold 25% | TLH=10%,-27.99%,-1.234,6.07%,-0.120,"$-6,324"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 70-30  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | TLH=10%,On (10%),7.66%,0.765,-15.46%,0.58%,1.159
1,Abs Threshold 10% | TLH=10%,On (10%),7.90%,0.756,-16.90%,0.54%,1.028
2,Abs Threshold 20% | TLH=10%,On (10%),7.90%,0.756,-16.90%,0.54%,1.028

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,7.45%,0.743,0.56%,1.161,"$+50,668"
1,Rel Threshold 50% | TLH=10%,7.66%,0.765,0.58%,1.159,"$+53,287"
2,Abs Threshold 5% | TLH=10%,7.55%,0.750,0.57%,1.153,"$+52,145"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 70-30  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | No TLH,Off,19.78%,1.761,-10.07%,0.00%,0.000
1,Rel Threshold 50% | No TLH,Off,19.78%,1.761,-10.07%,0.00%,0.000
2,Abs Threshold 20% | TLH=10%,On (10%),19.73%,1.756,-10.15%,0.13%,-0.947

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,16.94%,1.615,0.16%,-0.419,$+112
1,Yearly Rebal | TLH=10%,18.07%,1.668,0.14%,-0.681,$-517
2,Quarterly Rebal | TLH=10%,17.27%,1.645,0.14%,-0.827,"$-1,011"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 70-30  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,6.69%,0.688,-4.18%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),6.69%,0.688,-4.18%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,6.69%,0.688,-4.18%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,6.63%,0.686,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,6.58%,0.681,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.69%,0.688,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 70-30  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,6.69%,0.688,-4.18%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),6.69%,0.688,-4.18%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,6.69%,0.688,-4.18%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,6.63%,0.686,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,6.58%,0.681,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.69%,0.688,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 70-30  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,6.69%,0.688,-4.18%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),6.69%,0.688,-4.18%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,6.69%,0.688,-4.18%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,6.63%,0.686,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,6.58%,0.681,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.69%,0.688,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 80-20  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | TLH=10%,On (10%),-26.50%,-1.058,-34.56%,4.87%,-0.172
1,Rel Threshold 50% | No TLH,Off,-25.75%,-1.075,-34.51%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),-27.65%,-1.081,-35.13%,4.67%,-0.167

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-27.56%,-1.143,5.52%,0.009,"$+1,350"
1,Monthly Rebal | TLH=10%,-27.98%,-1.117,4.77%,-0.017,$+79
2,Rel Threshold 25% | TLH=10%,-28.34%,-1.084,4.78%,-0.088,"$-3,326"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 80-20  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | TLH=10%,On (10%),8.33%,0.745,-17.15%,0.69%,1.204
1,Abs Threshold 10% | TLH=10%,On (10%),8.56%,0.738,-18.36%,0.65%,1.024
2,Abs Threshold 20% | TLH=10%,On (10%),8.56%,0.738,-18.36%,0.65%,1.024

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,8.33%,0.745,0.69%,1.204,"$+67,130"
1,Yearly Rebal | TLH=10%,8.11%,0.721,0.67%,1.183,"$+63,471"
2,Abs Threshold 5% | TLH=10%,8.24%,0.734,0.73%,1.115,"$+65,311"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 80-20  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | No TLH,Off,21.27%,1.744,-10.43%,0.00%,0.000
1,Abs Threshold 20% | TLH=10%,On (10%),21.19%,1.736,-10.53%,0.14%,-1.073
2,Abs Threshold 10% | No TLH,Off,20.17%,1.707,-10.43%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,18.50%,1.602,0.22%,-0.117,"$+1,087"
1,Quarterly Rebal | TLH=10%,18.86%,1.632,0.20%,-0.391,$-191
2,Yearly Rebal | TLH=10%,19.62%,1.657,0.16%,-0.435,$+75

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 80-20  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,7.16%,0.690,-4.51%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),7.16%,0.690,-4.51%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,7.16%,0.690,-4.51%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.11%,0.690,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,7.05%,0.683,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,7.16%,0.690,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 80-20  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,7.16%,0.690,-4.51%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),7.16%,0.690,-4.51%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,7.16%,0.690,-4.51%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.11%,0.690,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,7.05%,0.683,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,7.16%,0.690,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 80-20  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,7.16%,0.690,-4.51%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),7.16%,0.690,-4.51%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,7.16%,0.690,-4.51%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.11%,0.690,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,7.05%,0.683,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,7.16%,0.690,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 90-10  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | TLH=10%,On (10%),-32.82%,-0.925,-42.87%,5.69%,-0.055
1,Abs Threshold 10% | No TLH,Off,-32.59%,-0.939,-43.21%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),-34.36%,-0.950,-44.10%,5.55%,-0.005

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-33.96%,-0.978,6.57%,0.167,"$+11,707"
1,Monthly Rebal | TLH=10%,-34.36%,-0.988,5.23%,0.163,"$+9,262"
2,Rel Threshold 25% | TLH=10%,-34.87%,-0.950,5.55%,0.093,"$+5,893"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 90-10  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),9.39%,0.717,-18.86%,0.72%,0.026
1,Quarterly Rebal | No TLH,Off,9.24%,0.709,-18.59%,0.00%,0.000
2,Rel Threshold 25% | No TLH,Off,9.29%,0.709,-18.74%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,9.39%,0.717,0.72%,0.026,"$+1,671"
1,Monthly Rebal | TLH=10%,9.18%,0.706,0.96%,-0.073,$+246
2,Quarterly Rebal | TLH=10%,8.60%,0.669,1.13%,-0.639,"$-10,159"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 90-10  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,19.96%,1.605,-8.38%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,20.01%,1.604,-8.42%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,20.01%,1.604,-8.42%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,19.64%,1.571,0.38%,0.065,"$+1,848"
1,Yearly Rebal | TLH=10%,19.97%,1.598,0.38%,-0.004,"$+1,497"
2,Abs Threshold 10% | TLH=10%,20.07%,1.602,0.38%,-0.134,$+825

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 90-10  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,9.02%,0.800,-4.98%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),9.02%,0.800,-4.98%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,9.03%,0.797,-5.06%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.02%,0.800,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,8.91%,0.790,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,9.03%,0.797,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 90-10  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,9.02%,0.800,-4.98%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),9.02%,0.800,-4.98%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,9.03%,0.797,-5.06%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.02%,0.800,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,8.91%,0.790,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,9.03%,0.797,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Aviator TaxAware - 90-10  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,9.02%,0.800,-4.98%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),9.02%,0.800,-4.98%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,9.03%,0.797,-5.06%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.02%,0.800,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,8.91%,0.790,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,9.03%,0.797,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 0-100  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,4.08%,0.428,-11.04%,0.00%,0.000
1,Rel Threshold 25% | No TLH,Off,3.68%,0.402,-11.13%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,3.24%,0.355,-11.13%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,1.74%,0.188,5.81%,-0.355,"$-20,037"
1,Yearly Rebal | TLH=10%,1.26%,0.136,5.80%,-0.360,"$-20,302"
2,Abs Threshold 10% | TLH=10%,1.27%,0.137,5.81%,-0.360,"$-20,362"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 0-100  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-3.53%,-0.914,-1.37%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-3.53%,-0.914,-1.37%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-3.53%,-0.914,-1.37%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-3.58%,-0.925,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-3.53%,-0.914,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-3.53%,-0.914,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 0-100  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),-1.21%,-0.184,-7.77%,0.19%,0.361
1,Quarterly Rebal | TLH=10%,On (10%),-1.27%,-0.195,-7.73%,0.15%,-0.318
2,Quarterly Rebal | No TLH,Off,-1.30%,-0.196,-7.70%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,-1.21%,-0.184,0.19%,0.361,"$+2,273"
1,Quarterly Rebal | TLH=10%,-1.27%,-0.195,0.15%,-0.318,$+428
2,Monthly Rebal | TLH=10%,-1.30%,-0.199,0.15%,-0.397,$+251

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 0-100  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),0.49%,0.082,-7.77%,0.17%,0.163
1,Quarterly Rebal | TLH=10%,On (10%),0.45%,0.075,-7.73%,0.13%,-0.355
2,Quarterly Rebal | No TLH,Off,0.45%,0.074,-7.70%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,0.49%,0.082,0.17%,0.163,"$+1,925"
1,Quarterly Rebal | TLH=10%,0.45%,0.075,0.13%,-0.355,$-26
2,Monthly Rebal | TLH=10%,0.44%,0.073,0.12%,-0.378,$+1

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 0-100  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),0.49%,0.082,-7.77%,0.17%,0.163
1,Quarterly Rebal | TLH=10%,On (10%),0.45%,0.075,-7.73%,0.13%,-0.355
2,Quarterly Rebal | No TLH,Off,0.45%,0.074,-7.70%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,0.49%,0.082,0.17%,0.163,"$+1,925"
1,Quarterly Rebal | TLH=10%,0.45%,0.075,0.13%,-0.355,$-26
2,Monthly Rebal | TLH=10%,0.44%,0.073,0.12%,-0.378,$+1

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 0-100  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),0.49%,0.082,-7.77%,0.17%,0.163
1,Quarterly Rebal | TLH=10%,On (10%),0.45%,0.075,-7.73%,0.13%,-0.355
2,Quarterly Rebal | No TLH,Off,0.45%,0.074,-7.70%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,0.49%,0.082,0.17%,0.163,"$+1,925"
1,Quarterly Rebal | TLH=10%,0.45%,0.075,0.13%,-0.355,$-26
2,Monthly Rebal | TLH=10%,0.44%,0.073,0.12%,-0.378,$+1

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 100-0  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),-25.03%,-0.706,-55.51%,4.35%,0.114
1,Abs Threshold 10% | TLH=10%,On (10%),-24.96%,-0.716,-55.56%,3.50%,-0.021
2,Monthly Rebal | TLH=10%,On (10%),-25.15%,-0.727,-55.52%,3.88%,0.149

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-25.15%,-0.727,3.88%,0.149,"$+8,926"
1,Quarterly Rebal | TLH=10%,-25.03%,-0.706,4.35%,0.114,"$+7,731"
2,Abs Threshold 10% | TLH=10%,-24.96%,-0.716,3.50%,-0.021,$-339

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 100-0  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,9.76%,0.665,-20.55%,0.00%,0.000
1,Quarterly Rebal | No TLH,Off,9.60%,0.657,-20.47%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,9.65%,0.655,-20.70%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.56%,0.653,0.83%,-0.144,$-545
1,Rel Threshold 25% | TLH=10%,9.29%,0.638,0.84%,-0.655,"$-7,435"
2,Quarterly Rebal | TLH=10%,8.77%,0.610,1.09%,-0.846,"$-13,466"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 100-0  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),21.80%,1.662,-9.25%,0.40%,0.308
1,Abs Threshold 10% | No TLH,Off,21.82%,1.647,-9.32%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,21.82%,1.647,-9.32%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,21.80%,1.662,0.40%,0.308,"$+3,222"
1,Rel Threshold 50% | TLH=10%,21.66%,1.646,0.46%,0.155,"$+2,513"
2,Abs Threshold 5% | TLH=10%,21.51%,1.641,0.48%,0.128,"$+2,388"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 100-0  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,12.39%,1.009,-5.26%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),12.39%,1.009,-5.26%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,12.36%,1.003,-5.35%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.39%,1.009,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,12.24%,0.996,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,12.36%,1.003,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 100-0  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,12.39%,1.009,-5.26%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),12.39%,1.009,-5.26%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,12.36%,1.003,-5.35%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.39%,1.009,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,12.24%,0.996,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,12.36%,1.003,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 100-0  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,12.39%,1.009,-5.26%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),12.39%,1.009,-5.26%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,12.36%,1.003,-5.35%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.39%,1.009,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,12.24%,0.996,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,12.36%,1.003,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 20-80  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,4.36%,0.470,-10.65%,0.00%,0.000
1,Rel Threshold 25% | No TLH,Off,3.99%,0.447,-10.74%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,3.56%,0.399,-10.74%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,2.18%,0.240,5.42%,-0.356,"$-18,701"
1,Yearly Rebal | TLH=10%,1.71%,0.188,5.41%,-0.362,"$-18,961"
2,Abs Threshold 10% | TLH=10%,1.71%,0.188,5.42%,-0.362,"$-19,018"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 20-80  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-1.79%,-0.420,-1.51%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-1.79%,-0.420,-1.51%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-1.79%,-0.420,-1.51%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-1.89%,-0.442,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-1.79%,-0.420,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-1.79%,-0.420,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 20-80  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),-0.07%,-0.010,-8.41%,0.30%,0.531
1,Rel Threshold 50% | TLH=10%,On (10%),-0.11%,-0.015,-8.41%,0.31%,0.102
2,Abs Threshold 5% | No TLH,Off,-0.14%,-0.020,-8.25%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,-0.07%,-0.010,0.30%,0.531,"$+3,708"
1,Rel Threshold 25% | TLH=10%,-0.16%,-0.022,0.30%,0.383,"$+3,048"
2,Monthly Rebal | TLH=10%,-0.28%,-0.041,0.36%,0.124,"$+1,916"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 20-80  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,-1.34%,-0.296,-2.05%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),-1.34%,-0.296,-2.05%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-1.34%,-0.296,-2.05%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-1.42%,-0.316,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-1.42%,-0.315,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-1.34%,-0.296,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 20-80  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,-1.34%,-0.296,-2.05%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),-1.34%,-0.296,-2.05%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-1.34%,-0.296,-2.05%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-1.42%,-0.316,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-1.42%,-0.315,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-1.34%,-0.296,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 20-80  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,-1.34%,-0.296,-2.05%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),-1.34%,-0.296,-2.05%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-1.34%,-0.296,-2.05%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-1.42%,-0.316,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-1.42%,-0.315,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-1.34%,-0.296,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 40-60  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,-4.02%,-0.393,-16.51%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,-4.75%,-0.494,-16.51%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,-4.75%,-0.494,-16.51%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,-7.73%,-0.726,5.82%,-0.280,"$-15,679"
1,Rel Threshold 50% | TLH=10%,-7.27%,-0.715,5.73%,-0.293,"$-16,145"
2,Abs Threshold 10% | TLH=10%,-6.34%,-0.680,5.61%,-0.304,"$-16,419"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 40-60  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,15.21%,4.462,-0.88%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),15.21%,4.462,-0.88%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,15.21%,4.462,-0.88%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,14.54%,4.233,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,15.21%,4.462,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,15.21%,4.462,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 40-60  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,8.35%,1.051,-8.78%,0.00%,0.000
1,Abs Threshold 20% | No TLH,Off,8.35%,1.051,-8.78%,0.00%,0.000
2,Rel Threshold 50% | No TLH,Off,8.35%,1.051,-8.78%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,7.91%,1.016,0.42%,0.881,"$+7,518"
1,Rel Threshold 25% | TLH=10%,7.41%,0.963,0.48%,0.715,"$+7,041"
2,Quarterly Rebal | TLH=10%,7.19%,0.952,0.37%,0.603,"$+5,051"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 40-60  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,1.30%,0.196,-3.09%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),1.30%,0.196,-3.09%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,1.30%,0.196,-3.09%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,1.23%,0.188,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,1.21%,0.185,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,1.30%,0.196,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 40-60  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,1.30%,0.196,-3.09%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),1.30%,0.196,-3.09%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,1.30%,0.196,-3.09%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,1.23%,0.188,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,1.21%,0.185,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,1.30%,0.196,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 40-60  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,1.30%,0.196,-3.09%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),1.30%,0.196,-3.09%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,1.30%,0.196,-3.09%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,1.23%,0.188,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,1.21%,0.185,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,1.30%,0.196,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 60-40  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,-21.87%,-0.888,-34.47%,0.00%,0.000
1,Rel Threshold 25% | No TLH,Off,-22.72%,-0.911,-35.22%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),-22.75%,-0.925,-34.41%,4.19%,-0.231

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-23.77%,-1.002,3.25%,-0.054,$-907
1,Yearly Rebal | TLH=10%,-22.50%,-1.082,4.11%,-0.126,"$-4,348"
2,Rel Threshold 50% | TLH=10%,-22.99%,-1.032,4.18%,-0.184,"$-6,938"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 60-40  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,35.86%,7.526,-1.31%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),35.86%,7.526,-1.31%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,35.86%,7.526,-1.31%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,35.10%,7.429,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,35.86%,7.526,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,35.86%,7.526,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 60-40  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,16.18%,1.543,-9.90%,0.00%,0.000
1,Abs Threshold 20% | No TLH,Off,16.18%,1.543,-9.90%,0.00%,0.000
2,Rel Threshold 50% | No TLH,Off,16.18%,1.543,-9.90%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,15.75%,1.525,0.52%,0.928,"$+9,912"
1,Rel Threshold 25% | TLH=10%,15.51%,1.534,0.59%,0.873,"$+10,532"
2,Quarterly Rebal | TLH=10%,14.94%,1.501,0.45%,0.636,"$+6,475"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 60-40  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,5.16%,0.572,-3.96%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),5.16%,0.572,-3.96%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,5.16%,0.572,-3.96%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.06%,0.565,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,5.01%,0.558,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,5.16%,0.572,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 60-40  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,5.16%,0.572,-3.96%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),5.16%,0.572,-3.96%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,5.16%,0.572,-3.96%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.06%,0.565,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,5.01%,0.558,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,5.16%,0.572,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 60-40  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,5.16%,0.572,-3.96%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),5.16%,0.572,-3.96%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,5.16%,0.572,-3.96%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.06%,0.565,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,5.01%,0.558,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,5.16%,0.572,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 80-20  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),-35.88%,-0.949,-48.79%,4.86%,0.077
1,Abs Threshold 5% | No TLH,Off,-35.60%,-0.955,-48.66%,0.00%,0.000
2,Rel Threshold 25% | No TLH,Off,-36.22%,-0.977,-48.75%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-35.88%,-0.949,4.86%,0.077,"$+4,555"
1,Quarterly Rebal | TLH=10%,-36.25%,-1.021,4.54%,-0.077,"$-2,786"
2,Yearly Rebal | TLH=10%,-36.08%,-1.033,3.98%,-0.088,"$-2,784"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 80-20  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,46.55%,7.766,-1.64%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),46.55%,7.766,-1.64%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,46.55%,7.766,-1.64%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,45.99%,7.729,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,46.55%,7.766,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,46.55%,7.766,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 80-20  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,19.62%,1.618,-10.46%,0.00%,0.000
1,Abs Threshold 20% | No TLH,Off,19.62%,1.618,-10.46%,0.00%,0.000
2,Rel Threshold 50% | No TLH,Off,19.62%,1.618,-10.46%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,18.91%,1.588,0.46%,0.722,"$+7,463"
1,Abs Threshold 5% | TLH=10%,19.03%,1.599,0.39%,0.627,"$+5,980"
2,Yearly Rebal | TLH=10%,19.00%,1.579,0.36%,0.519,"$+4,932"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 80-20  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,7.33%,0.684,-4.65%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),7.33%,0.684,-4.65%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,7.33%,0.684,-4.65%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.26%,0.682,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,7.20%,0.675,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,7.33%,0.684,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 80-20  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,7.33%,0.684,-4.65%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),7.33%,0.684,-4.65%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,7.33%,0.684,-4.65%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.26%,0.682,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,7.20%,0.675,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,7.33%,0.684,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects - 80-20  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,7.33%,0.684,-4.65%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),7.33%,0.684,-4.65%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,7.33%,0.684,-4.65%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.26%,0.682,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,7.20%,0.675,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,7.33%,0.684,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 20-80  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,-5.95%,-0.661,-16.32%,0.00%,0.000
1,Yearly Rebal | No TLH,Off,-6.14%,-0.689,-16.32%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-6.14%,-0.689,-16.32%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-8.78%,-0.932,3.67%,-0.706,"$-24,470"
1,Yearly Rebal | TLH=10%,-10.25%,-0.975,5.96%,-0.709,"$-40,659"
2,Abs Threshold 5% | TLH=10%,-10.25%,-0.975,5.96%,-0.709,"$-40,659"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 20-80  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-1.50%,-0.485,-1.30%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-1.50%,-0.485,-1.30%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-1.50%,-0.485,-1.30%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-1.57%,-0.509,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-1.50%,-0.485,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-1.50%,-0.485,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 20-80  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,-0.53%,-0.112,-3.74%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),-0.53%,-0.112,-3.74%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-0.53%,-0.112,-3.74%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-0.69%,-0.147,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-0.65%,-0.140,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-0.53%,-0.112,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 20-80  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,1.01%,0.251,-1.69%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),1.01%,0.251,-1.69%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,1.01%,0.251,-1.69%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.95%,0.237,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.94%,0.236,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,1.01%,0.251,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 20-80  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,1.01%,0.251,-1.69%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),1.01%,0.251,-1.69%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,1.01%,0.251,-1.69%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.95%,0.237,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.94%,0.236,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,1.01%,0.251,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 20-80  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,1.01%,0.251,-1.69%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),1.01%,0.251,-1.69%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,1.01%,0.251,-1.69%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.95%,0.237,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.94%,0.236,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,1.01%,0.251,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 40-60  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),-13.42%,-0.993,-21.28%,6.68%,-0.233
1,Abs Threshold 5% | No TLH,Off,-11.97%,-1.009,-20.98%,0.00%,0.000
2,Quarterly Rebal | TLH=10%,On (10%),-14.86%,-1.123,-22.41%,7.23%,-0.135

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-13.82%,-1.151,4.24%,0.042,"$+2,784"
1,Quarterly Rebal | TLH=10%,-14.86%,-1.123,7.23%,-0.135,"$-8,626"
2,Rel Threshold 50% | TLH=10%,-14.95%,-1.125,7.12%,-0.154,"$-9,844"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 40-60  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,16.29%,5.782,-0.81%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),16.29%,5.782,-0.81%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,16.29%,5.782,-0.81%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,15.64%,5.587,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,16.29%,5.782,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,16.29%,5.782,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 40-60  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,6.32%,0.991,-3.39%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),6.32%,0.991,-3.39%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,6.32%,0.991,-3.39%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,5.80%,0.947,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,6.32%,0.991,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,5.95%,0.962,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 40-60  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,2.97%,0.459,-2.82%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),2.97%,0.459,-2.82%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,2.97%,0.459,-2.82%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.92%,0.456,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,2.90%,0.451,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,2.97%,0.459,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 40-60  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,2.97%,0.459,-2.82%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),2.97%,0.459,-2.82%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,2.97%,0.459,-2.82%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.92%,0.456,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,2.90%,0.451,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,2.97%,0.459,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 40-60  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,2.97%,0.459,-2.82%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),2.97%,0.459,-2.82%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,2.97%,0.459,-2.82%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.92%,0.456,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,2.90%,0.451,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,2.97%,0.459,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 60-40  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),-26.38%,-1.138,-33.90%,5.04%,0.121
1,Abs Threshold 5% | TLH=10%,On (10%),-27.93%,-1.184,-33.95%,5.07%,-0.143
2,Rel Threshold 50% | TLH=10%,On (10%),-27.25%,-1.185,-33.39%,5.23%,-0.190

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,-26.38%,-1.138,5.04%,0.121,"$+6,924"
1,Quarterly Rebal | TLH=10%,-26.86%,-1.210,6.09%,0.028,"$+2,575"
2,Monthly Rebal | TLH=10%,-27.30%,-1.196,5.26%,-0.028,$-582

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 60-40  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,33.70%,7.512,-1.31%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),33.70%,7.512,-1.31%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,33.70%,7.512,-1.31%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,32.95%,7.450,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,33.70%,7.512,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,33.70%,7.512,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 60-40  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | No TLH,Off,19.22%,1.793,-9.95%,0.00%,0.000
1,Abs Threshold 20% | TLH=10%,On (10%),19.11%,1.781,-10.08%,0.19%,-0.973
2,Abs Threshold 10% | No TLH,Off,18.00%,1.755,-9.95%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,16.36%,1.651,0.28%,-0.015,"$+1,519"
1,Yearly Rebal | TLH=10%,17.49%,1.700,0.23%,-0.281,$+154
2,Abs Threshold 5% | TLH=10%,17.12%,1.713,0.27%,-0.331,$-410

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 60-40  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,6.36%,0.703,-3.91%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),6.36%,0.703,-3.91%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,6.36%,0.703,-3.91%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,6.28%,0.699,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,6.23%,0.692,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.36%,0.703,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 60-40  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,6.36%,0.703,-3.91%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),6.36%,0.703,-3.91%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,6.36%,0.703,-3.91%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,6.28%,0.699,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,6.23%,0.692,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.36%,0.703,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 60-40  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,6.36%,0.703,-3.91%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),6.36%,0.703,-3.91%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,6.36%,0.703,-3.91%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,6.28%,0.699,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,6.23%,0.692,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.36%,0.703,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 80-20  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | TLH=10%,On (10%),-34.66%,-0.992,-44.25%,5.25%,-0.118
1,Abs Threshold 5% | TLH=10%,On (10%),-35.85%,-0.994,-45.49%,5.26%,-0.058
2,Rel Threshold 25% | TLH=10%,On (10%),-35.21%,-1.010,-44.56%,5.39%,0.105

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-34.97%,-1.038,6.12%,0.139,"$+9,210"
1,Monthly Rebal | TLH=10%,-35.33%,-1.014,5.32%,0.106,"$+6,402"
2,Rel Threshold 25% | TLH=10%,-35.21%,-1.010,5.39%,0.105,"$+6,400"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 80-20  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,45.30%,7.691,-1.64%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),45.30%,7.691,-1.64%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,45.30%,7.691,-1.64%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,44.71%,7.657,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,45.30%,7.691,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,45.30%,7.691,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 80-20  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | No TLH,Off,22.88%,1.806,-10.57%,0.00%,0.000
1,Abs Threshold 20% | TLH=10%,On (10%),22.78%,1.796,-10.70%,0.18%,-1.007
2,Yearly Rebal | No TLH,Off,21.28%,1.733,-10.57%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,20.26%,1.684,0.31%,0.122,"$+2,627"
1,Yearly Rebal | TLH=10%,21.32%,1.732,0.24%,-0.150,$+902
2,Quarterly Rebal | TLH=10%,20.60%,1.714,0.28%,-0.211,$+317

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 80-20  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,7.74%,0.724,-4.62%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),7.74%,0.724,-4.62%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,7.74%,0.724,-4.62%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.68%,0.723,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,7.62%,0.715,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,7.74%,0.724,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 80-20  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,7.74%,0.724,-4.62%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),7.74%,0.724,-4.62%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,7.74%,0.724,-4.62%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.68%,0.723,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,7.62%,0.715,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,7.74%,0.724,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - 80-20  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,7.74%,0.724,-4.62%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),7.74%,0.724,-4.62%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,7.74%,0.724,-4.62%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.68%,0.723,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,7.62%,0.715,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,7.74%,0.724,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - BlackRock 0-100 Global Allocation (GA) Selects Tax-Aware Model  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,-4.84%,-0.531,-15.80%,0.00%,0.000
1,Yearly Rebal | No TLH,Off,-5.05%,-0.557,-15.80%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-5.05%,-0.557,-15.80%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-7.46%,-0.668,7.13%,-0.346,"$-23,246"
1,Monthly Rebal | TLH=10%,-8.57%,-0.834,4.90%,-0.727,"$-34,053"
2,Yearly Rebal | TLH=10%,-10.77%,-0.991,5.96%,-0.979,"$-56,562"

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - BlackRock 0-100 Global Allocation (GA) Selects Tax-Aware Model  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,1.23%,0.451,-8.26%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),1.23%,0.451,-8.26%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,1.22%,0.448,-8.28%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,1.23%,0.451,0.00%,0.000,$+0
1,Abs Threshold 5% | TLH=10%,1.21%,0.446,0.00%,0.000,$+0
2,Abs Threshold 10% | TLH=10%,1.21%,0.446,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - BlackRock 0-100 Global Allocation (GA) Selects Tax-Aware Model  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,-1.90%,-0.438,-3.57%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),-1.90%,-0.438,-3.57%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,-1.90%,-0.438,-3.57%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-1.90%,-0.438,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-1.90%,-0.438,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-1.91%,-0.441,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - BlackRock 0-100 Global Allocation (GA) Selects Tax-Aware Model  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-0.20%,-0.047,-6.05%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-0.20%,-0.047,-6.05%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-0.21%,-0.048,-6.03%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-0.21%,-0.049,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-0.20%,-0.047,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-0.21%,-0.048,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - BlackRock 0-100 Global Allocation (GA) Selects Tax-Aware Model  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-0.20%,-0.047,-6.05%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-0.20%,-0.047,-6.05%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-0.21%,-0.048,-6.03%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-0.21%,-0.049,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-0.20%,-0.047,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-0.21%,-0.048,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GA Selects Tax Aware - BlackRock 0-100 Global Allocation (GA) Selects Tax-Aware Model  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-0.20%,-0.047,-6.05%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-0.20%,-0.047,-6.05%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-0.21%,-0.048,-6.03%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-0.21%,-0.049,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-0.20%,-0.047,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-0.21%,-0.048,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 0-100  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,6.52%,0.737,-12.44%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),6.52%,0.737,-12.44%,0.00%,0.000
2,Rel Threshold 25% | No TLH,Off,5.76%,0.653,-12.74%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.50%,0.635,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,4.83%,0.568,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,4.93%,0.581,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 0-100  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),5.05%,1.676,-2.46%,0.49%,0.048
1,Monthly Rebal | TLH=10%,On (10%),5.02%,1.669,-2.46%,0.48%,0.147
2,Yearly Rebal | TLH=10%,On (10%),5.04%,1.666,-2.47%,0.52%,0.019

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.02%,1.669,0.48%,0.147,"$+2,269"
1,Quarterly Rebal | TLH=10%,5.05%,1.676,0.49%,0.048,"$+1,611"
2,Yearly Rebal | TLH=10%,5.04%,1.666,0.52%,0.019,"$+1,422"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 0-100  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,1.29%,0.224,-6.61%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,1.29%,0.224,-6.61%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,1.29%,0.224,-6.61%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,1.15%,0.193,0.28%,-0.207,$+322
1,Quarterly Rebal | TLH=10%,1.15%,0.193,0.28%,-0.333,$-209
2,Rel Threshold 25% | TLH=10%,1.17%,0.198,0.27%,-0.341,$-189

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 0-100  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,3.56%,0.681,-6.61%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,3.56%,0.681,-6.61%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,3.56%,0.681,-6.61%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.83%,0.526,0.25%,-0.297,$-672
1,Quarterly Rebal | TLH=10%,2.87%,0.533,0.25%,-0.404,"$-1,372"
2,Rel Threshold 25% | TLH=10%,2.92%,0.545,0.25%,-0.433,"$-1,551"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 0-100  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,3.56%,0.681,-6.61%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,3.56%,0.681,-6.61%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,3.56%,0.681,-6.61%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.83%,0.526,0.25%,-0.297,$-672
1,Quarterly Rebal | TLH=10%,2.87%,0.533,0.25%,-0.404,"$-1,372"
2,Rel Threshold 25% | TLH=10%,2.92%,0.545,0.25%,-0.433,"$-1,551"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 0-100  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,3.56%,0.681,-6.61%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,3.56%,0.681,-6.61%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,3.56%,0.681,-6.61%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.83%,0.526,0.25%,-0.297,$-672
1,Quarterly Rebal | TLH=10%,2.87%,0.533,0.25%,-0.404,"$-1,372"
2,Rel Threshold 25% | TLH=10%,2.92%,0.545,0.25%,-0.433,"$-1,551"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 100-0  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),-19.12%,-0.672,-49.88%,5.11%,0.234
1,Abs Threshold 10% | TLH=10%,On (10%),-19.12%,-0.672,-49.88%,5.11%,0.234
2,Abs Threshold 20% | TLH=10%,On (10%),-19.12%,-0.672,-49.88%,5.11%,0.234

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,-19.18%,-0.673,4.99%,0.237,"$+19,737"
1,Abs Threshold 5% | TLH=10%,-19.12%,-0.672,5.11%,0.234,"$+19,918"
2,Abs Threshold 10% | TLH=10%,-19.12%,-0.672,5.11%,0.234,"$+19,918"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 100-0  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),14.88%,1.276,-5.99%,0.19%,0.170
1,Abs Threshold 5% | TLH=10%,On (10%),14.88%,1.276,-5.99%,0.19%,0.170
2,Abs Threshold 10% | TLH=10%,On (10%),14.88%,1.276,-5.99%,0.19%,0.170

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,14.83%,1.274,0.20%,0.263,"$+1,725"
1,Yearly Rebal | TLH=10%,14.88%,1.276,0.19%,0.170,"$+1,575"
2,Abs Threshold 5% | TLH=10%,14.88%,1.276,0.19%,0.170,"$+1,575"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 100-0  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,-34.13%,-2.523,-2.50%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),-34.13%,-2.523,-2.50%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,-34.13%,-2.523,-2.50%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-34.13%,-2.523,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-34.13%,-2.523,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-34.13%,-2.523,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 100-0  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),20.32%,1.122,-17.74%,0.89%,0.851
1,Abs Threshold 5% | TLH=10%,On (10%),20.32%,1.121,-17.74%,0.89%,0.851
2,Abs Threshold 10% | TLH=10%,On (10%),20.32%,1.121,-17.74%,0.89%,0.851

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,20.32%,1.122,0.89%,0.851,"$+9,145"
1,Abs Threshold 5% | TLH=10%,20.32%,1.121,0.89%,0.851,"$+9,150"
2,Abs Threshold 10% | TLH=10%,20.32%,1.121,0.89%,0.851,"$+9,150"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 100-0  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),20.32%,1.122,-17.74%,0.89%,0.851
1,Abs Threshold 5% | TLH=10%,On (10%),20.32%,1.121,-17.74%,0.89%,0.851
2,Abs Threshold 10% | TLH=10%,On (10%),20.32%,1.121,-17.74%,0.89%,0.851

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,20.32%,1.122,0.89%,0.851,"$+9,145"
1,Abs Threshold 5% | TLH=10%,20.32%,1.121,0.89%,0.851,"$+9,150"
2,Abs Threshold 10% | TLH=10%,20.32%,1.121,0.89%,0.851,"$+9,150"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 100-0  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),20.32%,1.122,-17.74%,0.89%,0.851
1,Abs Threshold 5% | TLH=10%,On (10%),20.32%,1.121,-17.74%,0.89%,0.851
2,Abs Threshold 10% | TLH=10%,On (10%),20.32%,1.121,-17.74%,0.89%,0.851

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,20.32%,1.122,0.89%,0.851,"$+9,145"
1,Abs Threshold 5% | TLH=10%,20.32%,1.121,0.89%,0.851,"$+9,150"
2,Abs Threshold 10% | TLH=10%,20.32%,1.121,0.89%,0.851,"$+9,150"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 20-80  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),-9.96%,-0.835,-20.83%,2.29%,0.427
1,Rel Threshold 50% | No TLH,Off,-10.40%,-0.845,-21.87%,0.00%,0.000
2,Rel Threshold 50% | TLH=10%,On (10%),-10.84%,-0.865,-22.20%,2.33%,-0.236

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,-9.96%,-0.835,2.29%,0.427,"$+11,105"
1,Quarterly Rebal | TLH=10%,-12.48%,-0.970,2.47%,0.002,"$+1,106"
2,Rel Threshold 25% | TLH=10%,-12.44%,-0.872,2.82%,-0.105,"$-2,007"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 20-80  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),7.97%,2.255,-1.38%,0.07%,-0.943
1,Yearly Rebal | TLH=10%,On (10%),7.94%,2.244,-1.37%,0.07%,-0.949
2,Abs Threshold 5% | TLH=10%,On (10%),7.94%,2.244,-1.37%,0.07%,-0.949

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.84%,2.210,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,7.97%,2.255,0.07%,-0.943,$+747
2,Yearly Rebal | TLH=10%,7.94%,2.244,0.07%,-0.949,$+744

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 20-80  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,9.54%,1.641,-3.18%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),9.54%,1.641,-3.18%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,9.57%,1.640,-3.19%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.78%,1.547,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,8.94%,1.574,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,9.54%,1.641,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 20-80  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,10.04%,1.604,-6.78%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),10.04%,1.604,-6.78%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,10.04%,1.604,-6.78%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.71%,1.477,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,8.86%,1.501,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,9.37%,1.574,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 20-80  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,10.04%,1.604,-6.78%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),10.04%,1.604,-6.78%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,10.04%,1.604,-6.78%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.71%,1.477,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,8.86%,1.501,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,9.37%,1.574,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 20-80  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,10.04%,1.604,-6.78%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),10.04%,1.604,-6.78%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,10.04%,1.604,-6.78%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.71%,1.477,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,8.86%,1.501,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,9.37%,1.574,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 40-60  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),-21.59%,-1.015,-33.43%,2.50%,-0.065
1,Rel Threshold 25% | No TLH,Off,-21.49%,-1.022,-32.82%,0.00%,0.000
2,Rel Threshold 25% | TLH=10%,On (10%),-22.65%,-1.023,-34.16%,3.50%,-0.355

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-21.59%,-1.015,2.50%,-0.065,$-742
1,Quarterly Rebal | TLH=10%,-21.98%,-1.069,2.39%,-0.112,"$-1,804"
2,Rel Threshold 25% | TLH=10%,-22.65%,-1.023,3.50%,-0.355,"$-11,784"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 40-60  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),10.72%,1.848,-2.55%,0.13%,0.094
1,Yearly Rebal | TLH=10%,On (10%),10.68%,1.843,-2.54%,0.12%,-0.033
2,Abs Threshold 5% | TLH=10%,On (10%),10.68%,1.843,-2.54%,0.12%,-0.033

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,10.72%,1.848,0.13%,0.094,"$+1,394"
1,Monthly Rebal | TLH=10%,10.51%,1.804,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,10.68%,1.843,0.12%,-0.033,"$+1,267"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 40-60  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-6.00%,-0.733,-3.47%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-6.00%,-0.733,-3.47%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-6.00%,-0.733,-3.47%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-5.97%,-0.733,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-6.00%,-0.733,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-6.00%,-0.733,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 40-60  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),9.85%,1.053,-9.75%,0.44%,0.908
1,Abs Threshold 5% | TLH=10%,On (10%),9.87%,1.042,-9.91%,0.44%,0.877
2,Abs Threshold 10% | TLH=10%,On (10%),9.87%,1.042,-9.91%,0.44%,0.877

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,9.85%,1.053,0.44%,0.908,"$+6,108"
1,Abs Threshold 5% | TLH=10%,9.87%,1.042,0.44%,0.877,"$+5,986"
2,Abs Threshold 10% | TLH=10%,9.87%,1.042,0.44%,0.877,"$+5,986"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 40-60  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),9.85%,1.053,-9.75%,0.44%,0.908
1,Abs Threshold 5% | TLH=10%,On (10%),9.87%,1.042,-9.91%,0.44%,0.877
2,Abs Threshold 10% | TLH=10%,On (10%),9.87%,1.042,-9.91%,0.44%,0.877

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,9.85%,1.053,0.44%,0.908,"$+6,108"
1,Abs Threshold 5% | TLH=10%,9.87%,1.042,0.44%,0.877,"$+5,986"
2,Abs Threshold 10% | TLH=10%,9.87%,1.042,0.44%,0.877,"$+5,986"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 40-60  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),9.85%,1.053,-9.75%,0.44%,0.908
1,Abs Threshold 5% | TLH=10%,On (10%),9.87%,1.042,-9.91%,0.44%,0.877
2,Abs Threshold 10% | TLH=10%,On (10%),9.87%,1.042,-9.91%,0.44%,0.877

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,9.85%,1.053,0.44%,0.908,"$+6,108"
1,Abs Threshold 5% | TLH=10%,9.87%,1.042,0.44%,0.877,"$+5,986"
2,Abs Threshold 10% | TLH=10%,9.87%,1.042,0.44%,0.877,"$+5,986"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 60-40  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),-25.22%,-1.013,-37.58%,4.52%,-0.297
1,Abs Threshold 5% | No TLH,Off,-23.96%,-1.024,-35.90%,0.00%,0.000
2,Monthly Rebal | TLH=10%,On (10%),-25.04%,-1.031,-37.27%,3.09%,-0.084

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-25.04%,-1.031,3.09%,-0.084,"$-1,754"
1,Quarterly Rebal | TLH=10%,-25.41%,-1.072,3.07%,-0.091,"$-1,960"
2,Abs Threshold 5% | TLH=10%,-25.22%,-1.013,4.52%,-0.297,"$-12,826"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 60-40  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),12.60%,1.659,-3.59%,0.15%,0.251
1,Yearly Rebal | TLH=10%,On (10%),12.54%,1.649,-3.60%,0.13%,-0.015
2,Abs Threshold 5% | TLH=10%,On (10%),12.54%,1.649,-3.60%,0.13%,-0.015

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,12.60%,1.659,0.15%,0.251,"$+1,607"
1,Monthly Rebal | TLH=10%,12.37%,1.624,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,12.54%,1.649,0.13%,-0.015,"$+1,300"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 60-40  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,-28.65%,-3.052,-1.78%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),-28.65%,-3.052,-1.78%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,-28.65%,-3.052,-1.78%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-28.65%,-3.052,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-28.65%,-3.052,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-28.65%,-3.052,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 60-40  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),17.23%,1.355,-12.45%,0.66%,1.228
1,Abs Threshold 5% | TLH=10%,On (10%),17.18%,1.354,-12.42%,0.66%,1.226
2,Abs Threshold 10% | TLH=10%,On (10%),17.18%,1.354,-12.42%,0.66%,1.226

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,16.89%,1.327,0.50%,1.736,"$+10,268"
1,Yearly Rebal | TLH=10%,17.23%,1.355,0.66%,1.228,"$+9,656"
2,Abs Threshold 5% | TLH=10%,17.18%,1.354,0.66%,1.226,"$+9,632"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 60-40  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),17.23%,1.355,-12.45%,0.66%,1.228
1,Abs Threshold 5% | TLH=10%,On (10%),17.18%,1.354,-12.42%,0.66%,1.226
2,Abs Threshold 10% | TLH=10%,On (10%),17.18%,1.354,-12.42%,0.66%,1.226

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,16.89%,1.327,0.50%,1.736,"$+10,268"
1,Yearly Rebal | TLH=10%,17.23%,1.355,0.66%,1.228,"$+9,656"
2,Abs Threshold 5% | TLH=10%,17.18%,1.354,0.66%,1.226,"$+9,632"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 60-40  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),17.23%,1.355,-12.45%,0.66%,1.228
1,Abs Threshold 5% | TLH=10%,On (10%),17.18%,1.354,-12.42%,0.66%,1.226
2,Abs Threshold 10% | TLH=10%,On (10%),17.18%,1.354,-12.42%,0.66%,1.226

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,16.89%,1.327,0.50%,1.736,"$+10,268"
1,Yearly Rebal | TLH=10%,17.23%,1.355,0.66%,1.228,"$+9,656"
2,Abs Threshold 5% | TLH=10%,17.18%,1.354,0.66%,1.226,"$+9,632"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 80-20  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),-13.18%,-0.563,-40.46%,4.50%,0.761
1,Abs Threshold 5% | TLH=10%,On (10%),-15.63%,-0.633,-43.58%,4.31%,0.096
2,Rel Threshold 50% | TLH=10%,On (10%),-15.63%,-0.633,-43.58%,4.31%,0.096

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-13.18%,-0.563,4.50%,0.761,"$+54,927"
1,Quarterly Rebal | TLH=10%,-16.00%,-0.637,2.55%,0.238,"$+10,330"
2,Yearly Rebal | TLH=10%,-15.28%,-0.648,4.06%,0.183,"$+12,554"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 80-20  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),14.44%,1.474,-4.82%,0.19%,0.345
1,Yearly Rebal | TLH=10%,On (10%),14.39%,1.468,-4.82%,0.16%,0.128
2,Abs Threshold 5% | TLH=10%,On (10%),14.39%,1.468,-4.82%,0.16%,0.128

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,14.44%,1.474,0.19%,0.345,"$+1,817"
1,Yearly Rebal | TLH=10%,14.39%,1.468,0.16%,0.128,"$+1,491"
2,Abs Threshold 5% | TLH=10%,14.39%,1.468,0.16%,0.128,"$+1,491"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 80-20  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,-31.72%,-2.632,-2.23%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),-31.72%,-2.632,-2.23%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,-31.72%,-2.632,-2.23%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-31.72%,-2.632,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-31.72%,-2.632,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-31.72%,-2.632,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 80-20  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),20.30%,1.262,-15.79%,0.77%,1.090
1,Abs Threshold 10% | TLH=10%,On (10%),20.30%,1.262,-15.79%,0.77%,1.090
2,Abs Threshold 20% | TLH=10%,On (10%),20.30%,1.262,-15.79%,0.77%,1.090

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,20.31%,1.262,0.77%,1.091,"$+10,000"
1,Abs Threshold 5% | TLH=10%,20.30%,1.262,0.77%,1.090,"$+9,989"
2,Abs Threshold 10% | TLH=10%,20.30%,1.262,0.77%,1.090,"$+9,989"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 80-20  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),20.30%,1.262,-15.79%,0.77%,1.090
1,Abs Threshold 10% | TLH=10%,On (10%),20.30%,1.262,-15.79%,0.77%,1.090
2,Abs Threshold 20% | TLH=10%,On (10%),20.30%,1.262,-15.79%,0.77%,1.090

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,20.31%,1.262,0.77%,1.091,"$+10,000"
1,Abs Threshold 5% | TLH=10%,20.30%,1.262,0.77%,1.090,"$+9,989"
2,Abs Threshold 10% | TLH=10%,20.30%,1.262,0.77%,1.090,"$+9,989"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Core - 80-20  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),20.30%,1.262,-15.79%,0.77%,1.090
1,Abs Threshold 10% | TLH=10%,On (10%),20.30%,1.262,-15.79%,0.77%,1.090
2,Abs Threshold 20% | TLH=10%,On (10%),20.30%,1.262,-15.79%,0.77%,1.090

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,20.31%,1.262,0.77%,1.091,"$+10,000"
1,Abs Threshold 5% | TLH=10%,20.30%,1.262,0.77%,1.090,"$+9,989"
2,Abs Threshold 10% | TLH=10%,20.30%,1.262,0.77%,1.090,"$+9,989"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 0-100  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,5.56%,0.678,-11.28%,0.00%,0.000
1,Rel Threshold 25% | TLH=10%,On (10%),5.56%,0.678,-11.28%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,5.28%,0.653,-10.94%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.28%,0.653,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,4.70%,0.590,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,4.79%,0.604,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 0-100  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),4.55%,1.573,-2.45%,0.32%,0.036
1,Monthly Rebal | TLH=10%,On (10%),4.53%,1.564,-2.45%,0.32%,0.112
2,Yearly Rebal | TLH=10%,On (10%),4.53%,1.563,-2.45%,0.34%,0.003

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,4.53%,1.564,0.32%,0.112,"$+1,765"
1,Rel Threshold 25% | TLH=10%,4.50%,1.552,0.32%,0.093,"$+1,691"
2,Quarterly Rebal | TLH=10%,4.55%,1.573,0.32%,0.036,"$+1,436"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 0-100  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,0.91%,0.157,-6.56%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,0.91%,0.157,-6.56%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,0.91%,0.157,-6.56%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.82%,0.138,0.23%,-0.211,$+422
1,Rel Threshold 25% | TLH=10%,0.85%,0.143,0.22%,-0.318,$+80
2,Quarterly Rebal | TLH=10%,0.82%,0.138,0.23%,-0.328,$-12

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 0-100  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,2.67%,0.506,-6.56%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,2.67%,0.506,-6.56%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,2.67%,0.506,-6.56%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.18%,0.403,0.21%,-0.330,$-575
1,Quarterly Rebal | TLH=10%,2.21%,0.408,0.21%,-0.409,"$-1,027"
2,Rel Threshold 25% | TLH=10%,2.29%,0.425,0.20%,-0.445,"$-1,154"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 0-100  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,2.67%,0.506,-6.56%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,2.67%,0.506,-6.56%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,2.67%,0.506,-6.56%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.18%,0.403,0.21%,-0.330,$-575
1,Quarterly Rebal | TLH=10%,2.21%,0.408,0.21%,-0.409,"$-1,027"
2,Rel Threshold 25% | TLH=10%,2.29%,0.425,0.20%,-0.445,"$-1,154"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 0-100  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,2.67%,0.506,-6.56%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,2.67%,0.506,-6.56%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,2.67%,0.506,-6.56%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.18%,0.403,0.21%,-0.330,$-575
1,Quarterly Rebal | TLH=10%,2.21%,0.408,0.21%,-0.409,"$-1,027"
2,Rel Threshold 25% | TLH=10%,2.29%,0.425,0.20%,-0.445,"$-1,154"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 10-90  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | TLH=10%,On (10%),-6.24%,-0.579,-17.17%,0.90%,0.178
1,Abs Threshold 5% | TLH=10%,On (10%),-6.21%,-0.608,-17.46%,0.91%,0.315
2,Rel Threshold 50% | No TLH,Off,-6.51%,-0.615,-17.43%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-6.21%,-0.608,0.91%,0.315,"$+4,055"
1,Rel Threshold 50% | TLH=10%,-6.24%,-0.579,0.90%,0.178,"$+2,781"
2,Quarterly Rebal | TLH=10%,-7.72%,-0.771,0.69%,-0.253,$-691

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 10-90  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),6.47%,2.188,-1.27%,0.12%,0.141
1,Yearly Rebal | TLH=10%,On (10%),6.43%,2.164,-1.29%,0.12%,0.115
2,Abs Threshold 5% | TLH=10%,On (10%),6.43%,2.164,-1.29%,0.12%,0.115

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,6.47%,2.188,0.12%,0.141,"$+1,389"
1,Yearly Rebal | TLH=10%,6.43%,2.164,0.12%,0.115,"$+1,363"
2,Abs Threshold 5% | TLH=10%,6.43%,2.164,0.12%,0.115,"$+1,363"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 10-90  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,3.66%,0.621,-6.59%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,3.66%,0.621,-6.59%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,3.66%,0.621,-6.59%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,3.18%,0.531,0.25%,-0.021,"$+1,177"
1,Rel Threshold 25% | TLH=10%,3.36%,0.562,0.24%,-0.106,$+853
2,Quarterly Rebal | TLH=10%,3.24%,0.541,0.24%,-0.121,$+783

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 10-90  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,5.35%,0.949,-6.59%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,5.35%,0.949,-6.59%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,5.35%,0.949,-6.59%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,4.38%,0.780,0.22%,-0.226,$-34
1,Rel Threshold 25% | TLH=10%,4.53%,0.809,0.21%,-0.309,$-499
2,Quarterly Rebal | TLH=10%,4.44%,0.791,0.22%,-0.313,$-536

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 10-90  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,5.35%,0.949,-6.59%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,5.35%,0.949,-6.59%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,5.35%,0.949,-6.59%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,4.38%,0.780,0.22%,-0.226,$-34
1,Rel Threshold 25% | TLH=10%,4.53%,0.809,0.21%,-0.309,$-499
2,Quarterly Rebal | TLH=10%,4.44%,0.791,0.22%,-0.313,$-536

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 10-90  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,5.35%,0.949,-6.59%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,5.35%,0.949,-6.59%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,5.35%,0.949,-6.59%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,4.38%,0.780,0.22%,-0.226,$-34
1,Rel Threshold 25% | TLH=10%,4.53%,0.809,0.21%,-0.309,$-499
2,Quarterly Rebal | TLH=10%,4.44%,0.791,0.22%,-0.313,$-536

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 100-0  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),-20.31%,-0.669,-49.99%,3.99%,0.561
1,Abs Threshold 5% | TLH=10%,On (10%),-20.32%,-0.670,-49.97%,4.02%,0.528
2,Abs Threshold 10% | TLH=10%,On (10%),-20.32%,-0.670,-49.97%,4.02%,0.528

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,-20.31%,-0.669,3.99%,0.561,"$+33,912"
1,Abs Threshold 5% | TLH=10%,-20.32%,-0.670,4.02%,0.528,"$+32,210"
2,Abs Threshold 10% | TLH=10%,-20.32%,-0.670,4.02%,0.528,"$+32,210"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 100-0  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),14.06%,1.192,-6.40%,0.40%,0.929
1,Abs Threshold 5% | TLH=10%,On (10%),14.06%,1.192,-6.40%,0.40%,0.929
2,Abs Threshold 10% | TLH=10%,On (10%),14.06%,1.192,-6.40%,0.40%,0.929

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,14.03%,1.190,0.42%,1.007,"$+4,511"
1,Yearly Rebal | TLH=10%,14.06%,1.192,0.40%,0.929,"$+4,136"
2,Abs Threshold 5% | TLH=10%,14.06%,1.192,0.40%,0.929,"$+4,136"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 100-0  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-5.30%,-0.421,-4.38%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-5.30%,-0.421,-4.38%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-5.30%,-0.421,-4.38%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-5.44%,-0.434,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-5.30%,-0.421,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-5.30%,-0.421,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 100-0  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,16.35%,0.948,-17.91%,0.00%,0.000
1,Quarterly Rebal | No TLH,Off,16.37%,0.943,-17.92%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,16.27%,0.936,-18.11%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,16.14%,0.930,0.56%,-0.289,$-543
1,Yearly Rebal | TLH=10%,16.12%,0.931,1.05%,-0.324,"$-2,683"
2,Abs Threshold 5% | TLH=10%,16.01%,0.918,1.06%,-0.361,"$-3,196"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 100-0  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,16.35%,0.948,-17.91%,0.00%,0.000
1,Quarterly Rebal | No TLH,Off,16.37%,0.943,-17.92%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,16.27%,0.936,-18.11%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,16.14%,0.930,0.56%,-0.289,$-543
1,Yearly Rebal | TLH=10%,16.12%,0.931,1.05%,-0.324,"$-2,683"
2,Abs Threshold 5% | TLH=10%,16.01%,0.918,1.06%,-0.361,"$-3,196"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 100-0  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,16.35%,0.948,-17.91%,0.00%,0.000
1,Quarterly Rebal | No TLH,Off,16.37%,0.943,-17.92%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,16.27%,0.936,-18.11%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,16.14%,0.930,0.56%,-0.289,$-543
1,Yearly Rebal | TLH=10%,16.12%,0.931,1.05%,-0.324,"$-2,683"
2,Abs Threshold 5% | TLH=10%,16.01%,0.918,1.06%,-0.361,"$-3,196"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 20-80  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | No TLH,Off,-11.43%,-0.810,-22.49%,0.00%,0.000
1,Rel Threshold 50% | TLH=10%,On (10%),-11.65%,-0.834,-22.80%,1.57%,-0.208
2,Rel Threshold 25% | No TLH,Off,-12.87%,-0.882,-23.09%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,-11.53%,-0.919,1.56%,0.102,"$+2,688"
1,Quarterly Rebal | TLH=10%,-13.23%,-0.947,1.20%,0.099,"$+2,253"
2,Monthly Rebal | TLH=10%,-13.16%,-0.907,1.46%,-0.038,$+459

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 20-80  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),7.54%,2.252,-1.24%,0.17%,0.623
1,Yearly Rebal | TLH=10%,On (10%),7.46%,2.224,-1.24%,0.14%,0.451
2,Abs Threshold 5% | TLH=10%,On (10%),7.46%,2.224,-1.24%,0.14%,0.451

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,7.54%,2.252,0.17%,0.623,"$+2,079"
1,Yearly Rebal | TLH=10%,7.46%,2.224,0.14%,0.451,"$+1,759"
2,Abs Threshold 5% | TLH=10%,7.46%,2.224,0.14%,0.451,"$+1,759"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 20-80  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-9.36%,-1.468,-3.31%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-9.36%,-1.468,-3.31%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-9.36%,-1.468,-3.31%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-9.35%,-1.470,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-9.36%,-1.468,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-9.36%,-1.468,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 20-80  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),5.66%,0.945,-5.93%,0.22%,0.648
1,Abs Threshold 5% | TLH=10%,On (10%),5.67%,0.942,-6.01%,0.22%,0.623
2,Abs Threshold 10% | TLH=10%,On (10%),5.67%,0.942,-6.01%,0.22%,0.623

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,5.66%,0.945,0.22%,0.648,"$+2,967"
1,Abs Threshold 5% | TLH=10%,5.67%,0.942,0.22%,0.623,"$+2,926"
2,Abs Threshold 10% | TLH=10%,5.67%,0.942,0.22%,0.623,"$+2,926"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 20-80  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),5.66%,0.945,-5.93%,0.22%,0.648
1,Abs Threshold 5% | TLH=10%,On (10%),5.67%,0.942,-6.01%,0.22%,0.623
2,Abs Threshold 10% | TLH=10%,On (10%),5.67%,0.942,-6.01%,0.22%,0.623

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,5.66%,0.945,0.22%,0.648,"$+2,967"
1,Abs Threshold 5% | TLH=10%,5.67%,0.942,0.22%,0.623,"$+2,926"
2,Abs Threshold 10% | TLH=10%,5.67%,0.942,0.22%,0.623,"$+2,926"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 20-80  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),5.66%,0.945,-5.93%,0.22%,0.648
1,Abs Threshold 5% | TLH=10%,On (10%),5.67%,0.942,-6.01%,0.22%,0.623
2,Abs Threshold 10% | TLH=10%,On (10%),5.67%,0.942,-6.01%,0.22%,0.623

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,5.66%,0.945,0.22%,0.648,"$+2,967"
1,Abs Threshold 5% | TLH=10%,5.67%,0.942,0.22%,0.623,"$+2,926"
2,Abs Threshold 10% | TLH=10%,5.67%,0.942,0.22%,0.623,"$+2,926"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 30-70  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | No TLH,Off,-15.05%,-0.882,-26.43%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,-15.85%,-0.895,-26.70%,0.00%,0.000
2,Rel Threshold 50% | TLH=10%,On (10%),-15.53%,-0.920,-26.95%,1.69%,-0.341

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,-16.39%,-0.936,1.84%,0.275,"$+6,185"
1,Yearly Rebal | TLH=10%,-15.13%,-0.983,1.87%,0.106,"$+3,043"
2,Quarterly Rebal | TLH=10%,-16.95%,-0.995,1.50%,0.063,"$+1,949"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 30-70  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),8.44%,2.040,-1.66%,0.19%,0.766
1,Yearly Rebal | TLH=10%,On (10%),8.35%,2.019,-1.66%,0.17%,0.610
2,Abs Threshold 5% | TLH=10%,On (10%),8.35%,2.019,-1.66%,0.17%,0.610

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,8.44%,2.040,0.19%,0.766,"$+2,414"
1,Yearly Rebal | TLH=10%,8.35%,2.019,0.17%,0.610,"$+2,055"
2,Abs Threshold 5% | TLH=10%,8.35%,2.019,0.17%,0.610,"$+2,055"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 30-70  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-8.72%,-1.252,-3.45%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-8.72%,-1.252,-3.45%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-8.72%,-1.252,-3.45%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-8.71%,-1.257,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-8.72%,-1.252,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-8.72%,-1.252,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 30-70  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),7.25%,1.010,-7.42%,0.33%,0.384
1,Abs Threshold 5% | TLH=10%,On (10%),7.25%,1.002,-7.54%,0.33%,0.335
2,Abs Threshold 10% | TLH=10%,On (10%),7.25%,1.002,-7.54%,0.33%,0.335

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,7.25%,1.010,0.33%,0.384,"$+2,816"
1,Abs Threshold 5% | TLH=10%,7.25%,1.002,0.33%,0.335,"$+2,644"
2,Abs Threshold 10% | TLH=10%,7.25%,1.002,0.33%,0.335,"$+2,644"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 30-70  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),7.25%,1.010,-7.42%,0.33%,0.384
1,Abs Threshold 5% | TLH=10%,On (10%),7.25%,1.002,-7.54%,0.33%,0.335
2,Abs Threshold 10% | TLH=10%,On (10%),7.25%,1.002,-7.54%,0.33%,0.335

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,7.25%,1.010,0.33%,0.384,"$+2,816"
1,Abs Threshold 5% | TLH=10%,7.25%,1.002,0.33%,0.335,"$+2,644"
2,Abs Threshold 10% | TLH=10%,7.25%,1.002,0.33%,0.335,"$+2,644"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 30-70  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),7.25%,1.010,-7.42%,0.33%,0.384
1,Abs Threshold 5% | TLH=10%,On (10%),7.25%,1.002,-7.54%,0.33%,0.335
2,Abs Threshold 10% | TLH=10%,On (10%),7.25%,1.002,-7.54%,0.33%,0.335

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,7.25%,1.010,0.33%,0.384,"$+2,816"
1,Abs Threshold 5% | TLH=10%,7.25%,1.002,0.33%,0.335,"$+2,644"
2,Abs Threshold 10% | TLH=10%,7.25%,1.002,0.33%,0.335,"$+2,644"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 40-60  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),-20.31%,-0.951,-31.87%,1.84%,0.259
1,Rel Threshold 25% | No TLH,Off,-20.84%,-0.957,-32.02%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-20.10%,-0.985,-31.45%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,-18.38%,-1.051,3.35%,0.259,"$+9,853"
1,Monthly Rebal | TLH=10%,-20.31%,-0.951,1.84%,0.259,"$+5,824"
2,Quarterly Rebal | TLH=10%,-22.05%,-1.182,3.36%,-0.331,"$-10,431"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 40-60  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),9.55%,1.849,-2.35%,0.22%,0.863
1,Yearly Rebal | TLH=10%,On (10%),9.46%,1.832,-2.34%,0.20%,0.717
2,Abs Threshold 5% | TLH=10%,On (10%),9.46%,1.832,-2.34%,0.20%,0.717

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,9.55%,1.849,0.22%,0.863,"$+2,759"
1,Yearly Rebal | TLH=10%,9.46%,1.832,0.20%,0.717,"$+2,370"
2,Abs Threshold 5% | TLH=10%,9.46%,1.832,0.20%,0.717,"$+2,370"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 40-60  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-8.68%,-1.131,-3.61%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-8.68%,-1.131,-3.61%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-8.68%,-1.131,-3.61%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-8.70%,-1.139,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-8.68%,-1.131,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-8.68%,-1.131,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 40-60  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),8.86%,1.031,-8.93%,0.34%,0.850
1,Abs Threshold 5% | TLH=10%,On (10%),8.86%,1.023,-9.07%,0.35%,0.807
2,Abs Threshold 10% | TLH=10%,On (10%),8.86%,1.023,-9.07%,0.35%,0.807

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,8.86%,1.031,0.34%,0.850,"$+4,782"
1,Abs Threshold 5% | TLH=10%,8.86%,1.023,0.35%,0.807,"$+4,737"
2,Abs Threshold 10% | TLH=10%,8.86%,1.023,0.35%,0.807,"$+4,737"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 40-60  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),8.86%,1.031,-8.93%,0.34%,0.850
1,Abs Threshold 5% | TLH=10%,On (10%),8.86%,1.023,-9.07%,0.35%,0.807
2,Abs Threshold 10% | TLH=10%,On (10%),8.86%,1.023,-9.07%,0.35%,0.807

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,8.86%,1.031,0.34%,0.850,"$+4,782"
1,Abs Threshold 5% | TLH=10%,8.86%,1.023,0.35%,0.807,"$+4,737"
2,Abs Threshold 10% | TLH=10%,8.86%,1.023,0.35%,0.807,"$+4,737"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 40-60  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),8.86%,1.031,-8.93%,0.34%,0.850
1,Abs Threshold 5% | TLH=10%,On (10%),8.86%,1.023,-9.07%,0.35%,0.807
2,Abs Threshold 10% | TLH=10%,On (10%),8.86%,1.023,-9.07%,0.35%,0.807

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,8.86%,1.031,0.34%,0.850,"$+4,782"
1,Abs Threshold 5% | TLH=10%,8.86%,1.023,0.35%,0.807,"$+4,737"
2,Abs Threshold 10% | TLH=10%,8.86%,1.023,0.35%,0.807,"$+4,737"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 50-50  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,-24.55%,-0.975,-36.32%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),-24.18%,-0.977,-36.12%,1.92%,0.220
2,Abs Threshold 5% | No TLH,Off,-23.65%,-0.986,-35.71%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,-22.42%,-1.070,3.64%,0.223,"$+9,221"
1,Monthly Rebal | TLH=10%,-24.18%,-0.977,1.92%,0.220,"$+5,216"
2,Rel Threshold 25% | TLH=10%,-24.67%,-1.023,3.02%,-0.070,"$-1,249"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 50-50  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),10.33%,1.709,-2.91%,0.26%,0.925
1,Yearly Rebal | TLH=10%,On (10%),10.24%,1.695,-2.90%,0.23%,0.789
2,Abs Threshold 5% | TLH=10%,On (10%),10.24%,1.695,-2.90%,0.23%,0.789

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,10.33%,1.709,0.26%,0.925,"$+3,109"
1,Yearly Rebal | TLH=10%,10.24%,1.695,0.23%,0.789,"$+2,699"
2,Abs Threshold 5% | TLH=10%,10.24%,1.695,0.23%,0.789,"$+2,699"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 50-50  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-8.09%,-0.960,-3.72%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-8.09%,-0.960,-3.72%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-8.09%,-0.960,-3.72%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-8.14%,-0.971,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-8.09%,-0.960,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-8.09%,-0.960,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 50-50  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),10.29%,1.032,-10.33%,0.51%,0.125
1,Abs Threshold 5% | TLH=10%,On (10%),10.28%,1.021,-10.52%,0.54%,0.091
2,Abs Threshold 10% | TLH=10%,On (10%),10.28%,1.021,-10.52%,0.54%,0.091

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.91%,0.989,0.39%,0.443,"$+3,418"
1,Yearly Rebal | TLH=10%,10.29%,1.032,0.51%,0.125,"$+2,108"
2,Abs Threshold 5% | TLH=10%,10.28%,1.021,0.54%,0.091,"$+1,934"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 50-50  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),10.29%,1.032,-10.33%,0.51%,0.125
1,Abs Threshold 5% | TLH=10%,On (10%),10.28%,1.021,-10.52%,0.54%,0.091
2,Abs Threshold 10% | TLH=10%,On (10%),10.28%,1.021,-10.52%,0.54%,0.091

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.91%,0.989,0.39%,0.443,"$+3,418"
1,Yearly Rebal | TLH=10%,10.29%,1.032,0.51%,0.125,"$+2,108"
2,Abs Threshold 5% | TLH=10%,10.28%,1.021,0.54%,0.091,"$+1,934"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 50-50  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),10.29%,1.032,-10.33%,0.51%,0.125
1,Abs Threshold 5% | TLH=10%,On (10%),10.28%,1.021,-10.52%,0.54%,0.091
2,Abs Threshold 10% | TLH=10%,On (10%),10.28%,1.021,-10.52%,0.54%,0.091

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.91%,0.989,0.39%,0.443,"$+3,418"
1,Yearly Rebal | TLH=10%,10.29%,1.032,0.51%,0.125,"$+2,108"
2,Abs Threshold 5% | TLH=10%,10.28%,1.021,0.54%,0.091,"$+1,934"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 60-40  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,-25.76%,-0.944,-37.87%,0.00%,0.000
1,Rel Threshold 50% | No TLH,Off,-23.94%,-0.952,-36.52%,0.00%,0.000
2,Monthly Rebal | TLH=10%,On (10%),-26.02%,-0.973,-38.11%,2.19%,0.221

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-26.02%,-0.973,2.19%,0.221,"$+5,823"
1,Yearly Rebal | TLH=10%,-24.73%,-1.067,3.70%,0.139,"$+6,128"
2,Quarterly Rebal | TLH=10%,-27.30%,-1.043,2.63%,-0.258,"$-6,051"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 60-40  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),11.36%,1.578,-3.59%,0.28%,0.966
1,Yearly Rebal | TLH=10%,On (10%),11.28%,1.567,-3.57%,0.26%,0.835
2,Abs Threshold 5% | TLH=10%,On (10%),11.28%,1.567,-3.57%,0.26%,0.835

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,11.36%,1.578,0.28%,0.966,"$+3,399"
1,Yearly Rebal | TLH=10%,11.28%,1.567,0.26%,0.835,"$+2,964"
2,Abs Threshold 5% | TLH=10%,11.28%,1.567,0.26%,0.835,"$+2,964"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 60-40  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-7.75%,-0.829,-3.91%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-7.75%,-0.829,-3.91%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-7.75%,-0.829,-3.91%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-7.83%,-0.841,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-7.75%,-0.829,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-7.75%,-0.829,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 60-40  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),11.93%,1.032,-12.09%,0.60%,0.374
1,Abs Threshold 5% | TLH=10%,On (10%),11.92%,1.020,-12.23%,0.63%,0.331
2,Abs Threshold 10% | TLH=10%,On (10%),11.92%,1.020,-12.23%,0.63%,0.331

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.47%,0.986,0.41%,0.515,"$+3,933"
1,Yearly Rebal | TLH=10%,11.93%,1.032,0.60%,0.374,"$+4,072"
2,Abs Threshold 5% | TLH=10%,11.92%,1.020,0.63%,0.331,"$+3,890"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 60-40  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),11.93%,1.032,-12.09%,0.60%,0.374
1,Abs Threshold 5% | TLH=10%,On (10%),11.92%,1.020,-12.23%,0.63%,0.331
2,Abs Threshold 10% | TLH=10%,On (10%),11.92%,1.020,-12.23%,0.63%,0.331

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.47%,0.986,0.41%,0.515,"$+3,933"
1,Yearly Rebal | TLH=10%,11.93%,1.032,0.60%,0.374,"$+4,072"
2,Abs Threshold 5% | TLH=10%,11.92%,1.020,0.63%,0.331,"$+3,890"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 60-40  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),11.93%,1.032,-12.09%,0.60%,0.374
1,Abs Threshold 5% | TLH=10%,On (10%),11.92%,1.020,-12.23%,0.63%,0.331
2,Abs Threshold 10% | TLH=10%,On (10%),11.92%,1.020,-12.23%,0.63%,0.331

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.47%,0.986,0.41%,0.515,"$+3,933"
1,Yearly Rebal | TLH=10%,11.93%,1.032,0.60%,0.374,"$+4,072"
2,Abs Threshold 5% | TLH=10%,11.92%,1.020,0.63%,0.331,"$+3,890"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 70-30  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | TLH=10%,On (10%),-13.50%,-0.570,-40.44%,2.98%,0.951
1,Abs Threshold 5% | TLH=10%,On (10%),-13.82%,-0.596,-41.03%,2.82%,0.620
2,Abs Threshold 10% | TLH=10%,On (10%),-14.21%,-0.632,-40.45%,2.87%,0.496

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,-13.50%,-0.570,2.98%,0.951,"$+45,521"
1,Abs Threshold 5% | TLH=10%,-13.82%,-0.596,2.82%,0.620,"$+28,483"
2,Yearly Rebal | TLH=10%,-14.49%,-0.637,2.80%,0.562,"$+25,545"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 70-30  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),12.33%,1.476,-4.25%,0.32%,0.996
1,Yearly Rebal | TLH=10%,On (10%),12.25%,1.468,-4.23%,0.30%,0.868
2,Abs Threshold 5% | TLH=10%,On (10%),12.25%,1.468,-4.23%,0.30%,0.868

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,12.33%,1.476,0.32%,0.996,"$+3,742"
1,Yearly Rebal | TLH=10%,12.25%,1.468,0.30%,0.868,"$+3,275"
2,Abs Threshold 5% | TLH=10%,12.25%,1.468,0.30%,0.868,"$+3,275"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 70-30  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-7.38%,-0.726,-4.05%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-7.38%,-0.726,-4.05%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-7.38%,-0.726,-4.05%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-7.48%,-0.739,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-7.38%,-0.726,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-7.38%,-0.726,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 70-30  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),13.50%,1.033,-13.73%,0.72%,0.126
1,Yearly Rebal | No TLH,Off,13.29%,1.021,-13.47%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),13.47%,1.020,-13.88%,0.75%,0.097

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,13.50%,1.033,0.72%,0.126,"$+2,478"
1,Monthly Rebal | TLH=10%,13.04%,0.992,0.48%,0.119,"$+2,075"
2,Abs Threshold 5% | TLH=10%,13.47%,1.020,0.75%,0.097,"$+2,274"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 70-30  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),13.50%,1.033,-13.73%,0.72%,0.126
1,Yearly Rebal | No TLH,Off,13.29%,1.021,-13.47%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),13.47%,1.020,-13.88%,0.75%,0.097

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,13.50%,1.033,0.72%,0.126,"$+2,478"
1,Monthly Rebal | TLH=10%,13.04%,0.992,0.48%,0.119,"$+2,075"
2,Abs Threshold 5% | TLH=10%,13.47%,1.020,0.75%,0.097,"$+2,274"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 70-30  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),13.50%,1.033,-13.73%,0.72%,0.126
1,Yearly Rebal | No TLH,Off,13.29%,1.021,-13.47%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),13.47%,1.020,-13.88%,0.75%,0.097

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,13.50%,1.033,0.72%,0.126,"$+2,478"
1,Monthly Rebal | TLH=10%,13.04%,0.992,0.48%,0.119,"$+2,075"
2,Abs Threshold 5% | TLH=10%,13.47%,1.020,0.75%,0.097,"$+2,274"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 80-20  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | TLH=10%,On (10%),-14.94%,-0.581,-42.96%,3.42%,0.960
1,Abs Threshold 5% | TLH=10%,On (10%),-15.32%,-0.604,-43.48%,3.25%,0.606
2,Abs Threshold 10% | TLH=10%,On (10%),-15.95%,-0.642,-43.42%,3.31%,0.519

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,-14.94%,-0.581,3.42%,0.960,"$+51,754"
1,Abs Threshold 5% | TLH=10%,-15.32%,-0.604,3.25%,0.606,"$+31,452"
2,Yearly Rebal | TLH=10%,-16.23%,-0.646,3.24%,0.578,"$+29,680"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 80-20  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),13.08%,1.378,-4.92%,0.36%,1.017
1,Yearly Rebal | TLH=10%,On (10%),13.03%,1.373,-4.90%,0.34%,0.901
2,Abs Threshold 5% | TLH=10%,On (10%),13.03%,1.373,-4.90%,0.34%,0.901

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,13.08%,1.378,0.36%,1.017,"$+4,120"
1,Yearly Rebal | TLH=10%,13.03%,1.373,0.34%,0.901,"$+3,647"
2,Abs Threshold 5% | TLH=10%,13.03%,1.373,0.34%,0.901,"$+3,647"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 80-20  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-7.37%,-0.667,-4.22%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-7.37%,-0.667,-4.22%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-7.37%,-0.667,-4.22%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-7.49%,-0.681,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-7.37%,-0.667,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-7.37%,-0.667,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 80-20  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),15.02%,1.028,-15.37%,0.76%,0.242
1,Abs Threshold 5% | TLH=10%,On (10%),14.97%,1.015,-15.50%,0.79%,0.213
2,Abs Threshold 10% | TLH=10%,On (10%),14.97%,1.015,-15.50%,0.79%,0.213

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,15.02%,1.028,0.76%,0.242,"$+3,640"
1,Abs Threshold 5% | TLH=10%,14.97%,1.015,0.79%,0.213,"$+3,458"
2,Abs Threshold 10% | TLH=10%,14.97%,1.015,0.79%,0.213,"$+3,458"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 80-20  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),15.02%,1.028,-15.37%,0.76%,0.242
1,Abs Threshold 5% | TLH=10%,On (10%),14.97%,1.015,-15.50%,0.79%,0.213
2,Abs Threshold 10% | TLH=10%,On (10%),14.97%,1.015,-15.50%,0.79%,0.213

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,15.02%,1.028,0.76%,0.242,"$+3,640"
1,Abs Threshold 5% | TLH=10%,14.97%,1.015,0.79%,0.213,"$+3,458"
2,Abs Threshold 10% | TLH=10%,14.97%,1.015,0.79%,0.213,"$+3,458"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 80-20  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),15.02%,1.028,-15.37%,0.76%,0.242
1,Abs Threshold 5% | TLH=10%,On (10%),14.97%,1.015,-15.50%,0.79%,0.213
2,Abs Threshold 10% | TLH=10%,On (10%),14.97%,1.015,-15.50%,0.79%,0.213

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,15.02%,1.028,0.76%,0.242,"$+3,640"
1,Abs Threshold 5% | TLH=10%,14.97%,1.015,0.79%,0.213,"$+3,458"
2,Abs Threshold 10% | TLH=10%,14.97%,1.015,0.79%,0.213,"$+3,458"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 90-10  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),-17.41%,-0.612,-46.77%,3.41%,0.736
1,Rel Threshold 25% | TLH=10%,On (10%),-18.25%,-0.641,-47.85%,3.50%,0.642
2,Abs Threshold 10% | TLH=10%,On (10%),-18.09%,-0.652,-47.09%,3.52%,0.500

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-17.41%,-0.612,3.41%,0.736,"$+38,963"
1,Rel Threshold 25% | TLH=10%,-18.25%,-0.641,3.50%,0.642,"$+34,728"
2,Yearly Rebal | TLH=10%,-18.37%,-0.655,3.44%,0.558,"$+29,818"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 90-10  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),13.90%,1.269,-5.85%,0.42%,1.031
1,Yearly Rebal | TLH=10%,On (10%),13.90%,1.268,-5.82%,0.40%,0.930
2,Abs Threshold 5% | TLH=10%,On (10%),13.90%,1.268,-5.82%,0.40%,0.930

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,13.90%,1.269,0.42%,1.031,"$+4,591"
1,Yearly Rebal | TLH=10%,13.90%,1.268,0.40%,0.930,"$+4,119"
2,Abs Threshold 5% | TLH=10%,13.90%,1.268,0.40%,0.930,"$+4,119"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 90-10  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-6.43%,-0.531,-4.34%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-6.43%,-0.531,-4.34%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-6.43%,-0.531,-4.34%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-6.59%,-0.545,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-6.43%,-0.531,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-6.43%,-0.531,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 90-10  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),16.77%,1.025,-17.24%,0.89%,0.063
1,Yearly Rebal | No TLH,Off,16.60%,1.018,-16.89%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),16.69%,1.011,-17.37%,0.94%,0.037

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,16.77%,1.025,0.89%,0.063,"$+2,125"
1,Abs Threshold 5% | TLH=10%,16.69%,1.011,0.94%,0.037,"$+1,860"
2,Abs Threshold 10% | TLH=10%,16.69%,1.011,0.94%,0.037,"$+1,860"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 90-10  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),16.77%,1.025,-17.24%,0.89%,0.063
1,Yearly Rebal | No TLH,Off,16.60%,1.018,-16.89%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),16.69%,1.011,-17.37%,0.94%,0.037

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,16.77%,1.025,0.89%,0.063,"$+2,125"
1,Abs Threshold 5% | TLH=10%,16.69%,1.011,0.94%,0.037,"$+1,860"
2,Abs Threshold 10% | TLH=10%,16.69%,1.011,0.94%,0.037,"$+1,860"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath ETF - 90-10  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),16.77%,1.025,-17.24%,0.89%,0.063
1,Yearly Rebal | No TLH,Off,16.60%,1.018,-16.89%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),16.69%,1.011,-17.37%,0.94%,0.037

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,16.77%,1.025,0.89%,0.063,"$+2,125"
1,Abs Threshold 5% | TLH=10%,16.69%,1.011,0.94%,0.037,"$+1,860"
2,Abs Threshold 10% | TLH=10%,16.69%,1.011,0.94%,0.037,"$+1,860"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Income - Conservative  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,9.12%,1.118,-7.12%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),9.12%,1.118,-7.12%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,9.12%,1.118,-7.12%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.12%,1.118,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,9.12%,1.118,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,9.12%,1.118,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Income - Conservative  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),1.51%,0.417,-8.71%,0.33%,0.498
1,Monthly Rebal | TLH=10%,On (10%),1.48%,0.409,-8.77%,0.34%,0.468
2,Yearly Rebal | TLH=10%,On (10%),1.44%,0.396,-8.87%,0.33%,0.481

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,1.51%,0.417,0.33%,0.498,"$+4,765"
1,Yearly Rebal | TLH=10%,1.44%,0.396,0.33%,0.481,"$+4,699"
2,Monthly Rebal | TLH=10%,1.48%,0.409,0.34%,0.468,"$+4,669"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Income - Conservative  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,2.91%,0.586,-4.91%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),2.91%,0.586,-4.91%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,2.91%,0.586,-4.91%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.79%,0.565,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,2.84%,0.576,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,2.88%,0.584,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Income - Conservative  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),4.11%,0.846,-6.31%,0.11%,0.532
1,Abs Threshold 10% | TLH=10%,On (10%),4.11%,0.846,-6.31%,0.11%,0.532
2,Abs Threshold 20% | TLH=10%,On (10%),4.11%,0.846,-6.31%,0.11%,0.532

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,4.11%,0.846,0.11%,0.532,"$+2,680"
1,Abs Threshold 10% | TLH=10%,4.11%,0.846,0.11%,0.532,"$+2,680"
2,Abs Threshold 20% | TLH=10%,4.11%,0.846,0.11%,0.532,"$+2,680"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Income - Conservative  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),4.11%,0.846,-6.31%,0.11%,0.532
1,Abs Threshold 10% | TLH=10%,On (10%),4.11%,0.846,-6.31%,0.11%,0.532
2,Abs Threshold 20% | TLH=10%,On (10%),4.11%,0.846,-6.31%,0.11%,0.532

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,4.11%,0.846,0.11%,0.532,"$+2,680"
1,Abs Threshold 10% | TLH=10%,4.11%,0.846,0.11%,0.532,"$+2,680"
2,Abs Threshold 20% | TLH=10%,4.11%,0.846,0.11%,0.532,"$+2,680"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Income - Conservative  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),4.11%,0.846,-6.31%,0.11%,0.532
1,Abs Threshold 10% | TLH=10%,On (10%),4.11%,0.846,-6.31%,0.11%,0.532
2,Abs Threshold 20% | TLH=10%,On (10%),4.11%,0.846,-6.31%,0.11%,0.532

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,4.11%,0.846,0.11%,0.532,"$+2,680"
1,Abs Threshold 10% | TLH=10%,4.11%,0.846,0.11%,0.532,"$+2,680"
2,Abs Threshold 20% | TLH=10%,4.11%,0.846,0.11%,0.532,"$+2,680"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Income - Moderate  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | TLH=10%,On (10%),-17.93%,-0.791,-28.63%,5.72%,-0.089
1,Rel Threshold 25% | TLH=10%,On (10%),-22.04%,-0.837,-32.37%,5.96%,-0.026
2,Abs Threshold 20% | No TLH,Off,-17.52%,-0.854,-28.47%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,-20.46%,-0.939,5.35%,0.168,"$+10,256"
1,Rel Threshold 25% | TLH=10%,-22.04%,-0.837,5.96%,-0.026,$-664
2,Abs Threshold 20% | TLH=10%,-17.93%,-0.791,5.72%,-0.089,"$-4,304"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Income - Moderate  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),2.88%,0.412,-14.09%,0.72%,0.500
1,Quarterly Rebal | TLH=10%,On (10%),2.79%,0.396,-14.13%,0.72%,0.308
2,Yearly Rebal | TLH=10%,On (10%),2.71%,0.381,-14.40%,0.72%,0.272

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.88%,0.412,0.72%,0.500,"$+9,137"
1,Quarterly Rebal | TLH=10%,2.79%,0.396,0.72%,0.308,"$+6,162"
2,Yearly Rebal | TLH=10%,2.71%,0.381,0.72%,0.272,"$+5,555"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Income - Moderate  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,6.30%,1.030,-4.82%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),6.30%,1.030,-4.82%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,6.30%,1.030,-4.82%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.88%,0.981,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,6.01%,1.002,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.16%,1.016,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Income - Moderate  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),7.65%,1.161,-8.14%,0.10%,0.520
1,Yearly Rebal | TLH=10%,On (10%),7.66%,1.155,-8.10%,0.10%,0.440
2,Abs Threshold 5% | TLH=10%,On (10%),7.87%,1.153,-8.40%,0.11%,0.519

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,7.65%,1.161,0.10%,0.520,"$+2,743"
1,Abs Threshold 5% | TLH=10%,7.87%,1.153,0.11%,0.519,"$+2,790"
2,Abs Threshold 10% | TLH=10%,7.87%,1.153,0.11%,0.519,"$+2,790"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Income - Moderate  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),7.65%,1.161,-8.14%,0.10%,0.520
1,Yearly Rebal | TLH=10%,On (10%),7.66%,1.155,-8.10%,0.10%,0.440
2,Abs Threshold 5% | TLH=10%,On (10%),7.87%,1.153,-8.40%,0.11%,0.519

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,7.65%,1.161,0.10%,0.520,"$+2,743"
1,Abs Threshold 5% | TLH=10%,7.87%,1.153,0.11%,0.519,"$+2,790"
2,Abs Threshold 10% | TLH=10%,7.87%,1.153,0.11%,0.519,"$+2,790"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Income - Moderate  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),7.65%,1.161,-8.14%,0.10%,0.520
1,Yearly Rebal | TLH=10%,On (10%),7.66%,1.155,-8.10%,0.10%,0.440
2,Abs Threshold 5% | TLH=10%,On (10%),7.87%,1.153,-8.40%,0.11%,0.519

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,7.65%,1.161,0.10%,0.520,"$+2,743"
1,Abs Threshold 5% | TLH=10%,7.87%,1.153,0.11%,0.519,"$+2,790"
2,Abs Threshold 10% | TLH=10%,7.87%,1.153,0.11%,0.519,"$+2,790"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Income - Moderate Growth  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),-43.78%,-0.856,-55.69%,7.98%,0.078
1,Abs Threshold 10% | TLH=10%,On (10%),-45.02%,-0.861,-56.00%,9.21%,0.077
2,Monthly Rebal | TLH=10%,On (10%),-45.49%,-0.884,-57.25%,9.52%,-0.008

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 20% | TLH=10%,-44.99%,-0.897,9.71%,0.079,"$+8,431"
1,Rel Threshold 50% | TLH=10%,-44.99%,-0.897,9.71%,0.079,"$+8,431"
2,Abs Threshold 5% | TLH=10%,-43.78%,-0.856,7.98%,0.078,"$+7,036"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Income - Moderate Growth  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | TLH=10%,On (10%),4.71%,0.452,-17.50%,0.91%,0.333
1,Rel Threshold 25% | TLH=10%,On (10%),4.62%,0.449,-17.28%,0.97%,0.432
2,Monthly Rebal | TLH=10%,On (10%),4.56%,0.446,-17.36%,0.92%,0.420

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,4.62%,0.449,0.97%,0.432,"$+10,669"
1,Monthly Rebal | TLH=10%,4.56%,0.446,0.92%,0.420,"$+9,967"
2,Abs Threshold 5% | TLH=10%,4.61%,0.445,0.92%,0.405,"$+9,604"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Income - Moderate Growth  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,9.01%,1.227,-4.98%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),9.01%,1.227,-4.98%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,9.01%,1.227,-4.98%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.47%,1.177,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,8.63%,1.199,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,8.82%,1.211,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Income - Moderate Growth  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),10.31%,1.230,-9.83%,0.10%,0.476
1,Yearly Rebal | TLH=10%,On (10%),10.29%,1.223,-9.77%,0.09%,0.382
2,Rel Threshold 25% | No TLH,Off,10.21%,1.220,-9.81%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,10.50%,1.213,0.10%,0.479,"$+2,706"
1,Abs Threshold 10% | TLH=10%,10.50%,1.213,0.10%,0.479,"$+2,706"
2,Abs Threshold 20% | TLH=10%,10.50%,1.213,0.10%,0.479,"$+2,706"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Income - Moderate Growth  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),10.31%,1.230,-9.83%,0.10%,0.476
1,Yearly Rebal | TLH=10%,On (10%),10.29%,1.223,-9.77%,0.09%,0.382
2,Rel Threshold 25% | No TLH,Off,10.21%,1.220,-9.81%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,10.50%,1.213,0.10%,0.479,"$+2,706"
1,Abs Threshold 10% | TLH=10%,10.50%,1.213,0.10%,0.479,"$+2,706"
2,Abs Threshold 20% | TLH=10%,10.50%,1.213,0.10%,0.479,"$+2,706"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath Income - Moderate Growth  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),10.31%,1.230,-9.83%,0.10%,0.476
1,Yearly Rebal | TLH=10%,On (10%),10.29%,1.223,-9.77%,0.09%,0.382
2,Rel Threshold 25% | No TLH,Off,10.21%,1.220,-9.81%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,10.50%,1.213,0.10%,0.479,"$+2,706"
1,Abs Threshold 10% | TLH=10%,10.50%,1.213,0.10%,0.479,"$+2,706"
2,Abs Threshold 20% | TLH=10%,10.50%,1.213,0.10%,0.479,"$+2,706"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 0-100  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,11.90%,1.227,-9.64%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),11.90%,1.227,-9.64%,0.00%,0.000
2,Rel Threshold 25% | No TLH,Off,11.66%,1.197,-9.77%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.60%,1.194,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,11.47%,1.181,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,11.58%,1.190,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 0-100  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,4.68%,1.463,-2.68%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),4.68%,1.463,-2.68%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,4.66%,1.459,-2.66%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,4.66%,1.459,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,4.68%,1.463,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,4.70%,1.457,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 0-100  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,0.37%,0.068,-8.58%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,0.37%,0.068,-8.58%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,0.37%,0.068,-8.58%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.14%,0.023,0.62%,-0.302,"$-2,551"
1,Quarterly Rebal | TLH=10%,0.13%,0.022,0.63%,-0.355,"$-3,286"
2,Rel Threshold 25% | TLH=10%,0.11%,0.019,0.61%,-0.396,"$-3,603"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 0-100  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,1.05%,0.220,-4.29%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),1.05%,0.220,-4.29%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,1.05%,0.220,-4.29%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.71%,0.149,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.76%,0.160,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,1.05%,0.220,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 0-100  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,1.05%,0.220,-4.29%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),1.05%,0.220,-4.29%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,1.05%,0.220,-4.29%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.71%,0.149,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.76%,0.160,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,1.05%,0.220,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 0-100  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,1.05%,0.220,-4.29%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),1.05%,0.220,-4.29%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,1.05%,0.220,-4.29%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.71%,0.149,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.76%,0.160,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,1.05%,0.220,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 100-0  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),-15.69%,-0.604,-46.81%,5.07%,0.918
1,Yearly Rebal | TLH=10%,On (10%),-19.18%,-0.640,-50.50%,7.90%,0.155
2,Abs Threshold 5% | TLH=10%,On (10%),-19.17%,-0.640,-50.50%,7.90%,0.149

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-15.69%,-0.604,5.07%,0.918,"$+76,970"
1,Yearly Rebal | TLH=10%,-19.18%,-0.640,7.90%,0.155,"$+20,355"
2,Abs Threshold 5% | TLH=10%,-19.17%,-0.640,7.90%,0.149,"$+19,611"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 100-0  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),14.21%,1.222,-6.33%,0.35%,0.866
1,Abs Threshold 5% | TLH=10%,On (10%),14.21%,1.222,-6.33%,0.35%,0.866
2,Abs Threshold 10% | TLH=10%,On (10%),14.21%,1.222,-6.33%,0.35%,0.866

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,14.14%,1.218,0.36%,0.939,"$+3,914"
1,Yearly Rebal | TLH=10%,14.21%,1.222,0.35%,0.866,"$+3,605"
2,Abs Threshold 5% | TLH=10%,14.21%,1.222,0.35%,0.866,"$+3,605"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 100-0  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-5.36%,-0.428,-4.23%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-5.36%,-0.428,-4.23%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-5.36%,-0.428,-4.23%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-5.59%,-0.447,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-5.36%,-0.428,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-5.36%,-0.428,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 100-0  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),17.59%,1.034,-17.37%,0.81%,1.231
1,Abs Threshold 5% | TLH=10%,On (10%),17.47%,1.021,-17.50%,0.83%,1.194
2,Abs Threshold 10% | TLH=10%,On (10%),17.47%,1.021,-17.50%,0.83%,1.194

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,17.59%,1.034,0.81%,1.231,"$+13,638"
1,Abs Threshold 5% | TLH=10%,17.47%,1.021,0.83%,1.194,"$+13,431"
2,Abs Threshold 10% | TLH=10%,17.47%,1.021,0.83%,1.194,"$+13,431"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 100-0  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),17.59%,1.034,-17.37%,0.81%,1.231
1,Abs Threshold 5% | TLH=10%,On (10%),17.47%,1.021,-17.50%,0.83%,1.194
2,Abs Threshold 10% | TLH=10%,On (10%),17.47%,1.021,-17.50%,0.83%,1.194

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,17.59%,1.034,0.81%,1.231,"$+13,638"
1,Abs Threshold 5% | TLH=10%,17.47%,1.021,0.83%,1.194,"$+13,431"
2,Abs Threshold 10% | TLH=10%,17.47%,1.021,0.83%,1.194,"$+13,431"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 100-0  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),17.59%,1.034,-17.37%,0.81%,1.231
1,Abs Threshold 5% | TLH=10%,On (10%),17.47%,1.021,-17.50%,0.83%,1.194
2,Abs Threshold 10% | TLH=10%,On (10%),17.47%,1.021,-17.50%,0.83%,1.194

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,17.59%,1.034,0.81%,1.231,"$+13,638"
1,Abs Threshold 5% | TLH=10%,17.47%,1.021,0.83%,1.194,"$+13,431"
2,Abs Threshold 10% | TLH=10%,17.47%,1.021,0.83%,1.194,"$+13,431"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 20-80  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),-1.67%,-0.163,-21.82%,2.16%,0.176
1,Abs Threshold 20% | TLH=10%,On (10%),-1.70%,-0.167,-21.24%,2.32%,-0.011
2,Abs Threshold 20% | No TLH,Off,-1.73%,-0.178,-22.06%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-2.30%,-0.197,2.46%,0.492,"$+24,266"
1,Rel Threshold 25% | TLH=10%,-2.52%,-0.213,2.24%,0.397,"$+18,129"
2,Quarterly Rebal | TLH=10%,-2.80%,-0.240,2.75%,0.226,"$+13,010"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 20-80  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),8.86%,2.555,-1.43%,0.20%,0.768
1,Yearly Rebal | TLH=10%,On (10%),8.71%,2.508,-1.41%,0.16%,0.551
2,Abs Threshold 5% | TLH=10%,On (10%),8.71%,2.508,-1.41%,0.16%,0.551

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,8.86%,2.555,0.20%,0.768,"$+2,438"
1,Yearly Rebal | TLH=10%,8.71%,2.508,0.16%,0.551,"$+1,949"
2,Abs Threshold 5% | TLH=10%,8.71%,2.508,0.16%,0.551,"$+1,949"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 20-80  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,8.57%,1.279,-8.16%,0.00%,0.000
1,Abs Threshold 20% | No TLH,Off,8.57%,1.279,-8.16%,0.00%,0.000
2,Rel Threshold 50% | No TLH,Off,8.57%,1.279,-8.16%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.10%,1.076,0.55%,0.040,"$+1,835"
1,Quarterly Rebal | TLH=10%,7.27%,1.101,0.54%,-0.028,"$+1,051"
2,Yearly Rebal | TLH=10%,7.73%,1.153,0.49%,-0.037,"$+1,000"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 20-80  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),6.80%,1.033,-7.28%,0.37%,0.880
1,Abs Threshold 5% | TLH=10%,On (10%),6.80%,1.033,-7.28%,0.37%,0.880
2,Abs Threshold 10% | TLH=10%,On (10%),6.80%,1.033,-7.28%,0.37%,0.880

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,6.80%,1.033,0.37%,0.880,"$+4,155"
1,Abs Threshold 5% | TLH=10%,6.80%,1.033,0.37%,0.880,"$+4,155"
2,Abs Threshold 10% | TLH=10%,6.80%,1.033,0.37%,0.880,"$+4,155"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 20-80  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),6.80%,1.033,-7.28%,0.37%,0.880
1,Abs Threshold 5% | TLH=10%,On (10%),6.80%,1.033,-7.28%,0.37%,0.880
2,Abs Threshold 10% | TLH=10%,On (10%),6.80%,1.033,-7.28%,0.37%,0.880

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,6.80%,1.033,0.37%,0.880,"$+4,155"
1,Abs Threshold 5% | TLH=10%,6.80%,1.033,0.37%,0.880,"$+4,155"
2,Abs Threshold 10% | TLH=10%,6.80%,1.033,0.37%,0.880,"$+4,155"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 20-80  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),6.80%,1.033,-7.28%,0.37%,0.880
1,Abs Threshold 5% | TLH=10%,On (10%),6.80%,1.033,-7.28%,0.37%,0.880
2,Abs Threshold 10% | TLH=10%,On (10%),6.80%,1.033,-7.28%,0.37%,0.880

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,6.80%,1.033,0.37%,0.880,"$+4,155"
1,Abs Threshold 5% | TLH=10%,6.80%,1.033,0.37%,0.880,"$+4,155"
2,Abs Threshold 10% | TLH=10%,6.80%,1.033,0.37%,0.880,"$+4,155"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 40-60  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),-10.26%,-0.525,-36.97%,4.35%,0.308
1,Abs Threshold 20% | TLH=10%,On (10%),-9.51%,-0.540,-34.92%,3.95%,0.231
2,Rel Threshold 50% | TLH=10%,On (10%),-10.30%,-0.543,-36.23%,4.28%,0.273

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-10.26%,-0.525,4.35%,0.308,"$+24,589"
1,Quarterly Rebal | TLH=10%,-11.19%,-0.651,2.80%,0.303,"$+15,788"
2,Rel Threshold 50% | TLH=10%,-10.30%,-0.543,4.28%,0.273,"$+21,498"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 40-60  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),11.75%,1.698,-3.37%,0.29%,0.969
1,Yearly Rebal | TLH=10%,On (10%),11.61%,1.683,-3.34%,0.26%,0.802
2,Abs Threshold 5% | TLH=10%,On (10%),11.61%,1.683,-3.34%,0.26%,0.802

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,11.75%,1.698,0.29%,0.969,"$+3,417"
1,Yearly Rebal | TLH=10%,11.61%,1.683,0.26%,0.802,"$+2,877"
2,Abs Threshold 5% | TLH=10%,11.61%,1.683,0.26%,0.802,"$+2,877"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 40-60  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-7.66%,-0.838,-3.93%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-7.66%,-0.838,-3.93%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-7.66%,-0.838,-3.93%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-7.78%,-0.853,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-7.66%,-0.838,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-7.66%,-0.838,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 40-60  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),12.82%,1.123,-11.96%,0.63%,1.328
1,Abs Threshold 5% | TLH=10%,On (10%),12.82%,1.123,-11.96%,0.63%,1.328
2,Abs Threshold 10% | TLH=10%,On (10%),12.82%,1.123,-11.96%,0.63%,1.328

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,12.82%,1.123,0.63%,1.328,"$+8,683"
1,Abs Threshold 5% | TLH=10%,12.82%,1.123,0.63%,1.328,"$+8,683"
2,Abs Threshold 10% | TLH=10%,12.82%,1.123,0.63%,1.328,"$+8,683"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 40-60  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),12.82%,1.123,-11.96%,0.63%,1.328
1,Abs Threshold 5% | TLH=10%,On (10%),12.82%,1.123,-11.96%,0.63%,1.328
2,Abs Threshold 10% | TLH=10%,On (10%),12.82%,1.123,-11.96%,0.63%,1.328

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,12.82%,1.123,0.63%,1.328,"$+8,683"
1,Abs Threshold 5% | TLH=10%,12.82%,1.123,0.63%,1.328,"$+8,683"
2,Abs Threshold 10% | TLH=10%,12.82%,1.123,0.63%,1.328,"$+8,683"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 40-60  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),12.82%,1.123,-11.96%,0.63%,1.328
1,Abs Threshold 5% | TLH=10%,On (10%),12.82%,1.123,-11.96%,0.63%,1.328
2,Abs Threshold 10% | TLH=10%,On (10%),12.82%,1.123,-11.96%,0.63%,1.328

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,12.82%,1.123,0.63%,1.328,"$+8,683"
1,Abs Threshold 5% | TLH=10%,12.82%,1.123,0.63%,1.328,"$+8,683"
2,Abs Threshold 10% | TLH=10%,12.82%,1.123,0.63%,1.328,"$+8,683"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 60-40  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),-10.35%,-0.484,-37.15%,5.80%,0.687
1,Quarterly Rebal | TLH=10%,On (10%),-10.16%,-0.518,-37.35%,4.44%,1.013
2,Abs Threshold 10% | TLH=10%,On (10%),-11.99%,-0.545,-39.79%,5.52%,0.186

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-10.16%,-0.518,4.44%,1.013,"$+78,915"
1,Rel Threshold 25% | TLH=10%,-10.35%,-0.484,5.80%,0.687,"$+70,090"
2,Abs Threshold 5% | TLH=10%,-12.07%,-0.595,4.40%,0.489,"$+37,821"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 60-40  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),13.54%,1.477,-4.62%,0.32%,0.988
1,Yearly Rebal | TLH=10%,On (10%),13.42%,1.469,-4.59%,0.29%,0.839
2,Abs Threshold 5% | TLH=10%,On (10%),13.42%,1.469,-4.59%,0.29%,0.839

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,13.54%,1.477,0.32%,0.988,"$+3,714"
1,Yearly Rebal | TLH=10%,13.42%,1.469,0.29%,0.839,"$+3,192"
2,Abs Threshold 5% | TLH=10%,13.42%,1.469,0.29%,0.839,"$+3,192"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 60-40  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-6.33%,-0.557,-4.17%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-6.33%,-0.557,-4.17%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-6.33%,-0.557,-4.17%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-6.51%,-0.575,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-6.33%,-0.557,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-6.33%,-0.557,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 60-40  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),17.49%,1.178,-14.57%,0.83%,1.664
1,Abs Threshold 5% | TLH=10%,On (10%),17.49%,1.178,-14.57%,0.83%,1.664
2,Abs Threshold 10% | TLH=10%,On (10%),17.49%,1.178,-14.57%,0.83%,1.664

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,17.49%,1.178,0.83%,1.664,"$+13,381"
1,Abs Threshold 5% | TLH=10%,17.49%,1.178,0.83%,1.664,"$+13,381"
2,Abs Threshold 10% | TLH=10%,17.49%,1.178,0.83%,1.664,"$+13,381"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 60-40  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),17.49%,1.178,-14.57%,0.83%,1.664
1,Abs Threshold 5% | TLH=10%,On (10%),17.49%,1.178,-14.57%,0.83%,1.664
2,Abs Threshold 10% | TLH=10%,On (10%),17.49%,1.178,-14.57%,0.83%,1.664

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,17.49%,1.178,0.83%,1.664,"$+13,381"
1,Abs Threshold 5% | TLH=10%,17.49%,1.178,0.83%,1.664,"$+13,381"
2,Abs Threshold 10% | TLH=10%,17.49%,1.178,0.83%,1.664,"$+13,381"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 60-40  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),17.49%,1.178,-14.57%,0.83%,1.664
1,Abs Threshold 5% | TLH=10%,On (10%),17.49%,1.178,-14.57%,0.83%,1.664
2,Abs Threshold 10% | TLH=10%,On (10%),17.49%,1.178,-14.57%,0.83%,1.664

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,17.49%,1.178,0.83%,1.664,"$+13,381"
1,Abs Threshold 5% | TLH=10%,17.49%,1.178,0.83%,1.664,"$+13,381"
2,Abs Threshold 10% | TLH=10%,17.49%,1.178,0.83%,1.664,"$+13,381"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 80-20  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),-16.17%,-0.635,-46.14%,5.96%,0.225
1,Abs Threshold 10% | TLH=10%,On (10%),-16.17%,-0.635,-46.14%,5.96%,0.225
2,Abs Threshold 20% | TLH=10%,On (10%),-16.17%,-0.635,-46.14%,5.96%,0.225

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,-17.16%,-0.730,3.94%,0.269,"$+18,097"
1,Yearly Rebal | TLH=10%,-16.42%,-0.636,6.08%,0.245,"$+25,267"
2,Abs Threshold 5% | TLH=10%,-16.17%,-0.635,5.96%,0.225,"$+22,953"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 80-20  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),14.13%,1.309,-5.70%,0.36%,0.972
1,Yearly Rebal | TLH=10%,On (10%),14.12%,1.307,-5.67%,0.34%,0.866
2,Abs Threshold 5% | TLH=10%,On (10%),14.12%,1.307,-5.67%,0.34%,0.866

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,14.13%,1.309,0.36%,0.972,"$+3,952"
1,Yearly Rebal | TLH=10%,14.12%,1.307,0.34%,0.866,"$+3,542"
2,Abs Threshold 5% | TLH=10%,14.12%,1.307,0.34%,0.866,"$+3,542"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 80-20  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-6.13%,-0.506,-4.16%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-6.13%,-0.506,-4.16%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-6.13%,-0.506,-4.16%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-6.31%,-0.523,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-6.13%,-0.506,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-6.13%,-0.506,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 80-20  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),18.99%,1.140,-16.18%,0.90%,1.486
1,Abs Threshold 5% | TLH=10%,On (10%),18.99%,1.140,-16.18%,0.90%,1.486
2,Abs Threshold 10% | TLH=10%,On (10%),18.99%,1.140,-16.18%,0.90%,1.486

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,18.99%,1.140,0.90%,1.486,"$+13,061"
1,Abs Threshold 5% | TLH=10%,18.99%,1.140,0.90%,1.486,"$+13,061"
2,Abs Threshold 10% | TLH=10%,18.99%,1.140,0.90%,1.486,"$+13,061"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 80-20  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),18.99%,1.140,-16.18%,0.90%,1.486
1,Abs Threshold 5% | TLH=10%,On (10%),18.99%,1.140,-16.18%,0.90%,1.486
2,Abs Threshold 10% | TLH=10%,On (10%),18.99%,1.140,-16.18%,0.90%,1.486

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,18.99%,1.140,0.90%,1.486,"$+13,061"
1,Abs Threshold 5% | TLH=10%,18.99%,1.140,0.90%,1.486,"$+13,061"
2,Abs Threshold 10% | TLH=10%,18.99%,1.140,0.90%,1.486,"$+13,061"

──────────────────────────────────────────────────────────────────────────────────────────
  GuidePath TaxAware - 80-20  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),18.99%,1.140,-16.18%,0.90%,1.486
1,Abs Threshold 5% | TLH=10%,On (10%),18.99%,1.140,-16.18%,0.90%,1.486
2,Abs Threshold 10% | TLH=10%,On (10%),18.99%,1.140,-16.18%,0.90%,1.486

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,18.99%,1.140,0.90%,1.486,"$+13,061"
1,Abs Threshold 5% | TLH=10%,18.99%,1.140,0.90%,1.486,"$+13,061"
2,Abs Threshold 10% | TLH=10%,18.99%,1.140,0.90%,1.486,"$+13,061"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Aggressive Growth  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | TLH=10%,On (10%),-25.65%,-0.843,-33.59%,9.92%,0.302
1,Monthly Rebal | TLH=10%,On (10%),-24.91%,-0.846,-32.93%,8.66%,0.548
2,Rel Threshold 25% | TLH=10%,On (10%),-26.11%,-0.858,-33.60%,9.60%,0.348

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-24.91%,-0.846,8.66%,0.548,"$+47,926"
1,Rel Threshold 25% | TLH=10%,-26.11%,-0.858,9.60%,0.348,"$+33,947"
2,Yearly Rebal | TLH=10%,-26.56%,-0.892,9.75%,0.336,"$+33,318"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Aggressive Growth  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | TLH=10%,On (10%),5.62%,0.494,-18.27%,1.36%,0.352
1,Abs Threshold 20% | TLH=10%,On (10%),5.62%,0.494,-18.27%,1.36%,0.352
2,Rel Threshold 50% | TLH=10%,On (10%),5.62%,0.494,-18.27%,1.36%,0.352

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.49%,0.490,1.13%,0.514,"$+14,440"
1,Abs Threshold 5% | TLH=10%,5.56%,0.490,1.36%,0.392,"$+13,385"
2,Yearly Rebal | TLH=10%,5.53%,0.488,1.38%,0.376,"$+13,043"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Aggressive Growth  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,12.57%,1.315,-5.95%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),12.57%,1.315,-5.95%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,12.57%,1.315,-5.95%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.29%,1.290,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,12.50%,1.308,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,12.57%,1.315,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Aggressive Growth  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,12.90%,1.089,-10.83%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,12.90%,1.089,-10.83%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,12.90%,1.089,-10.83%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.39%,1.051,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,12.44%,1.056,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,10.36%,0.875,1.29%,-2.086,"$-22,286"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Aggressive Growth  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,12.90%,1.089,-10.83%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,12.90%,1.089,-10.83%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,12.90%,1.089,-10.83%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.39%,1.051,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,12.44%,1.056,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,10.36%,0.875,1.29%,-2.086,"$-22,286"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Aggressive Growth  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,12.90%,1.089,-10.83%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,12.90%,1.089,-10.83%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,12.90%,1.089,-10.83%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.39%,1.051,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,12.44%,1.056,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,10.36%,0.875,1.29%,-2.086,"$-22,286"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Conservative  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),-6.61%,-0.632,-17.77%,6.52%,0.290
1,Abs Threshold 5% | No TLH,Off,-8.32%,-0.714,-19.40%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,-8.62%,-0.733,-19.56%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-6.61%,-0.632,6.52%,0.290,"$+19,806"
1,Quarterly Rebal | TLH=10%,-11.45%,-0.934,2.86%,-1.030,"$-28,026"
2,Abs Threshold 5% | TLH=10%,-13.54%,-1.091,4.47%,-1.193,"$-51,724"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Conservative  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),2.31%,0.785,-5.18%,0.32%,0.501
1,Quarterly Rebal | TLH=10%,On (10%),2.31%,0.784,-5.14%,0.36%,0.369
2,Yearly Rebal | TLH=10%,On (10%),2.29%,0.763,-5.30%,0.35%,0.343

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.31%,0.785,0.32%,0.501,"$+4,813"
1,Quarterly Rebal | TLH=10%,2.31%,0.784,0.36%,0.369,"$+4,190"
2,Abs Threshold 5% | TLH=10%,2.25%,0.745,0.34%,0.352,"$+3,896"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Conservative  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,7.20%,1.458,-3.42%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),7.20%,1.458,-3.42%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,7.20%,1.458,-3.42%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.04%,1.427,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,7.09%,1.437,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,7.18%,1.453,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Conservative  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,-0.61%,-0.108,-7.55%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,-0.61%,-0.108,-7.55%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,-0.61%,-0.108,-7.55%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-0.80%,-0.141,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-0.78%,-0.137,0.00%,0.000,$+0
2,Rel Threshold 25% | TLH=10%,-1.08%,-0.189,0.37%,-1.255,"$-2,991"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Conservative  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,-0.61%,-0.108,-7.55%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,-0.61%,-0.108,-7.55%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,-0.61%,-0.108,-7.55%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-0.80%,-0.141,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-0.78%,-0.137,0.00%,0.000,$+0
2,Rel Threshold 25% | TLH=10%,-1.08%,-0.189,0.37%,-1.255,"$-2,991"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Conservative  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,-0.61%,-0.108,-7.55%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,-0.61%,-0.108,-7.55%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,-0.61%,-0.108,-7.55%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-0.80%,-0.141,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-0.78%,-0.137,0.00%,0.000,$+0
2,Rel Threshold 25% | TLH=10%,-1.08%,-0.189,0.37%,-1.255,"$-2,991"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Fixed Income  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),-4.90%,-0.484,-16.15%,3.78%,0.292
1,Yearly Rebal | No TLH,Off,-6.04%,-0.557,-17.20%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-6.04%,-0.557,-17.20%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-4.90%,-0.484,3.78%,0.292,"$+12,061"
1,Quarterly Rebal | TLH=10%,-13.69%,-1.039,5.65%,-1.359,"$-74,837"
2,Yearly Rebal | TLH=10%,-15.22%,-1.130,6.47%,-1.436,"$-90,801"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Fixed Income  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,1.07%,0.421,-7.72%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),1.07%,0.421,-7.72%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,1.07%,0.421,-7.72%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,1.07%,0.420,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,1.07%,0.421,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,1.07%,0.421,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Fixed Income  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,1.27%,0.265,-8.41%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),1.27%,0.265,-8.41%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,1.27%,0.265,-8.41%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,1.26%,0.262,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,1.27%,0.263,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,1.27%,0.264,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Fixed Income  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,-2.13%,-0.379,-7.07%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),-2.13%,-0.379,-7.07%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-2.13%,-0.379,-7.07%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-2.13%,-0.379,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-2.13%,-0.379,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-2.13%,-0.379,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Fixed Income  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,-2.13%,-0.379,-7.07%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),-2.13%,-0.379,-7.07%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-2.13%,-0.379,-7.07%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-2.13%,-0.379,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-2.13%,-0.379,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-2.13%,-0.379,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Fixed Income  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,-2.13%,-0.379,-7.07%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),-2.13%,-0.379,-7.07%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-2.13%,-0.379,-7.07%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-2.13%,-0.379,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-2.13%,-0.379,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-2.13%,-0.379,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Moderate  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),-18.16%,-1.102,-25.76%,12.37%,0.197
1,Abs Threshold 5% | TLH=10%,On (10%),-18.39%,-1.115,-25.86%,12.43%,0.144
2,Yearly Rebal | TLH=10%,On (10%),-18.66%,-1.131,-26.32%,12.69%,0.157

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-18.16%,-1.102,12.37%,0.197,"$+25,082"
1,Yearly Rebal | TLH=10%,-18.66%,-1.131,12.69%,0.157,"$+20,661"
2,Abs Threshold 10% | TLH=10%,-18.66%,-1.131,12.69%,0.157,"$+20,661"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Moderate  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),4.78%,0.513,-15.45%,1.09%,0.379
1,Monthly Rebal | TLH=10%,On (10%),4.78%,0.511,-15.46%,0.99%,0.514
2,Abs Threshold 10% | TLH=10%,On (10%),4.84%,0.508,-15.66%,1.10%,0.364

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,4.78%,0.511,0.99%,0.514,"$+12,683"
1,Abs Threshold 5% | TLH=10%,4.70%,0.500,1.14%,0.390,"$+11,300"
2,Yearly Rebal | TLH=10%,4.80%,0.505,1.12%,0.387,"$+10,999"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Moderate  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,10.64%,1.427,-5.15%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),10.64%,1.427,-5.15%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,10.64%,1.427,-5.15%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,10.38%,1.399,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,10.61%,1.418,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,10.64%,1.427,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Moderate  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,4.00%,0.588,-8.31%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,4.00%,0.588,-8.31%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,4.00%,0.588,-8.31%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,3.46%,0.514,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,3.52%,0.523,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,3.21%,0.468,0.57%,-1.641,"$-6,975"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Moderate  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,4.00%,0.588,-8.31%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,4.00%,0.588,-8.31%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,4.00%,0.588,-8.31%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,3.46%,0.514,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,3.52%,0.523,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,3.21%,0.468,0.57%,-1.641,"$-6,975"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Moderate  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,4.00%,0.588,-8.31%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,4.00%,0.588,-8.31%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,4.00%,0.588,-8.31%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,3.46%,0.514,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,3.52%,0.523,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,3.21%,0.468,0.57%,-1.641,"$-6,975"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Moderate Growth  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),-20.43%,-1.178,-27.47%,12.07%,0.170
1,Abs Threshold 5% | TLH=10%,On (10%),-21.60%,-1.236,-28.42%,12.51%,0.063
2,Rel Threshold 25% | TLH=10%,On (10%),-21.60%,-1.236,-28.42%,12.51%,0.063

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-20.43%,-1.178,12.07%,0.170,"$+21,251"
1,Yearly Rebal | TLH=10%,-21.20%,-1.242,12.58%,0.104,"$+13,915"
2,Abs Threshold 10% | TLH=10%,-21.20%,-1.242,12.58%,0.104,"$+13,915"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Moderate Growth  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | TLH=10%,On (10%),5.84%,0.527,-17.46%,1.27%,0.399
1,Abs Threshold 20% | TLH=10%,On (10%),5.84%,0.527,-17.46%,1.27%,0.399
2,Rel Threshold 50% | TLH=10%,On (10%),5.84%,0.527,-17.46%,1.27%,0.399

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.66%,0.519,1.12%,0.531,"$+14,825"
1,Yearly Rebal | TLH=10%,5.74%,0.520,1.29%,0.428,"$+13,877"
2,Abs Threshold 5% | TLH=10%,5.73%,0.521,1.35%,0.421,"$+14,226"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Moderate Growth  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,12.02%,1.335,-5.77%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),12.02%,1.335,-5.77%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,12.02%,1.335,-5.77%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.73%,1.306,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,11.97%,1.326,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,12.02%,1.335,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Moderate Growth  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,8.28%,0.934,-9.53%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,8.28%,0.934,-9.53%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,8.28%,0.934,-9.53%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.65%,0.874,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,7.72%,0.882,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.91%,0.773,0.93%,-1.629,"$-12,059"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Moderate Growth  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,8.28%,0.934,-9.53%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,8.28%,0.934,-9.53%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,8.28%,0.934,-9.53%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.65%,0.874,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,7.72%,0.882,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.91%,0.773,0.93%,-1.629,"$-12,059"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Tax Aware - Moderate Growth  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,8.28%,0.934,-9.53%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,8.28%,0.934,-9.53%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,8.28%,0.934,-9.53%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.65%,0.874,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,7.72%,0.882,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.91%,0.773,0.93%,-1.629,"$-12,059"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Aggressive Growth  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),-42.53%,-0.894,-53.13%,10.58%,-0.014
1,Abs Threshold 10% | TLH=10%,On (10%),-42.07%,-0.900,-52.99%,10.63%,-0.059
2,Abs Threshold 5% | TLH=10%,On (10%),-42.98%,-0.904,-53.61%,10.65%,-0.068

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 20% | TLH=10%,-42.33%,-0.916,11.10%,-0.010,$-466
1,Rel Threshold 50% | TLH=10%,-42.33%,-0.916,11.10%,-0.010,$-466
2,Rel Threshold 25% | TLH=10%,-42.53%,-0.894,10.58%,-0.014,$-882

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Aggressive Growth  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),5.26%,0.451,-18.13%,1.04%,0.425
1,Abs Threshold 10% | TLH=10%,On (10%),5.24%,0.444,-18.33%,1.03%,0.155
2,Abs Threshold 20% | TLH=10%,On (10%),5.24%,0.444,-18.33%,1.03%,0.155

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.26%,0.451,1.04%,0.425,"$+11,296"
1,Abs Threshold 5% | TLH=10%,5.20%,0.441,1.04%,0.223,"$+6,556"
2,Yearly Rebal | TLH=10%,5.14%,0.437,1.06%,0.223,"$+6,642"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Aggressive Growth  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,12.04%,1.310,-6.10%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),12.04%,1.310,-6.10%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,12.04%,1.310,-6.10%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.59%,1.271,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,11.87%,1.297,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,12.04%,1.310,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Aggressive Growth  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,13.75%,1.280,-11.87%,0.00%,0.000
1,Rel Threshold 25% | TLH=10%,On (10%),13.75%,1.280,-11.87%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,13.69%,1.276,-11.93%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,13.69%,1.276,0.00%,0.000,$+0
1,Abs Threshold 5% | TLH=10%,13.65%,1.260,0.00%,0.000,$+0
2,Abs Threshold 10% | TLH=10%,13.65%,1.260,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Aggressive Growth  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,13.75%,1.280,-11.87%,0.00%,0.000
1,Rel Threshold 25% | TLH=10%,On (10%),13.75%,1.280,-11.87%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,13.69%,1.276,-11.93%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,13.69%,1.276,0.00%,0.000,$+0
1,Abs Threshold 5% | TLH=10%,13.65%,1.260,0.00%,0.000,$+0
2,Abs Threshold 10% | TLH=10%,13.65%,1.260,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Aggressive Growth  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,13.75%,1.280,-11.87%,0.00%,0.000
1,Rel Threshold 25% | TLH=10%,On (10%),13.75%,1.280,-11.87%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,13.69%,1.276,-11.93%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,13.69%,1.276,0.00%,0.000,$+0
1,Abs Threshold 5% | TLH=10%,13.65%,1.260,0.00%,0.000,$+0
2,Abs Threshold 10% | TLH=10%,13.65%,1.260,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Conservative  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,9.12%,1.118,-7.12%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),9.12%,1.118,-7.12%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,9.12%,1.118,-7.12%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.12%,1.118,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,9.12%,1.118,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,9.12%,1.118,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Conservative  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),1.51%,0.417,-8.71%,0.33%,0.498
1,Monthly Rebal | TLH=10%,On (10%),1.48%,0.409,-8.77%,0.34%,0.468
2,Yearly Rebal | TLH=10%,On (10%),1.44%,0.396,-8.87%,0.33%,0.481

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,1.51%,0.417,0.33%,0.498,"$+4,765"
1,Yearly Rebal | TLH=10%,1.44%,0.396,0.33%,0.481,"$+4,699"
2,Monthly Rebal | TLH=10%,1.48%,0.409,0.34%,0.468,"$+4,669"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Conservative  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,2.91%,0.586,-4.91%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),2.91%,0.586,-4.91%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,2.91%,0.586,-4.91%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.79%,0.565,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,2.84%,0.576,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,2.88%,0.584,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Conservative  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),4.11%,0.846,-6.31%,0.11%,0.532
1,Abs Threshold 10% | TLH=10%,On (10%),4.11%,0.846,-6.31%,0.11%,0.532
2,Abs Threshold 20% | TLH=10%,On (10%),4.11%,0.846,-6.31%,0.11%,0.532

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,4.11%,0.846,0.11%,0.532,"$+2,680"
1,Abs Threshold 10% | TLH=10%,4.11%,0.846,0.11%,0.532,"$+2,680"
2,Abs Threshold 20% | TLH=10%,4.11%,0.846,0.11%,0.532,"$+2,680"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Conservative  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),4.11%,0.846,-6.31%,0.11%,0.532
1,Abs Threshold 10% | TLH=10%,On (10%),4.11%,0.846,-6.31%,0.11%,0.532
2,Abs Threshold 20% | TLH=10%,On (10%),4.11%,0.846,-6.31%,0.11%,0.532

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,4.11%,0.846,0.11%,0.532,"$+2,680"
1,Abs Threshold 10% | TLH=10%,4.11%,0.846,0.11%,0.532,"$+2,680"
2,Abs Threshold 20% | TLH=10%,4.11%,0.846,0.11%,0.532,"$+2,680"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Conservative  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),4.11%,0.846,-6.31%,0.11%,0.532
1,Abs Threshold 10% | TLH=10%,On (10%),4.11%,0.846,-6.31%,0.11%,0.532
2,Abs Threshold 20% | TLH=10%,On (10%),4.11%,0.846,-6.31%,0.11%,0.532

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,4.11%,0.846,0.11%,0.532,"$+2,680"
1,Abs Threshold 10% | TLH=10%,4.11%,0.846,0.11%,0.532,"$+2,680"
2,Abs Threshold 20% | TLH=10%,4.11%,0.846,0.11%,0.532,"$+2,680"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Equity  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),-31.66%,-0.881,-40.89%,9.43%,0.288
1,Rel Threshold 25% | TLH=10%,On (10%),-36.13%,-0.970,-45.53%,7.76%,-0.254
2,Rel Threshold 25% | No TLH,Off,-34.24%,-0.974,-44.34%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-31.66%,-0.881,9.43%,0.288,"$+28,779"
1,Yearly Rebal | TLH=10%,-35.42%,-0.983,7.65%,-0.158,"$-11,623"
2,Abs Threshold 10% | TLH=10%,-36.08%,-0.995,7.92%,-0.212,"$-16,525"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Equity  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),6.04%,0.509,-17.87%,0.92%,0.358
1,Abs Threshold 10% | TLH=10%,On (10%),6.04%,0.507,-17.94%,0.91%,0.319
2,Abs Threshold 20% | TLH=10%,On (10%),6.04%,0.507,-17.94%,0.91%,0.319

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.90%,0.505,0.82%,0.448,"$+9,632"
1,Yearly Rebal | TLH=10%,5.97%,0.503,0.93%,0.379,"$+9,386"
2,Abs Threshold 5% | TLH=10%,6.04%,0.509,0.92%,0.358,"$+8,812"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Equity  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,12.32%,1.276,-6.66%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),12.32%,1.276,-6.66%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,12.32%,1.276,-6.66%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.98%,1.242,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,12.19%,1.264,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,12.32%,1.276,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Equity  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,13.75%,1.225,-12.00%,0.00%,0.000
1,Rel Threshold 25% | TLH=10%,On (10%),13.75%,1.225,-12.00%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,13.73%,1.222,-12.07%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,13.73%,1.222,0.00%,0.000,$+0
1,Abs Threshold 5% | TLH=10%,13.65%,1.212,0.00%,0.000,$+0
2,Abs Threshold 10% | TLH=10%,13.65%,1.212,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Equity  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,13.75%,1.225,-12.00%,0.00%,0.000
1,Rel Threshold 25% | TLH=10%,On (10%),13.75%,1.225,-12.00%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,13.73%,1.222,-12.07%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,13.73%,1.222,0.00%,0.000,$+0
1,Abs Threshold 5% | TLH=10%,13.65%,1.212,0.00%,0.000,$+0
2,Abs Threshold 10% | TLH=10%,13.65%,1.212,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Equity  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,13.75%,1.225,-12.00%,0.00%,0.000
1,Rel Threshold 25% | TLH=10%,On (10%),13.75%,1.225,-12.00%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,13.73%,1.222,-12.07%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,13.73%,1.222,0.00%,0.000,$+0
1,Abs Threshold 5% | TLH=10%,13.65%,1.212,0.00%,0.000,$+0
2,Abs Threshold 10% | TLH=10%,13.65%,1.212,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Fixed Income  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,9.12%,1.118,-7.12%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),9.12%,1.118,-7.12%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,9.12%,1.118,-7.12%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.12%,1.118,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,9.12%,1.118,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,9.12%,1.118,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Fixed Income  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),1.01%,0.301,-8.07%,0.23%,0.432
1,Monthly Rebal | TLH=10%,On (10%),0.99%,0.295,-8.08%,0.22%,0.384
2,Yearly Rebal | TLH=10%,On (10%),0.98%,0.292,-8.11%,0.22%,0.454

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,0.98%,0.292,0.22%,0.454,"$+3,737"
1,Quarterly Rebal | TLH=10%,1.01%,0.301,0.23%,0.432,"$+3,739"
2,Abs Threshold 5% | TLH=10%,0.96%,0.284,0.22%,0.421,"$+3,524"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Fixed Income  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),-0.38%,-0.076,-5.79%,0.08%,-0.199
1,Abs Threshold 5% | TLH=10%,On (10%),-0.40%,-0.079,-5.76%,0.09%,-0.110
2,Abs Threshold 10% | TLH=10%,On (10%),-0.40%,-0.079,-5.76%,0.09%,-0.110

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-0.47%,-0.093,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,-0.42%,-0.083,0.09%,-0.109,"$+1,039"
2,Abs Threshold 5% | TLH=10%,-0.40%,-0.079,0.09%,-0.110,"$+1,039"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Fixed Income  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),1.07%,0.228,-5.79%,0.10%,0.527
1,Yearly Rebal | TLH=10%,On (10%),1.06%,0.226,-5.76%,0.11%,0.551
2,Abs Threshold 5% | TLH=10%,On (10%),1.05%,0.226,-5.76%,0.11%,0.520

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,1.06%,0.226,0.11%,0.551,"$+2,856"
1,Quarterly Rebal | TLH=10%,1.07%,0.228,0.10%,0.527,"$+2,682"
2,Abs Threshold 5% | TLH=10%,1.05%,0.226,0.11%,0.520,"$+2,708"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Fixed Income  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),1.07%,0.228,-5.79%,0.10%,0.527
1,Yearly Rebal | TLH=10%,On (10%),1.06%,0.226,-5.76%,0.11%,0.551
2,Abs Threshold 5% | TLH=10%,On (10%),1.05%,0.226,-5.76%,0.11%,0.520

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,1.06%,0.226,0.11%,0.551,"$+2,856"
1,Quarterly Rebal | TLH=10%,1.07%,0.228,0.10%,0.527,"$+2,682"
2,Abs Threshold 5% | TLH=10%,1.05%,0.226,0.11%,0.520,"$+2,708"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Fixed Income  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),1.07%,0.228,-5.79%,0.10%,0.527
1,Yearly Rebal | TLH=10%,On (10%),1.06%,0.226,-5.76%,0.11%,0.551
2,Abs Threshold 5% | TLH=10%,On (10%),1.05%,0.226,-5.76%,0.11%,0.520

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,1.06%,0.226,0.11%,0.551,"$+2,856"
1,Quarterly Rebal | TLH=10%,1.07%,0.228,0.10%,0.527,"$+2,682"
2,Abs Threshold 5% | TLH=10%,1.05%,0.226,0.11%,0.520,"$+2,708"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Moderate  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | TLH=10%,On (10%),-17.93%,-0.791,-28.63%,5.72%,-0.089
1,Rel Threshold 25% | TLH=10%,On (10%),-22.04%,-0.837,-32.37%,5.96%,-0.026
2,Abs Threshold 20% | No TLH,Off,-17.52%,-0.854,-28.47%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,-20.46%,-0.939,5.35%,0.168,"$+10,256"
1,Rel Threshold 25% | TLH=10%,-22.04%,-0.837,5.96%,-0.026,$-664
2,Abs Threshold 20% | TLH=10%,-17.93%,-0.791,5.72%,-0.089,"$-4,304"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Moderate  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),2.88%,0.412,-14.09%,0.72%,0.500
1,Quarterly Rebal | TLH=10%,On (10%),2.79%,0.396,-14.13%,0.72%,0.308
2,Yearly Rebal | TLH=10%,On (10%),2.71%,0.381,-14.40%,0.72%,0.272

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.88%,0.412,0.72%,0.500,"$+9,137"
1,Quarterly Rebal | TLH=10%,2.79%,0.396,0.72%,0.308,"$+6,162"
2,Yearly Rebal | TLH=10%,2.71%,0.381,0.72%,0.272,"$+5,555"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Moderate  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,6.30%,1.030,-4.82%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),6.30%,1.030,-4.82%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,6.30%,1.030,-4.82%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.88%,0.981,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,6.01%,1.002,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.16%,1.016,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Moderate  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),7.65%,1.161,-8.14%,0.10%,0.520
1,Yearly Rebal | TLH=10%,On (10%),7.66%,1.155,-8.10%,0.10%,0.440
2,Abs Threshold 5% | TLH=10%,On (10%),7.87%,1.153,-8.40%,0.11%,0.519

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,7.65%,1.161,0.10%,0.520,"$+2,743"
1,Abs Threshold 5% | TLH=10%,7.87%,1.153,0.11%,0.519,"$+2,790"
2,Abs Threshold 10% | TLH=10%,7.87%,1.153,0.11%,0.519,"$+2,790"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Moderate  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),7.65%,1.161,-8.14%,0.10%,0.520
1,Yearly Rebal | TLH=10%,On (10%),7.66%,1.155,-8.10%,0.10%,0.440
2,Abs Threshold 5% | TLH=10%,On (10%),7.87%,1.153,-8.40%,0.11%,0.519

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,7.65%,1.161,0.10%,0.520,"$+2,743"
1,Abs Threshold 5% | TLH=10%,7.87%,1.153,0.11%,0.519,"$+2,790"
2,Abs Threshold 10% | TLH=10%,7.87%,1.153,0.11%,0.519,"$+2,790"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Moderate  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),7.65%,1.161,-8.14%,0.10%,0.520
1,Yearly Rebal | TLH=10%,On (10%),7.66%,1.155,-8.10%,0.10%,0.440
2,Abs Threshold 5% | TLH=10%,On (10%),7.87%,1.153,-8.40%,0.11%,0.519

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,7.65%,1.161,0.10%,0.520,"$+2,743"
1,Abs Threshold 5% | TLH=10%,7.87%,1.153,0.11%,0.519,"$+2,790"
2,Abs Threshold 10% | TLH=10%,7.87%,1.153,0.11%,0.519,"$+2,790"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Moderate Growth  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),-43.78%,-0.856,-55.69%,7.98%,0.078
1,Abs Threshold 10% | TLH=10%,On (10%),-45.02%,-0.861,-56.00%,9.21%,0.077
2,Monthly Rebal | TLH=10%,On (10%),-45.49%,-0.884,-57.25%,9.52%,-0.008

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 20% | TLH=10%,-44.99%,-0.897,9.71%,0.079,"$+8,431"
1,Rel Threshold 50% | TLH=10%,-44.99%,-0.897,9.71%,0.079,"$+8,431"
2,Abs Threshold 5% | TLH=10%,-43.78%,-0.856,7.98%,0.078,"$+7,036"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Moderate Growth  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | TLH=10%,On (10%),4.71%,0.452,-17.50%,0.91%,0.333
1,Rel Threshold 25% | TLH=10%,On (10%),4.62%,0.449,-17.28%,0.97%,0.432
2,Monthly Rebal | TLH=10%,On (10%),4.56%,0.446,-17.36%,0.92%,0.420

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,4.62%,0.449,0.97%,0.432,"$+10,669"
1,Monthly Rebal | TLH=10%,4.56%,0.446,0.92%,0.420,"$+9,967"
2,Abs Threshold 5% | TLH=10%,4.61%,0.445,0.92%,0.405,"$+9,604"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Moderate Growth  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,9.01%,1.227,-4.98%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),9.01%,1.227,-4.98%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,9.01%,1.227,-4.98%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.47%,1.177,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,8.63%,1.199,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,8.82%,1.211,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Moderate Growth  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),10.31%,1.230,-9.83%,0.10%,0.476
1,Yearly Rebal | TLH=10%,On (10%),10.29%,1.223,-9.77%,0.09%,0.382
2,Rel Threshold 25% | No TLH,Off,10.21%,1.220,-9.81%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,10.50%,1.213,0.10%,0.479,"$+2,706"
1,Abs Threshold 10% | TLH=10%,10.50%,1.213,0.10%,0.479,"$+2,706"
2,Abs Threshold 20% | TLH=10%,10.50%,1.213,0.10%,0.479,"$+2,706"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Moderate Growth  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),10.31%,1.230,-9.83%,0.10%,0.476
1,Yearly Rebal | TLH=10%,On (10%),10.29%,1.223,-9.77%,0.09%,0.382
2,Rel Threshold 25% | No TLH,Off,10.21%,1.220,-9.81%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,10.50%,1.213,0.10%,0.479,"$+2,706"
1,Abs Threshold 10% | TLH=10%,10.50%,1.213,0.10%,0.479,"$+2,706"
2,Abs Threshold 20% | TLH=10%,10.50%,1.213,0.10%,0.479,"$+2,706"

──────────────────────────────────────────────────────────────────────────────────────────
  MAI Taxable - Moderate Growth  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),10.31%,1.230,-9.83%,0.10%,0.476
1,Yearly Rebal | TLH=10%,On (10%),10.29%,1.223,-9.77%,0.09%,0.382
2,Rel Threshold 25% | No TLH,Off,10.21%,1.220,-9.81%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,10.50%,1.213,0.10%,0.479,"$+2,706"
1,Abs Threshold 10% | TLH=10%,10.50%,1.213,0.10%,0.479,"$+2,706"
2,Abs Threshold 20% | TLH=10%,10.50%,1.213,0.10%,0.479,"$+2,706"

──────────────────────────────────────────────────────────────────────────────────────────
  RFP Equity - Equity  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,-26.73%,-0.782,-54.65%,0.00%,0.000
1,Rel Threshold 50% | No TLH,Off,-26.58%,-0.783,-54.49%,0.00%,0.000
2,Rel Threshold 25% | No TLH,Off,-26.84%,-0.786,-54.75%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-26.71%,-0.802,2.93%,0.081,"$+3,933"
1,Abs Threshold 10% | TLH=10%,-26.71%,-0.802,2.93%,0.081,"$+3,933"
2,Abs Threshold 20% | TLH=10%,-26.71%,-0.802,2.93%,0.081,"$+3,933"

──────────────────────────────────────────────────────────────────────────────────────────
  RFP Equity - Equity  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),10.51%,0.832,-20.83%,0.92%,0.302
1,Yearly Rebal | TLH=10%,On (10%),10.44%,0.826,-20.87%,0.90%,0.309
2,Quarterly Rebal | TLH=10%,On (10%),10.41%,0.826,-20.66%,0.89%,0.340

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,10.41%,0.826,0.89%,0.340,"$+18,311"
1,Yearly Rebal | TLH=10%,10.44%,0.826,0.90%,0.309,"$+16,947"
2,Rel Threshold 25% | TLH=10%,10.51%,0.832,0.92%,0.302,"$+17,005"

──────────────────────────────────────────────────────────────────────────────────────────
  RFP Equity - Equity  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,17.01%,1.321,-11.59%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,17.01%,1.321,-11.59%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,17.01%,1.321,-11.59%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,16.04%,1.251,0.18%,-0.723,"$-1,311"
1,Yearly Rebal | TLH=10%,16.50%,1.286,0.14%,-0.774,$-904
2,Quarterly Rebal | TLH=10%,16.24%,1.267,0.17%,-0.775,"$-1,380"

──────────────────────────────────────────────────────────────────────────────────────────
  RFP Equity - Equity  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | TLH=10%,On (10%),15.91%,1.085,-17.91%,0.14%,-0.320
1,Abs Threshold 20% | TLH=10%,On (10%),15.91%,1.085,-17.91%,0.14%,-0.320
2,Rel Threshold 50% | TLH=10%,On (10%),15.91%,1.085,-17.91%,0.14%,-0.320

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,15.48%,1.066,0.15%,-0.173,$+794
1,Rel Threshold 25% | TLH=10%,15.63%,1.075,0.15%,-0.175,$+821
2,Monthly Rebal | TLH=10%,15.33%,1.055,0.16%,-0.261,$+145

──────────────────────────────────────────────────────────────────────────────────────────
  RFP Equity - Equity  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | TLH=10%,On (10%),15.91%,1.085,-17.91%,0.14%,-0.320
1,Abs Threshold 20% | TLH=10%,On (10%),15.91%,1.085,-17.91%,0.14%,-0.320
2,Rel Threshold 50% | TLH=10%,On (10%),15.91%,1.085,-17.91%,0.14%,-0.320

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,15.48%,1.066,0.15%,-0.173,$+794
1,Rel Threshold 25% | TLH=10%,15.63%,1.075,0.15%,-0.175,$+821
2,Monthly Rebal | TLH=10%,15.33%,1.055,0.16%,-0.261,$+145

──────────────────────────────────────────────────────────────────────────────────────────
  RFP Equity - Equity  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | TLH=10%,On (10%),15.91%,1.085,-17.91%,0.14%,-0.320
1,Abs Threshold 20% | TLH=10%,On (10%),15.91%,1.085,-17.91%,0.14%,-0.320
2,Rel Threshold 50% | TLH=10%,On (10%),15.91%,1.085,-17.91%,0.14%,-0.320

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,15.48%,1.066,0.15%,-0.173,$+794
1,Rel Threshold 25% | TLH=10%,15.63%,1.075,0.15%,-0.175,$+821
2,Monthly Rebal | TLH=10%,15.33%,1.055,0.16%,-0.261,$+145

──────────────────────────────────────────────────────────────────────────────────────────
  RFP Muni - Fixed Income  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,8.89%,3.742,-0.40%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),8.89%,3.742,-0.40%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,8.89%,3.742,-0.40%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.89%,3.742,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,8.89%,3.742,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,8.89%,3.742,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  RFP Muni - Fixed Income  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,0.17%,0.085,-3.69%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),0.17%,0.085,-3.69%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,0.17%,0.085,-3.69%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.17%,0.085,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.17%,0.085,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,0.17%,0.085,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  RFP Muni - Fixed Income  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-0.53%,-0.265,-1.55%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-0.53%,-0.265,-1.55%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,-0.54%,-0.266,-1.55%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-0.54%,-0.266,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-0.53%,-0.265,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-0.54%,-0.267,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  RFP Muni - Fixed Income  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,0.29%,0.139,-2.73%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),0.29%,0.139,-2.73%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,0.29%,0.138,-2.73%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.29%,0.138,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.29%,0.139,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,0.29%,0.137,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  RFP Muni - Fixed Income  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,0.29%,0.139,-2.73%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),0.29%,0.139,-2.73%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,0.29%,0.138,-2.73%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.29%,0.138,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.29%,0.139,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,0.29%,0.137,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  RFP Muni - Fixed Income  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,0.29%,0.139,-2.73%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),0.29%,0.139,-2.73%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,0.29%,0.138,-2.73%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.29%,0.138,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.29%,0.139,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,0.29%,0.137,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  RFP Taxable - Fixed Income  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,0.08%,0.071,-1.44%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),0.08%,0.071,-1.44%,0.00%,0.000
2,Quarterly Rebal | No TLH,Off,0.08%,0.070,-1.44%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.08%,0.070,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.08%,0.070,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,0.08%,0.071,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  RFP Taxable - Fixed Income  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-1.97%,-0.513,-4.30%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-1.97%,-0.513,-4.30%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,-1.97%,-0.514,-4.30%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-1.97%,-0.514,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-1.97%,-0.513,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-1.98%,-0.518,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  RFP Taxable - Fixed Income  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,0.15%,0.042,-4.89%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),0.15%,0.042,-4.89%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,0.15%,0.041,-4.88%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.15%,0.041,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.15%,0.042,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,0.14%,0.040,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  RFP Taxable - Fixed Income  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,0.15%,0.042,-4.89%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),0.15%,0.042,-4.89%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,0.15%,0.041,-4.88%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.15%,0.041,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.15%,0.042,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,0.14%,0.040,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  RFP Taxable - Fixed Income  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,0.15%,0.042,-4.89%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),0.15%,0.042,-4.89%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,0.15%,0.041,-4.88%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.15%,0.041,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.15%,0.042,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,0.14%,0.040,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 20-80  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 20% | No TLH,Off,-2.36%,-0.218,-20.46%,0.00%,0.000
1,Yearly Rebal | No TLH,Off,-2.64%,-0.242,-20.66%,0.00%,0.000
2,Abs Threshold 20% | TLH=10%,On (10%),-2.66%,-0.249,-20.68%,0.50%,-0.846

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-5.14%,-0.420,0.60%,0.235,"$+2,582"
1,Quarterly Rebal | TLH=10%,-4.95%,-0.419,0.43%,-0.668,"$-1,830"
2,Abs Threshold 5% | TLH=10%,-5.36%,-0.428,0.58%,-0.673,"$-2,898"

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 20-80  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,7.00%,1.534,-1.45%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),7.00%,1.534,-1.45%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,6.59%,1.435,-1.43%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,6.56%,1.421,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,7.00%,1.534,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.59%,1.435,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 20-80  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),-10.00%,-1.244,-4.18%,0.13%,-2.400
1,Yearly Rebal | TLH=10%,On (10%),-10.00%,-1.244,-4.18%,0.13%,-2.400
2,Abs Threshold 5% | TLH=10%,On (10%),-10.00%,-1.244,-4.18%,0.13%,-2.400

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-10.33%,-1.300,0.16%,-1.533,$+660
1,Rel Threshold 25% | TLH=10%,-10.46%,-1.314,0.13%,-2.381,$+535
2,Quarterly Rebal | TLH=10%,-10.00%,-1.244,0.13%,-2.400,$+536

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 20-80  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,7.42%,0.952,-8.46%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),7.18%,0.925,-8.48%,0.37%,-0.969
2,Abs Threshold 5% | No TLH,Off,7.19%,0.911,-8.69%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,6.83%,0.876,0.52%,-0.089,$+744
1,Rel Threshold 25% | TLH=10%,6.69%,0.865,0.49%,-0.197,$+148
2,Quarterly Rebal | TLH=10%,6.62%,0.856,0.27%,-0.877,"$-1,544"

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 20-80  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,7.42%,0.952,-8.46%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),7.18%,0.925,-8.48%,0.37%,-0.969
2,Abs Threshold 5% | No TLH,Off,7.19%,0.911,-8.69%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,6.83%,0.876,0.52%,-0.089,$+744
1,Rel Threshold 25% | TLH=10%,6.69%,0.865,0.49%,-0.197,$+148
2,Quarterly Rebal | TLH=10%,6.62%,0.856,0.27%,-0.877,"$-1,544"

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 20-80  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,7.42%,0.952,-8.46%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),7.18%,0.925,-8.48%,0.37%,-0.969
2,Abs Threshold 5% | No TLH,Off,7.19%,0.911,-8.69%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,6.83%,0.876,0.52%,-0.089,$+744
1,Rel Threshold 25% | TLH=10%,6.69%,0.865,0.49%,-0.197,$+148
2,Quarterly Rebal | TLH=10%,6.62%,0.856,0.27%,-0.877,"$-1,544"

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 40-60  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | TLH=10%,On (10%),-12.52%,-0.692,-26.97%,1.25%,0.023
1,Abs Threshold 10% | No TLH,Off,-12.65%,-0.712,-26.69%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,-10.73%,-0.719,-25.31%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-12.74%,-0.736,1.35%,0.924,"$+13,887"
1,Abs Threshold 5% | TLH=10%,-13.09%,-0.756,2.26%,0.270,"$+7,276"
2,Abs Threshold 10% | TLH=10%,-12.52%,-0.692,1.25%,0.023,"$+1,336"

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 40-60  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,13.84%,2.592,-2.13%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),13.84%,2.592,-2.13%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,13.43%,2.525,-2.12%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,13.35%,2.496,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,13.84%,2.592,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,13.43%,2.525,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 40-60  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),-8.24%,-0.881,-4.30%,0.12%,-2.808
1,Yearly Rebal | TLH=10%,On (10%),-8.24%,-0.881,-4.30%,0.12%,-2.808
2,Abs Threshold 5% | TLH=10%,On (10%),-8.24%,-0.881,-4.30%,0.12%,-2.808

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-8.62%,-0.931,0.15%,-1.858,$+612
1,Rel Threshold 25% | TLH=10%,-8.73%,-0.942,0.12%,-2.785,$+497
2,Quarterly Rebal | TLH=10%,-8.24%,-0.881,0.12%,-2.808,$+498

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 40-60  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,11.37%,1.026,-11.71%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,11.14%,0.991,-11.99%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,11.14%,0.991,-11.99%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,10.48%,0.948,0.45%,-0.243,$+24
1,Quarterly Rebal | TLH=10%,10.71%,0.973,0.56%,-0.359,"$-1,069"
2,Rel Threshold 50% | TLH=10%,10.28%,0.931,0.70%,-0.731,"$-4,768"

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 40-60  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,11.37%,1.026,-11.71%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,11.14%,0.991,-11.99%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,11.14%,0.991,-11.99%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,10.48%,0.948,0.45%,-0.243,$+24
1,Quarterly Rebal | TLH=10%,10.71%,0.973,0.56%,-0.359,"$-1,069"
2,Rel Threshold 50% | TLH=10%,10.28%,0.931,0.70%,-0.731,"$-4,768"

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 40-60  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,11.37%,1.026,-11.71%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,11.14%,0.991,-11.99%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,11.14%,0.991,-11.99%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,10.48%,0.948,0.45%,-0.243,$+24
1,Quarterly Rebal | TLH=10%,10.71%,0.973,0.56%,-0.359,"$-1,069"
2,Rel Threshold 50% | TLH=10%,10.28%,0.931,0.70%,-0.731,"$-4,768"

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 60-40  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,-19.64%,-0.840,-32.88%,0.00%,0.000
1,Rel Threshold 25% | No TLH,Off,-19.98%,-0.845,-33.18%,0.00%,0.000
2,Rel Threshold 25% | TLH=10%,On (10%),-20.07%,-0.878,-33.75%,2.04%,-0.091

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-20.33%,-0.903,1.99%,0.336,"$+7,797"
1,Rel Threshold 25% | TLH=10%,-20.07%,-0.878,2.04%,-0.091,$-952
2,Quarterly Rebal | TLH=10%,-20.54%,-0.906,1.55%,-0.142,"$-1,310"

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 60-40  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,17.55%,2.873,-2.49%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),17.55%,2.873,-2.49%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,17.17%,2.831,-2.48%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,17.11%,2.807,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,17.55%,2.873,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,17.17%,2.831,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 60-40  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),-6.57%,-0.606,-4.44%,0.11%,-3.439
1,Yearly Rebal | TLH=10%,On (10%),-6.57%,-0.606,-4.44%,0.11%,-3.439
2,Abs Threshold 5% | TLH=10%,On (10%),-6.57%,-0.606,-4.44%,0.11%,-3.439

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-6.99%,-0.649,0.13%,-2.358,$+549
1,Rel Threshold 25% | TLH=10%,-7.05%,-0.655,0.11%,-3.410,$+447
2,Quarterly Rebal | TLH=10%,-6.57%,-0.606,0.11%,-3.439,$+447

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 60-40  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,14.46%,1.057,-13.86%,0.00%,0.000
1,Rel Threshold 25% | No TLH,Off,14.39%,1.033,-13.97%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,14.24%,1.025,-14.19%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,13.58%,0.991,0.54%,-0.265,$-319
1,Quarterly Rebal | TLH=10%,13.70%,1.009,0.77%,-0.519,"$-3,436"
2,Rel Threshold 50% | TLH=10%,13.16%,0.964,0.82%,-0.928,"$-7,820"

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 60-40  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,14.46%,1.057,-13.86%,0.00%,0.000
1,Rel Threshold 25% | No TLH,Off,14.39%,1.033,-13.97%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,14.24%,1.025,-14.19%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,13.58%,0.991,0.54%,-0.265,$-319
1,Quarterly Rebal | TLH=10%,13.70%,1.009,0.77%,-0.519,"$-3,436"
2,Rel Threshold 50% | TLH=10%,13.16%,0.964,0.82%,-0.928,"$-7,820"

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 60-40  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,14.46%,1.057,-13.86%,0.00%,0.000
1,Rel Threshold 25% | No TLH,Off,14.39%,1.033,-13.97%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,14.24%,1.025,-14.19%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,13.58%,0.991,0.54%,-0.265,$-319
1,Quarterly Rebal | TLH=10%,13.70%,1.009,0.77%,-0.519,"$-3,436"
2,Rel Threshold 50% | TLH=10%,13.16%,0.964,0.82%,-0.928,"$-7,820"

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 80-20  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | TLH=10%,On (10%),-15.53%,-0.603,-45.13%,1.70%,0.272
1,Abs Threshold 10% | TLH=10%,On (10%),-14.80%,-0.607,-43.49%,1.68%,0.344
2,Abs Threshold 20% | TLH=10%,On (10%),-14.80%,-0.607,-43.49%,1.68%,0.344

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,-15.22%,-0.613,1.69%,0.393,"$+11,956"
1,Abs Threshold 5% | TLH=10%,-15.49%,-0.613,1.55%,0.362,"$+10,191"
2,Abs Threshold 10% | TLH=10%,-14.80%,-0.607,1.68%,0.344,"$+10,605"

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 80-20  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,23.74%,3.100,-3.38%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),23.74%,3.100,-3.38%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,23.59%,3.090,-3.38%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,23.56%,3.085,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,23.74%,3.100,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,23.59%,3.090,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 80-20  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),-5.19%,-0.428,-4.33%,0.10%,-4.004
1,Yearly Rebal | TLH=10%,On (10%),-5.19%,-0.428,-4.33%,0.10%,-4.004
2,Abs Threshold 5% | TLH=10%,On (10%),-5.19%,-0.428,-4.33%,0.10%,-4.004

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-5.62%,-0.466,0.12%,-2.808,$+504
1,Rel Threshold 25% | TLH=10%,-5.64%,-0.468,0.10%,-3.972,$+411
2,Quarterly Rebal | TLH=10%,-5.19%,-0.428,0.10%,-4.004,$+411

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 80-20  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,17.66%,1.104,-16.16%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),17.29%,1.074,-16.35%,0.93%,-0.526
2,Abs Threshold 5% | No TLH,Off,17.37%,1.073,-16.42%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,17.08%,1.052,1.03%,-0.153,$-479
1,Abs Threshold 5% | TLH=10%,16.99%,1.046,0.96%,-0.513,"$-4,553"
2,Abs Threshold 10% | TLH=10%,16.99%,1.046,0.96%,-0.513,"$-4,553"

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 80-20  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,17.66%,1.104,-16.16%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),17.29%,1.074,-16.35%,0.93%,-0.526
2,Abs Threshold 5% | No TLH,Off,17.37%,1.073,-16.42%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,17.08%,1.052,1.03%,-0.153,$-479
1,Abs Threshold 5% | TLH=10%,16.99%,1.046,0.96%,-0.513,"$-4,553"
2,Abs Threshold 10% | TLH=10%,16.99%,1.046,0.96%,-0.513,"$-4,553"

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - 80-20  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,17.66%,1.104,-16.16%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),17.29%,1.074,-16.35%,0.93%,-0.526
2,Abs Threshold 5% | No TLH,Off,17.37%,1.073,-16.42%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,17.08%,1.052,1.03%,-0.153,$-479
1,Abs Threshold 5% | TLH=10%,16.99%,1.046,0.96%,-0.513,"$-4,553"
2,Abs Threshold 10% | TLH=10%,16.99%,1.046,0.96%,-0.513,"$-4,553"

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - Equity  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),-17.73%,-0.613,-49.03%,1.74%,0.378
1,Abs Threshold 5% | No TLH,Off,-18.43%,-0.646,-49.49%,0.00%,0.000
2,Abs Threshold 10% | TLH=10%,On (10%),-18.32%,-0.648,-49.13%,1.76%,0.046

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-18.32%,-0.649,1.37%,0.478,"$+11,396"
1,Abs Threshold 5% | TLH=10%,-17.73%,-0.613,1.74%,0.378,"$+11,555"
2,Yearly Rebal | TLH=10%,-18.71%,-0.651,1.75%,0.100,"$+3,621"

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - Equity  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,26.28%,3.116,-3.72%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),26.28%,3.116,-3.72%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,26.25%,3.115,-3.72%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,26.25%,3.115,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,26.28%,3.116,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,26.25%,3.114,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - Equity  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-3.30%,-0.260,-4.18%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-3.30%,-0.260,-4.18%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-3.30%,-0.260,-4.18%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-3.74%,-0.296,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-3.30%,-0.260,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-3.30%,-0.260,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - Equity  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,18.14%,1.077,-17.01%,0.00%,0.000
1,Quarterly Rebal | No TLH,Off,18.00%,1.058,-17.09%,0.00%,0.000
2,Rel Threshold 25% | No TLH,Off,18.01%,1.056,-17.14%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,17.35%,1.028,0.64%,-0.699,"$-3,970"
1,Quarterly Rebal | TLH=10%,17.33%,1.036,0.92%,-0.855,"$-8,123"
2,Rel Threshold 25% | TLH=10%,17.18%,1.026,0.97%,-0.978,"$-10,145"

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - Equity  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,18.14%,1.077,-17.01%,0.00%,0.000
1,Quarterly Rebal | No TLH,Off,18.00%,1.058,-17.09%,0.00%,0.000
2,Rel Threshold 25% | No TLH,Off,18.01%,1.056,-17.14%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,17.35%,1.028,0.64%,-0.699,"$-3,970"
1,Quarterly Rebal | TLH=10%,17.33%,1.036,0.92%,-0.855,"$-8,123"
2,Rel Threshold 25% | TLH=10%,17.18%,1.026,0.97%,-0.978,"$-10,145"

──────────────────────────────────────────────────────────────────────────────────────────
  TA MM w Alts - Equity  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,18.14%,1.077,-17.01%,0.00%,0.000
1,Quarterly Rebal | No TLH,Off,18.00%,1.058,-17.09%,0.00%,0.000
2,Rel Threshold 25% | No TLH,Off,18.01%,1.056,-17.14%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,17.35%,1.028,0.64%,-0.699,"$-3,970"
1,Quarterly Rebal | TLH=10%,17.33%,1.036,0.92%,-0.855,"$-8,123"
2,Rel Threshold 25% | TLH=10%,17.18%,1.026,0.97%,-0.978,"$-10,145"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 0-100  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,1.83%,0.210,-12.39%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,1.83%,0.210,-12.39%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,1.83%,0.210,-12.39%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,1.66%,0.189,0.00%,0.000,$+0
1,Abs Threshold 5% | TLH=10%,-3.54%,-0.297,8.42%,-0.649,"$-65,500"
2,Abs Threshold 10% | TLH=10%,-3.54%,-0.297,8.42%,-0.649,"$-65,500"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 0-100  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,3.92%,1.353,-2.52%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),3.92%,1.353,-2.52%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,3.96%,1.353,-2.52%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,3.91%,1.350,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,3.92%,1.353,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,3.93%,1.350,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 0-100  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,0.12%,0.024,-8.16%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,0.12%,0.024,-8.16%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,0.12%,0.024,-8.16%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-0.01%,-0.001,0.39%,-0.312,"$-1,230"
1,Quarterly Rebal | TLH=10%,-0.01%,-0.002,0.40%,-0.361,"$-1,658"
2,Rel Threshold 25% | TLH=10%,-0.02%,-0.004,0.38%,-0.402,"$-1,837"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 0-100  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,1.05%,0.228,-4.67%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),1.05%,0.228,-4.67%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,1.05%,0.228,-4.67%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.83%,0.180,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.86%,0.187,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,1.05%,0.228,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 0-100  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,1.05%,0.228,-4.67%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),1.05%,0.228,-4.67%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,1.05%,0.228,-4.67%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.83%,0.180,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.86%,0.187,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,1.05%,0.228,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 0-100  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,1.05%,0.228,-4.67%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),1.05%,0.228,-4.67%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,1.05%,0.228,-4.67%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.83%,0.180,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.86%,0.187,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,1.05%,0.228,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 10-90  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,-0.92%,-0.111,-13.69%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,-0.92%,-0.111,-13.69%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,-0.92%,-0.111,-13.69%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,-1.01%,-0.118,0.53%,0.243,"$+2,763"
1,Rel Threshold 25% | TLH=10%,-6.20%,-0.555,7.74%,-0.616,"$-56,609"
2,Abs Threshold 5% | TLH=10%,-5.55%,-0.502,7.67%,-0.616,"$-56,159"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 10-90  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),6.03%,2.439,-1.52%,0.10%,-0.179
1,Yearly Rebal | TLH=10%,On (10%),6.02%,2.409,-1.53%,0.09%,-0.217
2,Abs Threshold 5% | TLH=10%,On (10%),6.02%,2.409,-1.53%,0.09%,-0.217

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.87%,2.371,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,6.03%,2.439,0.10%,-0.179,"$+1,123"
2,Yearly Rebal | TLH=10%,6.02%,2.409,0.09%,-0.217,"$+1,098"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 10-90  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,3.63%,0.698,-7.08%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,3.63%,0.698,-7.08%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,3.63%,0.698,-7.08%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.82%,0.524,0.41%,-0.009,"$+1,191"
1,Rel Threshold 25% | TLH=10%,3.00%,0.561,0.41%,-0.031,"$+1,010"
2,Quarterly Rebal | TLH=10%,2.89%,0.538,0.41%,-0.082,$+578

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 10-90  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),3.42%,0.695,-5.73%,0.18%,0.594
1,Abs Threshold 5% | TLH=10%,On (10%),3.42%,0.695,-5.73%,0.18%,0.594
2,Abs Threshold 10% | TLH=10%,On (10%),3.42%,0.695,-5.73%,0.18%,0.594

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,3.42%,0.695,0.18%,0.594,"$+2,204"
1,Abs Threshold 5% | TLH=10%,3.42%,0.695,0.18%,0.594,"$+2,204"
2,Abs Threshold 10% | TLH=10%,3.42%,0.695,0.18%,0.594,"$+2,204"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 10-90  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),3.42%,0.695,-5.73%,0.18%,0.594
1,Abs Threshold 5% | TLH=10%,On (10%),3.42%,0.695,-5.73%,0.18%,0.594
2,Abs Threshold 10% | TLH=10%,On (10%),3.42%,0.695,-5.73%,0.18%,0.594

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,3.42%,0.695,0.18%,0.594,"$+2,204"
1,Abs Threshold 5% | TLH=10%,3.42%,0.695,0.18%,0.594,"$+2,204"
2,Abs Threshold 10% | TLH=10%,3.42%,0.695,0.18%,0.594,"$+2,204"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 10-90  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),3.42%,0.695,-5.73%,0.18%,0.594
1,Abs Threshold 5% | TLH=10%,On (10%),3.42%,0.695,-5.73%,0.18%,0.594
2,Abs Threshold 10% | TLH=10%,On (10%),3.42%,0.695,-5.73%,0.18%,0.594

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,3.42%,0.695,0.18%,0.594,"$+2,204"
1,Abs Threshold 5% | TLH=10%,3.42%,0.695,0.18%,0.594,"$+2,204"
2,Abs Threshold 10% | TLH=10%,3.42%,0.695,0.18%,0.594,"$+2,204"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 100-0  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),-15.71%,-0.548,-44.96%,6.53%,1.001
1,Abs Threshold 10% | TLH=10%,On (10%),-15.71%,-0.548,-44.96%,6.53%,1.001
2,Abs Threshold 20% | TLH=10%,On (10%),-15.71%,-0.548,-44.96%,6.53%,1.001

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-15.71%,-0.548,6.53%,1.001,"$+99,901"
1,Abs Threshold 10% | TLH=10%,-15.71%,-0.548,6.53%,1.001,"$+99,901"
2,Abs Threshold 20% | TLH=10%,-15.71%,-0.548,6.53%,1.001,"$+99,901"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 100-0  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),14.41%,1.225,-6.27%,0.34%,0.875
1,Abs Threshold 5% | TLH=10%,On (10%),14.41%,1.225,-6.27%,0.34%,0.875
2,Abs Threshold 10% | TLH=10%,On (10%),14.41%,1.225,-6.27%,0.34%,0.875

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,14.37%,1.222,0.35%,0.957,"$+3,903"
1,Yearly Rebal | TLH=10%,14.41%,1.225,0.34%,0.875,"$+3,575"
2,Abs Threshold 5% | TLH=10%,14.41%,1.225,0.34%,0.875,"$+3,575"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 100-0  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-6.53%,-0.532,-4.29%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-6.53%,-0.532,-4.29%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-6.53%,-0.532,-4.29%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-6.70%,-0.546,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-6.53%,-0.532,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-6.53%,-0.532,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 100-0  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,15.77%,0.935,-17.38%,0.00%,0.000
1,Quarterly Rebal | No TLH,Off,15.75%,0.928,-17.40%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,15.69%,0.924,-17.54%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,15.30%,0.888,0.85%,-0.609,"$-4,847"
1,Abs Threshold 10% | TLH=10%,15.30%,0.888,0.85%,-0.609,"$-4,847"
2,Abs Threshold 20% | TLH=10%,15.30%,0.888,0.85%,-0.609,"$-4,847"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 100-0  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,15.77%,0.935,-17.38%,0.00%,0.000
1,Quarterly Rebal | No TLH,Off,15.75%,0.928,-17.40%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,15.69%,0.924,-17.54%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,15.30%,0.888,0.85%,-0.609,"$-4,847"
1,Abs Threshold 10% | TLH=10%,15.30%,0.888,0.85%,-0.609,"$-4,847"
2,Abs Threshold 20% | TLH=10%,15.30%,0.888,0.85%,-0.609,"$-4,847"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 100-0  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,15.77%,0.935,-17.38%,0.00%,0.000
1,Quarterly Rebal | No TLH,Off,15.75%,0.928,-17.40%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,15.69%,0.924,-17.54%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,15.30%,0.888,0.85%,-0.609,"$-4,847"
1,Abs Threshold 10% | TLH=10%,15.30%,0.888,0.85%,-0.609,"$-4,847"
2,Abs Threshold 20% | TLH=10%,15.30%,0.888,0.85%,-0.609,"$-4,847"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 20-80  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,-4.29%,-0.491,-15.61%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,-4.29%,-0.491,-15.61%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,-4.29%,-0.491,-15.61%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,-8.90%,-0.794,6.91%,-0.539,"$-43,629"
1,Abs Threshold 5% | TLH=10%,-8.42%,-0.768,7.14%,-0.592,"$-49,806"
2,Abs Threshold 10% | TLH=10%,-8.42%,-0.768,7.14%,-0.592,"$-49,806"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 20-80  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),6.99%,2.567,-1.18%,0.17%,0.584
1,Yearly Rebal | TLH=10%,On (10%),6.93%,2.528,-1.18%,0.14%,0.393
2,Abs Threshold 5% | TLH=10%,On (10%),6.93%,2.528,-1.18%,0.14%,0.393

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,6.99%,2.567,0.17%,0.584,"$+2,019"
1,Yearly Rebal | TLH=10%,6.93%,2.528,0.14%,0.393,"$+1,685"
2,Abs Threshold 5% | TLH=10%,6.93%,2.528,0.14%,0.393,"$+1,685"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 20-80  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,6.28%,1.097,-7.38%,0.00%,0.000
1,Abs Threshold 20% | No TLH,Off,6.28%,1.097,-7.38%,0.00%,0.000
2,Abs Threshold 10% | TLH=10%,On (10%),6.20%,1.061,-7.50%,0.30%,-0.474

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,5.56%,0.972,0.35%,0.048,"$+1,690"
1,Monthly Rebal | TLH=10%,5.00%,0.885,0.38%,0.042,"$+1,650"
2,Quarterly Rebal | TLH=10%,5.13%,0.908,0.37%,-0.025,"$+1,131"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 20-80  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),5.47%,0.947,-6.81%,0.26%,0.680
1,Abs Threshold 5% | TLH=10%,On (10%),5.47%,0.947,-6.81%,0.26%,0.680
2,Abs Threshold 10% | TLH=10%,On (10%),5.47%,0.947,-6.81%,0.26%,0.680

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,5.47%,0.947,0.26%,0.680,"$+2,790"
1,Abs Threshold 5% | TLH=10%,5.47%,0.947,0.26%,0.680,"$+2,790"
2,Abs Threshold 10% | TLH=10%,5.47%,0.947,0.26%,0.680,"$+2,790"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 20-80  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),5.47%,0.947,-6.81%,0.26%,0.680
1,Abs Threshold 5% | TLH=10%,On (10%),5.47%,0.947,-6.81%,0.26%,0.680
2,Abs Threshold 10% | TLH=10%,On (10%),5.47%,0.947,-6.81%,0.26%,0.680

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,5.47%,0.947,0.26%,0.680,"$+2,790"
1,Abs Threshold 5% | TLH=10%,5.47%,0.947,0.26%,0.680,"$+2,790"
2,Abs Threshold 10% | TLH=10%,5.47%,0.947,0.26%,0.680,"$+2,790"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 20-80  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),5.47%,0.947,-6.81%,0.26%,0.680
1,Abs Threshold 5% | TLH=10%,On (10%),5.47%,0.947,-6.81%,0.26%,0.680
2,Abs Threshold 10% | TLH=10%,On (10%),5.47%,0.947,-6.81%,0.26%,0.680

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,5.47%,0.947,0.26%,0.680,"$+2,790"
1,Abs Threshold 5% | TLH=10%,5.47%,0.947,0.26%,0.680,"$+2,790"
2,Abs Threshold 10% | TLH=10%,5.47%,0.947,0.26%,0.680,"$+2,790"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 30-70  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,-8.43%,-0.763,-18.75%,0.00%,0.000
1,Rel Threshold 50% | No TLH,Off,-8.43%,-0.763,-18.75%,0.00%,0.000
2,Rel Threshold 25% | No TLH,Off,-9.04%,-0.770,-19.83%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,-11.81%,-0.954,6.18%,-0.463,"$-33,083"
1,Monthly Rebal | TLH=10%,-13.06%,-1.034,6.21%,-0.543,"$-39,059"
2,Abs Threshold 10% | TLH=10%,-11.72%,-0.999,6.57%,-0.564,"$-43,173"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 30-70  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),8.23%,2.317,-1.40%,0.18%,0.655
1,Yearly Rebal | TLH=10%,On (10%),8.16%,2.295,-1.40%,0.15%,0.486
2,Abs Threshold 5% | TLH=10%,On (10%),8.16%,2.295,-1.40%,0.15%,0.486

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,8.23%,2.317,0.18%,0.655,"$+2,164"
1,Yearly Rebal | TLH=10%,8.16%,2.295,0.15%,0.486,"$+1,839"
2,Abs Threshold 5% | TLH=10%,8.16%,2.295,0.15%,0.486,"$+1,839"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 30-70  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,8.79%,1.355,-7.81%,0.00%,0.000
1,Abs Threshold 20% | No TLH,Off,8.79%,1.355,-7.81%,0.00%,0.000
2,Abs Threshold 10% | TLH=10%,On (10%),8.74%,1.331,-7.91%,0.24%,-0.495

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.21%,1.168,0.34%,0.073,"$+1,911"
1,Yearly Rebal | TLH=10%,7.89%,1.243,0.27%,0.008,"$+1,441"
2,Quarterly Rebal | TLH=10%,7.38%,1.193,0.34%,0.001,"$+1,389"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 30-70  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),7.13%,1.025,-8.09%,0.32%,0.957
1,Abs Threshold 5% | TLH=10%,On (10%),7.13%,1.025,-8.09%,0.32%,0.957
2,Abs Threshold 10% | TLH=10%,On (10%),7.13%,1.025,-8.09%,0.32%,0.957

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,7.13%,1.025,0.32%,0.957,"$+3,973"
1,Abs Threshold 5% | TLH=10%,7.13%,1.025,0.32%,0.957,"$+3,973"
2,Abs Threshold 10% | TLH=10%,7.13%,1.025,0.32%,0.957,"$+3,973"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 30-70  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),7.13%,1.025,-8.09%,0.32%,0.957
1,Abs Threshold 5% | TLH=10%,On (10%),7.13%,1.025,-8.09%,0.32%,0.957
2,Abs Threshold 10% | TLH=10%,On (10%),7.13%,1.025,-8.09%,0.32%,0.957

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,7.13%,1.025,0.32%,0.957,"$+3,973"
1,Abs Threshold 5% | TLH=10%,7.13%,1.025,0.32%,0.957,"$+3,973"
2,Abs Threshold 10% | TLH=10%,7.13%,1.025,0.32%,0.957,"$+3,973"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 30-70  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),7.13%,1.025,-8.09%,0.32%,0.957
1,Abs Threshold 5% | TLH=10%,On (10%),7.13%,1.025,-8.09%,0.32%,0.957
2,Abs Threshold 10% | TLH=10%,On (10%),7.13%,1.025,-8.09%,0.32%,0.957

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,7.13%,1.025,0.32%,0.957,"$+3,973"
1,Abs Threshold 5% | TLH=10%,7.13%,1.025,0.32%,0.957,"$+3,973"
2,Abs Threshold 10% | TLH=10%,7.13%,1.025,0.32%,0.957,"$+3,973"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 40-60  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | No TLH,Off,-11.69%,-0.863,-22.06%,0.00%,0.000
1,Rel Threshold 25% | No TLH,Off,-13.28%,-0.913,-23.57%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-12.49%,-0.945,-22.62%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,-14.17%,-0.994,5.48%,-0.469,"$-29,384"
1,Abs Threshold 10% | TLH=10%,-14.29%,-1.092,5.71%,-0.486,"$-31,855"
2,Abs Threshold 20% | TLH=10%,-14.29%,-1.092,5.71%,-0.486,"$-31,855"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 40-60  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),9.60%,1.985,-2.20%,0.20%,0.805
1,Yearly Rebal | TLH=10%,On (10%),9.52%,1.968,-2.20%,0.18%,0.660
2,Abs Threshold 5% | TLH=10%,On (10%),9.52%,1.968,-2.20%,0.18%,0.660

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,9.60%,1.985,0.20%,0.805,"$+2,539"
1,Yearly Rebal | TLH=10%,9.52%,1.968,0.18%,0.660,"$+2,190"
2,Abs Threshold 5% | TLH=10%,9.52%,1.968,0.18%,0.660,"$+2,190"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 40-60  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,11.71%,1.529,-8.32%,0.00%,0.000
1,Abs Threshold 20% | No TLH,Off,11.71%,1.529,-8.32%,0.00%,0.000
2,Abs Threshold 10% | TLH=10%,On (10%),11.67%,1.513,-8.41%,0.22%,-0.516

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.88%,1.375,0.35%,0.078,"$+2,037"
1,Quarterly Rebal | TLH=10%,10.09%,1.401,0.33%,-0.000,"$+1,448"
2,Yearly Rebal | TLH=10%,10.69%,1.437,0.25%,-0.006,"$+1,434"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 40-60  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),9.19%,1.063,-9.80%,0.45%,1.163
1,Abs Threshold 5% | TLH=10%,On (10%),9.19%,1.063,-9.80%,0.45%,1.163
2,Abs Threshold 10% | TLH=10%,On (10%),9.19%,1.063,-9.80%,0.45%,1.163

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,9.19%,1.063,0.45%,1.163,"$+5,849"
1,Abs Threshold 5% | TLH=10%,9.19%,1.063,0.45%,1.163,"$+5,849"
2,Abs Threshold 10% | TLH=10%,9.19%,1.063,0.45%,1.163,"$+5,849"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 40-60  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),9.19%,1.063,-9.80%,0.45%,1.163
1,Abs Threshold 5% | TLH=10%,On (10%),9.19%,1.063,-9.80%,0.45%,1.163
2,Abs Threshold 10% | TLH=10%,On (10%),9.19%,1.063,-9.80%,0.45%,1.163

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,9.19%,1.063,0.45%,1.163,"$+5,849"
1,Abs Threshold 5% | TLH=10%,9.19%,1.063,0.45%,1.163,"$+5,849"
2,Abs Threshold 10% | TLH=10%,9.19%,1.063,0.45%,1.163,"$+5,849"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 40-60  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),9.19%,1.063,-9.80%,0.45%,1.163
1,Abs Threshold 5% | TLH=10%,On (10%),9.19%,1.063,-9.80%,0.45%,1.163
2,Abs Threshold 10% | TLH=10%,On (10%),9.19%,1.063,-9.80%,0.45%,1.163

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,9.19%,1.063,0.45%,1.163,"$+5,849"
1,Abs Threshold 5% | TLH=10%,9.19%,1.063,0.45%,1.163,"$+5,849"
2,Abs Threshold 10% | TLH=10%,9.19%,1.063,0.45%,1.163,"$+5,849"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 50-50  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,-13.57%,-0.874,-25.64%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,-15.35%,-0.888,-27.59%,0.00%,0.000
2,Abs Threshold 10% | TLH=10%,On (10%),-15.18%,-0.942,-27.26%,4.68%,-0.361

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,-18.71%,-1.138,4.85%,-0.308,"$-16,537"
1,Abs Threshold 10% | TLH=10%,-15.18%,-0.942,4.68%,-0.361,"$-18,953"
2,Abs Threshold 5% | TLH=10%,-16.87%,-0.979,4.23%,-0.377,"$-17,789"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 50-50  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),10.50%,1.764,-2.85%,0.23%,0.864
1,Yearly Rebal | TLH=10%,On (10%),10.41%,1.753,-2.84%,0.21%,0.717
2,Abs Threshold 5% | TLH=10%,On (10%),10.41%,1.753,-2.84%,0.21%,0.717

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,10.50%,1.764,0.23%,0.864,"$+2,821"
1,Yearly Rebal | TLH=10%,10.41%,1.753,0.21%,0.717,"$+2,428"
2,Abs Threshold 5% | TLH=10%,10.41%,1.753,0.21%,0.717,"$+2,428"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 50-50  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-6.89%,-0.857,-3.70%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-6.89%,-0.857,-3.70%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-6.89%,-0.857,-3.70%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-6.94%,-0.865,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-6.89%,-0.857,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-6.89%,-0.857,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 50-50  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),10.91%,1.069,-11.12%,0.57%,0.418
1,Abs Threshold 5% | TLH=10%,On (10%),10.91%,1.069,-11.12%,0.57%,0.418
2,Abs Threshold 10% | TLH=10%,On (10%),10.91%,1.069,-11.12%,0.57%,0.418

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,10.91%,1.069,0.57%,0.418,"$+3,417"
1,Abs Threshold 5% | TLH=10%,10.91%,1.069,0.57%,0.418,"$+3,417"
2,Abs Threshold 10% | TLH=10%,10.91%,1.069,0.57%,0.418,"$+3,417"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 50-50  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),10.91%,1.069,-11.12%,0.57%,0.418
1,Abs Threshold 5% | TLH=10%,On (10%),10.91%,1.069,-11.12%,0.57%,0.418
2,Abs Threshold 10% | TLH=10%,On (10%),10.91%,1.069,-11.12%,0.57%,0.418

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,10.91%,1.069,0.57%,0.418,"$+3,417"
1,Abs Threshold 5% | TLH=10%,10.91%,1.069,0.57%,0.418,"$+3,417"
2,Abs Threshold 10% | TLH=10%,10.91%,1.069,0.57%,0.418,"$+3,417"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 50-50  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),10.91%,1.069,-11.12%,0.57%,0.418
1,Abs Threshold 5% | TLH=10%,On (10%),10.91%,1.069,-11.12%,0.57%,0.418
2,Abs Threshold 10% | TLH=10%,On (10%),10.91%,1.069,-11.12%,0.57%,0.418

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,10.91%,1.069,0.57%,0.418,"$+3,417"
1,Abs Threshold 5% | TLH=10%,10.91%,1.069,0.57%,0.418,"$+3,417"
2,Abs Threshold 10% | TLH=10%,10.91%,1.069,0.57%,0.418,"$+3,417"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 60-40  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 10% | No TLH,Off,-17.76%,-0.932,-31.15%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),-18.71%,-0.938,-30.84%,4.37%,0.245
2,Abs Threshold 10% | TLH=10%,On (10%),-18.33%,-0.941,-31.17%,3.99%,-0.164

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-18.71%,-0.938,4.37%,0.245,"$+13,409"
1,Rel Threshold 25% | TLH=10%,-21.70%,-1.110,4.77%,-0.099,"$-4,576"
2,Abs Threshold 10% | TLH=10%,-18.33%,-0.941,3.99%,-0.164,"$-6,682"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 60-40  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),11.66%,1.605,-3.60%,0.26%,0.916
1,Yearly Rebal | TLH=10%,On (10%),11.58%,1.596,-3.59%,0.23%,0.780
2,Abs Threshold 5% | TLH=10%,On (10%),11.58%,1.596,-3.59%,0.23%,0.780

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,11.66%,1.605,0.26%,0.916,"$+3,100"
1,Yearly Rebal | TLH=10%,11.58%,1.596,0.23%,0.780,"$+2,698"
2,Abs Threshold 5% | TLH=10%,11.58%,1.596,0.23%,0.780,"$+2,698"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 60-40  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-7.10%,-0.790,-3.87%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-7.10%,-0.790,-3.87%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-7.10%,-0.790,-3.87%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-7.18%,-0.800,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-7.10%,-0.790,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-7.10%,-0.790,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 60-40  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),13.53%,1.109,-12.52%,0.80%,0.961
1,Rel Threshold 25% | No TLH,Off,12.61%,1.040,-12.51%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,12.23%,1.030,-12.44%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,13.53%,1.109,0.80%,0.961,"$+8,060"
1,Yearly Rebal | TLH=10%,12.70%,1.022,1.34%,0.235,"$+4,093"
2,Abs Threshold 5% | TLH=10%,12.70%,1.022,1.34%,0.235,"$+4,093"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 60-40  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),13.53%,1.109,-12.52%,0.80%,0.961
1,Rel Threshold 25% | No TLH,Off,12.61%,1.040,-12.51%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,12.23%,1.030,-12.44%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,13.53%,1.109,0.80%,0.961,"$+8,060"
1,Yearly Rebal | TLH=10%,12.70%,1.022,1.34%,0.235,"$+4,093"
2,Abs Threshold 5% | TLH=10%,12.70%,1.022,1.34%,0.235,"$+4,093"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 60-40  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),13.53%,1.109,-12.52%,0.80%,0.961
1,Rel Threshold 25% | No TLH,Off,12.61%,1.040,-12.51%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,12.23%,1.030,-12.44%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,13.53%,1.109,0.80%,0.961,"$+8,060"
1,Yearly Rebal | TLH=10%,12.70%,1.022,1.34%,0.235,"$+4,093"
2,Abs Threshold 5% | TLH=10%,12.70%,1.022,1.34%,0.235,"$+4,093"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 70-30  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,-23.53%,-1.003,-37.79%,0.00%,0.000
1,Rel Threshold 50% | No TLH,Off,-24.08%,-1.008,-38.03%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),-23.84%,-1.010,-37.68%,3.18%,-0.123

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,-23.77%,-1.048,4.41%,0.054,"$+3,623"
1,Abs Threshold 5% | TLH=10%,-23.84%,-1.010,3.18%,-0.123,"$-3,648"
2,Abs Threshold 10% | TLH=10%,-23.41%,-1.074,3.41%,-0.130,"$-4,230"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 70-30  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),12.53%,1.487,-4.25%,0.29%,0.958
1,Yearly Rebal | TLH=10%,On (10%),12.47%,1.480,-4.24%,0.27%,0.824
2,Abs Threshold 5% | TLH=10%,On (10%),12.47%,1.480,-4.24%,0.27%,0.824

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,12.53%,1.487,0.29%,0.958,"$+3,434"
1,Yearly Rebal | TLH=10%,12.47%,1.480,0.27%,0.824,"$+2,994"
2,Abs Threshold 5% | TLH=10%,12.47%,1.480,0.27%,0.824,"$+2,994"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 70-30  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-7.41%,-0.745,-4.02%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-7.41%,-0.745,-4.02%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-7.41%,-0.745,-4.02%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-7.51%,-0.756,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-7.41%,-0.745,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-7.41%,-0.745,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 70-30  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),14.97%,1.077,-13.94%,0.81%,0.186
1,Rel Threshold 25% | No TLH,Off,14.66%,1.061,-13.77%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,14.25%,1.049,-13.72%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,14.72%,1.032,1.58%,0.201,"$+4,129"
1,Abs Threshold 5% | TLH=10%,14.72%,1.032,1.58%,0.201,"$+4,129"
2,Abs Threshold 10% | TLH=10%,14.72%,1.032,1.58%,0.201,"$+4,129"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 70-30  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),14.97%,1.077,-13.94%,0.81%,0.186
1,Rel Threshold 25% | No TLH,Off,14.66%,1.061,-13.77%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,14.25%,1.049,-13.72%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,14.72%,1.032,1.58%,0.201,"$+4,129"
1,Abs Threshold 5% | TLH=10%,14.72%,1.032,1.58%,0.201,"$+4,129"
2,Abs Threshold 10% | TLH=10%,14.72%,1.032,1.58%,0.201,"$+4,129"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 70-30  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),14.97%,1.077,-13.94%,0.81%,0.186
1,Rel Threshold 25% | No TLH,Off,14.66%,1.061,-13.77%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,14.25%,1.049,-13.72%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,14.72%,1.032,1.58%,0.201,"$+4,129"
1,Abs Threshold 5% | TLH=10%,14.72%,1.032,1.58%,0.201,"$+4,129"
2,Abs Threshold 10% | TLH=10%,14.72%,1.032,1.58%,0.201,"$+4,129"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 80-20  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),-27.19%,-0.900,-42.61%,4.09%,0.608
1,Abs Threshold 5% | TLH=10%,On (10%),-26.12%,-0.929,-41.70%,3.04%,0.355
2,Rel Threshold 50% | TLH=10%,On (10%),-26.59%,-0.973,-40.46%,5.07%,0.483

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-27.19%,-0.900,4.09%,0.608,"$+29,037"
1,Rel Threshold 50% | TLH=10%,-26.59%,-0.973,5.07%,0.483,"$+28,608"
2,Abs Threshold 5% | TLH=10%,-26.12%,-0.929,3.04%,0.355,"$+13,145"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 80-20  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),13.55%,1.375,-5.05%,0.33%,0.978
1,Yearly Rebal | TLH=10%,On (10%),13.51%,1.372,-5.03%,0.31%,0.856
2,Abs Threshold 5% | TLH=10%,On (10%),13.51%,1.372,-5.03%,0.31%,0.856

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,13.55%,1.375,0.33%,0.978,"$+3,751"
1,Yearly Rebal | TLH=10%,13.51%,1.372,0.31%,0.856,"$+3,311"
2,Abs Threshold 5% | TLH=10%,13.51%,1.372,0.31%,0.856,"$+3,311"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 80-20  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-7.51%,-0.682,-4.15%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-7.51%,-0.682,-4.15%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-7.51%,-0.682,-4.15%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-7.63%,-0.695,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-7.51%,-0.682,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-7.51%,-0.682,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 80-20  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),18.02%,1.152,-15.16%,1.07%,1.387
1,Rel Threshold 25% | No TLH,Off,16.37%,1.055,-15.14%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,15.99%,1.044,-15.13%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,18.02%,1.152,1.07%,1.387,"$+14,391"
1,Yearly Rebal | TLH=10%,16.60%,1.033,1.77%,0.261,"$+5,396"
2,Abs Threshold 5% | TLH=10%,16.60%,1.033,1.77%,0.261,"$+5,396"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 80-20  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),18.02%,1.152,-15.16%,1.07%,1.387
1,Rel Threshold 25% | No TLH,Off,16.37%,1.055,-15.14%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,15.99%,1.044,-15.13%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,18.02%,1.152,1.07%,1.387,"$+14,391"
1,Yearly Rebal | TLH=10%,16.60%,1.033,1.77%,0.261,"$+5,396"
2,Abs Threshold 5% | TLH=10%,16.60%,1.033,1.77%,0.261,"$+5,396"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 80-20  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),18.02%,1.152,-15.16%,1.07%,1.387
1,Rel Threshold 25% | No TLH,Off,16.37%,1.055,-15.14%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,15.99%,1.044,-15.13%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,18.02%,1.152,1.07%,1.387,"$+14,391"
1,Yearly Rebal | TLH=10%,16.60%,1.033,1.77%,0.261,"$+5,396"
2,Abs Threshold 5% | TLH=10%,16.60%,1.033,1.77%,0.261,"$+5,396"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 90-10  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),-34.84%,-0.985,-50.40%,3.23%,0.129
1,Rel Threshold 50% | No TLH,Off,-34.68%,-1.001,-50.58%,0.00%,0.000
2,Rel Threshold 25% | No TLH,Off,-35.10%,-1.002,-50.97%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-34.84%,-0.985,3.23%,0.129,"$+5,337"
1,Rel Threshold 50% | TLH=10%,-35.67%,-1.014,3.38%,-0.313,"$-11,034"
2,Rel Threshold 25% | TLH=10%,-36.37%,-1.026,3.36%,-0.398,"$-14,132"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 90-10  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),13.94%,1.231,-6.04%,0.34%,0.877
1,Abs Threshold 5% | TLH=10%,On (10%),13.94%,1.231,-6.04%,0.34%,0.877
2,Abs Threshold 10% | TLH=10%,On (10%),13.94%,1.231,-6.04%,0.34%,0.877

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,13.91%,1.229,0.36%,0.958,"$+3,942"
1,Yearly Rebal | TLH=10%,13.94%,1.231,0.34%,0.877,"$+3,617"
2,Abs Threshold 5% | TLH=10%,13.94%,1.231,0.34%,0.877,"$+3,617"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 90-10  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-6.54%,-0.549,-4.22%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-6.54%,-0.549,-4.22%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-6.54%,-0.549,-4.22%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-6.70%,-0.563,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-6.54%,-0.549,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-6.54%,-0.549,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 90-10  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),18.13%,1.026,-17.25%,1.11%,1.044
1,Abs Threshold 5% | TLH=10%,On (10%),18.13%,1.026,-17.25%,1.11%,1.044
2,Abs Threshold 10% | TLH=10%,On (10%),18.13%,1.026,-17.25%,1.11%,1.044

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,18.13%,1.026,1.11%,1.044,"$+11,495"
1,Abs Threshold 5% | TLH=10%,18.13%,1.026,1.11%,1.044,"$+11,495"
2,Abs Threshold 10% | TLH=10%,18.13%,1.026,1.11%,1.044,"$+11,495"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 90-10  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),18.13%,1.026,-17.25%,1.11%,1.044
1,Abs Threshold 5% | TLH=10%,On (10%),18.13%,1.026,-17.25%,1.11%,1.044
2,Abs Threshold 10% | TLH=10%,On (10%),18.13%,1.026,-17.25%,1.11%,1.044

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,18.13%,1.026,1.11%,1.044,"$+11,495"
1,Abs Threshold 5% | TLH=10%,18.13%,1.026,1.11%,1.044,"$+11,495"
2,Abs Threshold 10% | TLH=10%,18.13%,1.026,1.11%,1.044,"$+11,495"

──────────────────────────────────────────────────────────────────────────────────────────
  TA TaxAware ETF - 90-10  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),18.13%,1.026,-17.25%,1.11%,1.044
1,Abs Threshold 5% | TLH=10%,On (10%),18.13%,1.026,-17.25%,1.11%,1.044
2,Abs Threshold 10% | TLH=10%,On (10%),18.13%,1.026,-17.25%,1.11%,1.044

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,18.13%,1.026,1.11%,1.044,"$+11,495"
1,Abs Threshold 5% | TLH=10%,18.13%,1.026,1.11%,1.044,"$+11,495"
2,Abs Threshold 10% | TLH=10%,18.13%,1.026,1.11%,1.044,"$+11,495"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 0-100  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,6.98%,2.023,-2.36%,0.00%,0.000
1,Yearly Rebal | TLH=10%,On (10%),6.98%,2.023,-2.36%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,6.98%,2.021,-2.36%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,6.94%,2.014,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,6.94%,2.015,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,6.98%,2.023,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 0-100  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,0.62%,0.100,-8.52%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),0.62%,0.100,-8.52%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,0.62%,0.100,-8.52%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.52%,0.084,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,0.53%,0.086,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,0.57%,0.093,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 0-100  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),0.95%,0.154,-10.63%,0.13%,-0.104
1,Abs Threshold 10% | TLH=10%,On (10%),0.95%,0.154,-10.63%,0.13%,-0.104
2,Abs Threshold 20% | TLH=10%,On (10%),0.95%,0.154,-10.63%,0.13%,-0.104

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.54%,0.088,0.00%,0.000,$+0
1,Abs Threshold 5% | TLH=10%,0.95%,0.154,0.13%,-0.104,$+754
2,Abs Threshold 10% | TLH=10%,0.95%,0.154,0.13%,-0.104,$+754

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 0-100  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),0.95%,0.154,-10.63%,0.13%,-0.104
1,Abs Threshold 10% | TLH=10%,On (10%),0.95%,0.154,-10.63%,0.13%,-0.104
2,Abs Threshold 20% | TLH=10%,On (10%),0.95%,0.154,-10.63%,0.13%,-0.104

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.54%,0.088,0.00%,0.000,$+0
1,Abs Threshold 5% | TLH=10%,0.95%,0.154,0.13%,-0.104,$+754
2,Abs Threshold 10% | TLH=10%,0.95%,0.154,0.13%,-0.104,$+754

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 0-100  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),0.95%,0.154,-10.63%,0.13%,-0.104
1,Abs Threshold 10% | TLH=10%,On (10%),0.95%,0.154,-10.63%,0.13%,-0.104
2,Abs Threshold 20% | TLH=10%,On (10%),0.95%,0.154,-10.63%,0.13%,-0.104

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.54%,0.088,0.00%,0.000,$+0
1,Abs Threshold 5% | TLH=10%,0.95%,0.154,0.13%,-0.104,$+754
2,Abs Threshold 10% | TLH=10%,0.95%,0.154,0.13%,-0.104,$+754

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 10-90  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000
1,Quarterly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"
1,Quarterly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"
2,Yearly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 10-90  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),7.91%,2.422,-1.59%,0.01%,-26.581
1,Quarterly Rebal | No TLH,Off,7.91%,2.421,-1.59%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,7.88%,2.410,-1.55%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,7.88%,2.410,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,7.87%,2.403,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,7.87%,2.403,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 10-90  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),1.05%,0.175,-7.66%,0.09%,0.102
1,Abs Threshold 10% | TLH=10%,On (10%),1.05%,0.175,-7.66%,0.09%,0.102
2,Abs Threshold 20% | TLH=10%,On (10%),1.05%,0.175,-7.66%,0.09%,0.102

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,1.05%,0.175,0.09%,0.102,"$+1,389"
1,Abs Threshold 10% | TLH=10%,1.05%,0.175,0.09%,0.102,"$+1,389"
2,Abs Threshold 20% | TLH=10%,1.05%,0.175,0.09%,0.102,"$+1,389"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 10-90  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),3.21%,0.564,-7.66%,0.09%,0.081
1,Abs Threshold 10% | TLH=10%,On (10%),3.21%,0.564,-7.66%,0.09%,0.081
2,Abs Threshold 20% | TLH=10%,On (10%),3.21%,0.564,-7.66%,0.09%,0.081

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,3.21%,0.564,0.09%,0.081,"$+1,538"
1,Abs Threshold 10% | TLH=10%,3.21%,0.564,0.09%,0.081,"$+1,538"
2,Abs Threshold 20% | TLH=10%,3.21%,0.564,0.09%,0.081,"$+1,538"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 10-90  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),3.21%,0.564,-7.66%,0.09%,0.081
1,Abs Threshold 10% | TLH=10%,On (10%),3.21%,0.564,-7.66%,0.09%,0.081
2,Abs Threshold 20% | TLH=10%,On (10%),3.21%,0.564,-7.66%,0.09%,0.081

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,3.21%,0.564,0.09%,0.081,"$+1,538"
1,Abs Threshold 10% | TLH=10%,3.21%,0.564,0.09%,0.081,"$+1,538"
2,Abs Threshold 20% | TLH=10%,3.21%,0.564,0.09%,0.081,"$+1,538"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 10-90  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),3.21%,0.564,-7.66%,0.09%,0.081
1,Abs Threshold 10% | TLH=10%,On (10%),3.21%,0.564,-7.66%,0.09%,0.081
2,Abs Threshold 20% | TLH=10%,On (10%),3.21%,0.564,-7.66%,0.09%,0.081

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,3.21%,0.564,0.09%,0.081,"$+1,538"
1,Abs Threshold 10% | TLH=10%,3.21%,0.564,0.09%,0.081,"$+1,538"
2,Abs Threshold 20% | TLH=10%,3.21%,0.564,0.09%,0.081,"$+1,538"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 100-0  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000
1,Quarterly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"
1,Quarterly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"
2,Yearly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 100-0  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,17.60%,1.463,-6.65%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),17.60%,1.463,-6.65%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,17.58%,1.460,-6.65%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,17.60%,1.463,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,17.58%,1.460,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,17.58%,1.460,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 100-0  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),15.21%,1.186,-11.43%,0.57%,0.217
1,Abs Threshold 10% | TLH=10%,On (10%),15.21%,1.186,-11.43%,0.57%,0.217
2,Abs Threshold 20% | TLH=10%,On (10%),15.21%,1.186,-11.43%,0.57%,0.217

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,15.21%,1.186,0.57%,0.217,"$+4,265"
1,Abs Threshold 10% | TLH=10%,15.21%,1.186,0.57%,0.217,"$+4,265"
2,Abs Threshold 20% | TLH=10%,15.21%,1.186,0.57%,0.217,"$+4,265"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 100-0  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,15.99%,1.089,-18.06%,0.00%,0.000
1,Rel Threshold 25% | TLH=10%,On (10%),16.08%,1.087,-18.02%,0.62%,0.079
2,Yearly Rebal | No TLH,Off,15.86%,1.084,-17.89%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,16.08%,1.087,0.62%,0.079,"$+3,733"
1,Abs Threshold 5% | TLH=10%,16.03%,1.071,0.61%,0.067,"$+3,407"
2,Abs Threshold 10% | TLH=10%,16.03%,1.071,0.61%,0.067,"$+3,407"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 100-0  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,15.99%,1.089,-18.06%,0.00%,0.000
1,Rel Threshold 25% | TLH=10%,On (10%),16.08%,1.087,-18.02%,0.62%,0.079
2,Yearly Rebal | No TLH,Off,15.86%,1.084,-17.89%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,16.08%,1.087,0.62%,0.079,"$+3,733"
1,Abs Threshold 5% | TLH=10%,16.03%,1.071,0.61%,0.067,"$+3,407"
2,Abs Threshold 10% | TLH=10%,16.03%,1.071,0.61%,0.067,"$+3,407"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 100-0  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,15.99%,1.089,-18.06%,0.00%,0.000
1,Rel Threshold 25% | TLH=10%,On (10%),16.08%,1.087,-18.02%,0.62%,0.079
2,Yearly Rebal | No TLH,Off,15.86%,1.084,-17.89%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,16.08%,1.087,0.62%,0.079,"$+3,733"
1,Abs Threshold 5% | TLH=10%,16.03%,1.071,0.61%,0.067,"$+3,407"
2,Abs Threshold 10% | TLH=10%,16.03%,1.071,0.61%,0.067,"$+3,407"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 20-80  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000
1,Quarterly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"
1,Quarterly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"
2,Yearly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 20-80  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),8.68%,2.623,-1.21%,0.01%,-28.395
1,Quarterly Rebal | No TLH,Off,8.68%,2.622,-1.21%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,8.61%,2.599,-1.22%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,8.63%,2.598,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,8.61%,2.599,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,8.61%,2.599,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 20-80  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),2.80%,0.454,-7.10%,0.17%,0.227
1,Abs Threshold 10% | TLH=10%,On (10%),2.80%,0.454,-7.10%,0.17%,0.227
2,Abs Threshold 20% | TLH=10%,On (10%),2.80%,0.454,-7.10%,0.17%,0.227

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,2.80%,0.454,0.17%,0.227,"$+1,997"
1,Abs Threshold 10% | TLH=10%,2.80%,0.454,0.17%,0.227,"$+1,997"
2,Abs Threshold 20% | TLH=10%,2.80%,0.454,0.17%,0.227,"$+1,997"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 20-80  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),4.95%,0.791,-7.10%,0.18%,0.096
1,Abs Threshold 10% | TLH=10%,On (10%),4.95%,0.791,-7.10%,0.18%,0.096
2,Abs Threshold 20% | TLH=10%,On (10%),4.95%,0.791,-7.10%,0.18%,0.096

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,4.95%,0.791,0.18%,0.096,"$+1,927"
1,Abs Threshold 10% | TLH=10%,4.95%,0.791,0.18%,0.096,"$+1,927"
2,Abs Threshold 20% | TLH=10%,4.95%,0.791,0.18%,0.096,"$+1,927"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 20-80  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),4.95%,0.791,-7.10%,0.18%,0.096
1,Abs Threshold 10% | TLH=10%,On (10%),4.95%,0.791,-7.10%,0.18%,0.096
2,Abs Threshold 20% | TLH=10%,On (10%),4.95%,0.791,-7.10%,0.18%,0.096

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,4.95%,0.791,0.18%,0.096,"$+1,927"
1,Abs Threshold 10% | TLH=10%,4.95%,0.791,0.18%,0.096,"$+1,927"
2,Abs Threshold 20% | TLH=10%,4.95%,0.791,0.18%,0.096,"$+1,927"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 20-80  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),4.95%,0.791,-7.10%,0.18%,0.096
1,Abs Threshold 10% | TLH=10%,On (10%),4.95%,0.791,-7.10%,0.18%,0.096
2,Abs Threshold 20% | TLH=10%,On (10%),4.95%,0.791,-7.10%,0.18%,0.096

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,4.95%,0.791,0.18%,0.096,"$+1,927"
1,Abs Threshold 10% | TLH=10%,4.95%,0.791,0.18%,0.096,"$+1,927"
2,Abs Threshold 20% | TLH=10%,4.95%,0.791,0.18%,0.096,"$+1,927"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 30-70  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000
1,Quarterly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"
1,Quarterly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"
2,Yearly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 30-70  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,9.36%,2.612,-1.13%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),9.36%,2.612,-1.13%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,9.27%,2.589,-1.13%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.30%,2.581,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,9.36%,2.612,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,9.27%,2.589,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 30-70  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),4.51%,0.675,-7.30%,0.23%,0.262
1,Abs Threshold 10% | TLH=10%,On (10%),4.51%,0.675,-7.30%,0.23%,0.262
2,Abs Threshold 20% | TLH=10%,On (10%),4.51%,0.675,-7.30%,0.23%,0.262

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,4.51%,0.675,0.23%,0.262,"$+2,514"
1,Abs Threshold 10% | TLH=10%,4.51%,0.675,0.23%,0.262,"$+2,514"
2,Abs Threshold 20% | TLH=10%,4.51%,0.675,0.23%,0.262,"$+2,514"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 30-70  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),6.62%,0.925,-8.08%,0.26%,0.121
1,Abs Threshold 10% | TLH=10%,On (10%),6.62%,0.925,-8.08%,0.26%,0.121
2,Abs Threshold 20% | TLH=10%,On (10%),6.62%,0.925,-8.08%,0.26%,0.121

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,6.62%,0.925,0.26%,0.121,"$+2,453"
1,Abs Threshold 10% | TLH=10%,6.62%,0.925,0.26%,0.121,"$+2,453"
2,Abs Threshold 20% | TLH=10%,6.62%,0.925,0.26%,0.121,"$+2,453"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 30-70  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),6.62%,0.925,-8.08%,0.26%,0.121
1,Abs Threshold 10% | TLH=10%,On (10%),6.62%,0.925,-8.08%,0.26%,0.121
2,Abs Threshold 20% | TLH=10%,On (10%),6.62%,0.925,-8.08%,0.26%,0.121

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,6.62%,0.925,0.26%,0.121,"$+2,453"
1,Abs Threshold 10% | TLH=10%,6.62%,0.925,0.26%,0.121,"$+2,453"
2,Abs Threshold 20% | TLH=10%,6.62%,0.925,0.26%,0.121,"$+2,453"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 30-70  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),6.62%,0.925,-8.08%,0.26%,0.121
1,Abs Threshold 10% | TLH=10%,On (10%),6.62%,0.925,-8.08%,0.26%,0.121
2,Abs Threshold 20% | TLH=10%,On (10%),6.62%,0.925,-8.08%,0.26%,0.121

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,6.62%,0.925,0.26%,0.121,"$+2,453"
1,Abs Threshold 10% | TLH=10%,6.62%,0.925,0.26%,0.121,"$+2,453"
2,Abs Threshold 20% | TLH=10%,6.62%,0.925,0.26%,0.121,"$+2,453"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 40-60  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000
1,Quarterly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"
1,Quarterly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"
2,Yearly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 40-60  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,10.69%,2.458,-1.79%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),10.69%,2.458,-1.79%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,10.58%,2.440,-1.78%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,10.62%,2.425,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,10.69%,2.458,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,10.58%,2.440,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 40-60  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),6.52%,0.867,-7.93%,0.27%,0.210
1,Abs Threshold 10% | TLH=10%,On (10%),6.52%,0.867,-7.93%,0.27%,0.210
2,Abs Threshold 20% | TLH=10%,On (10%),6.52%,0.867,-7.93%,0.27%,0.210

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,6.52%,0.867,0.27%,0.210,"$+2,512"
1,Abs Threshold 10% | TLH=10%,6.52%,0.867,0.27%,0.210,"$+2,512"
2,Abs Threshold 20% | TLH=10%,6.52%,0.867,0.27%,0.210,"$+2,512"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 40-60  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,8.43%,1.012,-10.02%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),8.49%,1.012,-10.12%,0.30%,0.067
2,Abs Threshold 10% | No TLH,Off,8.43%,1.012,-10.02%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,8.49%,1.012,0.30%,0.067,"$+2,192"
1,Abs Threshold 10% | TLH=10%,8.49%,1.012,0.30%,0.067,"$+2,192"
2,Abs Threshold 20% | TLH=10%,8.49%,1.012,0.30%,0.067,"$+2,192"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 40-60  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,8.43%,1.012,-10.02%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),8.49%,1.012,-10.12%,0.30%,0.067
2,Abs Threshold 10% | No TLH,Off,8.43%,1.012,-10.02%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,8.49%,1.012,0.30%,0.067,"$+2,192"
1,Abs Threshold 10% | TLH=10%,8.49%,1.012,0.30%,0.067,"$+2,192"
2,Abs Threshold 20% | TLH=10%,8.49%,1.012,0.30%,0.067,"$+2,192"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 40-60  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,8.43%,1.012,-10.02%,0.00%,0.000
1,Abs Threshold 5% | TLH=10%,On (10%),8.49%,1.012,-10.12%,0.30%,0.067
2,Abs Threshold 10% | No TLH,Off,8.43%,1.012,-10.02%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,8.49%,1.012,0.30%,0.067,"$+2,192"
1,Abs Threshold 10% | TLH=10%,8.49%,1.012,0.30%,0.067,"$+2,192"
2,Abs Threshold 20% | TLH=10%,8.49%,1.012,0.30%,0.067,"$+2,192"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 50-50  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000
1,Quarterly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"
1,Quarterly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"
2,Yearly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 50-50  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),11.86%,2.294,-2.35%,0.01%,-27.785
1,Quarterly Rebal | No TLH,Off,11.86%,2.293,-2.35%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,11.74%,2.279,-2.34%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.79%,2.265,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,11.74%,2.279,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,11.74%,2.279,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 50-50  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),8.15%,0.967,-8.63%,0.34%,0.248
1,Abs Threshold 10% | TLH=10%,On (10%),8.15%,0.967,-8.63%,0.34%,0.248
2,Abs Threshold 20% | TLH=10%,On (10%),8.15%,0.967,-8.63%,0.34%,0.248

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,8.15%,0.967,0.34%,0.248,"$+3,098"
1,Abs Threshold 10% | TLH=10%,8.15%,0.967,0.34%,0.248,"$+3,098"
2,Abs Threshold 20% | TLH=10%,8.15%,0.967,0.34%,0.248,"$+3,098"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 50-50  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),9.58%,1.052,-10.92%,0.36%,0.019
1,Rel Threshold 25% | No TLH,Off,9.53%,1.051,-10.92%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,9.97%,1.049,-11.68%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,10.05%,1.047,0.37%,0.101,"$+2,858"
1,Abs Threshold 10% | TLH=10%,10.05%,1.047,0.37%,0.101,"$+2,858"
2,Abs Threshold 20% | TLH=10%,10.05%,1.047,0.37%,0.101,"$+2,858"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 50-50  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),9.58%,1.052,-10.92%,0.36%,0.019
1,Rel Threshold 25% | No TLH,Off,9.53%,1.051,-10.92%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,9.97%,1.049,-11.68%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,10.05%,1.047,0.37%,0.101,"$+2,858"
1,Abs Threshold 10% | TLH=10%,10.05%,1.047,0.37%,0.101,"$+2,858"
2,Abs Threshold 20% | TLH=10%,10.05%,1.047,0.37%,0.101,"$+2,858"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 50-50  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),9.58%,1.052,-10.92%,0.36%,0.019
1,Rel Threshold 25% | No TLH,Off,9.53%,1.051,-10.92%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,9.97%,1.049,-11.68%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,10.05%,1.047,0.37%,0.101,"$+2,858"
1,Abs Threshold 10% | TLH=10%,10.05%,1.047,0.37%,0.101,"$+2,858"
2,Abs Threshold 20% | TLH=10%,10.05%,1.047,0.37%,0.101,"$+2,858"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 60-40  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000
1,Quarterly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"
1,Quarterly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"
2,Yearly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 60-40  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,12.48%,2.166,-2.73%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),12.48%,2.166,-2.73%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,12.36%,2.151,-2.74%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,12.41%,2.141,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,12.48%,2.166,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,12.36%,2.151,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 60-40  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),9.93%,1.055,-9.27%,0.38%,0.213
1,Abs Threshold 10% | TLH=10%,On (10%),9.93%,1.055,-9.27%,0.38%,0.213
2,Abs Threshold 20% | TLH=10%,On (10%),9.93%,1.055,-9.27%,0.38%,0.213

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,9.93%,1.055,0.38%,0.213,"$+3,096"
1,Abs Threshold 10% | TLH=10%,9.93%,1.055,0.38%,0.213,"$+3,096"
2,Abs Threshold 20% | TLH=10%,9.93%,1.055,0.38%,0.213,"$+3,096"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 60-40  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),11.60%,1.112,-11.67%,0.41%,0.340
1,Rel Threshold 25% | No TLH,Off,11.42%,1.104,-11.87%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,11.56%,1.076,-13.33%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,11.60%,1.112,0.41%,0.340,"$+6,612"
1,Abs Threshold 5% | TLH=10%,11.64%,1.072,0.41%,0.066,"$+2,597"
2,Abs Threshold 10% | TLH=10%,11.64%,1.072,0.41%,0.066,"$+2,597"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 60-40  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),11.60%,1.112,-11.67%,0.41%,0.340
1,Rel Threshold 25% | No TLH,Off,11.42%,1.104,-11.87%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,11.56%,1.076,-13.33%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,11.60%,1.112,0.41%,0.340,"$+6,612"
1,Abs Threshold 5% | TLH=10%,11.64%,1.072,0.41%,0.066,"$+2,597"
2,Abs Threshold 10% | TLH=10%,11.64%,1.072,0.41%,0.066,"$+2,597"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 60-40  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | TLH=10%,On (10%),11.60%,1.112,-11.67%,0.41%,0.340
1,Rel Threshold 25% | No TLH,Off,11.42%,1.104,-11.87%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,11.56%,1.076,-13.33%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,11.60%,1.112,0.41%,0.340,"$+6,612"
1,Abs Threshold 5% | TLH=10%,11.64%,1.072,0.41%,0.066,"$+2,597"
2,Abs Threshold 10% | TLH=10%,11.64%,1.072,0.41%,0.066,"$+2,597"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 70-30  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000
1,Quarterly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"
1,Quarterly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"
2,Yearly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 70-30  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),14.09%,1.937,-3.67%,0.01%,-26.968
1,Quarterly Rebal | No TLH,Off,14.09%,1.937,-3.67%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,13.98%,1.928,-3.66%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,14.04%,1.921,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,13.98%,1.928,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,13.98%,1.928,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 70-30  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),11.63%,1.121,-9.87%,0.44%,0.240
1,Abs Threshold 10% | TLH=10%,On (10%),11.63%,1.121,-9.87%,0.44%,0.240
2,Abs Threshold 20% | TLH=10%,On (10%),11.63%,1.121,-9.87%,0.44%,0.240

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,11.63%,1.121,0.44%,0.240,"$+3,683"
1,Abs Threshold 10% | TLH=10%,11.63%,1.121,0.44%,0.240,"$+3,683"
2,Abs Threshold 20% | TLH=10%,11.63%,1.121,0.44%,0.240,"$+3,683"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 70-30  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,12.84%,1.110,-14.15%,0.00%,0.000
1,Rel Threshold 25% | TLH=10%,On (10%),12.90%,1.108,-14.14%,0.46%,0.045
2,Abs Threshold 5% | No TLH,Off,13.12%,1.102,-14.69%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,13.21%,1.098,0.47%,0.090,"$+3,263"
1,Abs Threshold 10% | TLH=10%,13.21%,1.098,0.47%,0.090,"$+3,263"
2,Abs Threshold 20% | TLH=10%,13.21%,1.098,0.47%,0.090,"$+3,263"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 70-30  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,12.84%,1.110,-14.15%,0.00%,0.000
1,Rel Threshold 25% | TLH=10%,On (10%),12.90%,1.108,-14.14%,0.46%,0.045
2,Abs Threshold 5% | No TLH,Off,13.12%,1.102,-14.69%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,13.21%,1.098,0.47%,0.090,"$+3,263"
1,Abs Threshold 10% | TLH=10%,13.21%,1.098,0.47%,0.090,"$+3,263"
2,Abs Threshold 20% | TLH=10%,13.21%,1.098,0.47%,0.090,"$+3,263"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 70-30  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,12.84%,1.110,-14.15%,0.00%,0.000
1,Rel Threshold 25% | TLH=10%,On (10%),12.90%,1.108,-14.14%,0.46%,0.045
2,Abs Threshold 5% | No TLH,Off,13.12%,1.102,-14.69%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,13.21%,1.098,0.47%,0.090,"$+3,263"
1,Abs Threshold 10% | TLH=10%,13.21%,1.098,0.47%,0.090,"$+3,263"
2,Abs Threshold 20% | TLH=10%,13.21%,1.098,0.47%,0.090,"$+3,263"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 80-20  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000
1,Quarterly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"
1,Quarterly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"
2,Yearly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 80-20  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),15.70%,1.725,-4.80%,0.01%,-26.120
1,Quarterly Rebal | No TLH,Off,15.70%,1.724,-4.80%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,15.62%,1.720,-4.78%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,15.69%,1.718,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,15.62%,1.720,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,15.62%,1.720,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 80-20  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),13.21%,1.164,-10.46%,0.49%,0.180
1,Abs Threshold 10% | TLH=10%,On (10%),13.21%,1.164,-10.46%,0.49%,0.180
2,Abs Threshold 20% | TLH=10%,On (10%),13.21%,1.164,-10.46%,0.49%,0.180

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,13.21%,1.164,0.49%,0.180,"$+3,386"
1,Abs Threshold 10% | TLH=10%,13.21%,1.164,0.49%,0.180,"$+3,386"
2,Abs Threshold 20% | TLH=10%,13.21%,1.164,0.49%,0.180,"$+3,386"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 80-20  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,14.60%,1.119,-16.10%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,14.60%,1.119,-16.10%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,14.60%,1.119,-16.10%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,14.67%,1.113,0.52%,0.032,"$+2,409"
1,Abs Threshold 10% | TLH=10%,14.67%,1.113,0.52%,0.032,"$+2,409"
2,Abs Threshold 20% | TLH=10%,14.67%,1.113,0.52%,0.032,"$+2,409"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 80-20  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,14.60%,1.119,-16.10%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,14.60%,1.119,-16.10%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,14.60%,1.119,-16.10%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,14.67%,1.113,0.52%,0.032,"$+2,409"
1,Abs Threshold 10% | TLH=10%,14.67%,1.113,0.52%,0.032,"$+2,409"
2,Abs Threshold 20% | TLH=10%,14.67%,1.113,0.52%,0.032,"$+2,409"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 80-20  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,14.60%,1.119,-16.10%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,14.60%,1.119,-16.10%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,14.60%,1.119,-16.10%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,14.67%,1.113,0.52%,0.032,"$+2,409"
1,Abs Threshold 10% | TLH=10%,14.67%,1.113,0.52%,0.032,"$+2,409"
2,Abs Threshold 20% | TLH=10%,14.67%,1.113,0.52%,0.032,"$+2,409"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 90-10  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000
1,Quarterly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-19.47%,-0.668,-49.94%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"
1,Quarterly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"
2,Yearly Rebal | TLH=10%,-20.04%,-0.706,7.87%,-0.078,"$-9,102"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 90-10  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | No TLH,Off,17.05%,1.501,-6.30%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),17.05%,1.501,-6.30%,0.00%,0.000
2,Quarterly Rebal | TLH=10%,On (10%),17.02%,1.499,-6.29%,0.01%,-30.049

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,17.05%,1.501,0.00%,0.000,$+0
1,Yearly Rebal | TLH=10%,17.01%,1.498,0.00%,0.000,$+0
2,Abs Threshold 5% | TLH=10%,17.01%,1.498,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 90-10  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),14.71%,1.196,-10.99%,0.56%,0.176
1,Abs Threshold 10% | TLH=10%,On (10%),14.71%,1.196,-10.99%,0.56%,0.176
2,Abs Threshold 20% | TLH=10%,On (10%),14.71%,1.196,-10.99%,0.56%,0.176

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,14.71%,1.196,0.56%,0.176,"$+3,677"
1,Abs Threshold 10% | TLH=10%,14.71%,1.196,0.56%,0.176,"$+3,677"
2,Abs Threshold 20% | TLH=10%,14.71%,1.196,0.56%,0.176,"$+3,677"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 90-10  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,15.83%,1.136,-16.92%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,15.99%,1.133,-17.32%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,15.99%,1.133,-17.32%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,16.06%,1.125,0.59%,0.028,"$+2,481"
1,Abs Threshold 10% | TLH=10%,16.06%,1.125,0.59%,0.028,"$+2,481"
2,Abs Threshold 20% | TLH=10%,16.06%,1.125,0.59%,0.028,"$+2,481"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 90-10  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,15.83%,1.136,-16.92%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,15.99%,1.133,-17.32%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,15.99%,1.133,-17.32%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,16.06%,1.125,0.59%,0.028,"$+2,481"
1,Abs Threshold 10% | TLH=10%,16.06%,1.125,0.59%,0.028,"$+2,481"
2,Abs Threshold 20% | TLH=10%,16.06%,1.125,0.59%,0.028,"$+2,481"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ESG - 90-10  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,15.83%,1.136,-16.92%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,15.99%,1.133,-17.32%,0.00%,0.000
2,Abs Threshold 10% | No TLH,Off,15.99%,1.133,-17.32%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,16.06%,1.125,0.59%,0.028,"$+2,481"
1,Abs Threshold 10% | TLH=10%,16.06%,1.125,0.59%,0.028,"$+2,481"
2,Abs Threshold 20% | TLH=10%,16.06%,1.125,0.59%,0.028,"$+2,481"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 0-100  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,5.56%,0.678,-11.28%,0.00%,0.000
1,Rel Threshold 25% | TLH=10%,On (10%),5.56%,0.678,-11.28%,0.00%,0.000
2,Monthly Rebal | No TLH,Off,5.28%,0.653,-10.94%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,5.28%,0.653,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,4.70%,0.590,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,4.79%,0.604,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 0-100  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),4.55%,1.573,-2.45%,0.32%,0.036
1,Monthly Rebal | TLH=10%,On (10%),4.53%,1.564,-2.45%,0.32%,0.112
2,Yearly Rebal | TLH=10%,On (10%),4.53%,1.563,-2.45%,0.34%,0.003

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,4.53%,1.564,0.32%,0.112,"$+1,765"
1,Rel Threshold 25% | TLH=10%,4.50%,1.552,0.32%,0.093,"$+1,691"
2,Quarterly Rebal | TLH=10%,4.55%,1.573,0.32%,0.036,"$+1,436"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 0-100  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,0.91%,0.157,-6.56%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,0.91%,0.157,-6.56%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,0.91%,0.157,-6.56%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,0.82%,0.138,0.23%,-0.211,$+422
1,Rel Threshold 25% | TLH=10%,0.85%,0.143,0.22%,-0.318,$+80
2,Quarterly Rebal | TLH=10%,0.82%,0.138,0.23%,-0.328,$-12

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 0-100  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,2.67%,0.506,-6.56%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,2.67%,0.506,-6.56%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,2.67%,0.506,-6.56%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.18%,0.403,0.21%,-0.330,$-575
1,Quarterly Rebal | TLH=10%,2.21%,0.408,0.21%,-0.409,"$-1,027"
2,Rel Threshold 25% | TLH=10%,2.29%,0.425,0.20%,-0.445,"$-1,154"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 0-100  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,2.67%,0.506,-6.56%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,2.67%,0.506,-6.56%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,2.67%,0.506,-6.56%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.18%,0.403,0.21%,-0.330,$-575
1,Quarterly Rebal | TLH=10%,2.21%,0.408,0.21%,-0.409,"$-1,027"
2,Rel Threshold 25% | TLH=10%,2.29%,0.425,0.20%,-0.445,"$-1,154"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 0-100  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,2.67%,0.506,-6.56%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,2.67%,0.506,-6.56%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,2.67%,0.506,-6.56%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,2.18%,0.403,0.21%,-0.330,$-575
1,Quarterly Rebal | TLH=10%,2.21%,0.408,0.21%,-0.409,"$-1,027"
2,Rel Threshold 25% | TLH=10%,2.29%,0.425,0.20%,-0.445,"$-1,154"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 10-90  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | TLH=10%,On (10%),-6.24%,-0.579,-17.17%,0.90%,0.178
1,Abs Threshold 5% | TLH=10%,On (10%),-6.21%,-0.608,-17.46%,0.91%,0.315
2,Rel Threshold 50% | No TLH,Off,-6.51%,-0.615,-17.43%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-6.21%,-0.608,0.91%,0.315,"$+4,055"
1,Rel Threshold 50% | TLH=10%,-6.24%,-0.579,0.90%,0.178,"$+2,781"
2,Quarterly Rebal | TLH=10%,-7.72%,-0.771,0.69%,-0.253,$-691

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 10-90  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),6.47%,2.188,-1.27%,0.12%,0.141
1,Yearly Rebal | TLH=10%,On (10%),6.43%,2.164,-1.29%,0.12%,0.115
2,Abs Threshold 5% | TLH=10%,On (10%),6.43%,2.164,-1.29%,0.12%,0.115

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,6.47%,2.188,0.12%,0.141,"$+1,389"
1,Yearly Rebal | TLH=10%,6.43%,2.164,0.12%,0.115,"$+1,363"
2,Abs Threshold 5% | TLH=10%,6.43%,2.164,0.12%,0.115,"$+1,363"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 10-90  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,3.66%,0.621,-6.59%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,3.66%,0.621,-6.59%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,3.66%,0.621,-6.59%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,3.18%,0.531,0.25%,-0.021,"$+1,177"
1,Rel Threshold 25% | TLH=10%,3.36%,0.562,0.24%,-0.106,$+853
2,Quarterly Rebal | TLH=10%,3.24%,0.541,0.24%,-0.121,$+783

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 10-90  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,5.35%,0.949,-6.59%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,5.35%,0.949,-6.59%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,5.35%,0.949,-6.59%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,4.38%,0.780,0.22%,-0.226,$-34
1,Rel Threshold 25% | TLH=10%,4.53%,0.809,0.21%,-0.309,$-499
2,Quarterly Rebal | TLH=10%,4.44%,0.791,0.22%,-0.313,$-536

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 10-90  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,5.35%,0.949,-6.59%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,5.35%,0.949,-6.59%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,5.35%,0.949,-6.59%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,4.38%,0.780,0.22%,-0.226,$-34
1,Rel Threshold 25% | TLH=10%,4.53%,0.809,0.21%,-0.309,$-499
2,Quarterly Rebal | TLH=10%,4.44%,0.791,0.22%,-0.313,$-536

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 10-90  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | No TLH,Off,5.35%,0.949,-6.59%,0.00%,0.000
1,Abs Threshold 10% | No TLH,Off,5.35%,0.949,-6.59%,0.00%,0.000
2,Abs Threshold 20% | No TLH,Off,5.35%,0.949,-6.59%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,4.38%,0.780,0.22%,-0.226,$-34
1,Rel Threshold 25% | TLH=10%,4.53%,0.809,0.21%,-0.309,$-499
2,Quarterly Rebal | TLH=10%,4.44%,0.791,0.22%,-0.313,$-536

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 100-0  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),-20.31%,-0.669,-49.99%,3.99%,0.561
1,Abs Threshold 5% | TLH=10%,On (10%),-20.32%,-0.670,-49.97%,4.02%,0.528
2,Abs Threshold 10% | TLH=10%,On (10%),-20.32%,-0.670,-49.97%,4.02%,0.528

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,-20.31%,-0.669,3.99%,0.561,"$+33,912"
1,Abs Threshold 5% | TLH=10%,-20.32%,-0.670,4.02%,0.528,"$+32,210"
2,Abs Threshold 10% | TLH=10%,-20.32%,-0.670,4.02%,0.528,"$+32,210"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 100-0  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),14.06%,1.192,-6.40%,0.40%,0.929
1,Abs Threshold 5% | TLH=10%,On (10%),14.06%,1.192,-6.40%,0.40%,0.929
2,Abs Threshold 10% | TLH=10%,On (10%),14.06%,1.192,-6.40%,0.40%,0.929

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,14.03%,1.190,0.42%,1.007,"$+4,511"
1,Yearly Rebal | TLH=10%,14.06%,1.192,0.40%,0.929,"$+4,136"
2,Abs Threshold 5% | TLH=10%,14.06%,1.192,0.40%,0.929,"$+4,136"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 100-0  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-5.30%,-0.421,-4.38%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-5.30%,-0.421,-4.38%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-5.30%,-0.421,-4.38%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-5.44%,-0.434,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-5.30%,-0.421,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-5.30%,-0.421,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 100-0  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,16.35%,0.948,-17.91%,0.00%,0.000
1,Quarterly Rebal | No TLH,Off,16.37%,0.943,-17.92%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,16.27%,0.936,-18.11%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,16.14%,0.930,0.56%,-0.289,$-543
1,Yearly Rebal | TLH=10%,16.12%,0.931,1.05%,-0.324,"$-2,683"
2,Abs Threshold 5% | TLH=10%,16.01%,0.918,1.06%,-0.361,"$-3,196"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 100-0  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,16.35%,0.948,-17.91%,0.00%,0.000
1,Quarterly Rebal | No TLH,Off,16.37%,0.943,-17.92%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,16.27%,0.936,-18.11%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,16.14%,0.930,0.56%,-0.289,$-543
1,Yearly Rebal | TLH=10%,16.12%,0.931,1.05%,-0.324,"$-2,683"
2,Abs Threshold 5% | TLH=10%,16.01%,0.918,1.06%,-0.361,"$-3,196"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 100-0  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | No TLH,Off,16.35%,0.948,-17.91%,0.00%,0.000
1,Quarterly Rebal | No TLH,Off,16.37%,0.943,-17.92%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,16.27%,0.936,-18.11%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,16.14%,0.930,0.56%,-0.289,$-543
1,Yearly Rebal | TLH=10%,16.12%,0.931,1.05%,-0.324,"$-2,683"
2,Abs Threshold 5% | TLH=10%,16.01%,0.918,1.06%,-0.361,"$-3,196"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 20-80  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | No TLH,Off,-11.43%,-0.810,-22.49%,0.00%,0.000
1,Rel Threshold 50% | TLH=10%,On (10%),-11.65%,-0.834,-22.80%,1.57%,-0.208
2,Rel Threshold 25% | No TLH,Off,-12.87%,-0.882,-23.09%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,-11.53%,-0.919,1.56%,0.102,"$+2,688"
1,Quarterly Rebal | TLH=10%,-13.23%,-0.947,1.20%,0.099,"$+2,253"
2,Monthly Rebal | TLH=10%,-13.16%,-0.907,1.46%,-0.038,$+459

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 20-80  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),7.54%,2.252,-1.24%,0.17%,0.623
1,Yearly Rebal | TLH=10%,On (10%),7.46%,2.224,-1.24%,0.14%,0.451
2,Abs Threshold 5% | TLH=10%,On (10%),7.46%,2.224,-1.24%,0.14%,0.451

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,7.54%,2.252,0.17%,0.623,"$+2,079"
1,Yearly Rebal | TLH=10%,7.46%,2.224,0.14%,0.451,"$+1,759"
2,Abs Threshold 5% | TLH=10%,7.46%,2.224,0.14%,0.451,"$+1,759"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 20-80  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-9.36%,-1.468,-3.31%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-9.36%,-1.468,-3.31%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-9.36%,-1.468,-3.31%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-9.35%,-1.470,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-9.36%,-1.468,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-9.36%,-1.468,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 20-80  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),5.66%,0.945,-5.93%,0.22%,0.648
1,Abs Threshold 5% | TLH=10%,On (10%),5.67%,0.942,-6.01%,0.22%,0.623
2,Abs Threshold 10% | TLH=10%,On (10%),5.67%,0.942,-6.01%,0.22%,0.623

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,5.66%,0.945,0.22%,0.648,"$+2,967"
1,Abs Threshold 5% | TLH=10%,5.67%,0.942,0.22%,0.623,"$+2,926"
2,Abs Threshold 10% | TLH=10%,5.67%,0.942,0.22%,0.623,"$+2,926"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 20-80  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),5.66%,0.945,-5.93%,0.22%,0.648
1,Abs Threshold 5% | TLH=10%,On (10%),5.67%,0.942,-6.01%,0.22%,0.623
2,Abs Threshold 10% | TLH=10%,On (10%),5.67%,0.942,-6.01%,0.22%,0.623

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,5.66%,0.945,0.22%,0.648,"$+2,967"
1,Abs Threshold 5% | TLH=10%,5.67%,0.942,0.22%,0.623,"$+2,926"
2,Abs Threshold 10% | TLH=10%,5.67%,0.942,0.22%,0.623,"$+2,926"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 20-80  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),5.66%,0.945,-5.93%,0.22%,0.648
1,Abs Threshold 5% | TLH=10%,On (10%),5.67%,0.942,-6.01%,0.22%,0.623
2,Abs Threshold 10% | TLH=10%,On (10%),5.67%,0.942,-6.01%,0.22%,0.623

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,5.66%,0.945,0.22%,0.648,"$+2,967"
1,Abs Threshold 5% | TLH=10%,5.67%,0.942,0.22%,0.623,"$+2,926"
2,Abs Threshold 10% | TLH=10%,5.67%,0.942,0.22%,0.623,"$+2,926"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 30-70  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | No TLH,Off,-15.05%,-0.882,-26.43%,0.00%,0.000
1,Abs Threshold 5% | No TLH,Off,-15.85%,-0.895,-26.70%,0.00%,0.000
2,Rel Threshold 50% | TLH=10%,On (10%),-15.53%,-0.920,-26.95%,1.69%,-0.341

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 25% | TLH=10%,-16.39%,-0.936,1.84%,0.275,"$+6,185"
1,Yearly Rebal | TLH=10%,-15.13%,-0.983,1.87%,0.106,"$+3,043"
2,Quarterly Rebal | TLH=10%,-16.95%,-0.995,1.50%,0.063,"$+1,949"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 30-70  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),8.44%,2.040,-1.66%,0.19%,0.766
1,Yearly Rebal | TLH=10%,On (10%),8.35%,2.019,-1.66%,0.17%,0.610
2,Abs Threshold 5% | TLH=10%,On (10%),8.35%,2.019,-1.66%,0.17%,0.610

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,8.44%,2.040,0.19%,0.766,"$+2,414"
1,Yearly Rebal | TLH=10%,8.35%,2.019,0.17%,0.610,"$+2,055"
2,Abs Threshold 5% | TLH=10%,8.35%,2.019,0.17%,0.610,"$+2,055"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 30-70  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-8.72%,-1.252,-3.45%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-8.72%,-1.252,-3.45%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-8.72%,-1.252,-3.45%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-8.71%,-1.257,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-8.72%,-1.252,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-8.72%,-1.252,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 30-70  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),7.25%,1.010,-7.42%,0.33%,0.384
1,Abs Threshold 5% | TLH=10%,On (10%),7.25%,1.002,-7.54%,0.33%,0.335
2,Abs Threshold 10% | TLH=10%,On (10%),7.25%,1.002,-7.54%,0.33%,0.335

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,7.25%,1.010,0.33%,0.384,"$+2,816"
1,Abs Threshold 5% | TLH=10%,7.25%,1.002,0.33%,0.335,"$+2,644"
2,Abs Threshold 10% | TLH=10%,7.25%,1.002,0.33%,0.335,"$+2,644"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 30-70  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),7.25%,1.010,-7.42%,0.33%,0.384
1,Abs Threshold 5% | TLH=10%,On (10%),7.25%,1.002,-7.54%,0.33%,0.335
2,Abs Threshold 10% | TLH=10%,On (10%),7.25%,1.002,-7.54%,0.33%,0.335

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,7.25%,1.010,0.33%,0.384,"$+2,816"
1,Abs Threshold 5% | TLH=10%,7.25%,1.002,0.33%,0.335,"$+2,644"
2,Abs Threshold 10% | TLH=10%,7.25%,1.002,0.33%,0.335,"$+2,644"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 30-70  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),7.25%,1.010,-7.42%,0.33%,0.384
1,Abs Threshold 5% | TLH=10%,On (10%),7.25%,1.002,-7.54%,0.33%,0.335
2,Abs Threshold 10% | TLH=10%,On (10%),7.25%,1.002,-7.54%,0.33%,0.335

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,7.25%,1.010,0.33%,0.384,"$+2,816"
1,Abs Threshold 5% | TLH=10%,7.25%,1.002,0.33%,0.335,"$+2,644"
2,Abs Threshold 10% | TLH=10%,7.25%,1.002,0.33%,0.335,"$+2,644"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 40-60  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Monthly Rebal | TLH=10%,On (10%),-20.31%,-0.951,-31.87%,1.84%,0.259
1,Rel Threshold 25% | No TLH,Off,-20.84%,-0.957,-32.02%,0.00%,0.000
2,Abs Threshold 5% | No TLH,Off,-20.10%,-0.985,-31.45%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,-18.38%,-1.051,3.35%,0.259,"$+9,853"
1,Monthly Rebal | TLH=10%,-20.31%,-0.951,1.84%,0.259,"$+5,824"
2,Quarterly Rebal | TLH=10%,-22.05%,-1.182,3.36%,-0.331,"$-10,431"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 40-60  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),9.55%,1.849,-2.35%,0.22%,0.863
1,Yearly Rebal | TLH=10%,On (10%),9.46%,1.832,-2.34%,0.20%,0.717
2,Abs Threshold 5% | TLH=10%,On (10%),9.46%,1.832,-2.34%,0.20%,0.717

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,9.55%,1.849,0.22%,0.863,"$+2,759"
1,Yearly Rebal | TLH=10%,9.46%,1.832,0.20%,0.717,"$+2,370"
2,Abs Threshold 5% | TLH=10%,9.46%,1.832,0.20%,0.717,"$+2,370"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 40-60  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-8.68%,-1.131,-3.61%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-8.68%,-1.131,-3.61%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-8.68%,-1.131,-3.61%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-8.70%,-1.139,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-8.68%,-1.131,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-8.68%,-1.131,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 40-60  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),8.86%,1.031,-8.93%,0.34%,0.850
1,Abs Threshold 5% | TLH=10%,On (10%),8.86%,1.023,-9.07%,0.35%,0.807
2,Abs Threshold 10% | TLH=10%,On (10%),8.86%,1.023,-9.07%,0.35%,0.807

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,8.86%,1.031,0.34%,0.850,"$+4,782"
1,Abs Threshold 5% | TLH=10%,8.86%,1.023,0.35%,0.807,"$+4,737"
2,Abs Threshold 10% | TLH=10%,8.86%,1.023,0.35%,0.807,"$+4,737"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 40-60  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),8.86%,1.031,-8.93%,0.34%,0.850
1,Abs Threshold 5% | TLH=10%,On (10%),8.86%,1.023,-9.07%,0.35%,0.807
2,Abs Threshold 10% | TLH=10%,On (10%),8.86%,1.023,-9.07%,0.35%,0.807

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,8.86%,1.031,0.34%,0.850,"$+4,782"
1,Abs Threshold 5% | TLH=10%,8.86%,1.023,0.35%,0.807,"$+4,737"
2,Abs Threshold 10% | TLH=10%,8.86%,1.023,0.35%,0.807,"$+4,737"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 40-60  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),8.86%,1.031,-8.93%,0.34%,0.850
1,Abs Threshold 5% | TLH=10%,On (10%),8.86%,1.023,-9.07%,0.35%,0.807
2,Abs Threshold 10% | TLH=10%,On (10%),8.86%,1.023,-9.07%,0.35%,0.807

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,8.86%,1.031,0.34%,0.850,"$+4,782"
1,Abs Threshold 5% | TLH=10%,8.86%,1.023,0.35%,0.807,"$+4,737"
2,Abs Threshold 10% | TLH=10%,8.86%,1.023,0.35%,0.807,"$+4,737"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 50-50  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,-24.55%,-0.975,-36.32%,0.00%,0.000
1,Monthly Rebal | TLH=10%,On (10%),-24.18%,-0.977,-36.12%,1.92%,0.220
2,Abs Threshold 5% | No TLH,Off,-23.65%,-0.986,-35.71%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,-22.42%,-1.070,3.64%,0.223,"$+9,221"
1,Monthly Rebal | TLH=10%,-24.18%,-0.977,1.92%,0.220,"$+5,216"
2,Rel Threshold 25% | TLH=10%,-24.67%,-1.023,3.02%,-0.070,"$-1,249"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 50-50  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),10.33%,1.709,-2.91%,0.26%,0.925
1,Yearly Rebal | TLH=10%,On (10%),10.24%,1.695,-2.90%,0.23%,0.789
2,Abs Threshold 5% | TLH=10%,On (10%),10.24%,1.695,-2.90%,0.23%,0.789

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,10.33%,1.709,0.26%,0.925,"$+3,109"
1,Yearly Rebal | TLH=10%,10.24%,1.695,0.23%,0.789,"$+2,699"
2,Abs Threshold 5% | TLH=10%,10.24%,1.695,0.23%,0.789,"$+2,699"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 50-50  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-8.09%,-0.960,-3.72%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-8.09%,-0.960,-3.72%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-8.09%,-0.960,-3.72%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-8.14%,-0.971,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-8.09%,-0.960,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-8.09%,-0.960,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 50-50  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),10.29%,1.032,-10.33%,0.51%,0.125
1,Abs Threshold 5% | TLH=10%,On (10%),10.28%,1.021,-10.52%,0.54%,0.091
2,Abs Threshold 10% | TLH=10%,On (10%),10.28%,1.021,-10.52%,0.54%,0.091

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.91%,0.989,0.39%,0.443,"$+3,418"
1,Yearly Rebal | TLH=10%,10.29%,1.032,0.51%,0.125,"$+2,108"
2,Abs Threshold 5% | TLH=10%,10.28%,1.021,0.54%,0.091,"$+1,934"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 50-50  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),10.29%,1.032,-10.33%,0.51%,0.125
1,Abs Threshold 5% | TLH=10%,On (10%),10.28%,1.021,-10.52%,0.54%,0.091
2,Abs Threshold 10% | TLH=10%,On (10%),10.28%,1.021,-10.52%,0.54%,0.091

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.91%,0.989,0.39%,0.443,"$+3,418"
1,Yearly Rebal | TLH=10%,10.29%,1.032,0.51%,0.125,"$+2,108"
2,Abs Threshold 5% | TLH=10%,10.28%,1.021,0.54%,0.091,"$+1,934"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 50-50  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),10.29%,1.032,-10.33%,0.51%,0.125
1,Abs Threshold 5% | TLH=10%,On (10%),10.28%,1.021,-10.52%,0.54%,0.091
2,Abs Threshold 10% | TLH=10%,On (10%),10.28%,1.021,-10.52%,0.54%,0.091

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,9.91%,0.989,0.39%,0.443,"$+3,418"
1,Yearly Rebal | TLH=10%,10.29%,1.032,0.51%,0.125,"$+2,108"
2,Abs Threshold 5% | TLH=10%,10.28%,1.021,0.54%,0.091,"$+1,934"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 60-40  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 25% | No TLH,Off,-25.76%,-0.944,-37.87%,0.00%,0.000
1,Rel Threshold 50% | No TLH,Off,-23.94%,-0.952,-36.52%,0.00%,0.000
2,Monthly Rebal | TLH=10%,On (10%),-26.02%,-0.973,-38.11%,2.19%,0.221

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-26.02%,-0.973,2.19%,0.221,"$+5,823"
1,Yearly Rebal | TLH=10%,-24.73%,-1.067,3.70%,0.139,"$+6,128"
2,Quarterly Rebal | TLH=10%,-27.30%,-1.043,2.63%,-0.258,"$-6,051"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 60-40  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),11.36%,1.578,-3.59%,0.28%,0.966
1,Yearly Rebal | TLH=10%,On (10%),11.28%,1.567,-3.57%,0.26%,0.835
2,Abs Threshold 5% | TLH=10%,On (10%),11.28%,1.567,-3.57%,0.26%,0.835

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,11.36%,1.578,0.28%,0.966,"$+3,399"
1,Yearly Rebal | TLH=10%,11.28%,1.567,0.26%,0.835,"$+2,964"
2,Abs Threshold 5% | TLH=10%,11.28%,1.567,0.26%,0.835,"$+2,964"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 60-40  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-7.75%,-0.829,-3.91%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-7.75%,-0.829,-3.91%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-7.75%,-0.829,-3.91%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-7.83%,-0.841,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-7.75%,-0.829,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-7.75%,-0.829,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 60-40  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),11.93%,1.032,-12.09%,0.60%,0.374
1,Abs Threshold 5% | TLH=10%,On (10%),11.92%,1.020,-12.23%,0.63%,0.331
2,Abs Threshold 10% | TLH=10%,On (10%),11.92%,1.020,-12.23%,0.63%,0.331

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.47%,0.986,0.41%,0.515,"$+3,933"
1,Yearly Rebal | TLH=10%,11.93%,1.032,0.60%,0.374,"$+4,072"
2,Abs Threshold 5% | TLH=10%,11.92%,1.020,0.63%,0.331,"$+3,890"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 60-40  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),11.93%,1.032,-12.09%,0.60%,0.374
1,Abs Threshold 5% | TLH=10%,On (10%),11.92%,1.020,-12.23%,0.63%,0.331
2,Abs Threshold 10% | TLH=10%,On (10%),11.92%,1.020,-12.23%,0.63%,0.331

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.47%,0.986,0.41%,0.515,"$+3,933"
1,Yearly Rebal | TLH=10%,11.93%,1.032,0.60%,0.374,"$+4,072"
2,Abs Threshold 5% | TLH=10%,11.92%,1.020,0.63%,0.331,"$+3,890"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 60-40  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),11.93%,1.032,-12.09%,0.60%,0.374
1,Abs Threshold 5% | TLH=10%,On (10%),11.92%,1.020,-12.23%,0.63%,0.331
2,Abs Threshold 10% | TLH=10%,On (10%),11.92%,1.020,-12.23%,0.63%,0.331

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,11.47%,0.986,0.41%,0.515,"$+3,933"
1,Yearly Rebal | TLH=10%,11.93%,1.032,0.60%,0.374,"$+4,072"
2,Abs Threshold 5% | TLH=10%,11.92%,1.020,0.63%,0.331,"$+3,890"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 70-30  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | TLH=10%,On (10%),-13.50%,-0.570,-40.44%,2.98%,0.951
1,Abs Threshold 5% | TLH=10%,On (10%),-13.82%,-0.596,-41.03%,2.82%,0.620
2,Abs Threshold 10% | TLH=10%,On (10%),-14.21%,-0.632,-40.45%,2.87%,0.496

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,-13.50%,-0.570,2.98%,0.951,"$+45,521"
1,Abs Threshold 5% | TLH=10%,-13.82%,-0.596,2.82%,0.620,"$+28,483"
2,Yearly Rebal | TLH=10%,-14.49%,-0.637,2.80%,0.562,"$+25,545"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 70-30  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),12.33%,1.476,-4.25%,0.32%,0.996
1,Yearly Rebal | TLH=10%,On (10%),12.25%,1.468,-4.23%,0.30%,0.868
2,Abs Threshold 5% | TLH=10%,On (10%),12.25%,1.468,-4.23%,0.30%,0.868

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,12.33%,1.476,0.32%,0.996,"$+3,742"
1,Yearly Rebal | TLH=10%,12.25%,1.468,0.30%,0.868,"$+3,275"
2,Abs Threshold 5% | TLH=10%,12.25%,1.468,0.30%,0.868,"$+3,275"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 70-30  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-7.38%,-0.726,-4.05%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-7.38%,-0.726,-4.05%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-7.38%,-0.726,-4.05%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-7.48%,-0.739,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-7.38%,-0.726,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-7.38%,-0.726,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 70-30  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),13.50%,1.033,-13.73%,0.72%,0.126
1,Yearly Rebal | No TLH,Off,13.29%,1.021,-13.47%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),13.47%,1.020,-13.88%,0.75%,0.097

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,13.50%,1.033,0.72%,0.126,"$+2,478"
1,Monthly Rebal | TLH=10%,13.04%,0.992,0.48%,0.119,"$+2,075"
2,Abs Threshold 5% | TLH=10%,13.47%,1.020,0.75%,0.097,"$+2,274"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 70-30  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),13.50%,1.033,-13.73%,0.72%,0.126
1,Yearly Rebal | No TLH,Off,13.29%,1.021,-13.47%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),13.47%,1.020,-13.88%,0.75%,0.097

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,13.50%,1.033,0.72%,0.126,"$+2,478"
1,Monthly Rebal | TLH=10%,13.04%,0.992,0.48%,0.119,"$+2,075"
2,Abs Threshold 5% | TLH=10%,13.47%,1.020,0.75%,0.097,"$+2,274"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 70-30  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),13.50%,1.033,-13.73%,0.72%,0.126
1,Yearly Rebal | No TLH,Off,13.29%,1.021,-13.47%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),13.47%,1.020,-13.88%,0.75%,0.097

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,13.50%,1.033,0.72%,0.126,"$+2,478"
1,Monthly Rebal | TLH=10%,13.04%,0.992,0.48%,0.119,"$+2,075"
2,Abs Threshold 5% | TLH=10%,13.47%,1.020,0.75%,0.097,"$+2,274"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 80-20  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Rel Threshold 50% | TLH=10%,On (10%),-14.94%,-0.581,-42.96%,3.42%,0.960
1,Abs Threshold 5% | TLH=10%,On (10%),-15.32%,-0.604,-43.48%,3.25%,0.606
2,Abs Threshold 10% | TLH=10%,On (10%),-15.95%,-0.642,-43.42%,3.31%,0.519

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Rel Threshold 50% | TLH=10%,-14.94%,-0.581,3.42%,0.960,"$+51,754"
1,Abs Threshold 5% | TLH=10%,-15.32%,-0.604,3.25%,0.606,"$+31,452"
2,Yearly Rebal | TLH=10%,-16.23%,-0.646,3.24%,0.578,"$+29,680"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 80-20  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),13.08%,1.378,-4.92%,0.36%,1.017
1,Yearly Rebal | TLH=10%,On (10%),13.03%,1.373,-4.90%,0.34%,0.901
2,Abs Threshold 5% | TLH=10%,On (10%),13.03%,1.373,-4.90%,0.34%,0.901

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,13.08%,1.378,0.36%,1.017,"$+4,120"
1,Yearly Rebal | TLH=10%,13.03%,1.373,0.34%,0.901,"$+3,647"
2,Abs Threshold 5% | TLH=10%,13.03%,1.373,0.34%,0.901,"$+3,647"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 80-20  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-7.37%,-0.667,-4.22%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-7.37%,-0.667,-4.22%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-7.37%,-0.667,-4.22%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-7.49%,-0.681,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-7.37%,-0.667,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-7.37%,-0.667,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 80-20  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),15.02%,1.028,-15.37%,0.76%,0.242
1,Abs Threshold 5% | TLH=10%,On (10%),14.97%,1.015,-15.50%,0.79%,0.213
2,Abs Threshold 10% | TLH=10%,On (10%),14.97%,1.015,-15.50%,0.79%,0.213

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,15.02%,1.028,0.76%,0.242,"$+3,640"
1,Abs Threshold 5% | TLH=10%,14.97%,1.015,0.79%,0.213,"$+3,458"
2,Abs Threshold 10% | TLH=10%,14.97%,1.015,0.79%,0.213,"$+3,458"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 80-20  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),15.02%,1.028,-15.37%,0.76%,0.242
1,Abs Threshold 5% | TLH=10%,On (10%),14.97%,1.015,-15.50%,0.79%,0.213
2,Abs Threshold 10% | TLH=10%,On (10%),14.97%,1.015,-15.50%,0.79%,0.213

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,15.02%,1.028,0.76%,0.242,"$+3,640"
1,Abs Threshold 5% | TLH=10%,14.97%,1.015,0.79%,0.213,"$+3,458"
2,Abs Threshold 10% | TLH=10%,14.97%,1.015,0.79%,0.213,"$+3,458"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 80-20  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),15.02%,1.028,-15.37%,0.76%,0.242
1,Abs Threshold 5% | TLH=10%,On (10%),14.97%,1.015,-15.50%,0.79%,0.213
2,Abs Threshold 10% | TLH=10%,On (10%),14.97%,1.015,-15.50%,0.79%,0.213

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,15.02%,1.028,0.76%,0.242,"$+3,640"
1,Abs Threshold 5% | TLH=10%,14.97%,1.015,0.79%,0.213,"$+3,458"
2,Abs Threshold 10% | TLH=10%,14.97%,1.015,0.79%,0.213,"$+3,458"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 90-10  |  Bear (2007–2008)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Abs Threshold 5% | TLH=10%,On (10%),-17.41%,-0.612,-46.77%,3.41%,0.736
1,Rel Threshold 25% | TLH=10%,On (10%),-18.25%,-0.641,-47.85%,3.50%,0.642
2,Abs Threshold 10% | TLH=10%,On (10%),-18.09%,-0.652,-47.09%,3.52%,0.500

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Abs Threshold 5% | TLH=10%,-17.41%,-0.612,3.41%,0.736,"$+38,963"
1,Rel Threshold 25% | TLH=10%,-18.25%,-0.641,3.50%,0.642,"$+34,728"
2,Yearly Rebal | TLH=10%,-18.37%,-0.655,3.44%,0.558,"$+29,818"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 90-10  |  Baseline (2010–2019)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | TLH=10%,On (10%),13.90%,1.269,-5.85%,0.42%,1.031
1,Yearly Rebal | TLH=10%,On (10%),13.90%,1.268,-5.82%,0.40%,0.930
2,Abs Threshold 5% | TLH=10%,On (10%),13.90%,1.268,-5.82%,0.40%,0.930

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Quarterly Rebal | TLH=10%,13.90%,1.269,0.42%,1.031,"$+4,591"
1,Yearly Rebal | TLH=10%,13.90%,1.268,0.40%,0.930,"$+4,119"
2,Abs Threshold 5% | TLH=10%,13.90%,1.268,0.40%,0.930,"$+4,119"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 90-10  |  Bull (2023–2024)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Quarterly Rebal | No TLH,Off,-6.43%,-0.531,-4.34%,0.00%,0.000
1,Quarterly Rebal | TLH=10%,On (10%),-6.43%,-0.531,-4.34%,0.00%,0.000
2,Yearly Rebal | No TLH,Off,-6.43%,-0.531,-4.34%,0.00%,0.000

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Monthly Rebal | TLH=10%,-6.59%,-0.545,0.00%,0.000,$+0
1,Quarterly Rebal | TLH=10%,-6.43%,-0.531,0.00%,0.000,$+0
2,Yearly Rebal | TLH=10%,-6.43%,-0.531,0.00%,0.000,$+0

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 90-10  |  Past 5Y (2021–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),16.77%,1.025,-17.24%,0.89%,0.063
1,Yearly Rebal | No TLH,Off,16.60%,1.018,-16.89%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),16.69%,1.011,-17.37%,0.94%,0.037

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,16.77%,1.025,0.89%,0.063,"$+2,125"
1,Abs Threshold 5% | TLH=10%,16.69%,1.011,0.94%,0.037,"$+1,860"
2,Abs Threshold 10% | TLH=10%,16.69%,1.011,0.94%,0.037,"$+1,860"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 90-10  |  Past 10Y (2016–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),16.77%,1.025,-17.24%,0.89%,0.063
1,Yearly Rebal | No TLH,Off,16.60%,1.018,-16.89%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),16.69%,1.011,-17.37%,0.94%,0.037

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,16.77%,1.025,0.89%,0.063,"$+2,125"
1,Abs Threshold 5% | TLH=10%,16.69%,1.011,0.94%,0.037,"$+1,860"
2,Abs Threshold 10% | TLH=10%,16.69%,1.011,0.94%,0.037,"$+1,860"

──────────────────────────────────────────────────────────────────────────────────────────
  Target Allocation ETF - 90-10  |  Past 20Y (2006–2025)
──────────────────────────────────────────────────────────────────────────────────────────
  Top 3 by Sharpe Ratio (all strategies):

,Strategy,TLH,CAGR,Sharpe Ratio,Max Drawdown,Tracking Error,Information Ratio
0,Yearly Rebal | TLH=10%,On (10%),16.77%,1.025,-17.24%,0.89%,0.063
1,Yearly Rebal | No TLH,Off,16.60%,1.018,-16.89%,0.00%,0.000
2,Abs Threshold 5% | TLH=10%,On (10%),16.69%,1.011,-17.37%,0.94%,0.037

  Top 3 TLH strategies by Information Ratio (TLH value-add):

,Strategy,CAGR,Sharpe Ratio,Tracking Error,Information Ratio,Tax Alpha 2 ($)
0,Yearly Rebal | TLH=10%,16.77%,1.025,0.89%,0.063,"$+2,125"
1,Abs Threshold 5% | TLH=10%,16.69%,1.011,0.94%,0.037,"$+1,860"
2,Abs Threshold 10% | TLH=10%,16.69%,1.011,0.94%,0.037,"$+1,860"

In [21]:
# ══════════════════════════════════════════════════════════════════════════════
# CELL 12 — EXPORT TO CSV (grouped by category)
#
# Outputs:
#   full_results.csv           — all portfolios, all periods, all strategies
#   outputs/equity_heavy.csv   — portfolios with >=70% equity
#   outputs/balanced.csv       — portfolios with 30-69% equity
#   outputs/fixed_income.csv   — portfolios with <30% equity
# ══════════════════════════════════════════════════════════════════════════════

export_df = results_df.copy()

# ── Rename columns for clean export ──────────────────────────────────────────
export_df = export_df.rename(columns={
    'Period':               'Market State',
    'Strategy':             'Strategy Label',
    'Strategy Type':        'Rebal Type',
    'Strategy Value':       'Rebal Value',
    'TLH':                  'TLH Status',
    'Final NAV ($)':        'Final NAV',
    'Volatility':           'Volatility (Ann)',
    'Tracking Error':       'Tracking Error (Ann)',
    'Skewness':             'Return Skewness',
    'Kurtosis':             'Return Kurtosis',
    'Tax Paid ($)':         'Tax Paid',
    'Losses Harvested ($)': 'Realized Losses (All)',
    'TLH Losses ($)':       'TLH Losses',
    'Rebal Losses ($)':     'Rebal Losses',
    'TLH Events':           'TLH Event Count',
    'Exec Costs ($)':       'Execution Costs',
    'Tax Alpha 2 ($)':      'Tax Alpha 2',
    'Loss CF ST ($)':       'Loss Carryforward ST',
    'Loss CF LT ($)':       'Loss Carryforward LT',
    'Liquidation NAV ($)':    'Liquidation NAV',
    'Unrealized Gain ST ($)': 'Unrealized Gain ST',
    'Unrealized Gain LT ($)': 'Unrealized Gain LT',
    'Liquidation Tax ($)':    'Liquidation Tax',
    'Liquidation Exec Cost ($)': 'Liquidation Exec Cost',
    'Equity %':              'Equity Allocation',
})

# ── Map period names to market conditions ────────────────────────────────────
condition_map = {
    'Bear (2007\u20132008)':     'Bear Market',
    'Baseline (2010\u20132019)': 'Baseline Market',
    'Bull (2023\u20132024)':     'Bull Market',
    'Past 5Y (2021\u20132025)':  'Past 5 Years',
    'Past 10Y (2016\u20132025)': 'Past 10 Years',
    'Past 20Y (2006\u20132025)': 'Past 20 Years',
}
export_df['Market Condition'] = export_df['Market State'].map(condition_map).fillna(export_df['Market State'])

type_map = {'calendar': 'Calendar', 'abs': 'Absolute Threshold', 'rel': 'Relative Threshold'}
export_df['Rebal Type'] = export_df['Rebal Type'].map(type_map).fillna(export_df['Rebal Type'])

# ── Column ordering ──────────────────────────────────────────────────────────
ORDERED_COLS = [
    # Grouping
    'Category', 'Model Family', 'Portfolio', 'Equity Allocation',
    'Market Condition', 'Market State',
    'Rebal Type', 'Rebal Value', 'TLH Status', 'Strategy Label',
    # Performance
    'Final NAV', 'Total Return', 'CAGR',
    'Volatility (Ann)', 'Sharpe Ratio', 'Max Drawdown',
    'Return Skewness', 'Return Kurtosis',
    # Risk vs benchmark
    'Tracking Error (Ann)', 'Information Ratio',
    # Tax / TLH
    'Tax Paid', 'Realized Losses (All)', 'TLH Losses', 'Rebal Losses', 'TLH Event Count',
    'Execution Costs', 'Tax Alpha 2',
    'Loss Carryforward ST', 'Loss Carryforward LT',
    # Liquidation
    'Liquidation NAV', 'Unrealized Gain ST', 'Unrealized Gain LT',
    'Liquidation Tax', 'Liquidation Exec Cost',
]
final_cols = [c for c in ORDERED_COLS if c in export_df.columns]
export_df = export_df[final_cols]

# ── Sort: Category -> Model Family -> Portfolio -> Period -> Strategy ────────
_period_order = {
    'Bear Market': 0, 'Baseline Market': 1, 'Bull Market': 2,
    'Past 5 Years': 3, 'Past 10 Years': 4, 'Past 20 Years': 5,
}
export_df['_sort_period'] = export_df['Market Condition'].map(_period_order).fillna(9)
_cat_order = {'Equity-Heavy': 0, 'Balanced': 1, 'Fixed Income-Heavy': 2}
export_df['_sort_cat'] = export_df['Category'].map(_cat_order).fillna(9)
export_df = (
    export_df
    .sort_values(['_sort_cat', 'Model Family', 'Portfolio', '_sort_period', 'Rebal Type', 'TLH Status'])
    .drop(columns=['_sort_period', '_sort_cat'])
    .reset_index(drop=True)
)

# ── Export full results ──────────────────────────────────────────────────────
OUTPUTS_DIR = NOTEBOOK_DIR / 'outputs'
OUTPUTS_DIR.mkdir(exist_ok=True)

CSV_PATH = NOTEBOOK_DIR / 'full_results.csv'
export_df.to_csv(CSV_PATH, index=False, float_format='%.6f')
print(f'Exported: {CSV_PATH}')
print(f'Shape: {export_df.shape[0]} rows x {export_df.shape[1]} columns')

# ── Export per-category CSVs ─────────────────────────────────────────────────
for cat in ['Equity-Heavy', 'Balanced', 'Fixed Income-Heavy']:
    cat_df = export_df[export_df['Category'] == cat]
    if cat_df.empty:
        continue
    fname = cat.lower().replace('-', '_').replace(' ', '_') + '.csv'
    cat_path = OUTPUTS_DIR / fname
    cat_df.to_csv(cat_path, index=False, float_format='%.6f')
    n_ports = cat_df['Portfolio'].nunique()
    print(f'  {cat:20s}: {cat_path.name}  ({len(cat_df):,} rows, {n_ports} portfolios)')

print(f'\nColumn list ({len(final_cols)}):')
for i, col in enumerate(final_cols, 1):
    print(f'  {i:2d}. {col}')

display(export_df.head(3))

Exported: c:\Users\ry092\Desktop\MIS 382N - Capstone\portfolio-tlh-optimizer\Backtest\full_results.csv
Shape: 15136 rows x 34 columns
  Equity-Heavy        : equity_heavy.csv  (3,360 rows, 35 portfolios)
  Balanced            : balanced.csv  (7,584 rows, 79 portfolios)
  Fixed Income-Heavy  : fixed_income_heavy.csv  (4,192 rows, 44 portfolios)

Column list (34):
   1. Category
   2. Model Family
   3. Portfolio
   4. Equity Allocation
   5. Market Condition
   6. Market State
   7. Rebal Type
   8. Rebal Value
   9. TLH Status
  10. Strategy Label
  11. Final NAV
  12. Total Return
  13. CAGR
  14. Volatility (Ann)
  15. Sharpe Ratio
  16. Max Drawdown
  17. Return Skewness
  18. Return Kurtosis
  19. Tracking Error (Ann)
  20. Information Ratio
  21. Tax Paid
  22. Realized Losses (All)
  23. TLH Losses
  24. Rebal Losses
  25. TLH Event Count
  26. Execution Costs
  27. Tax Alpha 2
  28. Loss Carryforward ST
  29. Loss Carryforward LT
  30. Liquidation NAV
  31. Unrealized Gain ST
  32. Unrealized Gain LT
  33. Liquidation Tax
  34. Liquidation Exec Cost

,Category,Model Family,Portfolio,Equity Allocation,Market Condition,Market State,Rebal Type,Rebal Value,TLH Status,Strategy Label,...,TLH Event Count,Execution Costs,Tax Alpha 2,Loss Carryforward ST,Loss Carryforward LT,Liquidation NAV,Unrealized Gain ST,Unrealized Gain LT,Liquidation Tax,Liquidation Exec Cost
0,Equity-Heavy,FFG Qualified,FFG Qualified - 100-0,0.88,Bear Market,Bear (2007–2008),Absolute Threshold,0.05,Off,Abs Threshold 5% | No TLH,...,0,1198.56,NaN,0.0,0.0,598465.46,0.0,-400668.22,-1050.0,717.76
1,Equity-Heavy,FFG Qualified,FFG Qualified - 100-0,0.88,Bear Market,Bear (2007–2008),Absolute Threshold,0.1,Off,Abs Threshold 10% | No TLH,...,0,1198.56,NaN,0.0,0.0,598465.46,0.0,-400668.22,-1050.0,717.76
2,Equity-Heavy,FFG Qualified,FFG Qualified - 100-0,0.88,Bear Market,Bear (2007–2008),Absolute Threshold,0.2,Off,Abs Threshold 20% | No TLH,...,0,1198.56,NaN,0.0,0.0,598465.46,0.0,-400668.22,-1050.0,717.76

In [22]:
# ══════════════════════════════════════════════════════════════════════════════
# CELL 13 — PLAYBOOK EXPORT (grouped by Category + Model Family)
# ══════════════════════════════════════════════════════════════════════════════
from openpyxl.styles import PatternFill, Font, Alignment, Border, Side
from openpyxl.utils import get_column_letter

PLAYBOOK_PATH = NOTEBOOK_DIR / 'strategy_playbook.xlsx'
_period_order = {
    'Bear Market': 0, 'Baseline Market': 1, 'Bull Market': 2,
    'Past 5 Years': 3, 'Past 10 Years': 4, 'Past 20 Years': 5,
}

# ── 1. PLAYBOOK SHEET — TLH On rows, composite-ranked per portfolio x period ─
pb = export_df[export_df['TLH Status'] == 'On (10%)'].copy()

# Rank within each (Portfolio, Market Condition) group
_grp = ['Portfolio', 'Market Condition']
pb['_rank_sharpe']    = pb.groupby(_grp)['Sharpe Ratio'].rank(ascending=True)
pb['_rank_cagr']      = pb.groupby(_grp)['CAGR'].rank(ascending=True)
pb['_rank_dd']        = pb.groupby(_grp)['Max Drawdown'].rank(ascending=False)
pb['_ir_filled']      = pb['Information Ratio'].fillna(0)
pb['_rank_ir']        = pb.groupby(_grp)['_ir_filled'].rank(ascending=True)
pb['_ta_filled']      = pb['Tax Alpha 2'].fillna(0)
pb['_rank_tax_alpha'] = pb.groupby(_grp)['_ta_filled'].rank(ascending=True)

# Composite: Tax Alpha 30%, Sharpe 25%, CAGR 20%, MaxDD 15%, IR 10%
pb['Composite Score'] = (
    0.30 * pb['_rank_tax_alpha'] +
    0.25 * pb['_rank_sharpe'] +
    0.20 * pb['_rank_cagr'] +
    0.15 * pb['_rank_dd'] +
    0.10 * pb['_rank_ir']
).round(3)

pb['Rank'] = (
    pb.groupby(_grp)['Composite Score']
    .rank(ascending=False, method='min').astype(int)
)

pb['_sort'] = pb['Market Condition'].map(_period_order).fillna(9)
_cat_order = {'Equity-Heavy': 0, 'Balanced': 1, 'Fixed Income-Heavy': 2}
pb['_sort_cat'] = pb['Category'].map(_cat_order).fillna(9)
pb = pb.sort_values(['_sort_cat', 'Model Family', 'Portfolio', '_sort', 'Rank'])
pb = pb.drop(columns=[c for c in pb.columns if c.startswith('_')])

PLAYBOOK_COLS = [
    'Category', 'Model Family', 'Portfolio', 'Market Condition', 'Rank',
    'Rebal Type', 'Rebal Value', 'Strategy Label',
    'CAGR', 'Sharpe Ratio', 'Max Drawdown',
    'Realized Losses (All)', 'TLH Event Count', 'Tax Alpha 2',
    'Tracking Error (Ann)', 'Information Ratio', 'Composite Score',
]
pb_out = pb[[c for c in PLAYBOOK_COLS if c in pb.columns]].reset_index(drop=True)

for col in ['CAGR', 'Sharpe Ratio', 'Max Drawdown', 'Tracking Error (Ann)', 'Information Ratio']:
    if col in pb_out.columns:
        pb_out[col] = pb_out[col].round(4)
for col in ['Realized Losses (All)', 'Tax Alpha 2']:
    if col in pb_out.columns:
        pb_out[col] = pb_out[col].round(2)

# ── 2. TLH VALUE-ADD SHEET — delta metrics (On minus Off) ───────────────────
tlh_on  = export_df[export_df['TLH Status'] == 'On (10%)'].copy()
tlh_off = export_df[export_df['TLH Status'] == 'Off'].copy()

merge_keys = ['Category', 'Model Family', 'Portfolio', 'Market Condition', 'Rebal Type', 'Rebal Value']
va = tlh_on.merge(
    tlh_off[merge_keys + ['CAGR', 'Sharpe Ratio', 'Max Drawdown', 'Final NAV']],
    on=merge_keys,
    suffixes=('', '_bench'),
)
va['Delta CAGR']         = (va['CAGR']        - va['CAGR_bench']).round(4)
va['Delta Sharpe']       = (va['Sharpe Ratio'] - va['Sharpe Ratio_bench']).round(4)
va['Delta Max Drawdown'] = (va['Max Drawdown'] - va['Max Drawdown_bench']).round(4)
va['Delta Final NAV']    = (va['Final NAV']    - va['Final NAV_bench']).round(2)

va['_sort'] = va['Market Condition'].map(_period_order).fillna(9)
va['_sort_cat'] = va['Category'].map(_cat_order).fillna(9)
va = va.sort_values(['_sort_cat', 'Model Family', 'Portfolio', '_sort', 'Rebal Type'])

VA_COLS = [
    'Category', 'Model Family', 'Portfolio', 'Market Condition',
    'Rebal Type', 'Rebal Value', 'Strategy Label',
    'Delta CAGR', 'Delta Sharpe', 'Delta Max Drawdown', 'Delta Final NAV',
    'Realized Losses (All)', 'TLH Event Count', 'Tax Alpha 2',
    'Tracking Error (Ann)', 'Information Ratio',
]
va_out = va[[c for c in VA_COLS if c in va.columns]].reset_index(drop=True)

# ── 3. RECOMMENDATIONS SHEET — Rank 1 from each group ───────────────────────
rec_out = pb_out[pb_out['Rank'] == 1].copy()

REC_COLS = [
    'Category', 'Model Family', 'Portfolio', 'Market Condition',
    'Strategy Label', 'Rebal Type', 'Rebal Value',
    'CAGR', 'Sharpe Ratio', 'Max Drawdown',
    'Realized Losses (All)', 'Tax Alpha 2', 'Composite Score',
]
rec_out = rec_out[[c for c in REC_COLS if c in rec_out.columns]].reset_index(drop=True)

# ── 4. RAW DATA SHEET ────────────────────────────────────────────────────────
raw_out = export_df.copy()
raw_out['_sort'] = raw_out['Market Condition'].map(_period_order).fillna(9)
raw_out['_sort_cat'] = raw_out['Category'].map(_cat_order).fillna(9)
raw_out = (
    raw_out
    .sort_values(['_sort_cat', 'Model Family', 'Portfolio', '_sort', 'Rebal Type', 'TLH Status'])
    .drop(columns=['_sort', '_sort_cat'])
    .reset_index(drop=True)
)

# ── Write Excel ──────────────────────────────────────────────────────────────
with pd.ExcelWriter(PLAYBOOK_PATH, engine='openpyxl') as writer:
    rec_out.to_excel(writer, sheet_name='Recommendations', index=False)
    pb_out.to_excel(writer, sheet_name='Playbook',         index=False)
    va_out.to_excel(writer, sheet_name='TLH Value-Add',    index=False)
    raw_out.to_excel(writer, sheet_name='Raw Data',        index=False)

    # Auto-fit column widths
    for sheet_name in writer.sheets:
        ws = writer.sheets[sheet_name]
        for col_cells in ws.columns:
            max_len = max(len(str(c.value or '')) for c in col_cells)
            header_len = len(str(col_cells[0].value or ''))
            ws.column_dimensions[get_column_letter(col_cells[0].column)].width = min(max(max_len, header_len) + 2, 30)

print(f'Playbook exported -> {PLAYBOOK_PATH}')
print(f'  Recommendations : {len(rec_out):,} rows')
print(f'  Playbook        : {len(pb_out):,} rows')
print(f'  TLH Value-Add   : {len(va_out):,} rows')
print(f'  Raw Data        : {len(raw_out):,} rows')

display(rec_out.head(10))

Playbook exported -> c:\Users\ry092\Desktop\MIS 382N - Capstone\portfolio-tlh-optimizer\Backtest\strategy_playbook.xlsx
  Recommendations : 2,739 rows
  Playbook        : 7,568 rows
  TLH Value-Add   : 7,568 rows
  Raw Data        : 15,136 rows

,Category,Model Family,Portfolio,Market Condition,Strategy Label,Rebal Type,Rebal Value,CAGR,Sharpe Ratio,Max Drawdown,Realized Losses (All),Tax Alpha 2,Composite Score
0,Equity-Heavy,FFG Qualified,FFG Qualified - 100-0,Bear Market,Rel Threshold 25% | TLH=10%,Relative Threshold,0.25,-0.2246,-0.6936,-0.5482,93531.3,5833.13,6.20
1,Equity-Heavy,FFG Qualified,FFG Qualified - 100-0,Baseline Market,Abs Threshold 5% | TLH=10%,Absolute Threshold,0.05,0.3835,6.0822,-0.0176,0.0,0.00,4.65
2,Equity-Heavy,FFG Qualified,FFG Qualified - 100-0,Baseline Market,Abs Threshold 10% | TLH=10%,Absolute Threshold,0.1,0.3835,6.0822,-0.0176,0.0,0.00,4.65
3,Equity-Heavy,FFG Qualified,FFG Qualified - 100-0,Baseline Market,Abs Threshold 20% | TLH=10%,Absolute Threshold,0.2,0.3835,6.0822,-0.0176,0.0,0.00,4.65
4,Equity-Heavy,FFG Qualified,FFG Qualified - 100-0,Baseline Market,Quarterly Rebal | TLH=10%,Calendar,Quarterly,0.3835,6.0822,-0.0176,0.0,0.00,4.65
5,Equity-Heavy,FFG Qualified,FFG Qualified - 100-0,Baseline Market,Yearly Rebal | TLH=10%,Calendar,Yearly,0.3835,6.0822,-0.0176,0.0,0.00,4.65
6,Equity-Heavy,FFG Qualified,FFG Qualified - 100-0,Baseline Market,Rel Threshold 25% | TLH=10%,Relative Threshold,0.25,0.3835,6.0822,-0.0176,0.0,0.00,4.65
7,Equity-Heavy,FFG Qualified,FFG Qualified - 100-0,Baseline Market,Rel Threshold 50% | TLH=10%,Relative Threshold,0.5,0.3835,6.0822,-0.0176,0.0,0.00,4.65
8,Equity-Heavy,FFG Qualified,FFG Qualified - 100-0,Bull Market,Abs Threshold 5% | TLH=10%,Absolute Threshold,0.05,-0.0227,-0.1685,-0.0468,0.0,0.00,4.65
9,Equity-Heavy,FFG Qualified,FFG Qualified - 100-0,Bull Market,Abs Threshold 10% | TLH=10%,Absolute Threshold,0.1,-0.0227,-0.1685,-0.0468,0.0,0.00,4.65

In [23]:
# ══════════════════════════════════════════════════════════════════════════════
# CELL 14 — STRATEGY RECOMMENDATION DASHBOARD
#
# Helps reviewers pick the best strategy by answering three questions:
#   1. What is your portfolio type?  (Equity-Heavy / Balanced / Fixed Income)
#   2. What market regime are you in? (Bear / Baseline / Bull / Long-horizon)
#   3. What is your objective?        (Max return / Min risk / Max TLH benefit / Best after-tax liquidation)
#
# Output: one recommendation table per (Category x Regime) showing the best
# strategy for each objective, with and without TLH.
# ══════════════════════════════════════════════════════════════════════════════

from IPython.display import display, Markdown

print('=' * 100)
print('  STRATEGY RECOMMENDATION DASHBOARD')
print('  Pick the best strategy by portfolio type, market regime, and objective')
print('=' * 100)

# Work from the renamed export_df (post Cell 12)
df = export_df.copy()

# ── 1. CATEGORY-LEVEL SUMMARY: Does TLH help or hurt? ───────────────────────
print('\n\n' + '=' * 100)
print('  SECTION 1 — TLH IMPACT BY CATEGORY AND MARKET REGIME')
print('  Average Tax Alpha 2 across all portfolios in each group')
print('=' * 100)

tlh_rows = df[df['TLH Status'] == 'On (10%)'].copy()
tlh_summary = (
    tlh_rows
    .groupby(['Category', 'Market Condition'])
    .agg(
        Portfolios=('Portfolio', 'nunique'),
        Avg_Tax_Alpha=('Tax Alpha 2', 'mean'),
        Median_Tax_Alpha=('Tax Alpha 2', 'median'),
        Pct_Positive=('Tax Alpha 2', lambda x: (x > 0).mean()),
        Avg_TLH_Events=('TLH Event Count', 'mean'),
    )
    .round(2)
)
tlh_summary.columns = ['Portfolios', 'Avg Tax Alpha ($)', 'Median Tax Alpha ($)',
                        '% Positive', 'Avg TLH Events']
tlh_summary['% Positive'] = (tlh_summary['% Positive'] * 100).round(1).astype(str) + '%'
display(Markdown('### TLH Impact Summary'))
display(tlh_summary)

# ── 2. BEST STRATEGY BY OBJECTIVE ───────────────────────────────────────────
print('\n\n' + '=' * 100)
print('  SECTION 2 — BEST STRATEGY PER OBJECTIVE')
print('  For each (Category x Regime), shows the top strategy for 4 objectives')
print('=' * 100)

objectives = {
    'Max Return (CAGR)':         ('CAGR',            True),   # highest CAGR
    'Min Risk (Sharpe)':         ('Sharpe Ratio',    True),   # highest Sharpe
    'Min Drawdown':              ('Max Drawdown',    False),  # least negative (closest to 0)
    'Best TLH Benefit':          ('Tax Alpha 2',     True),   # highest Tax Alpha
}

# For liquidation objective, only consider TLH-on rows
liq_obj = {
    'Best Liquidation Value':    ('Liquidation NAV', True),
}

for cat in ['Equity-Heavy', 'Balanced', 'Fixed Income-Heavy']:
    cat_df = df[df['Category'] == cat]
    if cat_df.empty:
        continue

    for regime in sorted(cat_df['Market Condition'].unique(),
                         key=lambda x: {'Bear Market': 0, 'Baseline Market': 1, 'Bull Market': 2,
                                        'Past 5 Years': 3, 'Past 10 Years': 4, 'Past 20 Years': 5}.get(x, 9)):
        regime_df = cat_df[cat_df['Market Condition'] == regime]
        if regime_df.empty:
            continue

        print(f'\n{"─" * 100}')
        print(f'  {cat}  |  {regime}  ({regime_df["Portfolio"].nunique()} portfolios)')
        print(f'{"─" * 100}')

        rows = []
        for obj_name, (col, ascending) in {**objectives, **liq_obj}.items():
            if col not in regime_df.columns:
                continue

            # For TLH-specific objectives, only look at TLH-on rows
            if col in ('Tax Alpha 2',):
                subset = regime_df[regime_df['TLH Status'] == 'On (10%)'].dropna(subset=[col])
            elif col == 'Liquidation NAV':
                subset = regime_df.dropna(subset=[col])
            else:
                subset = regime_df

            if subset.empty:
                continue

            if ascending:
                best = subset.loc[subset[col].idxmax()]
            else:
                best = subset.loc[subset[col].idxmax()]  # Max Drawdown: closest to 0 = max

            rows.append({
                'Objective': obj_name,
                'Strategy': best.get('Strategy Label', ''),
                'TLH': best.get('TLH Status', ''),
                'CAGR': f"{best.get('CAGR', 0):.2%}",
                'Sharpe': f"{best.get('Sharpe Ratio', 0):.3f}",
                'Max DD': f"{best.get('Max Drawdown', 0):.2%}",
                'Tax Alpha': f"${best.get('Tax Alpha 2', 0):+,.0f}" if pd.notna(best.get('Tax Alpha 2')) else 'N/A',
                'Liq NAV': f"${best.get('Liquidation NAV', 0):,.0f}" if pd.notna(best.get('Liquidation NAV')) else 'N/A',
                'Portfolio': best.get('Portfolio', '')[:40],
            })

        if rows:
            display(pd.DataFrame(rows).set_index('Objective'))

# ── 3. REBALANCING STRATEGY COMPARISON ───────────────────────────────────────
print('\n\n' + '=' * 100)
print('  SECTION 3 — REBALANCING STRATEGY COMPARISON')
print('  Average metrics by rebalancing type, across all portfolios (TLH On only)')
print('=' * 100)

rebal_summary = (
    tlh_rows
    .groupby(['Category', 'Rebal Type'])
    .agg(
        Avg_CAGR=('CAGR', 'mean'),
        Avg_Sharpe=('Sharpe Ratio', 'mean'),
        Avg_MaxDD=('Max Drawdown', 'mean'),
        Avg_Tax_Alpha=('Tax Alpha 2', 'mean'),
        Avg_Exec_Cost=('Execution Costs', 'mean'),
    )
    .round(4)
)
rebal_summary.columns = ['Avg CAGR', 'Avg Sharpe', 'Avg Max DD', 'Avg Tax Alpha ($)', 'Avg Exec Cost ($)']
for col in ['Avg CAGR', 'Avg Max DD']:
    rebal_summary[col] = rebal_summary[col].apply(lambda x: f'{x:.2%}')
rebal_summary['Avg Sharpe'] = rebal_summary['Avg Sharpe'].apply(lambda x: f'{x:.3f}')
rebal_summary['Avg Tax Alpha ($)'] = rebal_summary['Avg Tax Alpha ($)'].apply(lambda x: f'${x:+,.0f}')
rebal_summary['Avg Exec Cost ($)'] = rebal_summary['Avg Exec Cost ($)'].apply(lambda x: f'${x:,.0f}')

display(Markdown('### Average Metrics by Rebalancing Strategy (TLH On)'))
display(rebal_summary)

# ── 4. TLH ON vs OFF: WHEN IS TLH WORTH IT? ────────────────────────────────
print('\n\n' + '=' * 100)
print('  SECTION 4 — WHEN IS TLH WORTH IT?')
print('  For each category, shows % of scenarios where TLH improves each metric')
print('=' * 100)

on_df  = df[df['TLH Status'] == 'On (10%)'].copy()
off_df = df[df['TLH Status'] == 'Off'].copy()
merge_k = ['Category', 'Portfolio', 'Market Condition', 'Rebal Type', 'Rebal Value']
paired = on_df.merge(off_df[merge_k + ['CAGR', 'Sharpe Ratio', 'Final NAV', 'Liquidation NAV']],
                     on=merge_k, suffixes=('_on', '_off'))

worth_it = []
for cat in ['Equity-Heavy', 'Balanced', 'Fixed Income-Heavy']:
    cat_paired = paired[paired['Category'] == cat]
    if cat_paired.empty:
        continue
    n = len(cat_paired)
    worth_it.append({
        'Category': cat,
        'Scenarios': n,
        'Higher CAGR': f"{(cat_paired['CAGR_on'] > cat_paired['CAGR_off']).sum() / n:.0%}",
        'Higher Sharpe': f"{(cat_paired['Sharpe Ratio_on'] > cat_paired['Sharpe Ratio_off']).sum() / n:.0%}",
        'Higher Final NAV': f"{(cat_paired['Final NAV_on'] > cat_paired['Final NAV_off']).sum() / n:.0%}",
        'Higher Liq NAV': f"{(cat_paired['Liquidation NAV_on'] > cat_paired['Liquidation NAV_off']).sum() / n:.0%}",
    })

display(Markdown('### % of Scenarios Where TLH Outperforms No-TLH'))
display(pd.DataFrame(worth_it).set_index('Category'))

print('\n' + '=' * 100)
print('  END OF RECOMMENDATIONS')
print('=' * 100)

====================================================================================================
  STRATEGY RECOMMENDATION DASHBOARD
  Pick the best strategy by portfolio type, market regime, and objective
====================================================================================================


====================================================================================================
  SECTION 1 — TLH IMPACT BY CATEGORY AND MARKET REGIME
  Average Tax Alpha 2 across all portfolios in each group
====================================================================================================

### TLH Impact Summary

                                     Portfolios  Avg Tax Alpha ($)  \
Category           Market Condition
Balanced           Baseline Market           79            2456.05
                   Bear Market               79           -5731.07
                   Bull Market               79             447.34
                   Past 10 Years             79             562.82
                   Past 20 Years             79             562.82
                   Past 5 Years              79             562.82
Equity-Heavy       Baseline Market           35            3133.58
                   Bear Market               35            6499.69
                   Bull Market               35              78.93
                   Past 10 Years             35            -360.36
                   Past 20 Years             35            -360.36
                   Past 5 Years              35            -360.36
Fixed Income-Heavy Baseline Market           44             473.95
                   Bear Market               42          -14623.64
                   Bull Market               44             -17.76
                   Past 10 Years             44              88.11
                   Past 20 Years             44              88.11
                   Past 5 Years              44              88.11

                                     Median Tax Alpha ($) % Positive  \
Category           Market Condition
Balanced           Baseline Market                   0.00      36.0%
                   Bear Market                   -6777.90      17.0%
                   Bull Market                       0.00      21.0%
                   Past 10 Years                     0.00      40.0%
                   Past 20 Years                     0.00      40.0%
                   Past 5 Years                      0.00      40.0%
Equity-Heavy       Baseline Market                   0.00      47.0%
                   Bear Market                    1512.06      54.0%
                   Bull Market                       0.00      17.0%
                   Past 10 Years                     0.00      40.0%
                   Past 20 Years                     0.00      40.0%
                   Past 5 Years                      0.00      40.0%
Fixed Income-Heavy Baseline Market                   0.00      32.0%
                   Bear Market                   -3259.81       9.0%
                   Bull Market                       0.00      20.0%
                   Past 10 Years                     0.00      26.0%
                   Past 20 Years                     0.00      26.0%
                   Past 5 Years                      0.00      26.0%

                                     Avg TLH Events
Category           Market Condition
Balanced           Baseline Market             3.20
                   Bear Market                24.68
                   Bull Market                 1.01
                   Past 10 Years               5.67
                   Past 20 Years               5.67
                   Past 5 Years                5.67
Equity-Heavy       Baseline Market             3.62
                   Bear Market                24.79
                   Bull Market                 0.85
                   Past 10 Years               6.79
                   Past 20 Years               6.79
                   Past 5 Years                6.79
Fixed Income-Heavy Baseline Market             0.88
                   Bear Market                 9.12
                   Bull Market                 0.93
                   Past 10 Years               1.93
                   Past 20 Years               1.93
                   Past 5 Years                1.93

====================================================================================================
  SECTION 2 — BEST STRATEGY PER OBJECTIVE
  For each (Category x Regime), shows the top strategy for 4 objectives
====================================================================================================

────────────────────────────────────────────────────────────────────────────────────────────────────
  Equity-Heavy  |  Bear Market  (35 portfolios)
────────────────────────────────────────────────────────────────────────────────────────────────────

,Strategy,TLH,CAGR,Sharpe,Max DD,Tax Alpha,Liq NAV,Portfolio
Objective,,,,,,,,
Max Return (CAGR),Monthly Rebal | TLH=10%,On (10%),-13.18%,-0.563,-40.46%,"$+54,927","$774,773",GuidePath Core - 80-20
Min Risk (Sharpe),Abs Threshold 5% | TLH=10%,On (10%),-15.71%,-0.548,-44.96%,"$+99,901","$735,594",TA TaxAware ETF - 100-0
Min Drawdown,Quarterly Rebal | TLH=10%,On (10%),-26.95%,-0.930,-32.80%,"$+26,124","$732,321",MAI Tax Aware - Aggressive Growth
Best TLH Benefit,Abs Threshold 5% | TLH=10%,On (10%),-15.71%,-0.548,-44.96%,"$+99,901","$735,594",TA TaxAware ETF - 100-0
Best Liquidation Value,Monthly Rebal | TLH=10%,On (10%),-13.18%,-0.563,-40.46%,"$+54,927","$774,773",GuidePath Core - 80-20

────────────────────────────────────────────────────────────────────────────────────────────────────
  Equity-Heavy  |  Baseline Market  (35 portfolios)
────────────────────────────────────────────────────────────────────────────────────────────────────

,Strategy,TLH,CAGR,Sharpe,Max DD,Tax Alpha,Liq NAV,Portfolio
Objective,,,,,,,,
Max Return (CAGR),Abs Threshold 5% | No TLH,Off,44.77%,7.782,-1.57%,N/A,"$1,053,981",GA Aviator - 80-20
Min Risk (Sharpe),Abs Threshold 5% | No TLH,Off,44.77%,7.782,-1.57%,N/A,"$1,053,981",GA Aviator - 80-20
Min Drawdown,Monthly Rebal | No TLH,Off,44.28%,7.753,-1.55%,N/A,"$1,053,649",GA Aviator - 80-20
Best TLH Benefit,Rel Threshold 50% | TLH=10%,On (10%),8.33%,0.745,-17.15%,"$+67,130","$1,443,783",GA Aviator TaxAware - 80-20
Best Liquidation Value,Abs Threshold 10% | TLH=10%,On (10%),8.56%,0.738,-18.36%,"$+54,901","$1,457,200",GA Aviator TaxAware - 80-20

────────────────────────────────────────────────────────────────────────────────────────────────────
  Equity-Heavy  |  Bull Market  (35 portfolios)
────────────────────────────────────────────────────────────────────────────────────────────────────

,Strategy,TLH,CAGR,Sharpe,Max DD,Tax Alpha,Liq NAV,Portfolio
Objective,,,,,,,,
Max Return (CAGR),Abs Threshold 20% | No TLH,Off,21.27%,1.744,-10.43%,N/A,"$1,371,762",GA Aviator TaxAware - 80-20
Min Risk (Sharpe),Abs Threshold 20% | No TLH,Off,21.27%,1.744,-10.43%,N/A,"$1,371,762",GA Aviator TaxAware - 80-20
Min Drawdown,Abs Threshold 5% | No TLH,Off,-31.72%,-2.632,-2.23%,N/A,"$990,817",GuidePath Core - 80-20
Best TLH Benefit,Abs Threshold 5% | TLH=10%,On (10%),15.21%,1.186,-11.43%,"$+4,265","$1,244,956",Target Allocation ESG - 100-0
Best Liquidation Value,Rel Threshold 50% | No TLH,Off,20.59%,1.681,-10.43%,N/A,"$1,376,714",GA Aviator TaxAware - 80-20

────────────────────────────────────────────────────────────────────────────────────────────────────
  Equity-Heavy  |  Past 5 Years  (35 portfolios)
────────────────────────────────────────────────────────────────────────────────────────────────────

,Strategy,TLH,CAGR,Sharpe,Max DD,Tax Alpha,Liq NAV,Portfolio
Objective,,,,,,,,
Max Return (CAGR),Yearly Rebal | TLH=10%,On (10%),20.32%,1.122,-17.74%,"$+9,145","$1,146,191",GuidePath Core - 100-0
Min Risk (Sharpe),Abs Threshold 5% | TLH=10%,On (10%),20.30%,1.262,-15.79%,"$+9,989","$1,147,766",GuidePath Core - 80-20
Min Drawdown,Monthly Rebal | No TLH,Off,7.11%,0.690,-4.46%,N/A,"$1,012,033",GA Aviator TaxAware - 80-20
Best TLH Benefit,Rel Threshold 25% | TLH=10%,On (10%),18.02%,1.152,-15.16%,"$+14,391","$1,096,614",TA TaxAware ETF - 80-20
Best Liquidation Value,Abs Threshold 5% | No TLH,Off,15.71%,1.071,-17.89%,N/A,"$1,455,114",RFP Equity - Equity

────────────────────────────────────────────────────────────────────────────────────────────────────
  Equity-Heavy  |  Past 10 Years  (35 portfolios)
────────────────────────────────────────────────────────────────────────────────────────────────────

,Strategy,TLH,CAGR,Sharpe,Max DD,Tax Alpha,Liq NAV,Portfolio
Objective,,,,,,,,
Max Return (CAGR),Yearly Rebal | TLH=10%,On (10%),20.32%,1.122,-17.74%,"$+9,145","$1,146,191",GuidePath Core - 100-0
Min Risk (Sharpe),Abs Threshold 5% | TLH=10%,On (10%),20.30%,1.262,-15.79%,"$+9,989","$1,147,766",GuidePath Core - 80-20
Min Drawdown,Monthly Rebal | No TLH,Off,7.11%,0.690,-4.46%,N/A,"$1,012,033",GA Aviator TaxAware - 80-20
Best TLH Benefit,Rel Threshold 25% | TLH=10%,On (10%),18.02%,1.152,-15.16%,"$+14,391","$1,096,614",TA TaxAware ETF - 80-20
Best Liquidation Value,Abs Threshold 5% | No TLH,Off,15.71%,1.071,-17.89%,N/A,"$1,455,114",RFP Equity - Equity

────────────────────────────────────────────────────────────────────────────────────────────────────
  Equity-Heavy  |  Past 20 Years  (35 portfolios)
────────────────────────────────────────────────────────────────────────────────────────────────────

,Strategy,TLH,CAGR,Sharpe,Max DD,Tax Alpha,Liq NAV,Portfolio
Objective,,,,,,,,
Max Return (CAGR),Yearly Rebal | TLH=10%,On (10%),20.32%,1.122,-17.74%,"$+9,145","$1,146,191",GuidePath Core - 100-0
Min Risk (Sharpe),Abs Threshold 5% | TLH=10%,On (10%),20.30%,1.262,-15.79%,"$+9,989","$1,147,766",GuidePath Core - 80-20
Min Drawdown,Monthly Rebal | No TLH,Off,7.11%,0.690,-4.46%,N/A,"$1,012,033",GA Aviator TaxAware - 80-20
Best TLH Benefit,Rel Threshold 25% | TLH=10%,On (10%),18.02%,1.152,-15.16%,"$+14,391","$1,096,614",TA TaxAware ETF - 80-20
Best Liquidation Value,Abs Threshold 5% | No TLH,Off,15.71%,1.071,-17.89%,N/A,"$1,455,114",RFP Equity - Equity

────────────────────────────────────────────────────────────────────────────────────────────────────
  Balanced  |  Bear Market  (79 portfolios)
────────────────────────────────────────────────────────────────────────────────────────────────────

,Strategy,TLH,CAGR,Sharpe,Max DD,Tax Alpha,Liq NAV,Portfolio
Objective,,,,,,,,
Max Return (CAGR),Abs Threshold 5% | No TLH,Off,0.82%,0.090,-13.17%,N/A,"$1,009,510",GA Aviator - 40-60
Min Risk (Sharpe),Abs Threshold 5% | No TLH,Off,0.82%,0.090,-13.17%,N/A,"$1,009,510",GA Aviator - 40-60
Min Drawdown,Abs Threshold 10% | No TLH,Off,0.44%,0.051,-12.82%,N/A,"$1,004,876",GA Aviator - 30-70
Best TLH Benefit,Quarterly Rebal | TLH=10%,On (10%),-10.16%,-0.518,-37.35%,"$+78,915","$808,476",GuidePath TaxAware - 60-40
Best Liquidation Value,Abs Threshold 5% | No TLH,Off,0.82%,0.090,-13.17%,N/A,"$1,009,510",GA Aviator - 40-60

────────────────────────────────────────────────────────────────────────────────────────────────────
  Balanced  |  Baseline Market  (79 portfolios)
────────────────────────────────────────────────────────────────────────────────────────────────────

,Strategy,TLH,CAGR,Sharpe,Max DD,Tax Alpha,Liq NAV,Portfolio
Objective,,,,,,,,
Max Return (CAGR),Abs Threshold 5% | No TLH,Off,46.55%,7.766,-1.64%,N/A,"$1,055,894",GA Selects - 80-20
Min Risk (Sharpe),Abs Threshold 5% | No TLH,Off,46.55%,7.766,-1.64%,N/A,"$1,055,894",GA Selects - 80-20
Min Drawdown,Monthly Rebal | No TLH,Off,15.87%,5.596,-0.79%,N/A,"$1,014,153",FFG Taxable High - 30-70
Best TLH Benefit,Rel Threshold 50% | TLH=10%,On (10%),7.66%,0.765,-15.46%,"$+53,287","$1,404,239",GA Aviator TaxAware - 70-30
Best Liquidation Value,Abs Threshold 10% | TLH=10%,On (10%),7.90%,0.756,-16.90%,"$+44,881","$1,415,349",GA Aviator TaxAware - 70-30

────────────────────────────────────────────────────────────────────────────────────────────────────
  Balanced  |  Bull Market  (79 portfolios)
────────────────────────────────────────────────────────────────────────────────────────────────────

,Strategy,TLH,CAGR,Sharpe,Max DD,Tax Alpha,Liq NAV,Portfolio
Objective,,,,,,,,
Max Return (CAGR),Abs Threshold 20% | No TLH,Off,22.88%,1.806,-10.57%,N/A,"$1,403,012",GA Selects Tax Aware - 80-20
Min Risk (Sharpe),Abs Threshold 20% | No TLH,Off,22.88%,1.806,-10.57%,N/A,"$1,403,012",GA Selects Tax Aware - 80-20
Min Drawdown,Abs Threshold 5% | No TLH,Off,-28.65%,-3.052,-1.78%,N/A,"$991,854",GuidePath Core - 60-40
Best TLH Benefit,Rel Threshold 25% | TLH=10%,On (10%),15.51%,1.534,-10.07%,"$+10,532","$1,206,336",GA Selects - 60-40
Best Liquidation Value,Abs Threshold 20% | No TLH,Off,22.88%,1.806,-10.57%,N/A,"$1,403,012",GA Selects Tax Aware - 80-20

────────────────────────────────────────────────────────────────────────────────────────────────────
  Balanced  |  Past 5 Years  (79 portfolios)
────────────────────────────────────────────────────────────────────────────────────────────────────

,Strategy,TLH,CAGR,Sharpe,Max DD,Tax Alpha,Liq NAV,Portfolio
Objective,,,,,,,,
Max Return (CAGR),Abs Threshold 5% | TLH=10%,On (10%),17.49%,1.178,-14.57%,"$+13,381","$1,097,119",GuidePath TaxAware - 60-40
Min Risk (Sharpe),Yearly Rebal | TLH=10%,On (10%),17.23%,1.355,-12.45%,"$+9,656","$1,125,492",GuidePath Core - 60-40
Min Drawdown,Monthly Rebal | No TLH,Off,1.63%,0.338,-2.32%,N/A,"$1,001,571",GA Aviator TaxAware - 30-70
Best TLH Benefit,Abs Threshold 5% | TLH=10%,On (10%),17.49%,1.178,-14.57%,"$+13,381","$1,097,119",GuidePath TaxAware - 60-40
Best Liquidation Value,Rel Threshold 25% | TLH=10%,On (10%),11.60%,1.112,-11.67%,"$+6,612","$1,299,120",Target Allocation ESG - 60-40

────────────────────────────────────────────────────────────────────────────────────────────────────
  Balanced  |  Past 10 Years  (79 portfolios)
────────────────────────────────────────────────────────────────────────────────────────────────────

,Strategy,TLH,CAGR,Sharpe,Max DD,Tax Alpha,Liq NAV,Portfolio
Objective,,,,,,,,
Max Return (CAGR),Abs Threshold 5% | TLH=10%,On (10%),17.49%,1.178,-14.57%,"$+13,381","$1,097,119",GuidePath TaxAware - 60-40
Min Risk (Sharpe),Yearly Rebal | TLH=10%,On (10%),17.23%,1.355,-12.45%,"$+9,656","$1,125,492",GuidePath Core - 60-40
Min Drawdown,Monthly Rebal | No TLH,Off,1.63%,0.338,-2.32%,N/A,"$1,001,571",GA Aviator TaxAware - 30-70
Best TLH Benefit,Abs Threshold 5% | TLH=10%,On (10%),17.49%,1.178,-14.57%,"$+13,381","$1,097,119",GuidePath TaxAware - 60-40
Best Liquidation Value,Rel Threshold 25% | TLH=10%,On (10%),11.60%,1.112,-11.67%,"$+6,612","$1,299,120",Target Allocation ESG - 60-40

────────────────────────────────────────────────────────────────────────────────────────────────────
  Balanced  |  Past 20 Years  (79 portfolios)
────────────────────────────────────────────────────────────────────────────────────────────────────

,Strategy,TLH,CAGR,Sharpe,Max DD,Tax Alpha,Liq NAV,Portfolio
Objective,,,,,,,,
Max Return (CAGR),Abs Threshold 5% | TLH=10%,On (10%),17.49%,1.178,-14.57%,"$+13,381","$1,097,119",GuidePath TaxAware - 60-40
Min Risk (Sharpe),Yearly Rebal | TLH=10%,On (10%),17.23%,1.355,-12.45%,"$+9,656","$1,125,492",GuidePath Core - 60-40
Min Drawdown,Monthly Rebal | No TLH,Off,1.63%,0.338,-2.32%,N/A,"$1,001,571",GA Aviator TaxAware - 30-70
Best TLH Benefit,Abs Threshold 5% | TLH=10%,On (10%),17.49%,1.178,-14.57%,"$+13,381","$1,097,119",GuidePath TaxAware - 60-40
Best Liquidation Value,Rel Threshold 25% | TLH=10%,On (10%),11.60%,1.112,-11.67%,"$+6,612","$1,299,120",Target Allocation ESG - 60-40

────────────────────────────────────────────────────────────────────────────────────────────────────
  Fixed Income-Heavy  |  Bear Market  (42 portfolios)
────────────────────────────────────────────────────────────────────────────────────────────────────

,Strategy,TLH,CAGR,Sharpe,Max DD,Tax Alpha,Liq NAV,Portfolio
Objective,,,,,,,,
Max Return (CAGR),Abs Threshold 5% | No TLH,Off,11.90%,1.227,-9.64%,N/A,"$1,198,492",GuidePath TaxAware - 0-100
Min Risk (Sharpe),Abs Threshold 5% | No TLH,Off,8.89%,3.742,-0.40%,N/A,"$1,006,319",RFP Muni - Fixed Income
Min Drawdown,Abs Threshold 5% | No TLH,Off,8.89%,3.742,-0.40%,N/A,"$1,006,319",RFP Muni - Fixed Income
Best TLH Benefit,Monthly Rebal | TLH=10%,On (10%),-2.30%,-0.197,-22.99%,"$+24,266","$953,925",GuidePath TaxAware - 20-80
Best Liquidation Value,Abs Threshold 5% | No TLH,Off,11.90%,1.227,-9.64%,N/A,"$1,198,492",GuidePath TaxAware - 0-100

────────────────────────────────────────────────────────────────────────────────────────────────────
  Fixed Income-Heavy  |  Baseline Market  (44 portfolios)
────────────────────────────────────────────────────────────────────────────────────────────────────

,Strategy,TLH,CAGR,Sharpe,Max DD,Tax Alpha,Liq NAV,Portfolio
Objective,,,,,,,,
Max Return (CAGR),Abs Threshold 5% | No TLH,Off,16.67%,5.462,-0.87%,N/A,"$1,014,859",FFG Qualified - 30-70
Min Risk (Sharpe),Abs Threshold 5% | No TLH,Off,16.67%,5.462,-0.87%,N/A,"$1,014,859",FFG Qualified - 30-70
Min Drawdown,Monthly Rebal | No TLH,Off,10.28%,4.854,-0.55%,N/A,"$1,008,830",FFG Taxable High - 20-80
Best TLH Benefit,Monthly Rebal | TLH=10%,On (10%),2.31%,0.785,-5.18%,"$+4,813","$1,037,625",MAI Tax Aware - Conservative
Best Liquidation Value,Abs Threshold 10% | No TLH,Off,3.44%,1.096,-6.05%,N/A,"$1,125,055",GA Aviator TaxAware - 20-80

────────────────────────────────────────────────────────────────────────────────────────────────────
  Fixed Income-Heavy  |  Bull Market  (44 portfolios)
────────────────────────────────────────────────────────────────────────────────────────────────────

,Strategy,TLH,CAGR,Sharpe,Max DD,Tax Alpha,Liq NAV,Portfolio
Objective,,,,,,,,
Max Return (CAGR),Abs Threshold 5% | No TLH,Off,9.57%,1.640,-3.19%,N/A,"$1,083,614",GuidePath Core - 20-80
Min Risk (Sharpe),Yearly Rebal | No TLH,Off,9.54%,1.641,-3.18%,N/A,"$1,083,390",GuidePath Core - 20-80
Min Drawdown,Monthly Rebal | No TLH,Off,-0.54%,-0.266,-1.55%,N/A,"$994,934",RFP Muni - Fixed Income
Best TLH Benefit,Yearly Rebal | TLH=10%,On (10%),2.48%,0.389,-7.69%,"$+4,350","$1,030,383",GA Aviator - 20-80
Best Liquidation Value,Abs Threshold 10% | No TLH,Off,8.57%,1.279,-8.16%,N/A,"$1,140,356",GuidePath TaxAware - 20-80

────────────────────────────────────────────────────────────────────────────────────────────────────
  Fixed Income-Heavy  |  Past 5 Years  (44 portfolios)
────────────────────────────────────────────────────────────────────────────────────────────────────

,Strategy,TLH,CAGR,Sharpe,Max DD,Tax Alpha,Liq NAV,Portfolio
Objective,,,,,,,,
Max Return (CAGR),Abs Threshold 5% | No TLH,Off,10.04%,1.604,-6.78%,N/A,"$1,176,217",GuidePath Core - 20-80
Min Risk (Sharpe),Abs Threshold 5% | No TLH,Off,10.04%,1.604,-6.78%,N/A,"$1,176,217",GuidePath Core - 20-80
Min Drawdown,Monthly Rebal | No TLH,Off,-0.28%,-0.104,-1.33%,N/A,"$997,850",GA Aviator TaxAware - 10-90
Best TLH Benefit,Abs Threshold 5% | TLH=10%,On (10%),6.80%,1.033,-7.28%,"$+4,155","$1,036,566",GuidePath TaxAware - 20-80
Best Liquidation Value,Abs Threshold 5% | No TLH,Off,9.33%,1.293,-8.72%,N/A,"$1,206,583",FFG Qualified - 20-80

────────────────────────────────────────────────────────────────────────────────────────────────────
  Fixed Income-Heavy  |  Past 10 Years  (44 portfolios)
────────────────────────────────────────────────────────────────────────────────────────────────────

,Strategy,TLH,CAGR,Sharpe,Max DD,Tax Alpha,Liq NAV,Portfolio
Objective,,,,,,,,
Max Return (CAGR),Abs Threshold 5% | No TLH,Off,10.04%,1.604,-6.78%,N/A,"$1,176,217",GuidePath Core - 20-80
Min Risk (Sharpe),Abs Threshold 5% | No TLH,Off,10.04%,1.604,-6.78%,N/A,"$1,176,217",GuidePath Core - 20-80
Min Drawdown,Monthly Rebal | No TLH,Off,-0.28%,-0.104,-1.33%,N/A,"$997,850",GA Aviator TaxAware - 10-90
Best TLH Benefit,Abs Threshold 5% | TLH=10%,On (10%),6.80%,1.033,-7.28%,"$+4,155","$1,036,566",GuidePath TaxAware - 20-80
Best Liquidation Value,Abs Threshold 5% | No TLH,Off,9.33%,1.293,-8.72%,N/A,"$1,206,583",FFG Qualified - 20-80

────────────────────────────────────────────────────────────────────────────────────────────────────
  Fixed Income-Heavy  |  Past 20 Years  (44 portfolios)
────────────────────────────────────────────────────────────────────────────────────────────────────

,Strategy,TLH,CAGR,Sharpe,Max DD,Tax Alpha,Liq NAV,Portfolio
Objective,,,,,,,,
Max Return (CAGR),Abs Threshold 5% | No TLH,Off,10.04%,1.604,-6.78%,N/A,"$1,176,217",GuidePath Core - 20-80
Min Risk (Sharpe),Abs Threshold 5% | No TLH,Off,10.04%,1.604,-6.78%,N/A,"$1,176,217",GuidePath Core - 20-80
Min Drawdown,Monthly Rebal | No TLH,Off,-0.28%,-0.104,-1.33%,N/A,"$997,850",GA Aviator TaxAware - 10-90
Best TLH Benefit,Abs Threshold 5% | TLH=10%,On (10%),6.80%,1.033,-7.28%,"$+4,155","$1,036,566",GuidePath TaxAware - 20-80
Best Liquidation Value,Abs Threshold 5% | No TLH,Off,9.33%,1.293,-8.72%,N/A,"$1,206,583",FFG Qualified - 20-80

====================================================================================================
  SECTION 3 — REBALANCING STRATEGY COMPARISON
  Average metrics by rebalancing type, across all portfolios (TLH On only)
====================================================================================================

### Average Metrics by Rebalancing Strategy (TLH On)

                                      Avg CAGR Avg Sharpe Avg Max DD  \
Category           Rebal Type
Balanced           Absolute Threshold    4.30%      0.924    -12.79%
                   Calendar              4.04%      0.912    -12.78%
                   Relative Threshold    4.17%      0.921    -12.85%
Equity-Heavy       Absolute Threshold    6.95%      0.808    -17.72%
                   Calendar              6.72%      0.803    -17.72%
                   Relative Threshold    6.85%      0.807    -17.77%
Fixed Income-Heavy Absolute Threshold    1.69%      0.507     -7.26%
                   Calendar              1.50%      0.482     -7.21%
                   Relative Threshold    1.58%      0.494     -7.27%

                                      Avg Tax Alpha ($) Avg Exec Cost ($)
Category           Rebal Type
Balanced           Absolute Threshold             $-357            $2,231
                   Calendar                       $+172            $2,208
                   Relative Threshold             $-481            $2,333
Equity-Heavy       Absolute Threshold           $+1,969            $2,645
                   Calendar                       $+954            $2,545
                   Relative Threshold           $+1,371            $2,780
Fixed Income-Heavy Absolute Threshold           $-2,524            $1,558
                   Calendar                     $-1,893            $1,644
                   Relative Threshold           $-2,266            $1,603

====================================================================================================
  SECTION 4 — WHEN IS TLH WORTH IT?
  For each category, shows % of scenarios where TLH improves each metric
====================================================================================================

### % of Scenarios Where TLH Outperforms No-TLH

,Scenarios,Higher CAGR,Higher Sharpe,Higher Final NAV,Higher Liq NAV
Category,,,,,
Equity-Heavy,1680,40%,37%,40%,24%
Balanced,3792,33%,33%,33%,19%
Fixed Income-Heavy,2096,23%,23%,23%,15%

====================================================================================================
  END OF RECOMMENDATIONS
====================================================================================================